#
# linux/drivers/applitevduveu
#

obj-${CONFIG_APPLITE_VDU} 		+= applitevdu.o

applitevdu-objs 	:= applite_vdu_base.o \
			applite_vdu_internal.o \
			applite_vdu_procfs.o \
			applite_vdu_dbg.o \
			applite_vdu_ioctl.o \
			applite_vdu_reset_power_seq.o \
			vd_api.o \
			vd_accessor.o
