obj-y					+= ma/

obj-$(CONFIG_APPLITE_VCONV)		+= vconv/

obj-$(CONFIG_APPLITE_VEU)		+= veu/

obj-$(CONFIG_APPLITE_VDU)		+= vdu/

obj-$(CONFIG_APPLITE_SYSCON)		+= syscon/

obj-$(CONFIG_APPLITE_IRECOG)		+= irecog/

obj-$(CONFIG_APPLITE_PWM)		+= pwm/

obj-$(CONFIG_APPLITE_YUVC)		+= yuvc/

obj-$(CONFIG_APPLITE_EMMC)		+= emmc/

obj-$(CONFIG_APPLITE_MIRAGELITE)	+= miragelite/
