/*
 * arch/arm/mach-tz2000/include/mach/regs/gconf_reg_def.h
 *
 * (C) Copyright TOSHIBA Corporation
 * Semiconductor & Storage Products Company 2013
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#ifndef _GCONF_REG_DEF_H
#define _GCONF_REG_DEF_H

#ifdef __cplusplus
extern  {
#endif /* __cplusplus */

// PINSHARE0 Register
#define GCONF_PINSHARE0_OFS                      0x00000010
// Reserved7 bitfiled (RO) Reset=0
#define GCONF_PINSHARE0_RESERVED7_MASK           0x3
#define GCONF_PINSHARE0_RESERVED7_SHIFT          0 
#define GCONF_PINSHARE0_RESERVED7_BIT            0x3
#define GCONF_PINSHARE0_RESERVED7_BITWIDTH       2
// GPIO_SPI2_SEL bitfiled (RW) Reset=0
#define GCONF_PINSHARE0_GPIO_SPI2_SEL_MASK       0x4
#define GCONF_PINSHARE0_GPIO_SPI2_SEL_SHIFT      2 
#define GCONF_PINSHARE0_GPIO_SPI2_SEL_BIT        0x1
#define GCONF_PINSHARE0_GPIO_SPI2_SEL_BITWIDTH   1
// GPIO_SPI3_SEL bitfiled (RW) Reset=0
#define GCONF_PINSHARE0_GPIO_SPI3_SEL_MASK       0x8
#define GCONF_PINSHARE0_GPIO_SPI3_SEL_SHIFT      3 
#define GCONF_PINSHARE0_GPIO_SPI3_SEL_BIT        0x1
#define GCONF_PINSHARE0_GPIO_SPI3_SEL_BITWIDTH   1
// Reserved6 bitfiled (RO) Reset=0
#define GCONF_PINSHARE0_RESERVED6_MASK           0xF0
#define GCONF_PINSHARE0_RESERVED6_SHIFT          4 
#define GCONF_PINSHARE0_RESERVED6_BIT            0xF
#define GCONF_PINSHARE0_RESERVED6_BITWIDTH       4
// Reserved5 bitfiled (RO) Reset=0
#define GCONF_PINSHARE0_RESERVED5_MASK           0xF00
#define GCONF_PINSHARE0_RESERVED5_SHIFT          8 
#define GCONF_PINSHARE0_RESERVED5_BIT            0xF
#define GCONF_PINSHARE0_RESERVED5_BITWIDTH       4
// GPIO_UART2_FSEL bitfiled (RW) Reset=0
#define GCONF_PINSHARE0_GPIO_UART2_FSEL_MASK     0x1000
#define GCONF_PINSHARE0_GPIO_UART2_FSEL_SHIFT    12 
#define GCONF_PINSHARE0_GPIO_UART2_FSEL_BIT      0x1
#define GCONF_PINSHARE0_GPIO_UART2_FSEL_BITWIDTH 1
// GPIO_UART2_DSEL bitfiled (RW) Reset=0
#define GCONF_PINSHARE0_GPIO_UART2_DSEL_MASK     0x2000
#define GCONF_PINSHARE0_GPIO_UART2_DSEL_SHIFT    13 
#define GCONF_PINSHARE0_GPIO_UART2_DSEL_BIT      0x1
#define GCONF_PINSHARE0_GPIO_UART2_DSEL_BITWIDTH 1
// GPIO_UART3_FSEL bitfiled (RW) Reset=0
#define GCONF_PINSHARE0_GPIO_UART3_FSEL_MASK     0x4000
#define GCONF_PINSHARE0_GPIO_UART3_FSEL_SHIFT    14 
#define GCONF_PINSHARE0_GPIO_UART3_FSEL_BIT      0x1
#define GCONF_PINSHARE0_GPIO_UART3_FSEL_BITWIDTH 1
// GPIO_UART3_DSEL bitfiled (RW) Reset=0
#define GCONF_PINSHARE0_GPIO_UART3_DSEL_MASK     0x8000
#define GCONF_PINSHARE0_GPIO_UART3_DSEL_SHIFT    15 
#define GCONF_PINSHARE0_GPIO_UART3_DSEL_BIT      0x1
#define GCONF_PINSHARE0_GPIO_UART3_DSEL_BITWIDTH 1
// Reserved4 bitfiled (RO) Reset=0
#define GCONF_PINSHARE0_RESERVED4_MASK           0xF0000
#define GCONF_PINSHARE0_RESERVED4_SHIFT          16 
#define GCONF_PINSHARE0_RESERVED4_BIT            0xF
#define GCONF_PINSHARE0_RESERVED4_BITWIDTH       4
// GPIO_EMMC0_SEL bitfiled (RW) Reset=0
#define GCONF_PINSHARE0_GPIO_EMMC0_SEL_MASK      0x100000
#define GCONF_PINSHARE0_GPIO_EMMC0_SEL_SHIFT     20 
#define GCONF_PINSHARE0_GPIO_EMMC0_SEL_BIT       0x1
#define GCONF_PINSHARE0_GPIO_EMMC0_SEL_BITWIDTH  1
// GPIO_EMMC1_SEL bitfiled (RW) Reset=0
#define GCONF_PINSHARE0_GPIO_EMMC1_SEL_MASK      0x200000
#define GCONF_PINSHARE0_GPIO_EMMC1_SEL_SHIFT     21 
#define GCONF_PINSHARE0_GPIO_EMMC1_SEL_BIT       0x1
#define GCONF_PINSHARE0_GPIO_EMMC1_SEL_BITWIDTH  1
// Reserved3 bitfiled (RO) Reset=0
#define GCONF_PINSHARE0_RESERVED3_MASK           0xC00000
#define GCONF_PINSHARE0_RESERVED3_SHIFT          22 
#define GCONF_PINSHARE0_RESERVED3_BIT            0x3
#define GCONF_PINSHARE0_RESERVED3_BITWIDTH       2
// GPIO_ETHER_SEL bitfiled (RW) Reset=0
#define GCONF_PINSHARE0_GPIO_ETHER_SEL_MASK      0x1000000
#define GCONF_PINSHARE0_GPIO_ETHER_SEL_SHIFT     24 
#define GCONF_PINSHARE0_GPIO_ETHER_SEL_BIT       0x1
#define GCONF_PINSHARE0_GPIO_ETHER_SEL_BITWIDTH  1
// Reserved2 bitfiled (RO) Reset=0
#define GCONF_PINSHARE0_RESERVED2_MASK           0xE000000
#define GCONF_PINSHARE0_RESERVED2_SHIFT          25 
#define GCONF_PINSHARE0_RESERVED2_BIT            0x7
#define GCONF_PINSHARE0_RESERVED2_BITWIDTH       3
// GPIO_DISP_SEL bitfiled (RW) Reset=0
#define GCONF_PINSHARE0_GPIO_DISP_SEL_MASK       0x10000000
#define GCONF_PINSHARE0_GPIO_DISP_SEL_SHIFT      28 
#define GCONF_PINSHARE0_GPIO_DISP_SEL_BIT        0x1
#define GCONF_PINSHARE0_GPIO_DISP_SEL_BITWIDTH   1
// Reserved bitfiled (RO) Reset=0
#define GCONF_PINSHARE0_RESERVED_MASK            0xE0000000
#define GCONF_PINSHARE0_RESERVED_SHIFT           29 
#define GCONF_PINSHARE0_RESERVED_BIT             0x7
#define GCONF_PINSHARE0_RESERVED_BITWIDTH        3
// PINSHARE1 Register
#define GCONF_PINSHARE1_OFS                      0x00000014
// EMMC1_SDCARD_SEL bitfiled (RW) Reset=0
#define GCONF_PINSHARE1_EMMC1_SDCARD_SEL_MASK    0x1
#define GCONF_PINSHARE1_EMMC1_SDCARD_SEL_SHIFT   0 
#define GCONF_PINSHARE1_EMMC1_SDCARD_SEL_BIT     0x1
#define GCONF_PINSHARE1_EMMC1_SDCARD_SEL_BITWIDTH 1
// reserved1 bitfiled (RO) Reset=0
#define GCONF_PINSHARE1_RESERVED1_MASK           0xFFFFFFFE
#define GCONF_PINSHARE1_RESERVED1_SHIFT          1 
#define GCONF_PINSHARE1_RESERVED1_BIT            0x7FFFFFFF
#define GCONF_PINSHARE1_RESERVED1_BITWIDTH       31
// PINSHARE2 Register
#define GCONF_PINSHARE2_OFS                      0x00000020
// SDIME_SEL bitfiled (RW) Reset=1
#define GCONF_PINSHARE2_SDIME_SEL_MASK           0x1
#define GCONF_PINSHARE2_SDIME_SEL_SHIFT          0 
#define GCONF_PINSHARE2_SDIME_SEL_BIT            0x1
#define GCONF_PINSHARE2_SDIME_SEL_BITWIDTH       1
// TDIME_SEL bitfiled (RW) Reset=0
#define GCONF_PINSHARE2_TDIME_SEL_MASK           0x2
#define GCONF_PINSHARE2_TDIME_SEL_SHIFT          1 
#define GCONF_PINSHARE2_TDIME_SEL_BIT            0x1
#define GCONF_PINSHARE2_TDIME_SEL_BITWIDTH       1
// reserved1 bitfiled (RO) Reset=0
#define GCONF_PINSHARE2_RESERVED1_MASK           0xFFFFFFFC
#define GCONF_PINSHARE2_RESERVED1_SHIFT          2 
#define GCONF_PINSHARE2_RESERVED1_BIT            0x3FFFFFFF
#define GCONF_PINSHARE2_RESERVED1_BITWIDTH       30
// PINSHARE3 Register
#define GCONF_PINSHARE3_OFS                      0x00000028
// DDRPHY_DEBUG_SEL bitfiled (RW) Reset=0
#define GCONF_PINSHARE3_DDRPHY_DEBUG_SEL_MASK    0x1
#define GCONF_PINSHARE3_DDRPHY_DEBUG_SEL_SHIFT   0 
#define GCONF_PINSHARE3_DDRPHY_DEBUG_SEL_BIT     0x1
#define GCONF_PINSHARE3_DDRPHY_DEBUG_SEL_BITWIDTH 1
// reserved1 bitfiled (RO) Reset=0
#define GCONF_PINSHARE3_RESERVED1_MASK           0xFFFFFFFE
#define GCONF_PINSHARE3_RESERVED1_SHIFT          1 
#define GCONF_PINSHARE3_RESERVED1_BIT            0x7FFFFFFF
#define GCONF_PINSHARE3_RESERVED1_BITWIDTH       31
// CPU_EVENT Register
#define GCONF_CPU_EVENT_OFS                      0x00000038
// CPU_EVENT bitfiled (RW) Reset=0
#define GCONF_CPU_EVENT_CPU_EVENT_MASK           0x1
#define GCONF_CPU_EVENT_CPU_EVENT_SHIFT          0 
#define GCONF_CPU_EVENT_CPU_EVENT_BIT            0x1
#define GCONF_CPU_EVENT_CPU_EVENT_BITWIDTH       1
// reserved bitfiled (RO) Reset=0
#define GCONF_CPU_EVENT_RESERVED_MASK            0x7FFFFFFE
#define GCONF_CPU_EVENT_RESERVED_SHIFT           1 
#define GCONF_CPU_EVENT_RESERVED_BIT             0x3FFFFFFF
#define GCONF_CPU_EVENT_RESERVED_BITWIDTH        30
// reserved2 bitfiled (RO) Reset=0
#define GCONF_CPU_EVENT_RESERVED2_MASK           0x80000000
#define GCONF_CPU_EVENT_RESERVED2_SHIFT          31 
#define GCONF_CPU_EVENT_RESERVED2_BIT            0x1
#define GCONF_CPU_EVENT_RESERVED2_BITWIDTH       1
// CPU_STANDBY_STATUS Register
#define GCONF_CPU_STANDBY_STATUS_OFS             0x0000003C
// CPU_STANDBYWFI bitfiled (RO) Reset=0
#define GCONF_CPU_STANDBY_STATUS_CPU_STANDBYWFI_MASK 0x1
#define GCONF_CPU_STANDBY_STATUS_CPU_STANDBYWFI_SHIFT 0 
#define GCONF_CPU_STANDBY_STATUS_CPU_STANDBYWFI_BIT 0x1
#define GCONF_CPU_STANDBY_STATUS_CPU_STANDBYWFI_BITWIDTH 1
// reserved2 bitfiled (RO) Reset=0
#define GCONF_CPU_STANDBY_STATUS_RESERVED2_MASK  0xE
#define GCONF_CPU_STANDBY_STATUS_RESERVED2_SHIFT 1 
#define GCONF_CPU_STANDBY_STATUS_RESERVED2_BIT   0x7
#define GCONF_CPU_STANDBY_STATUS_RESERVED2_BITWIDTH 3
// CPU_STANDBYWFE bitfiled (RO) Reset=0
#define GCONF_CPU_STANDBY_STATUS_CPU_STANDBYWFE_MASK 0x10
#define GCONF_CPU_STANDBY_STATUS_CPU_STANDBYWFE_SHIFT 4 
#define GCONF_CPU_STANDBY_STATUS_CPU_STANDBYWFE_BIT 0x1
#define GCONF_CPU_STANDBY_STATUS_CPU_STANDBYWFE_BITWIDTH 1
// reserved bitfiled (RO) Reset=0
#define GCONF_CPU_STANDBY_STATUS_RESERVED_MASK   0xFFFFFFE0
#define GCONF_CPU_STANDBY_STATUS_RESERVED_SHIFT  5 
#define GCONF_CPU_STANDBY_STATUS_RESERVED_BIT    0x7FFFFFF
#define GCONF_CPU_STANDBY_STATUS_RESERVED_BITWIDTH 27
// GDMAC_CTRL0 Register
#define GCONF_GDMAC_CTRL0_OFS                    0x00000040
// reserved2 bitfiled (RO) Reset=0
#define GCONF_GDMAC_CTRL0_RESERVED2_MASK         0x1
#define GCONF_GDMAC_CTRL0_RESERVED2_SHIFT        0 
#define GCONF_GDMAC_CTRL0_RESERVED2_BIT          0x1
#define GCONF_GDMAC_CTRL0_RESERVED2_BITWIDTH     1
// BOOT_FROM_PC bitfiled (RW) Reset=0
#define GCONF_GDMAC_CTRL0_BOOT_FROM_PC_MASK      0x2
#define GCONF_GDMAC_CTRL0_BOOT_FROM_PC_SHIFT     1 
#define GCONF_GDMAC_CTRL0_BOOT_FROM_PC_BIT       0x1
#define GCONF_GDMAC_CTRL0_BOOT_FROM_PC_BITWIDTH  1
// BOOT_MANAGER_NS bitfiled (RW) Reset=1
#define GCONF_GDMAC_CTRL0_BOOT_MANAGER_NS_MASK   0x4
#define GCONF_GDMAC_CTRL0_BOOT_MANAGER_NS_SHIFT  2 
#define GCONF_GDMAC_CTRL0_BOOT_MANAGER_NS_BIT    0x1
#define GCONF_GDMAC_CTRL0_BOOT_MANAGER_NS_BITWIDTH 1
// reserved bitfiled (RO) Reset=0
#define GCONF_GDMAC_CTRL0_RESERVED_MASK          0xFFFFFFF8
#define GCONF_GDMAC_CTRL0_RESERVED_SHIFT         3 
#define GCONF_GDMAC_CTRL0_RESERVED_BIT           0x1FFFFFFF
#define GCONF_GDMAC_CTRL0_RESERVED_BITWIDTH      29
// GDMAC_CTRL1 Register
#define GCONF_GDMAC_CTRL1_OFS                    0x00000044
// BOOT_ADDR bitfiled (RW) Reset=0
#define GCONF_GDMAC_CTRL1_BOOT_ADDR_MASK         0xFFFFFFFF
#define GCONF_GDMAC_CTRL1_BOOT_ADDR_SHIFT        0 
#define GCONF_GDMAC_CTRL1_BOOT_ADDR_BIT          0xFFFFFFFF
#define GCONF_GDMAC_CTRL1_BOOT_ADDR_BITWIDTH     32
// GDMAC_CTRL2 Register
#define GCONF_GDMAC_CTRL2_OFS                    0x00000048
// BOOT_IRQ_NS bitfiled (RW) Reset=1111111111111111
#define GCONF_GDMAC_CTRL2_BOOT_IRQ_NS_MASK       0xFFFF
#define GCONF_GDMAC_CTRL2_BOOT_IRQ_NS_SHIFT      0 
#define GCONF_GDMAC_CTRL2_BOOT_IRQ_NS_BIT        0xFFFF
#define GCONF_GDMAC_CTRL2_BOOT_IRQ_NS_BITWIDTH   16
// reserved bitfiled (RO) Reset=0
#define GCONF_GDMAC_CTRL2_RESERVED_MASK          0xFFFF0000
#define GCONF_GDMAC_CTRL2_RESERVED_SHIFT         16 
#define GCONF_GDMAC_CTRL2_RESERVED_BIT           0xFFFF
#define GCONF_GDMAC_CTRL2_RESERVED_BITWIDTH      16
// GDMAC_CTRL3 Register
#define GCONF_GDMAC_CTRL3_OFS                    0x0000004C
// BOOT_PERIPH_NS bitfiled (RW) Reset=111111111111111111111111
#define GCONF_GDMAC_CTRL3_BOOT_PERIPH_NS_MASK    0xFFFFFF
#define GCONF_GDMAC_CTRL3_BOOT_PERIPH_NS_SHIFT   0 
#define GCONF_GDMAC_CTRL3_BOOT_PERIPH_NS_BIT     0xFFFFFF
#define GCONF_GDMAC_CTRL3_BOOT_PERIPH_NS_BITWIDTH 24
// reserved bitfiled (RO) Reset=0
#define GCONF_GDMAC_CTRL3_RESERVED_MASK          0xFF000000
#define GCONF_GDMAC_CTRL3_RESERVED_SHIFT         24 
#define GCONF_GDMAC_CTRL3_RESERVED_BIT           0xFF
#define GCONF_GDMAC_CTRL3_RESERVED_BITWIDTH      8
// GDMAC_CTRL4 Register
#define GCONF_GDMAC_CTRL4_OFS                    0x00000050
// SYNCSEL bitfiled (RW) Reset=0
#define GCONF_GDMAC_CTRL4_SYNCSEL_MASK           0xFFFFFF
#define GCONF_GDMAC_CTRL4_SYNCSEL_SHIFT          0 
#define GCONF_GDMAC_CTRL4_SYNCSEL_BIT            0xFFFFFF
#define GCONF_GDMAC_CTRL4_SYNCSEL_BITWIDTH       24
// reserved bitfiled (RO) Reset=0
#define GCONF_GDMAC_CTRL4_RESERVED_MASK          0xFF000000
#define GCONF_GDMAC_CTRL4_RESERVED_SHIFT         24 
#define GCONF_GDMAC_CTRL4_RESERVED_BIT           0xFF
#define GCONF_GDMAC_CTRL4_RESERVED_BITWIDTH      8
// GDMAC_CTRL5 Register
#define GCONF_GDMAC_CTRL5_OFS                    0x00000054
// ENABLE_DMACTC bitfiled (RW) Reset=0
#define GCONF_GDMAC_CTRL5_ENABLE_DMACTC_MASK     0xFFFFFF
#define GCONF_GDMAC_CTRL5_ENABLE_DMACTC_SHIFT    0 
#define GCONF_GDMAC_CTRL5_ENABLE_DMACTC_BIT      0xFFFFFF
#define GCONF_GDMAC_CTRL5_ENABLE_DMACTC_BITWIDTH 24
// reserved bitfiled (RO) Reset=0
#define GCONF_GDMAC_CTRL5_RESERVED_MASK          0xFF000000
#define GCONF_GDMAC_CTRL5_RESERVED_SHIFT         24 
#define GCONF_GDMAC_CTRL5_RESERVED_BIT           0xFF
#define GCONF_GDMAC_CTRL5_RESERVED_BITWIDTH      8

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* _GCONF_REG_DEF_H */
