/*
 * arch/arm/mach-tz2000/include/mach/regs/rtc_reg_def.h
 *
 * (C) Copyright TOSHIBA Corporation
 * Semiconductor & Storage Products Company 2013
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#ifndef _RTC_REG_DEF_H
#define _RTC_REG_DEF_H

#ifdef __cplusplus
extern  {
#endif /* __cplusplus */

// RTC_TIMESET1 Register
#define RTC_RTC_TIMESET1_OFS                     0x00000000
// SECSET_UNDER10 bitfiled (RW) Reset=0
#define RTC_RTC_TIMESET1_SECSET_UNDER10_MASK     0xF
#define RTC_RTC_TIMESET1_SECSET_UNDER10_SHIFT    0 
#define RTC_RTC_TIMESET1_SECSET_UNDER10_BIT      0xF
#define RTC_RTC_TIMESET1_SECSET_UNDER10_BITWIDTH 4
// SECSET_OVER10 bitfiled (RW) Reset=0
#define RTC_RTC_TIMESET1_SECSET_OVER10_MASK      0x70
#define RTC_RTC_TIMESET1_SECSET_OVER10_SHIFT     4 
#define RTC_RTC_TIMESET1_SECSET_OVER10_BIT       0x7
#define RTC_RTC_TIMESET1_SECSET_OVER10_BITWIDTH  3
// reserved2 bitfiled (RO) Reset=0
#define RTC_RTC_TIMESET1_RESERVED2_MASK          0x80
#define RTC_RTC_TIMESET1_RESERVED2_SHIFT         7 
#define RTC_RTC_TIMESET1_RESERVED2_BIT           0x1
#define RTC_RTC_TIMESET1_RESERVED2_BITWIDTH      1
// MINSET_UNDER10 bitfiled (RW) Reset=0
#define RTC_RTC_TIMESET1_MINSET_UNDER10_MASK     0xF00
#define RTC_RTC_TIMESET1_MINSET_UNDER10_SHIFT    8 
#define RTC_RTC_TIMESET1_MINSET_UNDER10_BIT      0xF
#define RTC_RTC_TIMESET1_MINSET_UNDER10_BITWIDTH 4
// MINSET_OVER10 bitfiled (RW) Reset=0
#define RTC_RTC_TIMESET1_MINSET_OVER10_MASK      0x7000
#define RTC_RTC_TIMESET1_MINSET_OVER10_SHIFT     12 
#define RTC_RTC_TIMESET1_MINSET_OVER10_BIT       0x7
#define RTC_RTC_TIMESET1_MINSET_OVER10_BITWIDTH  3
// reserved bitfiled (RO) Reset=0
#define RTC_RTC_TIMESET1_RESERVED_MASK           0xFFFF8000
#define RTC_RTC_TIMESET1_RESERVED_SHIFT          15 
#define RTC_RTC_TIMESET1_RESERVED_BIT            0x1FFFF
#define RTC_RTC_TIMESET1_RESERVED_BITWIDTH       17
// RTC_TIMESET2 Register
#define RTC_RTC_TIMESET2_OFS                     0x00000004
// HOURSET_UNDER10 bitfiled (RW) Reset=0
#define RTC_RTC_TIMESET2_HOURSET_UNDER10_MASK    0xF
#define RTC_RTC_TIMESET2_HOURSET_UNDER10_SHIFT   0 
#define RTC_RTC_TIMESET2_HOURSET_UNDER10_BIT     0xF
#define RTC_RTC_TIMESET2_HOURSET_UNDER10_BITWIDTH 4
// HOURSET_OVER10 bitfiled (RW) Reset=0
#define RTC_RTC_TIMESET2_HOURSET_OVER10_MASK     0x30
#define RTC_RTC_TIMESET2_HOURSET_OVER10_SHIFT    4 
#define RTC_RTC_TIMESET2_HOURSET_OVER10_BIT      0x3
#define RTC_RTC_TIMESET2_HOURSET_OVER10_BITWIDTH 2
// reserved2 bitfiled (RO) Reset=0
#define RTC_RTC_TIMESET2_RESERVED2_MASK          0xC0
#define RTC_RTC_TIMESET2_RESERVED2_SHIFT         6 
#define RTC_RTC_TIMESET2_RESERVED2_BIT           0x3
#define RTC_RTC_TIMESET2_RESERVED2_BITWIDTH      2
// DAYSET_UNDER10 bitfiled (RW) Reset=0
#define RTC_RTC_TIMESET2_DAYSET_UNDER10_MASK     0xF00
#define RTC_RTC_TIMESET2_DAYSET_UNDER10_SHIFT    8 
#define RTC_RTC_TIMESET2_DAYSET_UNDER10_BIT      0xF
#define RTC_RTC_TIMESET2_DAYSET_UNDER10_BITWIDTH 4
// DAYSET_OVER10 bitfiled (RW) Reset=0
#define RTC_RTC_TIMESET2_DAYSET_OVER10_MASK      0x3000
#define RTC_RTC_TIMESET2_DAYSET_OVER10_SHIFT     12 
#define RTC_RTC_TIMESET2_DAYSET_OVER10_BIT       0x3
#define RTC_RTC_TIMESET2_DAYSET_OVER10_BITWIDTH  2
// reserved bitfiled (RO) Reset=0
#define RTC_RTC_TIMESET2_RESERVED_MASK           0xFFFFC000
#define RTC_RTC_TIMESET2_RESERVED_SHIFT          14 
#define RTC_RTC_TIMESET2_RESERVED_BIT            0x3FFFF
#define RTC_RTC_TIMESET2_RESERVED_BITWIDTH       18
// RTC_TIMESET3 Register
#define RTC_RTC_TIMESET3_OFS                     0x00000008
// MONTHSET_UNDER10 bitfiled (RW) Reset=0
#define RTC_RTC_TIMESET3_MONTHSET_UNDER10_MASK   0xF
#define RTC_RTC_TIMESET3_MONTHSET_UNDER10_SHIFT  0 
#define RTC_RTC_TIMESET3_MONTHSET_UNDER10_BIT    0xF
#define RTC_RTC_TIMESET3_MONTHSET_UNDER10_BITWIDTH 4
// MONTHSET_OVER10 bitfiled (RW) Reset=0
#define RTC_RTC_TIMESET3_MONTHSET_OVER10_MASK    0x10
#define RTC_RTC_TIMESET3_MONTHSET_OVER10_SHIFT   4 
#define RTC_RTC_TIMESET3_MONTHSET_OVER10_BIT     0x1
#define RTC_RTC_TIMESET3_MONTHSET_OVER10_BITWIDTH 1
// WEEKSET bitfiled (RW) Reset=0
#define RTC_RTC_TIMESET3_WEEKSET_MASK            0xE0
#define RTC_RTC_TIMESET3_WEEKSET_SHIFT           5 
#define RTC_RTC_TIMESET3_WEEKSET_BIT             0x7
#define RTC_RTC_TIMESET3_WEEKSET_BITWIDTH        3
// YEARSET_UNDER10 bitfiled (RW) Reset=0
#define RTC_RTC_TIMESET3_YEARSET_UNDER10_MASK    0xF00
#define RTC_RTC_TIMESET3_YEARSET_UNDER10_SHIFT   8 
#define RTC_RTC_TIMESET3_YEARSET_UNDER10_BIT     0xF
#define RTC_RTC_TIMESET3_YEARSET_UNDER10_BITWIDTH 4
// YEARSET_OVER10 bitfiled (RW) Reset=0
#define RTC_RTC_TIMESET3_YEARSET_OVER10_MASK     0xF000
#define RTC_RTC_TIMESET3_YEARSET_OVER10_SHIFT    12 
#define RTC_RTC_TIMESET3_YEARSET_OVER10_BIT      0xF
#define RTC_RTC_TIMESET3_YEARSET_OVER10_BITWIDTH 4
// reserved bitfiled (RO) Reset=0
#define RTC_RTC_TIMESET3_RESERVED_MASK           0xFFFF0000
#define RTC_RTC_TIMESET3_RESERVED_SHIFT          16 
#define RTC_RTC_TIMESET3_RESERVED_BIT            0xFFFF
#define RTC_RTC_TIMESET3_RESERVED_BITWIDTH       16
// RTC_TIMESET4 Register
#define RTC_RTC_TIMESET4_OFS                     0x0000000C
// LEAP bitfiled (RW) Reset=0
#define RTC_RTC_TIMESET4_LEAP_MASK               0x3
#define RTC_RTC_TIMESET4_LEAP_SHIFT              0 
#define RTC_RTC_TIMESET4_LEAP_BIT                0x3
#define RTC_RTC_TIMESET4_LEAP_BITWIDTH           2
// reserved bitfiled (RO) Reset=0
#define RTC_RTC_TIMESET4_RESERVED_MASK           0xFFFFFFFC
#define RTC_RTC_TIMESET4_RESERVED_SHIFT          2 
#define RTC_RTC_TIMESET4_RESERVED_BIT            0x3FFFFFFF
#define RTC_RTC_TIMESET4_RESERVED_BITWIDTH       30
// RTC_CTRL Register
#define RTC_RTC_CTRL_OFS                         0x00000010
// ALRST bitfiled (RW) Reset=0
#define RTC_RTC_CTRL_ALRST_MASK                  0x1
#define RTC_RTC_CTRL_ALRST_SHIFT                 0 
#define RTC_RTC_CTRL_ALRST_BIT                   0x1
#define RTC_RTC_CTRL_ALRST_BITWIDTH              1
// ALEN bitfiled (RW) Reset=0
#define RTC_RTC_CTRL_ALEN_MASK                   0x2
#define RTC_RTC_CTRL_ALEN_SHIFT                  1 
#define RTC_RTC_CTRL_ALEN_BIT                    0x1
#define RTC_RTC_CTRL_ALEN_BITWIDTH               1
// PRRST bitfiled (RW) Reset=0
#define RTC_RTC_CTRL_PRRST_MASK                  0x4
#define RTC_RTC_CTRL_PRRST_SHIFT                 2 
#define RTC_RTC_CTRL_PRRST_BIT                   0x1
#define RTC_RTC_CTRL_PRRST_BITWIDTH              1
// PREN bitfiled (RW) Reset=0
#define RTC_RTC_CTRL_PREN_MASK                   0x8
#define RTC_RTC_CTRL_PREN_SHIFT                  3 
#define RTC_RTC_CTRL_PREN_BIT                    0x1
#define RTC_RTC_CTRL_PREN_BITWIDTH               1
// ADJUST bitfiled (RW) Reset=0
#define RTC_RTC_CTRL_ADJUST_MASK                 0x10
#define RTC_RTC_CTRL_ADJUST_SHIFT                4 
#define RTC_RTC_CTRL_ADJUST_BIT                  0x1
#define RTC_RTC_CTRL_ADJUST_BITWIDTH             1
// HR24_12 bitfiled (RW) Reset=0
#define RTC_RTC_CTRL_HR24_12_MASK                0x20
#define RTC_RTC_CTRL_HR24_12_SHIFT               5 
#define RTC_RTC_CTRL_HR24_12_BIT                 0x1
#define RTC_RTC_CTRL_HR24_12_BITWIDTH            1
// TMRST bitfiled (RW) Reset=0
#define RTC_RTC_CTRL_TMRST_MASK                  0x40
#define RTC_RTC_CTRL_TMRST_SHIFT                 6 
#define RTC_RTC_CTRL_TMRST_BIT                   0x1
#define RTC_RTC_CTRL_TMRST_BITWIDTH              1
// TMEN bitfiled (RW) Reset=0
#define RTC_RTC_CTRL_TMEN_MASK                   0x80
#define RTC_RTC_CTRL_TMEN_SHIFT                  7 
#define RTC_RTC_CTRL_TMEN_BIT                    0x1
#define RTC_RTC_CTRL_TMEN_BITWIDTH               1
// reserved bitfiled (RO) Reset=0
#define RTC_RTC_CTRL_RESERVED_MASK               0xFFFFFF00
#define RTC_RTC_CTRL_RESERVED_SHIFT              8 
#define RTC_RTC_CTRL_RESERVED_BIT                0xFFFFFF
#define RTC_RTC_CTRL_RESERVED_BITWIDTH           24
// RTC_RIS Register
#define RTC_RTC_RIS_OFS                          0x00000020
// ALARM_INTRAWST bitfiled (RO) Reset=0
#define RTC_RTC_RIS_ALARM_INTRAWST_MASK          0x1
#define RTC_RTC_RIS_ALARM_INTRAWST_SHIFT         0 
#define RTC_RTC_RIS_ALARM_INTRAWST_BIT           0x1
#define RTC_RTC_RIS_ALARM_INTRAWST_BITWIDTH      1
// PERIOD_INTRAWST bitfiled (RO) Reset=0
#define RTC_RTC_RIS_PERIOD_INTRAWST_MASK         0x2
#define RTC_RTC_RIS_PERIOD_INTRAWST_SHIFT        1 
#define RTC_RTC_RIS_PERIOD_INTRAWST_BIT          0x1
#define RTC_RTC_RIS_PERIOD_INTRAWST_BITWIDTH     1
// reserved bitfiled (RO) Reset=0
#define RTC_RTC_RIS_RESERVED_MASK                0xFFFFFFFC
#define RTC_RTC_RIS_RESERVED_SHIFT               2 
#define RTC_RTC_RIS_RESERVED_BIT                 0x3FFFFFFF
#define RTC_RTC_RIS_RESERVED_BITWIDTH            30
// RTC_MIS Register
#define RTC_RTC_MIS_OFS                          0x00000024
// ALARM_INTMASKST bitfiled (RO) Reset=0
#define RTC_RTC_MIS_ALARM_INTMASKST_MASK         0x1
#define RTC_RTC_MIS_ALARM_INTMASKST_SHIFT        0 
#define RTC_RTC_MIS_ALARM_INTMASKST_BIT          0x1
#define RTC_RTC_MIS_ALARM_INTMASKST_BITWIDTH     1
// PERIOD_INTMASKST bitfiled (RO) Reset=0
#define RTC_RTC_MIS_PERIOD_INTMASKST_MASK        0x2
#define RTC_RTC_MIS_PERIOD_INTMASKST_SHIFT       1 
#define RTC_RTC_MIS_PERIOD_INTMASKST_BIT         0x1
#define RTC_RTC_MIS_PERIOD_INTMASKST_BITWIDTH    1
// reserved bitfiled (RO) Reset=0
#define RTC_RTC_MIS_RESERVED_MASK                0xFFFFFFFC
#define RTC_RTC_MIS_RESERVED_SHIFT               2 
#define RTC_RTC_MIS_RESERVED_BIT                 0x3FFFFFFF
#define RTC_RTC_MIS_RESERVED_BITWIDTH            30
// RTC_INTMASK Register
#define RTC_RTC_INTMASK_OFS                      0x00000028
// ALARM_INTMASK bitfiled (RW) Reset=0
#define RTC_RTC_INTMASK_ALARM_INTMASK_MASK       0x1
#define RTC_RTC_INTMASK_ALARM_INTMASK_SHIFT      0 
#define RTC_RTC_INTMASK_ALARM_INTMASK_BIT        0x1
#define RTC_RTC_INTMASK_ALARM_INTMASK_BITWIDTH   1
// PERIOD_INTMASK bitfiled (RW) Reset=0
#define RTC_RTC_INTMASK_PERIOD_INTMASK_MASK      0x2
#define RTC_RTC_INTMASK_PERIOD_INTMASK_SHIFT     1 
#define RTC_RTC_INTMASK_PERIOD_INTMASK_BIT       0x1
#define RTC_RTC_INTMASK_PERIOD_INTMASK_BITWIDTH  1
// reserved bitfiled (RO) Reset=0
#define RTC_RTC_INTMASK_RESERVED_MASK            0xFFFFFFFC
#define RTC_RTC_INTMASK_RESERVED_SHIFT           2 
#define RTC_RTC_INTMASK_RESERVED_BIT             0x3FFFFFFF
#define RTC_RTC_INTMASK_RESERVED_BITWIDTH        30
// RTC_PERIODIC Register
#define RTC_RTC_PERIODIC_OFS                     0x0000002C
// PERIODIC_INTSET bitfiled (RW) Reset=0
#define RTC_RTC_PERIODIC_PERIODIC_INTSET_MASK    0x7
#define RTC_RTC_PERIODIC_PERIODIC_INTSET_SHIFT   0 
#define RTC_RTC_PERIODIC_PERIODIC_INTSET_BIT     0x7
#define RTC_RTC_PERIODIC_PERIODIC_INTSET_BITWIDTH 3
// reserved bitfiled (RO) Reset=0
#define RTC_RTC_PERIODIC_RESERVED_MASK           0xFFFFFFF8
#define RTC_RTC_PERIODIC_RESERVED_SHIFT          3 
#define RTC_RTC_PERIODIC_RESERVED_BIT            0x1FFFFFFF
#define RTC_RTC_PERIODIC_RESERVED_BITWIDTH       29
// RTC_PERIOD_INTCLR Register
#define RTC_RTC_PERIOD_INTCLR_OFS                0x00000030
// PERIOD_INTCLR bitfiled (RW) Reset=0
#define RTC_RTC_PERIOD_INTCLR_PERIOD_INTCLR_MASK 0xFFFFFFFF
#define RTC_RTC_PERIOD_INTCLR_PERIOD_INTCLR_SHIFT 0 
#define RTC_RTC_PERIOD_INTCLR_PERIOD_INTCLR_BIT  0xFFFFFFFF
#define RTC_RTC_PERIOD_INTCLR_PERIOD_INTCLR_BITWIDTH 32
// RTC_ALARM_INTCLR Register
#define RTC_RTC_ALARM_INTCLR_OFS                 0x00000034
// ALARM_INTCLR bitfiled (RW) Reset=0
#define RTC_RTC_ALARM_INTCLR_ALARM_INTCLR_MASK   0xFFFFFFFF
#define RTC_RTC_ALARM_INTCLR_ALARM_INTCLR_SHIFT  0 
#define RTC_RTC_ALARM_INTCLR_ALARM_INTCLR_BIT    0xFFFFFFFF
#define RTC_RTC_ALARM_INTCLR_ALARM_INTCLR_BITWIDTH 32
// RTC_CURRENT1 Register
#define RTC_RTC_CURRENT1_OFS                     0x00000040
// SECVAL_UNDER10 bitfiled (RO) Reset=0
#define RTC_RTC_CURRENT1_SECVAL_UNDER10_MASK     0xF
#define RTC_RTC_CURRENT1_SECVAL_UNDER10_SHIFT    0 
#define RTC_RTC_CURRENT1_SECVAL_UNDER10_BIT      0xF
#define RTC_RTC_CURRENT1_SECVAL_UNDER10_BITWIDTH 4
// SECVAL_OVER10 bitfiled (RO) Reset=0
#define RTC_RTC_CURRENT1_SECVAL_OVER10_MASK      0x70
#define RTC_RTC_CURRENT1_SECVAL_OVER10_SHIFT     4 
#define RTC_RTC_CURRENT1_SECVAL_OVER10_BIT       0x7
#define RTC_RTC_CURRENT1_SECVAL_OVER10_BITWIDTH  3
// reserved2 bitfiled (RO) Reset=0
#define RTC_RTC_CURRENT1_RESERVED2_MASK          0x80
#define RTC_RTC_CURRENT1_RESERVED2_SHIFT         7 
#define RTC_RTC_CURRENT1_RESERVED2_BIT           0x1
#define RTC_RTC_CURRENT1_RESERVED2_BITWIDTH      1
// MINVAL_UNDER10 bitfiled (RO) Reset=0
#define RTC_RTC_CURRENT1_MINVAL_UNDER10_MASK     0xF00
#define RTC_RTC_CURRENT1_MINVAL_UNDER10_SHIFT    8 
#define RTC_RTC_CURRENT1_MINVAL_UNDER10_BIT      0xF
#define RTC_RTC_CURRENT1_MINVAL_UNDER10_BITWIDTH 4
// MINVAL_OVER10 bitfiled (RO) Reset=0
#define RTC_RTC_CURRENT1_MINVAL_OVER10_MASK      0x7000
#define RTC_RTC_CURRENT1_MINVAL_OVER10_SHIFT     12 
#define RTC_RTC_CURRENT1_MINVAL_OVER10_BIT       0x7
#define RTC_RTC_CURRENT1_MINVAL_OVER10_BITWIDTH  3
// reserved bitfiled (RO) Reset=0
#define RTC_RTC_CURRENT1_RESERVED_MASK           0xFFFF8000
#define RTC_RTC_CURRENT1_RESERVED_SHIFT          15 
#define RTC_RTC_CURRENT1_RESERVED_BIT            0x1FFFF
#define RTC_RTC_CURRENT1_RESERVED_BITWIDTH       17
// RTC_CURRENT2 Register
#define RTC_RTC_CURRENT2_OFS                     0x00000044
// HOURVAL_UNDER10 bitfiled (RO) Reset=0
#define RTC_RTC_CURRENT2_HOURVAL_UNDER10_MASK    0xF
#define RTC_RTC_CURRENT2_HOURVAL_UNDER10_SHIFT   0 
#define RTC_RTC_CURRENT2_HOURVAL_UNDER10_BIT     0xF
#define RTC_RTC_CURRENT2_HOURVAL_UNDER10_BITWIDTH 4
// HOURVAL_OVER10 bitfiled (RO) Reset=0
#define RTC_RTC_CURRENT2_HOURVAL_OVER10_MASK     0x30
#define RTC_RTC_CURRENT2_HOURVAL_OVER10_SHIFT    4 
#define RTC_RTC_CURRENT2_HOURVAL_OVER10_BIT      0x3
#define RTC_RTC_CURRENT2_HOURVAL_OVER10_BITWIDTH 2
// reserved2 bitfiled (RO) Reset=0
#define RTC_RTC_CURRENT2_RESERVED2_MASK          0xC0
#define RTC_RTC_CURRENT2_RESERVED2_SHIFT         6 
#define RTC_RTC_CURRENT2_RESERVED2_BIT           0x3
#define RTC_RTC_CURRENT2_RESERVED2_BITWIDTH      2
// DAYVAL_UNDER10 bitfiled (RO) Reset=0
#define RTC_RTC_CURRENT2_DAYVAL_UNDER10_MASK     0xF00
#define RTC_RTC_CURRENT2_DAYVAL_UNDER10_SHIFT    8 
#define RTC_RTC_CURRENT2_DAYVAL_UNDER10_BIT      0xF
#define RTC_RTC_CURRENT2_DAYVAL_UNDER10_BITWIDTH 4
// DAYVAL_OVER10 bitfiled (RO) Reset=0
#define RTC_RTC_CURRENT2_DAYVAL_OVER10_MASK      0x3000
#define RTC_RTC_CURRENT2_DAYVAL_OVER10_SHIFT     12 
#define RTC_RTC_CURRENT2_DAYVAL_OVER10_BIT       0x3
#define RTC_RTC_CURRENT2_DAYVAL_OVER10_BITWIDTH  2
// reserved bitfiled (RO) Reset=0
#define RTC_RTC_CURRENT2_RESERVED_MASK           0xFFFFC000
#define RTC_RTC_CURRENT2_RESERVED_SHIFT          14 
#define RTC_RTC_CURRENT2_RESERVED_BIT            0x3FFFF
#define RTC_RTC_CURRENT2_RESERVED_BITWIDTH       18
// RTC_CURRENT3 Register
#define RTC_RTC_CURRENT3_OFS                     0x00000048
// MONTHVAL_UNDER10 bitfiled (RO) Reset=0
#define RTC_RTC_CURRENT3_MONTHVAL_UNDER10_MASK   0xF
#define RTC_RTC_CURRENT3_MONTHVAL_UNDER10_SHIFT  0 
#define RTC_RTC_CURRENT3_MONTHVAL_UNDER10_BIT    0xF
#define RTC_RTC_CURRENT3_MONTHVAL_UNDER10_BITWIDTH 4
// MONTHVAL_OVER10 bitfiled (RO) Reset=0
#define RTC_RTC_CURRENT3_MONTHVAL_OVER10_MASK    0x10
#define RTC_RTC_CURRENT3_MONTHVAL_OVER10_SHIFT   4 
#define RTC_RTC_CURRENT3_MONTHVAL_OVER10_BIT     0x1
#define RTC_RTC_CURRENT3_MONTHVAL_OVER10_BITWIDTH 1
// WEEKVAL bitfiled (RO) Reset=0
#define RTC_RTC_CURRENT3_WEEKVAL_MASK            0xE0
#define RTC_RTC_CURRENT3_WEEKVAL_SHIFT           5 
#define RTC_RTC_CURRENT3_WEEKVAL_BIT             0x7
#define RTC_RTC_CURRENT3_WEEKVAL_BITWIDTH        3
// YEARVAL_UNDER10 bitfiled (RO) Reset=0
#define RTC_RTC_CURRENT3_YEARVAL_UNDER10_MASK    0xF00
#define RTC_RTC_CURRENT3_YEARVAL_UNDER10_SHIFT   8 
#define RTC_RTC_CURRENT3_YEARVAL_UNDER10_BIT     0xF
#define RTC_RTC_CURRENT3_YEARVAL_UNDER10_BITWIDTH 4
// YEARVAL_OVER10 bitfiled (RO) Reset=0
#define RTC_RTC_CURRENT3_YEARVAL_OVER10_MASK     0xF000
#define RTC_RTC_CURRENT3_YEARVAL_OVER10_SHIFT    12 
#define RTC_RTC_CURRENT3_YEARVAL_OVER10_BIT      0xF
#define RTC_RTC_CURRENT3_YEARVAL_OVER10_BITWIDTH 4
// reserved bitfiled (RO) Reset=0
#define RTC_RTC_CURRENT3_RESERVED_MASK           0xFFFF0000
#define RTC_RTC_CURRENT3_RESERVED_SHIFT          16 
#define RTC_RTC_CURRENT3_RESERVED_BIT            0xFFFF
#define RTC_RTC_CURRENT3_RESERVED_BITWIDTH       16
// RTC_CURRENT4 Register
#define RTC_RTC_CURRENT4_OFS                     0x0000004C
// LEAP bitfiled (RO) Reset=0
#define RTC_RTC_CURRENT4_LEAP_MASK               0x3
#define RTC_RTC_CURRENT4_LEAP_SHIFT              0 
#define RTC_RTC_CURRENT4_LEAP_BIT                0x3
#define RTC_RTC_CURRENT4_LEAP_BITWIDTH           2
// reserved bitfiled (RO) Reset=0
#define RTC_RTC_CURRENT4_RESERVED_MASK           0xFFFFFFFC
#define RTC_RTC_CURRENT4_RESERVED_SHIFT          2 
#define RTC_RTC_CURRENT4_RESERVED_BIT            0x3FFFFFFF
#define RTC_RTC_CURRENT4_RESERVED_BITWIDTH       30
// RTC_ALARM1 Register
#define RTC_RTC_ALARM1_OFS                       0x00000050
// reserved2 bitfiled (RO) Reset=0
#define RTC_RTC_ALARM1_RESERVED2_MASK            0xFF
#define RTC_RTC_ALARM1_RESERVED2_SHIFT           0 
#define RTC_RTC_ALARM1_RESERVED2_BIT             0xFF
#define RTC_RTC_ALARM1_RESERVED2_BITWIDTH        8
// AL_MINSET_UNDER10 bitfiled (RW) Reset=0
#define RTC_RTC_ALARM1_AL_MINSET_UNDER10_MASK    0xF00
#define RTC_RTC_ALARM1_AL_MINSET_UNDER10_SHIFT   8 
#define RTC_RTC_ALARM1_AL_MINSET_UNDER10_BIT     0xF
#define RTC_RTC_ALARM1_AL_MINSET_UNDER10_BITWIDTH 4
// AL_MINSET_OVER10 bitfiled (RW) Reset=0
#define RTC_RTC_ALARM1_AL_MINSET_OVER10_MASK     0x7000
#define RTC_RTC_ALARM1_AL_MINSET_OVER10_SHIFT    12 
#define RTC_RTC_ALARM1_AL_MINSET_OVER10_BIT      0x7
#define RTC_RTC_ALARM1_AL_MINSET_OVER10_BITWIDTH 3
// reserved bitfiled (RO) Reset=0
#define RTC_RTC_ALARM1_RESERVED_MASK             0xFFFF8000
#define RTC_RTC_ALARM1_RESERVED_SHIFT            15 
#define RTC_RTC_ALARM1_RESERVED_BIT              0x1FFFF
#define RTC_RTC_ALARM1_RESERVED_BITWIDTH         17
// RTC_ALARM2 Register
#define RTC_RTC_ALARM2_OFS                       0x00000054
// AL_HOURSET_UNDER10 bitfiled (RW) Reset=0
#define RTC_RTC_ALARM2_AL_HOURSET_UNDER10_MASK   0xF
#define RTC_RTC_ALARM2_AL_HOURSET_UNDER10_SHIFT  0 
#define RTC_RTC_ALARM2_AL_HOURSET_UNDER10_BIT    0xF
#define RTC_RTC_ALARM2_AL_HOURSET_UNDER10_BITWIDTH 4
// AL_HOURSET_OVER10 bitfiled (RW) Reset=0
#define RTC_RTC_ALARM2_AL_HOURSET_OVER10_MASK    0x30
#define RTC_RTC_ALARM2_AL_HOURSET_OVER10_SHIFT   4 
#define RTC_RTC_ALARM2_AL_HOURSET_OVER10_BIT     0x3
#define RTC_RTC_ALARM2_AL_HOURSET_OVER10_BITWIDTH 2
// reserved2 bitfiled (RO) Reset=0
#define RTC_RTC_ALARM2_RESERVED2_MASK            0xC0
#define RTC_RTC_ALARM2_RESERVED2_SHIFT           6 
#define RTC_RTC_ALARM2_RESERVED2_BIT             0x3
#define RTC_RTC_ALARM2_RESERVED2_BITWIDTH        2
// AL_DAYSET_UNDER10 bitfiled (RW) Reset=0
#define RTC_RTC_ALARM2_AL_DAYSET_UNDER10_MASK    0xF00
#define RTC_RTC_ALARM2_AL_DAYSET_UNDER10_SHIFT   8 
#define RTC_RTC_ALARM2_AL_DAYSET_UNDER10_BIT     0xF
#define RTC_RTC_ALARM2_AL_DAYSET_UNDER10_BITWIDTH 4
// AL_DAYSET_OVER10 bitfiled (RW) Reset=0
#define RTC_RTC_ALARM2_AL_DAYSET_OVER10_MASK     0x3000
#define RTC_RTC_ALARM2_AL_DAYSET_OVER10_SHIFT    12 
#define RTC_RTC_ALARM2_AL_DAYSET_OVER10_BIT      0x3
#define RTC_RTC_ALARM2_AL_DAYSET_OVER10_BITWIDTH 2
// reserved bitfiled (RO) Reset=0
#define RTC_RTC_ALARM2_RESERVED_MASK             0xFFFFC000
#define RTC_RTC_ALARM2_RESERVED_SHIFT            14 
#define RTC_RTC_ALARM2_RESERVED_BIT              0x3FFFF
#define RTC_RTC_ALARM2_RESERVED_BITWIDTH         18
// RTC_ALARM3 Register
#define RTC_RTC_ALARM3_OFS                       0x00000058
// reserved2 bitfiled (RO) Reset=0
#define RTC_RTC_ALARM3_RESERVED2_MASK            0x1F
#define RTC_RTC_ALARM3_RESERVED2_SHIFT           0 
#define RTC_RTC_ALARM3_RESERVED2_BIT             0x1F
#define RTC_RTC_ALARM3_RESERVED2_BITWIDTH        5
// AL_WEEKSET bitfiled (RW) Reset=0
#define RTC_RTC_ALARM3_AL_WEEKSET_MASK           0xE0
#define RTC_RTC_ALARM3_AL_WEEKSET_SHIFT          5 
#define RTC_RTC_ALARM3_AL_WEEKSET_BIT            0x7
#define RTC_RTC_ALARM3_AL_WEEKSET_BITWIDTH       3
// reserved bitfiled (RO) Reset=0
#define RTC_RTC_ALARM3_RESERVED_MASK             0xFFFFFF00
#define RTC_RTC_ALARM3_RESERVED_SHIFT            8 
#define RTC_RTC_ALARM3_RESERVED_BIT              0xFFFFFF
#define RTC_RTC_ALARM3_RESERVED_BITWIDTH         24
// RTC_TESTMODE Register
#define RTC_RTC_TESTMODE_OFS                     0x00000F00
// TESTSET bitfiled (RW) Reset=0
#define RTC_RTC_TESTMODE_TESTSET_MASK            0x1
#define RTC_RTC_TESTMODE_TESTSET_SHIFT           0 
#define RTC_RTC_TESTMODE_TESTSET_BIT             0x1
#define RTC_RTC_TESTMODE_TESTSET_BITWIDTH        1
// reserved bitfiled (RO) Reset=0
#define RTC_RTC_TESTMODE_RESERVED_MASK           0xFFFFFFFE
#define RTC_RTC_TESTMODE_RESERVED_SHIFT          1 
#define RTC_RTC_TESTMODE_RESERVED_BIT            0x7FFFFFFF
#define RTC_RTC_TESTMODE_RESERVED_BITWIDTH       31
// RTC_TESTINT Register
#define RTC_RTC_TESTINT_OFS                      0x00000F04
// TESTINT_ALARM bitfiled (RW) Reset=0
#define RTC_RTC_TESTINT_TESTINT_ALARM_MASK       0x1
#define RTC_RTC_TESTINT_TESTINT_ALARM_SHIFT      0 
#define RTC_RTC_TESTINT_TESTINT_ALARM_BIT        0x1
#define RTC_RTC_TESTINT_TESTINT_ALARM_BITWIDTH   1
// TESTINT_PERIOD bitfiled (RW) Reset=0
#define RTC_RTC_TESTINT_TESTINT_PERIOD_MASK      0x2
#define RTC_RTC_TESTINT_TESTINT_PERIOD_SHIFT     1 
#define RTC_RTC_TESTINT_TESTINT_PERIOD_BIT       0x1
#define RTC_RTC_TESTINT_TESTINT_PERIOD_BITWIDTH  1
// reserved bitfiled (RO) Reset=0
#define RTC_RTC_TESTINT_RESERVED_MASK            0xFFFFFFFC
#define RTC_RTC_TESTINT_RESERVED_SHIFT           2 
#define RTC_RTC_TESTINT_RESERVED_BIT             0x3FFFFFFF
#define RTC_RTC_TESTINT_RESERVED_BITWIDTH        30
// RTC_TESTCLK Register
#define RTC_RTC_TESTCLK_OFS                      0x00000F08
// SEC_ACC bitfiled (RW) Reset=0
#define RTC_RTC_TESTCLK_SEC_ACC_MASK             0x1
#define RTC_RTC_TESTCLK_SEC_ACC_SHIFT            0 
#define RTC_RTC_TESTCLK_SEC_ACC_BIT              0x1
#define RTC_RTC_TESTCLK_SEC_ACC_BITWIDTH         1
// MIN_ACC bitfiled (RW) Reset=0
#define RTC_RTC_TESTCLK_MIN_ACC_MASK             0x2
#define RTC_RTC_TESTCLK_MIN_ACC_SHIFT            1 
#define RTC_RTC_TESTCLK_MIN_ACC_BIT              0x1
#define RTC_RTC_TESTCLK_MIN_ACC_BITWIDTH         1
// HOUR_ACC bitfiled (RW) Reset=0
#define RTC_RTC_TESTCLK_HOUR_ACC_MASK            0x4
#define RTC_RTC_TESTCLK_HOUR_ACC_SHIFT           2 
#define RTC_RTC_TESTCLK_HOUR_ACC_BIT             0x1
#define RTC_RTC_TESTCLK_HOUR_ACC_BITWIDTH        1
// DAY_ACC bitfiled (RW) Reset=0
#define RTC_RTC_TESTCLK_DAY_ACC_MASK             0x8
#define RTC_RTC_TESTCLK_DAY_ACC_SHIFT            3 
#define RTC_RTC_TESTCLK_DAY_ACC_BIT              0x1
#define RTC_RTC_TESTCLK_DAY_ACC_BITWIDTH         1
// MON_ACC bitfiled (RW) Reset=0
#define RTC_RTC_TESTCLK_MON_ACC_MASK             0x10
#define RTC_RTC_TESTCLK_MON_ACC_SHIFT            4 
#define RTC_RTC_TESTCLK_MON_ACC_BIT              0x1
#define RTC_RTC_TESTCLK_MON_ACC_BITWIDTH         1
// YEAR_ACC bitfiled (RW) Reset=0
#define RTC_RTC_TESTCLK_YEAR_ACC_MASK            0x20
#define RTC_RTC_TESTCLK_YEAR_ACC_SHIFT           5 
#define RTC_RTC_TESTCLK_YEAR_ACC_BIT             0x1
#define RTC_RTC_TESTCLK_YEAR_ACC_BITWIDTH        1
// reserved bitfiled (RO) Reset=0
#define RTC_RTC_TESTCLK_RESERVED_MASK            0xFFFFFFC0
#define RTC_RTC_TESTCLK_RESERVED_SHIFT           6 
#define RTC_RTC_TESTCLK_RESERVED_BIT             0x3FFFFFF
#define RTC_RTC_TESTCLK_RESERVED_BITWIDTH        26
// RTC_TESTCLKLD Register
#define RTC_RTC_TESTCLKLD_OFS                    0x00000F0C
// TESTCLKLD bitfiled (RW) Reset=0
#define RTC_RTC_TESTCLKLD_TESTCLKLD_MASK         0x1
#define RTC_RTC_TESTCLKLD_TESTCLKLD_SHIFT        0 
#define RTC_RTC_TESTCLKLD_TESTCLKLD_BIT          0x1
#define RTC_RTC_TESTCLKLD_TESTCLKLD_BITWIDTH     1
// reserved bitfiled (RO) Reset=0
#define RTC_RTC_TESTCLKLD_RESERVED_MASK          0xFFFFFFFE
#define RTC_RTC_TESTCLKLD_RESERVED_SHIFT         1 
#define RTC_RTC_TESTCLKLD_RESERVED_BIT           0x7FFFFFFF
#define RTC_RTC_TESTCLKLD_RESERVED_BITWIDTH      31
// RTC_CellID0 Register
#define RTC_RTC_CELLID0_OFS                      0x00000FF0
// RTC_CellID0 bitfiled (RO) Reset=1101
#define RTC_RTC_CELLID0_RTC_CELLID0_MASK         0xFF
#define RTC_RTC_CELLID0_RTC_CELLID0_SHIFT        0 
#define RTC_RTC_CELLID0_RTC_CELLID0_BIT          0xFF
#define RTC_RTC_CELLID0_RTC_CELLID0_BITWIDTH     8
// reserved bitfiled (RO) Reset=0
#define RTC_RTC_CELLID0_RESERVED_MASK            0xFFFFFF00
#define RTC_RTC_CELLID0_RESERVED_SHIFT           8 
#define RTC_RTC_CELLID0_RESERVED_BIT             0xFFFFFF
#define RTC_RTC_CELLID0_RESERVED_BITWIDTH        24
// RTC_CellID1 Register
#define RTC_RTC_CELLID1_OFS                      0x00000FF4
// RTC_CellID1 bitfiled (RO) Reset=11110000
#define RTC_RTC_CELLID1_RTC_CELLID1_MASK         0xFF
#define RTC_RTC_CELLID1_RTC_CELLID1_SHIFT        0 
#define RTC_RTC_CELLID1_RTC_CELLID1_BIT          0xFF
#define RTC_RTC_CELLID1_RTC_CELLID1_BITWIDTH     8
// reserved bitfiled (RO) Reset=0
#define RTC_RTC_CELLID1_RESERVED_MASK            0xFFFFFF00
#define RTC_RTC_CELLID1_RESERVED_SHIFT           8 
#define RTC_RTC_CELLID1_RESERVED_BIT             0xFFFFFF
#define RTC_RTC_CELLID1_RESERVED_BITWIDTH        24
// RTC_CellID2 Register
#define RTC_RTC_CELLID2_OFS                      0x00000FF8
// RTC_CellID2 bitfiled (RO) Reset=101
#define RTC_RTC_CELLID2_RTC_CELLID2_MASK         0xFF
#define RTC_RTC_CELLID2_RTC_CELLID2_SHIFT        0 
#define RTC_RTC_CELLID2_RTC_CELLID2_BIT          0xFF
#define RTC_RTC_CELLID2_RTC_CELLID2_BITWIDTH     8
// reserved bitfiled (RO) Reset=0
#define RTC_RTC_CELLID2_RESERVED_MASK            0xFFFFFF00
#define RTC_RTC_CELLID2_RESERVED_SHIFT           8 
#define RTC_RTC_CELLID2_RESERVED_BIT             0xFFFFFF
#define RTC_RTC_CELLID2_RESERVED_BITWIDTH        24
// RTC_CellID3 Register
#define RTC_RTC_CELLID3_OFS                      0x00000FFC
// RTC_CellID3 bitfiled (RO) Reset=10110001
#define RTC_RTC_CELLID3_RTC_CELLID3_MASK         0xFF
#define RTC_RTC_CELLID3_RTC_CELLID3_SHIFT        0 
#define RTC_RTC_CELLID3_RTC_CELLID3_BIT          0xFF
#define RTC_RTC_CELLID3_RTC_CELLID3_BITWIDTH     8
// reserved bitfiled (RO) Reset=0
#define RTC_RTC_CELLID3_RESERVED_MASK            0xFFFFFF00
#define RTC_RTC_CELLID3_RESERVED_SHIFT           8 
#define RTC_RTC_CELLID3_RESERVED_BIT             0xFFFFFF
#define RTC_RTC_CELLID3_RESERVED_BITWIDTH        24

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* _RTC_REG_DEF_H */
