/*
 * arch/arm/mach-tz2000/include/mach/regs/telomere_reg_def.h
 *
 * (C) Copyright TOSHIBA Corporation
 * Semiconductor & Storage Products Company 2013
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#ifndef _TELOMERE_REG_DEF_H
#define _TELOMERE_REG_DEF_H

#ifdef __cplusplus
extern  {
#endif /* __cplusplus */

// NCM_MODE Register
#define TELOMERE_NCM_MODE_OFS                    0x00000000
// MODE bitfiled (RW) Reset=1
#define TELOMERE_NCM_MODE_MODE_MASK              0x3
#define TELOMERE_NCM_MODE_MODE_SHIFT             0 
#define TELOMERE_NCM_MODE_MODE_BIT               0x3
#define TELOMERE_NCM_MODE_MODE_BITWIDTH          2
// reserved bitfiled (RO) Reset=0
#define TELOMERE_NCM_MODE_RESERVED_MASK          0xFFFFFFFC
#define TELOMERE_NCM_MODE_RESERVED_SHIFT         2 
#define TELOMERE_NCM_MODE_RESERVED_BIT           0x3FFFFFFF
#define TELOMERE_NCM_MODE_RESERVED_BITWIDTH      30
// NCM_STAT Register
#define TELOMERE_NCM_STAT_OFS                    0x00000014
// STAT bitfiled (RO) Reset=0
#define TELOMERE_NCM_STAT_STAT_MASK              0x7
#define TELOMERE_NCM_STAT_STAT_SHIFT             0 
#define TELOMERE_NCM_STAT_STAT_BIT               0x7
#define TELOMERE_NCM_STAT_STAT_BITWIDTH          3
// reserved bitfiled (RO) Reset=0
#define TELOMERE_NCM_STAT_RESERVED_MASK          0xFFFFFFF8
#define TELOMERE_NCM_STAT_RESERVED_SHIFT         3 
#define TELOMERE_NCM_STAT_RESERVED_BIT           0x1FFFFFFF
#define TELOMERE_NCM_STAT_RESERVED_BITWIDTH      29
// NANDC_SETTING Register
#define TELOMERE_NANDC_SETTING_OFS               0x00000024
// READY bitfiled (RW) Reset=0
#define TELOMERE_NANDC_SETTING_READY_MASK        0x1
#define TELOMERE_NANDC_SETTING_READY_SHIFT       0 
#define TELOMERE_NANDC_SETTING_READY_BIT         0x1
#define TELOMERE_NANDC_SETTING_READY_BITWIDTH    1
// CACHE_READY bitfiled (RW) Reset=0
#define TELOMERE_NANDC_SETTING_CACHE_READY_MASK  0x2
#define TELOMERE_NANDC_SETTING_CACHE_READY_SHIFT 1 
#define TELOMERE_NANDC_SETTING_CACHE_READY_BIT   0x1
#define TELOMERE_NANDC_SETTING_CACHE_READY_BITWIDTH 1
// reserved2 bitfiled (RO) Reset=0
#define TELOMERE_NANDC_SETTING_RESERVED2_MASK    0xFFC
#define TELOMERE_NANDC_SETTING_RESERVED2_SHIFT   2 
#define TELOMERE_NANDC_SETTING_RESERVED2_BIT     0x3FF
#define TELOMERE_NANDC_SETTING_RESERVED2_BITWIDTH 10
// MEM_SIZE bitfiled (RW) Reset=0
#define TELOMERE_NANDC_SETTING_MEM_SIZE_MASK     0xF000
#define TELOMERE_NANDC_SETTING_MEM_SIZE_SHIFT    12 
#define TELOMERE_NANDC_SETTING_MEM_SIZE_BIT      0xF
#define TELOMERE_NANDC_SETTING_MEM_SIZE_BITWIDTH 4
// STORAGE_SIZE bitfiled (RW) Reset=0
#define TELOMERE_NANDC_SETTING_STORAGE_SIZE_MASK 0xF0000
#define TELOMERE_NANDC_SETTING_STORAGE_SIZE_SHIFT 16 
#define TELOMERE_NANDC_SETTING_STORAGE_SIZE_BIT  0xF
#define TELOMERE_NANDC_SETTING_STORAGE_SIZE_BITWIDTH 4
// reserved bitfiled (RO) Reset=0
#define TELOMERE_NANDC_SETTING_RESERVED_MASK     0xFFF00000
#define TELOMERE_NANDC_SETTING_RESERVED_SHIFT    20 
#define TELOMERE_NANDC_SETTING_RESERVED_BIT      0xFFF
#define TELOMERE_NANDC_SETTING_RESERVED_BITWIDTH 12
// NANDC_STAT Register
#define TELOMERE_NANDC_STAT_OFS                  0x00000028
// VALUE bitfiled (RW) Reset=11111111111111111111111111111111
#define TELOMERE_NANDC_STAT_VALUE_MASK           0xFFFFFFFF
#define TELOMERE_NANDC_STAT_VALUE_SHIFT          0 
#define TELOMERE_NANDC_STAT_VALUE_BIT            0xFFFFFFFF
#define TELOMERE_NANDC_STAT_VALUE_BITWIDTH       32
// INTM_STAT Register
#define TELOMERE_INTM_STAT_OFS                   0x00000080
// CACHEOP bitfiled (RO) Reset=0
#define TELOMERE_INTM_STAT_CACHEOP_MASK          0x1
#define TELOMERE_INTM_STAT_CACHEOP_SHIFT         0 
#define TELOMERE_INTM_STAT_CACHEOP_BIT           0x1
#define TELOMERE_INTM_STAT_CACHEOP_BITWIDTH      1
// MAILBOX bitfiled (RO) Reset=0
#define TELOMERE_INTM_STAT_MAILBOX_MASK          0x2
#define TELOMERE_INTM_STAT_MAILBOX_SHIFT         1 
#define TELOMERE_INTM_STAT_MAILBOX_BIT           0x1
#define TELOMERE_INTM_STAT_MAILBOX_BITWIDTH      1
// AXI_ERROR bitfiled (RO) Reset=0
#define TELOMERE_INTM_STAT_AXI_ERROR_MASK        0x4
#define TELOMERE_INTM_STAT_AXI_ERROR_SHIFT       2 
#define TELOMERE_INTM_STAT_AXI_ERROR_BIT         0x1
#define TELOMERE_INTM_STAT_AXI_ERROR_BITWIDTH    1
// CACHE_ACCESS_ERROR bitfiled (RO) Reset=0
#define TELOMERE_INTM_STAT_CACHE_ACCESS_ERROR_MASK 0x8
#define TELOMERE_INTM_STAT_CACHE_ACCESS_ERROR_SHIFT 3 
#define TELOMERE_INTM_STAT_CACHE_ACCESS_ERROR_BIT 0x1
#define TELOMERE_INTM_STAT_CACHE_ACCESS_ERROR_BITWIDTH 1
// reserved bitfiled (RO) Reset=0
#define TELOMERE_INTM_STAT_RESERVED_MASK         0xFFFFFFF0
#define TELOMERE_INTM_STAT_RESERVED_SHIFT        4 
#define TELOMERE_INTM_STAT_RESERVED_BIT          0xFFFFFFF
#define TELOMERE_INTM_STAT_RESERVED_BITWIDTH     28
// INTM_MSKEDSTAT Register
#define TELOMERE_INTM_MSKEDSTAT_OFS              0x00000084
// CACHEOP bitfiled (RO) Reset=0
#define TELOMERE_INTM_MSKEDSTAT_CACHEOP_MASK     0x1
#define TELOMERE_INTM_MSKEDSTAT_CACHEOP_SHIFT    0 
#define TELOMERE_INTM_MSKEDSTAT_CACHEOP_BIT      0x1
#define TELOMERE_INTM_MSKEDSTAT_CACHEOP_BITWIDTH 1
// MAILBOX bitfiled (RO) Reset=0
#define TELOMERE_INTM_MSKEDSTAT_MAILBOX_MASK     0x2
#define TELOMERE_INTM_MSKEDSTAT_MAILBOX_SHIFT    1 
#define TELOMERE_INTM_MSKEDSTAT_MAILBOX_BIT      0x1
#define TELOMERE_INTM_MSKEDSTAT_MAILBOX_BITWIDTH 1
// AXI_ERROR bitfiled (RO) Reset=0
#define TELOMERE_INTM_MSKEDSTAT_AXI_ERROR_MASK   0x4
#define TELOMERE_INTM_MSKEDSTAT_AXI_ERROR_SHIFT  2 
#define TELOMERE_INTM_MSKEDSTAT_AXI_ERROR_BIT    0x1
#define TELOMERE_INTM_MSKEDSTAT_AXI_ERROR_BITWIDTH 1
// CACHE_ACCESS_ERROR bitfiled (RO) Reset=0
#define TELOMERE_INTM_MSKEDSTAT_CACHE_ACCESS_ERROR_MASK 0x8
#define TELOMERE_INTM_MSKEDSTAT_CACHE_ACCESS_ERROR_SHIFT 3 
#define TELOMERE_INTM_MSKEDSTAT_CACHE_ACCESS_ERROR_BIT 0x1
#define TELOMERE_INTM_MSKEDSTAT_CACHE_ACCESS_ERROR_BITWIDTH 1
// reserved bitfiled (RO) Reset=0
#define TELOMERE_INTM_MSKEDSTAT_RESERVED_MASK    0xFFFFFFF0
#define TELOMERE_INTM_MSKEDSTAT_RESERVED_SHIFT   4 
#define TELOMERE_INTM_MSKEDSTAT_RESERVED_BIT     0xFFFFFFF
#define TELOMERE_INTM_MSKEDSTAT_RESERVED_BITWIDTH 28
// INTM_CLR Register
#define TELOMERE_INTM_CLR_OFS                    0x00000088
// CACHEOP bitfiled (RW) Reset=0
#define TELOMERE_INTM_CLR_CACHEOP_MASK           0x1
#define TELOMERE_INTM_CLR_CACHEOP_SHIFT          0 
#define TELOMERE_INTM_CLR_CACHEOP_BIT            0x1
#define TELOMERE_INTM_CLR_CACHEOP_BITWIDTH       1
// reserved2 bitfiled (RO) Reset=0
#define TELOMERE_INTM_CLR_RESERVED2_MASK         0x2
#define TELOMERE_INTM_CLR_RESERVED2_SHIFT        1 
#define TELOMERE_INTM_CLR_RESERVED2_BIT          0x1
#define TELOMERE_INTM_CLR_RESERVED2_BITWIDTH     1
// AXI_ERROR bitfiled (RW) Reset=0
#define TELOMERE_INTM_CLR_AXI_ERROR_MASK         0x4
#define TELOMERE_INTM_CLR_AXI_ERROR_SHIFT        2 
#define TELOMERE_INTM_CLR_AXI_ERROR_BIT          0x1
#define TELOMERE_INTM_CLR_AXI_ERROR_BITWIDTH     1
// CACHE_ACCESS_ERROR bitfiled (RW) Reset=0
#define TELOMERE_INTM_CLR_CACHE_ACCESS_ERROR_MASK 0x8
#define TELOMERE_INTM_CLR_CACHE_ACCESS_ERROR_SHIFT 3 
#define TELOMERE_INTM_CLR_CACHE_ACCESS_ERROR_BIT 0x1
#define TELOMERE_INTM_CLR_CACHE_ACCESS_ERROR_BITWIDTH 1
// reserved bitfiled (RO) Reset=0
#define TELOMERE_INTM_CLR_RESERVED_MASK          0xFFFFFFF0
#define TELOMERE_INTM_CLR_RESERVED_SHIFT         4 
#define TELOMERE_INTM_CLR_RESERVED_BIT           0xFFFFFFF
#define TELOMERE_INTM_CLR_RESERVED_BITWIDTH      28
// INTM_MASK Register
#define TELOMERE_INTM_MASK_OFS                   0x0000008C
// CACHEOP bitfiled (RW) Reset=0
#define TELOMERE_INTM_MASK_CACHEOP_MASK          0x1
#define TELOMERE_INTM_MASK_CACHEOP_SHIFT         0 
#define TELOMERE_INTM_MASK_CACHEOP_BIT           0x1
#define TELOMERE_INTM_MASK_CACHEOP_BITWIDTH      1
// MAILBOX bitfiled (RW) Reset=0
#define TELOMERE_INTM_MASK_MAILBOX_MASK          0x2
#define TELOMERE_INTM_MASK_MAILBOX_SHIFT         1 
#define TELOMERE_INTM_MASK_MAILBOX_BIT           0x1
#define TELOMERE_INTM_MASK_MAILBOX_BITWIDTH      1
// AXI_ERROR bitfiled (RW) Reset=0
#define TELOMERE_INTM_MASK_AXI_ERROR_MASK        0x4
#define TELOMERE_INTM_MASK_AXI_ERROR_SHIFT       2 
#define TELOMERE_INTM_MASK_AXI_ERROR_BIT         0x1
#define TELOMERE_INTM_MASK_AXI_ERROR_BITWIDTH    1
// CACHE_ACCESS_ERROR bitfiled (RW) Reset=0
#define TELOMERE_INTM_MASK_CACHE_ACCESS_ERROR_MASK 0x8
#define TELOMERE_INTM_MASK_CACHE_ACCESS_ERROR_SHIFT 3 
#define TELOMERE_INTM_MASK_CACHE_ACCESS_ERROR_BIT 0x1
#define TELOMERE_INTM_MASK_CACHE_ACCESS_ERROR_BITWIDTH 1
// reserved bitfiled (RO) Reset=0
#define TELOMERE_INTM_MASK_RESERVED_MASK         0xFFFFFFF0
#define TELOMERE_INTM_MASK_RESERVED_SHIFT        4 
#define TELOMERE_INTM_MASK_RESERVED_BIT          0xFFFFFFF
#define TELOMERE_INTM_MASK_RESERVED_BITWIDTH     28
// CCTRL_MFADDR Register
#define TELOMERE_CCTRL_MFADDR_OFS                0x000000E0
// reserved bitfiled (RO) Reset=0
#define TELOMERE_CCTRL_MFADDR_RESERVED_MASK      0xFFF
#define TELOMERE_CCTRL_MFADDR_RESERVED_SHIFT     0 
#define TELOMERE_CCTRL_MFADDR_RESERVED_BIT       0xFFF
#define TELOMERE_CCTRL_MFADDR_RESERVED_BITWIDTH  12
// ADDR bitfiled (RW) Reset=0
#define TELOMERE_CCTRL_MFADDR_ADDR_MASK          0xFFFFF000
#define TELOMERE_CCTRL_MFADDR_ADDR_SHIFT         12 
#define TELOMERE_CCTRL_MFADDR_ADDR_BIT           0xFFFFF
#define TELOMERE_CCTRL_MFADDR_ADDR_BITWIDTH      20
// CCTRL_MFSIZE Register
#define TELOMERE_CCTRL_MFSIZE_OFS                0x000000E4
// COMMAND bitfiled (RW) Reset=0
#define TELOMERE_CCTRL_MFSIZE_COMMAND_MASK       0x7
#define TELOMERE_CCTRL_MFSIZE_COMMAND_SHIFT      0 
#define TELOMERE_CCTRL_MFSIZE_COMMAND_BIT        0x7
#define TELOMERE_CCTRL_MFSIZE_COMMAND_BITWIDTH   3
// reserved bitfiled (RO) Reset=0
#define TELOMERE_CCTRL_MFSIZE_RESERVED_MASK      0xFF8
#define TELOMERE_CCTRL_MFSIZE_RESERVED_SHIFT     3 
#define TELOMERE_CCTRL_MFSIZE_RESERVED_BIT       0x1FF
#define TELOMERE_CCTRL_MFSIZE_RESERVED_BITWIDTH  9
// FLUSH_SIZE bitfiled (RW) Reset=0
#define TELOMERE_CCTRL_MFSIZE_FLUSH_SIZE_MASK    0xFFFFF000
#define TELOMERE_CCTRL_MFSIZE_FLUSH_SIZE_SHIFT   12 
#define TELOMERE_CCTRL_MFSIZE_FLUSH_SIZE_BIT     0xFFFFF
#define TELOMERE_CCTRL_MFSIZE_FLUSH_SIZE_BITWIDTH 20
// GPR_0 Register
#define TELOMERE_GPR_0_OFS                       0x00000100
// VALUE bitfiled (RW) Reset=0
#define TELOMERE_GPR_0_VALUE_MASK                0xFFFFFFFF
#define TELOMERE_GPR_0_VALUE_SHIFT               0 
#define TELOMERE_GPR_0_VALUE_BIT                 0xFFFFFFFF
#define TELOMERE_GPR_0_VALUE_BITWIDTH            32
// GPR_1 Register
#define TELOMERE_GPR_1_OFS                       0x00000104
// VALUE bitfiled (RW) Reset=0
#define TELOMERE_GPR_1_VALUE_MASK                0xFFFFFFFF
#define TELOMERE_GPR_1_VALUE_SHIFT               0 
#define TELOMERE_GPR_1_VALUE_BIT                 0xFFFFFFFF
#define TELOMERE_GPR_1_VALUE_BITWIDTH            32
// GPR_2 Register
#define TELOMERE_GPR_2_OFS                       0x00000108
// VALUE bitfiled (RW) Reset=0
#define TELOMERE_GPR_2_VALUE_MASK                0xFFFFFFFF
#define TELOMERE_GPR_2_VALUE_SHIFT               0 
#define TELOMERE_GPR_2_VALUE_BIT                 0xFFFFFFFF
#define TELOMERE_GPR_2_VALUE_BITWIDTH            32
// GPR_3 Register
#define TELOMERE_GPR_3_OFS                       0x0000010C
// VALUE bitfiled (RW) Reset=0
#define TELOMERE_GPR_3_VALUE_MASK                0xFFFFFFFF
#define TELOMERE_GPR_3_VALUE_SHIFT               0 
#define TELOMERE_GPR_3_VALUE_BIT                 0xFFFFFFFF
#define TELOMERE_GPR_3_VALUE_BITWIDTH            32
// BINSEMA_0 Register
#define TELOMERE_BINSEMA_0_OFS                   0x00000180
// SEMAPHORE bitfiled (RW) Reset=0
#define TELOMERE_BINSEMA_0_SEMAPHORE_MASK        0x1
#define TELOMERE_BINSEMA_0_SEMAPHORE_SHIFT       0 
#define TELOMERE_BINSEMA_0_SEMAPHORE_BIT         0x1
#define TELOMERE_BINSEMA_0_SEMAPHORE_BITWIDTH    1
// reserved bitfiled (RO) Reset=0
#define TELOMERE_BINSEMA_0_RESERVED_MASK         0xFFFFFFFE
#define TELOMERE_BINSEMA_0_RESERVED_SHIFT        1 
#define TELOMERE_BINSEMA_0_RESERVED_BIT          0x7FFFFFFF
#define TELOMERE_BINSEMA_0_RESERVED_BITWIDTH     31
// BINSEMA_1 Register
#define TELOMERE_BINSEMA_1_OFS                   0x00000184
// SEMAPHORE bitfiled (RW) Reset=0
#define TELOMERE_BINSEMA_1_SEMAPHORE_MASK        0x1
#define TELOMERE_BINSEMA_1_SEMAPHORE_SHIFT       0 
#define TELOMERE_BINSEMA_1_SEMAPHORE_BIT         0x1
#define TELOMERE_BINSEMA_1_SEMAPHORE_BITWIDTH    1
// reserved bitfiled (RO) Reset=0
#define TELOMERE_BINSEMA_1_RESERVED_MASK         0xFFFFFFFE
#define TELOMERE_BINSEMA_1_RESERVED_SHIFT        1 
#define TELOMERE_BINSEMA_1_RESERVED_BIT          0x7FFFFFFF
#define TELOMERE_BINSEMA_1_RESERVED_BITWIDTH     31
// BINSEMA_2 Register
#define TELOMERE_BINSEMA_2_OFS                   0x00000188
// SEMAPHORE bitfiled (RW) Reset=0
#define TELOMERE_BINSEMA_2_SEMAPHORE_MASK        0x1
#define TELOMERE_BINSEMA_2_SEMAPHORE_SHIFT       0 
#define TELOMERE_BINSEMA_2_SEMAPHORE_BIT         0x1
#define TELOMERE_BINSEMA_2_SEMAPHORE_BITWIDTH    1
// reserved bitfiled (RO) Reset=0
#define TELOMERE_BINSEMA_2_RESERVED_MASK         0xFFFFFFFE
#define TELOMERE_BINSEMA_2_RESERVED_SHIFT        1 
#define TELOMERE_BINSEMA_2_RESERVED_BIT          0x7FFFFFFF
#define TELOMERE_BINSEMA_2_RESERVED_BITWIDTH     31
// BINSEMA_3 Register
#define TELOMERE_BINSEMA_3_OFS                   0x0000018C
// SEMAPHORE bitfiled (RW) Reset=0
#define TELOMERE_BINSEMA_3_SEMAPHORE_MASK        0x1
#define TELOMERE_BINSEMA_3_SEMAPHORE_SHIFT       0 
#define TELOMERE_BINSEMA_3_SEMAPHORE_BIT         0x1
#define TELOMERE_BINSEMA_3_SEMAPHORE_BITWIDTH    1
// reserved bitfiled (RO) Reset=0
#define TELOMERE_BINSEMA_3_RESERVED_MASK         0xFFFFFFFE
#define TELOMERE_BINSEMA_3_RESERVED_SHIFT        1 
#define TELOMERE_BINSEMA_3_RESERVED_BIT          0x7FFFFFFF
#define TELOMERE_BINSEMA_3_RESERVED_BITWIDTH     31
// MAILBOX_M2N Register
#define TELOMERE_MAILBOX_M2N_OFS                 0x000001C0
// VALUE bitfiled (RW) Reset=0
#define TELOMERE_MAILBOX_M2N_VALUE_MASK          0xFFFFFFFF
#define TELOMERE_MAILBOX_M2N_VALUE_SHIFT         0 
#define TELOMERE_MAILBOX_M2N_VALUE_BIT           0xFFFFFFFF
#define TELOMERE_MAILBOX_M2N_VALUE_BITWIDTH      32
// MAILBOX_M2NC Register
#define TELOMERE_MAILBOX_M2NC_OFS                0x000001C4
// VALUE bitfiled (RW) Reset=0
#define TELOMERE_MAILBOX_M2NC_VALUE_MASK         0xFFFFFFFF
#define TELOMERE_MAILBOX_M2NC_VALUE_SHIFT        0 
#define TELOMERE_MAILBOX_M2NC_VALUE_BIT          0xFFFFFFFF
#define TELOMERE_MAILBOX_M2NC_VALUE_BITWIDTH     32
// MAILBOX_N2M Register
#define TELOMERE_MAILBOX_N2M_OFS                 0x000001C8
// VALUE bitfiled (RW) Reset=0
#define TELOMERE_MAILBOX_N2M_VALUE_MASK          0xFFFFFFFF
#define TELOMERE_MAILBOX_N2M_VALUE_SHIFT         0 
#define TELOMERE_MAILBOX_N2M_VALUE_BIT           0xFFFFFFFF
#define TELOMERE_MAILBOX_N2M_VALUE_BITWIDTH      32
// MAILBOX_N2MC Register
#define TELOMERE_MAILBOX_N2MC_OFS                0x000001CC
// VALUE bitfiled (RW) Reset=0
#define TELOMERE_MAILBOX_N2MC_VALUE_MASK         0xFFFFFFFF
#define TELOMERE_MAILBOX_N2MC_VALUE_SHIFT        0 
#define TELOMERE_MAILBOX_N2MC_VALUE_BIT          0xFFFFFFFF
#define TELOMERE_MAILBOX_N2MC_VALUE_BITWIDTH     32
// BINSEMA_REF_0 Register
#define TELOMERE_BINSEMA_REF_0_OFS               0x00000200
// SEMAPHORE bitfiled (RO) Reset=0
#define TELOMERE_BINSEMA_REF_0_SEMAPHORE_MASK    0x1
#define TELOMERE_BINSEMA_REF_0_SEMAPHORE_SHIFT   0 
#define TELOMERE_BINSEMA_REF_0_SEMAPHORE_BIT     0x1
#define TELOMERE_BINSEMA_REF_0_SEMAPHORE_BITWIDTH 1
// reserved bitfiled (RO) Reset=0
#define TELOMERE_BINSEMA_REF_0_RESERVED_MASK     0xFFFFFFFE
#define TELOMERE_BINSEMA_REF_0_RESERVED_SHIFT    1 
#define TELOMERE_BINSEMA_REF_0_RESERVED_BIT      0x7FFFFFFF
#define TELOMERE_BINSEMA_REF_0_RESERVED_BITWIDTH 31
// BINSEMA_REF_1 Register
#define TELOMERE_BINSEMA_REF_1_OFS               0x00000204
// SEMAPHORE bitfiled (RO) Reset=0
#define TELOMERE_BINSEMA_REF_1_SEMAPHORE_MASK    0x1
#define TELOMERE_BINSEMA_REF_1_SEMAPHORE_SHIFT   0 
#define TELOMERE_BINSEMA_REF_1_SEMAPHORE_BIT     0x1
#define TELOMERE_BINSEMA_REF_1_SEMAPHORE_BITWIDTH 1
// reserved bitfiled (RO) Reset=0
#define TELOMERE_BINSEMA_REF_1_RESERVED_MASK     0xFFFFFFFE
#define TELOMERE_BINSEMA_REF_1_RESERVED_SHIFT    1 
#define TELOMERE_BINSEMA_REF_1_RESERVED_BIT      0x7FFFFFFF
#define TELOMERE_BINSEMA_REF_1_RESERVED_BITWIDTH 31
// BINSEMA_REF_2 Register
#define TELOMERE_BINSEMA_REF_2_OFS               0x00000208
// SEMAPHORE bitfiled (RO) Reset=0
#define TELOMERE_BINSEMA_REF_2_SEMAPHORE_MASK    0x1
#define TELOMERE_BINSEMA_REF_2_SEMAPHORE_SHIFT   0 
#define TELOMERE_BINSEMA_REF_2_SEMAPHORE_BIT     0x1
#define TELOMERE_BINSEMA_REF_2_SEMAPHORE_BITWIDTH 1
// reserved bitfiled (RO) Reset=0
#define TELOMERE_BINSEMA_REF_2_RESERVED_MASK     0xFFFFFFFE
#define TELOMERE_BINSEMA_REF_2_RESERVED_SHIFT    1 
#define TELOMERE_BINSEMA_REF_2_RESERVED_BIT      0x7FFFFFFF
#define TELOMERE_BINSEMA_REF_2_RESERVED_BITWIDTH 31
// BINSEMA_REF_3 Register
#define TELOMERE_BINSEMA_REF_3_OFS               0x0000020C
// SEMAPHORE bitfiled (RO) Reset=0
#define TELOMERE_BINSEMA_REF_3_SEMAPHORE_MASK    0x1
#define TELOMERE_BINSEMA_REF_3_SEMAPHORE_SHIFT   0 
#define TELOMERE_BINSEMA_REF_3_SEMAPHORE_BIT     0x1
#define TELOMERE_BINSEMA_REF_3_SEMAPHORE_BITWIDTH 1
// reserved bitfiled (RO) Reset=0
#define TELOMERE_BINSEMA_REF_3_RESERVED_MASK     0xFFFFFFFE
#define TELOMERE_BINSEMA_REF_3_RESERVED_SHIFT    1 
#define TELOMERE_BINSEMA_REF_3_RESERVED_BIT      0x7FFFFFFF
#define TELOMERE_BINSEMA_REF_3_RESERVED_BITWIDTH 31
// INTN_STAT Register
#define TELOMERE_INTN_STAT_OFS                   0x00001000
// REFILL bitfiled (RO) Reset=0
#define TELOMERE_INTN_STAT_REFILL_MASK           0x1
#define TELOMERE_INTN_STAT_REFILL_SHIFT          0 
#define TELOMERE_INTN_STAT_REFILL_BIT            0x1
#define TELOMERE_INTN_STAT_REFILL_BITWIDTH       1
// WRITEBACK bitfiled (RO) Reset=0
#define TELOMERE_INTN_STAT_WRITEBACK_MASK        0x2
#define TELOMERE_INTN_STAT_WRITEBACK_SHIFT       1 
#define TELOMERE_INTN_STAT_WRITEBACK_BIT         0x1
#define TELOMERE_INTN_STAT_WRITEBACK_BITWIDTH    1
// MAILBOX bitfiled (RO) Reset=0
#define TELOMERE_INTN_STAT_MAILBOX_MASK          0x4
#define TELOMERE_INTN_STAT_MAILBOX_SHIFT         2 
#define TELOMERE_INTN_STAT_MAILBOX_BIT           0x1
#define TELOMERE_INTN_STAT_MAILBOX_BITWIDTH      1
// reserved bitfiled (RO) Reset=0
#define TELOMERE_INTN_STAT_RESERVED_MASK         0xFFFFFFF8
#define TELOMERE_INTN_STAT_RESERVED_SHIFT        3 
#define TELOMERE_INTN_STAT_RESERVED_BIT          0x1FFFFFFF
#define TELOMERE_INTN_STAT_RESERVED_BITWIDTH     29
// INTN_MSKEDSTAT Register
#define TELOMERE_INTN_MSKEDSTAT_OFS              0x00001004
// REFILL bitfiled (RO) Reset=0
#define TELOMERE_INTN_MSKEDSTAT_REFILL_MASK      0x1
#define TELOMERE_INTN_MSKEDSTAT_REFILL_SHIFT     0 
#define TELOMERE_INTN_MSKEDSTAT_REFILL_BIT       0x1
#define TELOMERE_INTN_MSKEDSTAT_REFILL_BITWIDTH  1
// WRITEBACK bitfiled (RO) Reset=0
#define TELOMERE_INTN_MSKEDSTAT_WRITEBACK_MASK   0x2
#define TELOMERE_INTN_MSKEDSTAT_WRITEBACK_SHIFT  1 
#define TELOMERE_INTN_MSKEDSTAT_WRITEBACK_BIT    0x1
#define TELOMERE_INTN_MSKEDSTAT_WRITEBACK_BITWIDTH 1
// MAILBOX bitfiled (RO) Reset=0
#define TELOMERE_INTN_MSKEDSTAT_MAILBOX_MASK     0x4
#define TELOMERE_INTN_MSKEDSTAT_MAILBOX_SHIFT    2 
#define TELOMERE_INTN_MSKEDSTAT_MAILBOX_BIT      0x1
#define TELOMERE_INTN_MSKEDSTAT_MAILBOX_BITWIDTH 1
// reserved bitfiled (RO) Reset=0
#define TELOMERE_INTN_MSKEDSTAT_RESERVED_MASK    0xFFFFFFF8
#define TELOMERE_INTN_MSKEDSTAT_RESERVED_SHIFT   3 
#define TELOMERE_INTN_MSKEDSTAT_RESERVED_BIT     0x1FFFFFFF
#define TELOMERE_INTN_MSKEDSTAT_RESERVED_BITWIDTH 29
// INTN_MASK Register
#define TELOMERE_INTN_MASK_OFS                   0x0000100C
// REFILL bitfiled (RW) Reset=0
#define TELOMERE_INTN_MASK_REFILL_MASK           0x1
#define TELOMERE_INTN_MASK_REFILL_SHIFT          0 
#define TELOMERE_INTN_MASK_REFILL_BIT            0x1
#define TELOMERE_INTN_MASK_REFILL_BITWIDTH       1
// WRITEBACK bitfiled (RW) Reset=0
#define TELOMERE_INTN_MASK_WRITEBACK_MASK        0x2
#define TELOMERE_INTN_MASK_WRITEBACK_SHIFT       1 
#define TELOMERE_INTN_MASK_WRITEBACK_BIT         0x1
#define TELOMERE_INTN_MASK_WRITEBACK_BITWIDTH    1
// MAILBOX bitfiled (RW) Reset=0
#define TELOMERE_INTN_MASK_MAILBOX_MASK          0x4
#define TELOMERE_INTN_MASK_MAILBOX_SHIFT         2 
#define TELOMERE_INTN_MASK_MAILBOX_BIT           0x1
#define TELOMERE_INTN_MASK_MAILBOX_BITWIDTH      1
// reserved bitfiled (RO) Reset=0
#define TELOMERE_INTN_MASK_RESERVED_MASK         0xFFFFFFF8
#define TELOMERE_INTN_MASK_RESERVED_SHIFT        3 
#define TELOMERE_INTN_MASK_RESERVED_BIT          0x1FFFFFFF
#define TELOMERE_INTN_MASK_RESERVED_BITWIDTH     29

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* _TELOMERE_REG_DEF_H */
