/*
 * arch/arm/mach-tz2000/include/mach/regs/tmr_reg_def.h
 *
 * (C) Copyright TOSHIBA Corporation
 * Semiconductor & Storage Products Company 2013
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#ifndef _TMR_REG_DEF_H
#define _TMR_REG_DEF_H

#ifdef __cplusplus
extern  {
#endif /* __cplusplus */

// T0Control Register
#define TMR_T0CONTROL_OFS                        0x00000000
// TMODE bitfiled (RW) Reset=0
#define TMR_T0CONTROL_TMODE_MASK                 0x3
#define TMR_T0CONTROL_TMODE_SHIFT                0 
#define TMR_T0CONTROL_TMODE_BIT                  0x3
#define TMR_T0CONTROL_TMODE_BITWIDTH             2
// reserved2 bitfiled (RO) Reset=0
#define TMR_T0CONTROL_RESERVED2_MASK             0x1C
#define TMR_T0CONTROL_RESERVED2_SHIFT            2 
#define TMR_T0CONTROL_RESERVED2_BIT              0x7
#define TMR_T0CONTROL_RESERVED2_BITWIDTH         3
// CRE bitfiled (RW) Reset=0
#define TMR_T0CONTROL_CRE_MASK                   0x20
#define TMR_T0CONTROL_CRE_SHIFT                  5 
#define TMR_T0CONTROL_CRE_BIT                    0x1
#define TMR_T0CONTROL_CRE_BITWIDTH               1
// CCDE bitfiled (RW) Reset=0
#define TMR_T0CONTROL_CCDE_MASK                  0x40
#define TMR_T0CONTROL_CCDE_SHIFT                 6 
#define TMR_T0CONTROL_CCDE_BIT                   0x1
#define TMR_T0CONTROL_CCDE_BITWIDTH              1
// TCE bitfiled (RW) Reset=0
#define TMR_T0CONTROL_TCE_MASK                   0x80
#define TMR_T0CONTROL_TCE_SHIFT                  7 
#define TMR_T0CONTROL_TCE_BIT                    0x1
#define TMR_T0CONTROL_TCE_BITWIDTH               1
// reserved bitfiled (RO) Reset=0
#define TMR_T0CONTROL_RESERVED_MASK              0xFFFFFF00
#define TMR_T0CONTROL_RESERVED_SHIFT             8 
#define TMR_T0CONTROL_RESERVED_BIT               0xFFFFFF
#define TMR_T0CONTROL_RESERVED_BITWIDTH          24
// T0Interrupt_Status Register
#define TMR_T0INTERRUPT_STATUS_OFS               0x00000004
// TIIS bitfiled (RW) Reset=0
#define TMR_T0INTERRUPT_STATUS_TIIS_MASK         0x1
#define TMR_T0INTERRUPT_STATUS_TIIS_SHIFT        0 
#define TMR_T0INTERRUPT_STATUS_TIIS_BIT          0x1
#define TMR_T0INTERRUPT_STATUS_TIIS_BITWIDTH     1
// reserved2 bitfiled (RO) Reset=0
#define TMR_T0INTERRUPT_STATUS_RESERVED2_MASK    0x6
#define TMR_T0INTERRUPT_STATUS_RESERVED2_SHIFT   1 
#define TMR_T0INTERRUPT_STATUS_RESERVED2_BIT     0x3
#define TMR_T0INTERRUPT_STATUS_RESERVED2_BITWIDTH 2
// TWIS bitfiled (RW) Reset=0
#define TMR_T0INTERRUPT_STATUS_TWIS_MASK         0x8
#define TMR_T0INTERRUPT_STATUS_TWIS_SHIFT        3 
#define TMR_T0INTERRUPT_STATUS_TWIS_BIT          0x1
#define TMR_T0INTERRUPT_STATUS_TWIS_BITWIDTH     1
// reserved bitfiled (RO) Reset=0
#define TMR_T0INTERRUPT_STATUS_RESERVED_MASK     0xFFFFFFF0
#define TMR_T0INTERRUPT_STATUS_RESERVED_SHIFT    4 
#define TMR_T0INTERRUPT_STATUS_RESERVED_BIT      0xFFFFFFF
#define TMR_T0INTERRUPT_STATUS_RESERVED_BITWIDTH 28
// T0Compare_A Register
#define TMR_T0COMPARE_A_OFS                      0x00000008
// TCVA bitfiled (RW) Reset=11111111111111111111111111111111
#define TMR_T0COMPARE_A_TCVA_MASK                0xFFFFFFFF
#define TMR_T0COMPARE_A_TCVA_SHIFT               0 
#define TMR_T0COMPARE_A_TCVA_BIT                 0xFFFFFFFF
#define TMR_T0COMPARE_A_TCVA_BITWIDTH            32
// T0Interval_Mode Register
#define TMR_T0INTERVAL_MODE_OFS                  0x00000010
// TZCE bitfiled (RW) Reset=0
#define TMR_T0INTERVAL_MODE_TZCE_MASK            0x1
#define TMR_T0INTERVAL_MODE_TZCE_SHIFT           0 
#define TMR_T0INTERVAL_MODE_TZCE_BIT             0x1
#define TMR_T0INTERVAL_MODE_TZCE_BITWIDTH        1
// reserved2 bitfiled (RO) Reset=0
#define TMR_T0INTERVAL_MODE_RESERVED2_MASK       0x7FFE
#define TMR_T0INTERVAL_MODE_RESERVED2_SHIFT      1 
#define TMR_T0INTERVAL_MODE_RESERVED2_BIT        0x3FFF
#define TMR_T0INTERVAL_MODE_RESERVED2_BITWIDTH   14
// TIIE bitfiled (RW) Reset=0
#define TMR_T0INTERVAL_MODE_TIIE_MASK            0x8000
#define TMR_T0INTERVAL_MODE_TIIE_SHIFT           15 
#define TMR_T0INTERVAL_MODE_TIIE_BIT             0x1
#define TMR_T0INTERVAL_MODE_TIIE_BITWIDTH        1
// reserved bitfiled (RO) Reset=0
#define TMR_T0INTERVAL_MODE_RESERVED_MASK        0xFFFF0000
#define TMR_T0INTERVAL_MODE_RESERVED_SHIFT       16 
#define TMR_T0INTERVAL_MODE_RESERVED_BIT         0xFFFF
#define TMR_T0INTERVAL_MODE_RESERVED_BITWIDTH    16
// T0Timer_Counter_Clock_Divider Register
#define TMR_T0TIMER_COUNTER_CLOCK_DIVIDER_OFS    0x00000020
// CCD bitfiled (RW) Reset=0
#define TMR_T0TIMER_COUNTER_CLOCK_DIVIDER_CCD_MASK 0x7
#define TMR_T0TIMER_COUNTER_CLOCK_DIVIDER_CCD_SHIFT 0 
#define TMR_T0TIMER_COUNTER_CLOCK_DIVIDER_CCD_BIT 0x7
#define TMR_T0TIMER_COUNTER_CLOCK_DIVIDER_CCD_BITWIDTH 3
// reserved bitfiled (RO) Reset=0
#define TMR_T0TIMER_COUNTER_CLOCK_DIVIDER_RESERVED_MASK 0xFFFFFFF8
#define TMR_T0TIMER_COUNTER_CLOCK_DIVIDER_RESERVED_SHIFT 3 
#define TMR_T0TIMER_COUNTER_CLOCK_DIVIDER_RESERVED_BIT 0x1FFFFFFF
#define TMR_T0TIMER_COUNTER_CLOCK_DIVIDER_RESERVED_BITWIDTH 29
// T0Watchdog_Timer_Mode Register
#define TMR_T0WATCHDOG_TIMER_MODE_OFS            0x00000040
// TWC bitfiled (RW) Reset=0
#define TMR_T0WATCHDOG_TIMER_MODE_TWC_MASK       0x1
#define TMR_T0WATCHDOG_TIMER_MODE_TWC_SHIFT      0 
#define TMR_T0WATCHDOG_TIMER_MODE_TWC_BIT        0x1
#define TMR_T0WATCHDOG_TIMER_MODE_TWC_BITWIDTH   1
// reserved3 bitfiled (RO) Reset=0
#define TMR_T0WATCHDOG_TIMER_MODE_RESERVED3_MASK 0x7E
#define TMR_T0WATCHDOG_TIMER_MODE_RESERVED3_SHIFT 1 
#define TMR_T0WATCHDOG_TIMER_MODE_RESERVED3_BIT  0x3F
#define TMR_T0WATCHDOG_TIMER_MODE_RESERVED3_BITWIDTH 6
// WDIS bitfiled (RW) Reset=0
#define TMR_T0WATCHDOG_TIMER_MODE_WDIS_MASK      0x80
#define TMR_T0WATCHDOG_TIMER_MODE_WDIS_SHIFT     7 
#define TMR_T0WATCHDOG_TIMER_MODE_WDIS_BIT       0x1
#define TMR_T0WATCHDOG_TIMER_MODE_WDIS_BITWIDTH  1
// reserved2 bitfiled (RO) Reset=0
#define TMR_T0WATCHDOG_TIMER_MODE_RESERVED2_MASK 0x7F00
#define TMR_T0WATCHDOG_TIMER_MODE_RESERVED2_SHIFT 8 
#define TMR_T0WATCHDOG_TIMER_MODE_RESERVED2_BIT  0x7F
#define TMR_T0WATCHDOG_TIMER_MODE_RESERVED2_BITWIDTH 7
// TWIE bitfiled (RW) Reset=0
#define TMR_T0WATCHDOG_TIMER_MODE_TWIE_MASK      0x8000
#define TMR_T0WATCHDOG_TIMER_MODE_TWIE_SHIFT     15 
#define TMR_T0WATCHDOG_TIMER_MODE_TWIE_BIT       0x1
#define TMR_T0WATCHDOG_TIMER_MODE_TWIE_BITWIDTH  1
// reserved bitfiled (RO) Reset=0
#define TMR_T0WATCHDOG_TIMER_MODE_RESERVED_MASK  0xFFFF0000
#define TMR_T0WATCHDOG_TIMER_MODE_RESERVED_SHIFT 16 
#define TMR_T0WATCHDOG_TIMER_MODE_RESERVED_BIT   0xFFFF
#define TMR_T0WATCHDOG_TIMER_MODE_RESERVED_BITWIDTH 16
// T0Timer_Counter_Read Register
#define TMR_T0TIMER_COUNTER_READ_OFS             0x000000F0
// TCNT bitfiled (RO) Reset=0
#define TMR_T0TIMER_COUNTER_READ_TCNT_MASK       0xFFFFFFFF
#define TMR_T0TIMER_COUNTER_READ_TCNT_SHIFT      0 
#define TMR_T0TIMER_COUNTER_READ_TCNT_BIT        0xFFFFFFFF
#define TMR_T0TIMER_COUNTER_READ_TCNT_BITWIDTH   32
// T1Control Register
#define TMR_T1CONTROL_OFS                        0x00000100
// TMODE bitfiled (RW) Reset=0
#define TMR_T1CONTROL_TMODE_MASK                 0x3
#define TMR_T1CONTROL_TMODE_SHIFT                0 
#define TMR_T1CONTROL_TMODE_BIT                  0x3
#define TMR_T1CONTROL_TMODE_BITWIDTH             2
// reserved2 bitfiled (RO) Reset=0
#define TMR_T1CONTROL_RESERVED2_MASK             0x1C
#define TMR_T1CONTROL_RESERVED2_SHIFT            2 
#define TMR_T1CONTROL_RESERVED2_BIT              0x7
#define TMR_T1CONTROL_RESERVED2_BITWIDTH         3
// CRE bitfiled (RW) Reset=0
#define TMR_T1CONTROL_CRE_MASK                   0x20
#define TMR_T1CONTROL_CRE_SHIFT                  5 
#define TMR_T1CONTROL_CRE_BIT                    0x1
#define TMR_T1CONTROL_CRE_BITWIDTH               1
// CCDE bitfiled (RW) Reset=0
#define TMR_T1CONTROL_CCDE_MASK                  0x40
#define TMR_T1CONTROL_CCDE_SHIFT                 6 
#define TMR_T1CONTROL_CCDE_BIT                   0x1
#define TMR_T1CONTROL_CCDE_BITWIDTH              1
// TCE bitfiled (RW) Reset=0
#define TMR_T1CONTROL_TCE_MASK                   0x80
#define TMR_T1CONTROL_TCE_SHIFT                  7 
#define TMR_T1CONTROL_TCE_BIT                    0x1
#define TMR_T1CONTROL_TCE_BITWIDTH               1
// reserved bitfiled (RO) Reset=0
#define TMR_T1CONTROL_RESERVED_MASK              0xFFFFFF00
#define TMR_T1CONTROL_RESERVED_SHIFT             8 
#define TMR_T1CONTROL_RESERVED_BIT               0xFFFFFF
#define TMR_T1CONTROL_RESERVED_BITWIDTH          24
// T1Interrupt_Status Register
#define TMR_T1INTERRUPT_STATUS_OFS               0x00000104
// TIIS bitfiled (RW) Reset=0
#define TMR_T1INTERRUPT_STATUS_TIIS_MASK         0x1
#define TMR_T1INTERRUPT_STATUS_TIIS_SHIFT        0 
#define TMR_T1INTERRUPT_STATUS_TIIS_BIT          0x1
#define TMR_T1INTERRUPT_STATUS_TIIS_BITWIDTH     1
// reserved2 bitfiled (RO) Reset=0
#define TMR_T1INTERRUPT_STATUS_RESERVED2_MASK    0x6
#define TMR_T1INTERRUPT_STATUS_RESERVED2_SHIFT   1 
#define TMR_T1INTERRUPT_STATUS_RESERVED2_BIT     0x3
#define TMR_T1INTERRUPT_STATUS_RESERVED2_BITWIDTH 2
// TWIS bitfiled (RW) Reset=0
#define TMR_T1INTERRUPT_STATUS_TWIS_MASK         0x8
#define TMR_T1INTERRUPT_STATUS_TWIS_SHIFT        3 
#define TMR_T1INTERRUPT_STATUS_TWIS_BIT          0x1
#define TMR_T1INTERRUPT_STATUS_TWIS_BITWIDTH     1
// reserved bitfiled (RO) Reset=0
#define TMR_T1INTERRUPT_STATUS_RESERVED_MASK     0xFFFFFFF0
#define TMR_T1INTERRUPT_STATUS_RESERVED_SHIFT    4 
#define TMR_T1INTERRUPT_STATUS_RESERVED_BIT      0xFFFFFFF
#define TMR_T1INTERRUPT_STATUS_RESERVED_BITWIDTH 28
// T1Compare_A Register
#define TMR_T1COMPARE_A_OFS                      0x00000108
// TCVA bitfiled (RW) Reset=11111111111111111111111111111111
#define TMR_T1COMPARE_A_TCVA_MASK                0xFFFFFFFF
#define TMR_T1COMPARE_A_TCVA_SHIFT               0 
#define TMR_T1COMPARE_A_TCVA_BIT                 0xFFFFFFFF
#define TMR_T1COMPARE_A_TCVA_BITWIDTH            32
// T1Interval_Mode Register
#define TMR_T1INTERVAL_MODE_OFS                  0x00000110
// TZCE bitfiled (RW) Reset=0
#define TMR_T1INTERVAL_MODE_TZCE_MASK            0x1
#define TMR_T1INTERVAL_MODE_TZCE_SHIFT           0 
#define TMR_T1INTERVAL_MODE_TZCE_BIT             0x1
#define TMR_T1INTERVAL_MODE_TZCE_BITWIDTH        1
// reserved2 bitfiled (RO) Reset=0
#define TMR_T1INTERVAL_MODE_RESERVED2_MASK       0x7FFE
#define TMR_T1INTERVAL_MODE_RESERVED2_SHIFT      1 
#define TMR_T1INTERVAL_MODE_RESERVED2_BIT        0x3FFF
#define TMR_T1INTERVAL_MODE_RESERVED2_BITWIDTH   14
// TIIE bitfiled (RW) Reset=0
#define TMR_T1INTERVAL_MODE_TIIE_MASK            0x8000
#define TMR_T1INTERVAL_MODE_TIIE_SHIFT           15 
#define TMR_T1INTERVAL_MODE_TIIE_BIT             0x1
#define TMR_T1INTERVAL_MODE_TIIE_BITWIDTH        1
// reserved bitfiled (RO) Reset=0
#define TMR_T1INTERVAL_MODE_RESERVED_MASK        0xFFFF0000
#define TMR_T1INTERVAL_MODE_RESERVED_SHIFT       16 
#define TMR_T1INTERVAL_MODE_RESERVED_BIT         0xFFFF
#define TMR_T1INTERVAL_MODE_RESERVED_BITWIDTH    16
// T1Timer_Counter_Clock_Divider Register
#define TMR_T1TIMER_COUNTER_CLOCK_DIVIDER_OFS    0x00000120
// CCD bitfiled (RW) Reset=0
#define TMR_T1TIMER_COUNTER_CLOCK_DIVIDER_CCD_MASK 0x7
#define TMR_T1TIMER_COUNTER_CLOCK_DIVIDER_CCD_SHIFT 0 
#define TMR_T1TIMER_COUNTER_CLOCK_DIVIDER_CCD_BIT 0x7
#define TMR_T1TIMER_COUNTER_CLOCK_DIVIDER_CCD_BITWIDTH 3
// reserved bitfiled (RO) Reset=0
#define TMR_T1TIMER_COUNTER_CLOCK_DIVIDER_RESERVED_MASK 0xFFFFFFF8
#define TMR_T1TIMER_COUNTER_CLOCK_DIVIDER_RESERVED_SHIFT 3 
#define TMR_T1TIMER_COUNTER_CLOCK_DIVIDER_RESERVED_BIT 0x1FFFFFFF
#define TMR_T1TIMER_COUNTER_CLOCK_DIVIDER_RESERVED_BITWIDTH 29
// T1Watchdog_Timer_Mode Register
#define TMR_T1WATCHDOG_TIMER_MODE_OFS            0x00000140
// TWC bitfiled (RW) Reset=0
#define TMR_T1WATCHDOG_TIMER_MODE_TWC_MASK       0x1
#define TMR_T1WATCHDOG_TIMER_MODE_TWC_SHIFT      0 
#define TMR_T1WATCHDOG_TIMER_MODE_TWC_BIT        0x1
#define TMR_T1WATCHDOG_TIMER_MODE_TWC_BITWIDTH   1
// reserved3 bitfiled (RO) Reset=0
#define TMR_T1WATCHDOG_TIMER_MODE_RESERVED3_MASK 0x7E
#define TMR_T1WATCHDOG_TIMER_MODE_RESERVED3_SHIFT 1 
#define TMR_T1WATCHDOG_TIMER_MODE_RESERVED3_BIT  0x3F
#define TMR_T1WATCHDOG_TIMER_MODE_RESERVED3_BITWIDTH 6
// WDIS bitfiled (RW) Reset=0
#define TMR_T1WATCHDOG_TIMER_MODE_WDIS_MASK      0x80
#define TMR_T1WATCHDOG_TIMER_MODE_WDIS_SHIFT     7 
#define TMR_T1WATCHDOG_TIMER_MODE_WDIS_BIT       0x1
#define TMR_T1WATCHDOG_TIMER_MODE_WDIS_BITWIDTH  1
// reserved2 bitfiled (RO) Reset=0
#define TMR_T1WATCHDOG_TIMER_MODE_RESERVED2_MASK 0x7F00
#define TMR_T1WATCHDOG_TIMER_MODE_RESERVED2_SHIFT 8 
#define TMR_T1WATCHDOG_TIMER_MODE_RESERVED2_BIT  0x7F
#define TMR_T1WATCHDOG_TIMER_MODE_RESERVED2_BITWIDTH 7
// TWIE bitfiled (RW) Reset=0
#define TMR_T1WATCHDOG_TIMER_MODE_TWIE_MASK      0x8000
#define TMR_T1WATCHDOG_TIMER_MODE_TWIE_SHIFT     15 
#define TMR_T1WATCHDOG_TIMER_MODE_TWIE_BIT       0x1
#define TMR_T1WATCHDOG_TIMER_MODE_TWIE_BITWIDTH  1
// reserved bitfiled (RO) Reset=0
#define TMR_T1WATCHDOG_TIMER_MODE_RESERVED_MASK  0xFFFF0000
#define TMR_T1WATCHDOG_TIMER_MODE_RESERVED_SHIFT 16 
#define TMR_T1WATCHDOG_TIMER_MODE_RESERVED_BIT   0xFFFF
#define TMR_T1WATCHDOG_TIMER_MODE_RESERVED_BITWIDTH 16
// T1Timer_Counter_Read Register
#define TMR_T1TIMER_COUNTER_READ_OFS             0x000001F0
// TCNT bitfiled (RO) Reset=0
#define TMR_T1TIMER_COUNTER_READ_TCNT_MASK       0xFFFFFFFF
#define TMR_T1TIMER_COUNTER_READ_TCNT_SHIFT      0 
#define TMR_T1TIMER_COUNTER_READ_TCNT_BIT        0xFFFFFFFF
#define TMR_T1TIMER_COUNTER_READ_TCNT_BITWIDTH   32
// T2Control Register
#define TMR_T2CONTROL_OFS                        0x00000200
// TMODE bitfiled (RW) Reset=0
#define TMR_T2CONTROL_TMODE_MASK                 0x3
#define TMR_T2CONTROL_TMODE_SHIFT                0 
#define TMR_T2CONTROL_TMODE_BIT                  0x3
#define TMR_T2CONTROL_TMODE_BITWIDTH             2
// reserved2 bitfiled (RO) Reset=0
#define TMR_T2CONTROL_RESERVED2_MASK             0x1C
#define TMR_T2CONTROL_RESERVED2_SHIFT            2 
#define TMR_T2CONTROL_RESERVED2_BIT              0x7
#define TMR_T2CONTROL_RESERVED2_BITWIDTH         3
// CRE bitfiled (RW) Reset=0
#define TMR_T2CONTROL_CRE_MASK                   0x20
#define TMR_T2CONTROL_CRE_SHIFT                  5 
#define TMR_T2CONTROL_CRE_BIT                    0x1
#define TMR_T2CONTROL_CRE_BITWIDTH               1
// CCDE bitfiled (RW) Reset=0
#define TMR_T2CONTROL_CCDE_MASK                  0x40
#define TMR_T2CONTROL_CCDE_SHIFT                 6 
#define TMR_T2CONTROL_CCDE_BIT                   0x1
#define TMR_T2CONTROL_CCDE_BITWIDTH              1
// TCE bitfiled (RW) Reset=0
#define TMR_T2CONTROL_TCE_MASK                   0x80
#define TMR_T2CONTROL_TCE_SHIFT                  7 
#define TMR_T2CONTROL_TCE_BIT                    0x1
#define TMR_T2CONTROL_TCE_BITWIDTH               1
// reserved bitfiled (RO) Reset=0
#define TMR_T2CONTROL_RESERVED_MASK              0xFFFFFF00
#define TMR_T2CONTROL_RESERVED_SHIFT             8 
#define TMR_T2CONTROL_RESERVED_BIT               0xFFFFFF
#define TMR_T2CONTROL_RESERVED_BITWIDTH          24
// T2Interrupt_Status Register
#define TMR_T2INTERRUPT_STATUS_OFS               0x00000204
// TIIS bitfiled (RW) Reset=0
#define TMR_T2INTERRUPT_STATUS_TIIS_MASK         0x1
#define TMR_T2INTERRUPT_STATUS_TIIS_SHIFT        0 
#define TMR_T2INTERRUPT_STATUS_TIIS_BIT          0x1
#define TMR_T2INTERRUPT_STATUS_TIIS_BITWIDTH     1
// reserved2 bitfiled (RO) Reset=0
#define TMR_T2INTERRUPT_STATUS_RESERVED2_MASK    0x6
#define TMR_T2INTERRUPT_STATUS_RESERVED2_SHIFT   1 
#define TMR_T2INTERRUPT_STATUS_RESERVED2_BIT     0x3
#define TMR_T2INTERRUPT_STATUS_RESERVED2_BITWIDTH 2
// TWIS bitfiled (RW) Reset=0
#define TMR_T2INTERRUPT_STATUS_TWIS_MASK         0x8
#define TMR_T2INTERRUPT_STATUS_TWIS_SHIFT        3 
#define TMR_T2INTERRUPT_STATUS_TWIS_BIT          0x1
#define TMR_T2INTERRUPT_STATUS_TWIS_BITWIDTH     1
// reserved bitfiled (RO) Reset=0
#define TMR_T2INTERRUPT_STATUS_RESERVED_MASK     0xFFFFFFF0
#define TMR_T2INTERRUPT_STATUS_RESERVED_SHIFT    4 
#define TMR_T2INTERRUPT_STATUS_RESERVED_BIT      0xFFFFFFF
#define TMR_T2INTERRUPT_STATUS_RESERVED_BITWIDTH 28
// T2Compare_A Register
#define TMR_T2COMPARE_A_OFS                      0x00000208
// TCVA bitfiled (RW) Reset=11111111111111111111111111111111
#define TMR_T2COMPARE_A_TCVA_MASK                0xFFFFFFFF
#define TMR_T2COMPARE_A_TCVA_SHIFT               0 
#define TMR_T2COMPARE_A_TCVA_BIT                 0xFFFFFFFF
#define TMR_T2COMPARE_A_TCVA_BITWIDTH            32
// T2Interval_Mode Register
#define TMR_T2INTERVAL_MODE_OFS                  0x00000210
// TZCE bitfiled (RW) Reset=0
#define TMR_T2INTERVAL_MODE_TZCE_MASK            0x1
#define TMR_T2INTERVAL_MODE_TZCE_SHIFT           0 
#define TMR_T2INTERVAL_MODE_TZCE_BIT             0x1
#define TMR_T2INTERVAL_MODE_TZCE_BITWIDTH        1
// reserved2 bitfiled (RO) Reset=0
#define TMR_T2INTERVAL_MODE_RESERVED2_MASK       0x7FFE
#define TMR_T2INTERVAL_MODE_RESERVED2_SHIFT      1 
#define TMR_T2INTERVAL_MODE_RESERVED2_BIT        0x3FFF
#define TMR_T2INTERVAL_MODE_RESERVED2_BITWIDTH   14
// TIIE bitfiled (RW) Reset=0
#define TMR_T2INTERVAL_MODE_TIIE_MASK            0x8000
#define TMR_T2INTERVAL_MODE_TIIE_SHIFT           15 
#define TMR_T2INTERVAL_MODE_TIIE_BIT             0x1
#define TMR_T2INTERVAL_MODE_TIIE_BITWIDTH        1
// reserved bitfiled (RO) Reset=0
#define TMR_T2INTERVAL_MODE_RESERVED_MASK        0xFFFF0000
#define TMR_T2INTERVAL_MODE_RESERVED_SHIFT       16 
#define TMR_T2INTERVAL_MODE_RESERVED_BIT         0xFFFF
#define TMR_T2INTERVAL_MODE_RESERVED_BITWIDTH    16
// T2Timer_Counter_Clock_Divider Register
#define TMR_T2TIMER_COUNTER_CLOCK_DIVIDER_OFS    0x00000220
// CCD bitfiled (RW) Reset=0
#define TMR_T2TIMER_COUNTER_CLOCK_DIVIDER_CCD_MASK 0x7
#define TMR_T2TIMER_COUNTER_CLOCK_DIVIDER_CCD_SHIFT 0 
#define TMR_T2TIMER_COUNTER_CLOCK_DIVIDER_CCD_BIT 0x7
#define TMR_T2TIMER_COUNTER_CLOCK_DIVIDER_CCD_BITWIDTH 3
// reserved bitfiled (RO) Reset=0
#define TMR_T2TIMER_COUNTER_CLOCK_DIVIDER_RESERVED_MASK 0xFFFFFFF8
#define TMR_T2TIMER_COUNTER_CLOCK_DIVIDER_RESERVED_SHIFT 3 
#define TMR_T2TIMER_COUNTER_CLOCK_DIVIDER_RESERVED_BIT 0x1FFFFFFF
#define TMR_T2TIMER_COUNTER_CLOCK_DIVIDER_RESERVED_BITWIDTH 29
// T2Watchdog_Timer_Mode Register
#define TMR_T2WATCHDOG_TIMER_MODE_OFS            0x00000240
// TWC bitfiled (RW) Reset=0
#define TMR_T2WATCHDOG_TIMER_MODE_TWC_MASK       0x1
#define TMR_T2WATCHDOG_TIMER_MODE_TWC_SHIFT      0 
#define TMR_T2WATCHDOG_TIMER_MODE_TWC_BIT        0x1
#define TMR_T2WATCHDOG_TIMER_MODE_TWC_BITWIDTH   1
// reserved3 bitfiled (RO) Reset=0
#define TMR_T2WATCHDOG_TIMER_MODE_RESERVED3_MASK 0x7E
#define TMR_T2WATCHDOG_TIMER_MODE_RESERVED3_SHIFT 1 
#define TMR_T2WATCHDOG_TIMER_MODE_RESERVED3_BIT  0x3F
#define TMR_T2WATCHDOG_TIMER_MODE_RESERVED3_BITWIDTH 6
// WDIS bitfiled (RW) Reset=0
#define TMR_T2WATCHDOG_TIMER_MODE_WDIS_MASK      0x80
#define TMR_T2WATCHDOG_TIMER_MODE_WDIS_SHIFT     7 
#define TMR_T2WATCHDOG_TIMER_MODE_WDIS_BIT       0x1
#define TMR_T2WATCHDOG_TIMER_MODE_WDIS_BITWIDTH  1
// reserved2 bitfiled (RO) Reset=0
#define TMR_T2WATCHDOG_TIMER_MODE_RESERVED2_MASK 0x7F00
#define TMR_T2WATCHDOG_TIMER_MODE_RESERVED2_SHIFT 8 
#define TMR_T2WATCHDOG_TIMER_MODE_RESERVED2_BIT  0x7F
#define TMR_T2WATCHDOG_TIMER_MODE_RESERVED2_BITWIDTH 7
// TWIE bitfiled (RW) Reset=0
#define TMR_T2WATCHDOG_TIMER_MODE_TWIE_MASK      0x8000
#define TMR_T2WATCHDOG_TIMER_MODE_TWIE_SHIFT     15 
#define TMR_T2WATCHDOG_TIMER_MODE_TWIE_BIT       0x1
#define TMR_T2WATCHDOG_TIMER_MODE_TWIE_BITWIDTH  1
// reserved bitfiled (RO) Reset=0
#define TMR_T2WATCHDOG_TIMER_MODE_RESERVED_MASK  0xFFFF0000
#define TMR_T2WATCHDOG_TIMER_MODE_RESERVED_SHIFT 16 
#define TMR_T2WATCHDOG_TIMER_MODE_RESERVED_BIT   0xFFFF
#define TMR_T2WATCHDOG_TIMER_MODE_RESERVED_BITWIDTH 16
// T2Timer_Counter_Read Register
#define TMR_T2TIMER_COUNTER_READ_OFS             0x000002F0
// TCNT bitfiled (RO) Reset=0
#define TMR_T2TIMER_COUNTER_READ_TCNT_MASK       0xFFFFFFFF
#define TMR_T2TIMER_COUNTER_READ_TCNT_SHIFT      0 
#define TMR_T2TIMER_COUNTER_READ_TCNT_BIT        0xFFFFFFFF
#define TMR_T2TIMER_COUNTER_READ_TCNT_BITWIDTH   32
// T3Control Register
#define TMR_T3CONTROL_OFS                        0x00000300
// TMODE bitfiled (RW) Reset=0
#define TMR_T3CONTROL_TMODE_MASK                 0x3
#define TMR_T3CONTROL_TMODE_SHIFT                0 
#define TMR_T3CONTROL_TMODE_BIT                  0x3
#define TMR_T3CONTROL_TMODE_BITWIDTH             2
// reserved2 bitfiled (RO) Reset=0
#define TMR_T3CONTROL_RESERVED2_MASK             0x1C
#define TMR_T3CONTROL_RESERVED2_SHIFT            2 
#define TMR_T3CONTROL_RESERVED2_BIT              0x7
#define TMR_T3CONTROL_RESERVED2_BITWIDTH         3
// CRE bitfiled (RW) Reset=0
#define TMR_T3CONTROL_CRE_MASK                   0x20
#define TMR_T3CONTROL_CRE_SHIFT                  5 
#define TMR_T3CONTROL_CRE_BIT                    0x1
#define TMR_T3CONTROL_CRE_BITWIDTH               1
// CCDE bitfiled (RW) Reset=0
#define TMR_T3CONTROL_CCDE_MASK                  0x40
#define TMR_T3CONTROL_CCDE_SHIFT                 6 
#define TMR_T3CONTROL_CCDE_BIT                   0x1
#define TMR_T3CONTROL_CCDE_BITWIDTH              1
// TCE bitfiled (RW) Reset=0
#define TMR_T3CONTROL_TCE_MASK                   0x80
#define TMR_T3CONTROL_TCE_SHIFT                  7 
#define TMR_T3CONTROL_TCE_BIT                    0x1
#define TMR_T3CONTROL_TCE_BITWIDTH               1
// reserved bitfiled (RO) Reset=0
#define TMR_T3CONTROL_RESERVED_MASK              0xFFFFFF00
#define TMR_T3CONTROL_RESERVED_SHIFT             8 
#define TMR_T3CONTROL_RESERVED_BIT               0xFFFFFF
#define TMR_T3CONTROL_RESERVED_BITWIDTH          24
// T3Interrupt_Status Register
#define TMR_T3INTERRUPT_STATUS_OFS               0x00000304
// TIIS bitfiled (RW) Reset=0
#define TMR_T3INTERRUPT_STATUS_TIIS_MASK         0x1
#define TMR_T3INTERRUPT_STATUS_TIIS_SHIFT        0 
#define TMR_T3INTERRUPT_STATUS_TIIS_BIT          0x1
#define TMR_T3INTERRUPT_STATUS_TIIS_BITWIDTH     1
// reserved2 bitfiled (RO) Reset=0
#define TMR_T3INTERRUPT_STATUS_RESERVED2_MASK    0x6
#define TMR_T3INTERRUPT_STATUS_RESERVED2_SHIFT   1 
#define TMR_T3INTERRUPT_STATUS_RESERVED2_BIT     0x3
#define TMR_T3INTERRUPT_STATUS_RESERVED2_BITWIDTH 2
// TWIS bitfiled (RW) Reset=0
#define TMR_T3INTERRUPT_STATUS_TWIS_MASK         0x8
#define TMR_T3INTERRUPT_STATUS_TWIS_SHIFT        3 
#define TMR_T3INTERRUPT_STATUS_TWIS_BIT          0x1
#define TMR_T3INTERRUPT_STATUS_TWIS_BITWIDTH     1
// reserved bitfiled (RO) Reset=0
#define TMR_T3INTERRUPT_STATUS_RESERVED_MASK     0xFFFFFFF0
#define TMR_T3INTERRUPT_STATUS_RESERVED_SHIFT    4 
#define TMR_T3INTERRUPT_STATUS_RESERVED_BIT      0xFFFFFFF
#define TMR_T3INTERRUPT_STATUS_RESERVED_BITWIDTH 28
// T3Compare_A Register
#define TMR_T3COMPARE_A_OFS                      0x00000308
// TCVA bitfiled (RW) Reset=11111111111111111111111111111111
#define TMR_T3COMPARE_A_TCVA_MASK                0xFFFFFFFF
#define TMR_T3COMPARE_A_TCVA_SHIFT               0 
#define TMR_T3COMPARE_A_TCVA_BIT                 0xFFFFFFFF
#define TMR_T3COMPARE_A_TCVA_BITWIDTH            32
// T3Interval_Mode Register
#define TMR_T3INTERVAL_MODE_OFS                  0x00000310
// TZCE bitfiled (RW) Reset=0
#define TMR_T3INTERVAL_MODE_TZCE_MASK            0x1
#define TMR_T3INTERVAL_MODE_TZCE_SHIFT           0 
#define TMR_T3INTERVAL_MODE_TZCE_BIT             0x1
#define TMR_T3INTERVAL_MODE_TZCE_BITWIDTH        1
// reserved2 bitfiled (RO) Reset=0
#define TMR_T3INTERVAL_MODE_RESERVED2_MASK       0x7FFE
#define TMR_T3INTERVAL_MODE_RESERVED2_SHIFT      1 
#define TMR_T3INTERVAL_MODE_RESERVED2_BIT        0x3FFF
#define TMR_T3INTERVAL_MODE_RESERVED2_BITWIDTH   14
// TIIE bitfiled (RW) Reset=0
#define TMR_T3INTERVAL_MODE_TIIE_MASK            0x8000
#define TMR_T3INTERVAL_MODE_TIIE_SHIFT           15 
#define TMR_T3INTERVAL_MODE_TIIE_BIT             0x1
#define TMR_T3INTERVAL_MODE_TIIE_BITWIDTH        1
// reserved bitfiled (RO) Reset=0
#define TMR_T3INTERVAL_MODE_RESERVED_MASK        0xFFFF0000
#define TMR_T3INTERVAL_MODE_RESERVED_SHIFT       16 
#define TMR_T3INTERVAL_MODE_RESERVED_BIT         0xFFFF
#define TMR_T3INTERVAL_MODE_RESERVED_BITWIDTH    16
// T3Timer_Counter_Clock_Divider Register
#define TMR_T3TIMER_COUNTER_CLOCK_DIVIDER_OFS    0x00000320
// CCD bitfiled (RW) Reset=0
#define TMR_T3TIMER_COUNTER_CLOCK_DIVIDER_CCD_MASK 0x7
#define TMR_T3TIMER_COUNTER_CLOCK_DIVIDER_CCD_SHIFT 0 
#define TMR_T3TIMER_COUNTER_CLOCK_DIVIDER_CCD_BIT 0x7
#define TMR_T3TIMER_COUNTER_CLOCK_DIVIDER_CCD_BITWIDTH 3
// reserved bitfiled (RO) Reset=0
#define TMR_T3TIMER_COUNTER_CLOCK_DIVIDER_RESERVED_MASK 0xFFFFFFF8
#define TMR_T3TIMER_COUNTER_CLOCK_DIVIDER_RESERVED_SHIFT 3 
#define TMR_T3TIMER_COUNTER_CLOCK_DIVIDER_RESERVED_BIT 0x1FFFFFFF
#define TMR_T3TIMER_COUNTER_CLOCK_DIVIDER_RESERVED_BITWIDTH 29
// T3Watchdog_Timer_Mode Register
#define TMR_T3WATCHDOG_TIMER_MODE_OFS            0x00000340
// TWC bitfiled (RW) Reset=0
#define TMR_T3WATCHDOG_TIMER_MODE_TWC_MASK       0x1
#define TMR_T3WATCHDOG_TIMER_MODE_TWC_SHIFT      0 
#define TMR_T3WATCHDOG_TIMER_MODE_TWC_BIT        0x1
#define TMR_T3WATCHDOG_TIMER_MODE_TWC_BITWIDTH   1
// reserved3 bitfiled (RO) Reset=0
#define TMR_T3WATCHDOG_TIMER_MODE_RESERVED3_MASK 0x7E
#define TMR_T3WATCHDOG_TIMER_MODE_RESERVED3_SHIFT 1 
#define TMR_T3WATCHDOG_TIMER_MODE_RESERVED3_BIT  0x3F
#define TMR_T3WATCHDOG_TIMER_MODE_RESERVED3_BITWIDTH 6
// WDIS bitfiled (RW) Reset=0
#define TMR_T3WATCHDOG_TIMER_MODE_WDIS_MASK      0x80
#define TMR_T3WATCHDOG_TIMER_MODE_WDIS_SHIFT     7 
#define TMR_T3WATCHDOG_TIMER_MODE_WDIS_BIT       0x1
#define TMR_T3WATCHDOG_TIMER_MODE_WDIS_BITWIDTH  1
// reserved2 bitfiled (RO) Reset=0
#define TMR_T3WATCHDOG_TIMER_MODE_RESERVED2_MASK 0x7F00
#define TMR_T3WATCHDOG_TIMER_MODE_RESERVED2_SHIFT 8 
#define TMR_T3WATCHDOG_TIMER_MODE_RESERVED2_BIT  0x7F
#define TMR_T3WATCHDOG_TIMER_MODE_RESERVED2_BITWIDTH 7
// TWIE bitfiled (RW) Reset=0
#define TMR_T3WATCHDOG_TIMER_MODE_TWIE_MASK      0x8000
#define TMR_T3WATCHDOG_TIMER_MODE_TWIE_SHIFT     15 
#define TMR_T3WATCHDOG_TIMER_MODE_TWIE_BIT       0x1
#define TMR_T3WATCHDOG_TIMER_MODE_TWIE_BITWIDTH  1
// reserved bitfiled (RO) Reset=0
#define TMR_T3WATCHDOG_TIMER_MODE_RESERVED_MASK  0xFFFF0000
#define TMR_T3WATCHDOG_TIMER_MODE_RESERVED_SHIFT 16 
#define TMR_T3WATCHDOG_TIMER_MODE_RESERVED_BIT   0xFFFF
#define TMR_T3WATCHDOG_TIMER_MODE_RESERVED_BITWIDTH 16
// T3Timer_Counter_Read Register
#define TMR_T3TIMER_COUNTER_READ_OFS             0x000003F0
// TCNT bitfiled (RO) Reset=0
#define TMR_T3TIMER_COUNTER_READ_TCNT_MASK       0xFFFFFFFF
#define TMR_T3TIMER_COUNTER_READ_TCNT_SHIFT      0 
#define TMR_T3TIMER_COUNTER_READ_TCNT_BIT        0xFFFFFFFF
#define TMR_T3TIMER_COUNTER_READ_TCNT_BITWIDTH   32

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* _TMR_REG_DEF_H */
