/*
 * arch/arm/mach-tz2000/include/mach/regs/usb2hce_reg_def.h
 *
 * (C) Copyright TOSHIBA Corporation
 * Semiconductor & Storage Products Company 2013
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#ifndef _USB2HCE_REG_DEF_H
#define _USB2HCE_REG_DEF_H

#ifdef __cplusplus
extern  {
#endif /* __cplusplus */

// HCCAPBASE Register
#define USB2HCE_HCCAPBASE_OFS                    0x00000000
// Reserved2 bitfiled (RO) Reset=0
#define USB2HCE_HCCAPBASE_RESERVED2_MASK         0x3
#define USB2HCE_HCCAPBASE_RESERVED2_SHIFT        0 
#define USB2HCE_HCCAPBASE_RESERVED2_BIT          0x3
#define USB2HCE_HCCAPBASE_RESERVED2_BITWIDTH     2
// CAPLENGTH bitfiled (RO) Reset=100
#define USB2HCE_HCCAPBASE_CAPLENGTH_MASK         0xFC
#define USB2HCE_HCCAPBASE_CAPLENGTH_SHIFT        2 
#define USB2HCE_HCCAPBASE_CAPLENGTH_BIT          0x3F
#define USB2HCE_HCCAPBASE_CAPLENGTH_BITWIDTH     6
// Reserved bitfiled (RO) Reset=0
#define USB2HCE_HCCAPBASE_RESERVED_MASK          0xFF00
#define USB2HCE_HCCAPBASE_RESERVED_SHIFT         8 
#define USB2HCE_HCCAPBASE_RESERVED_BIT           0xFF
#define USB2HCE_HCCAPBASE_RESERVED_BITWIDTH      8
// HCIVERSION bitfiled (RO) Reset=100000000
#define USB2HCE_HCCAPBASE_HCIVERSION_MASK        0xFFFF0000
#define USB2HCE_HCCAPBASE_HCIVERSION_SHIFT       16 
#define USB2HCE_HCCAPBASE_HCIVERSION_BIT         0xFFFF
#define USB2HCE_HCCAPBASE_HCIVERSION_BITWIDTH    16
// HCSPARAMS Register
#define USB2HCE_HCSPARAMS_OFS                    0x00000004
// n_ports bitfiled (RO) Reset=1
#define USB2HCE_HCSPARAMS_N_PORTS_MASK           0xF
#define USB2HCE_HCSPARAMS_N_PORTS_SHIFT          0 
#define USB2HCE_HCSPARAMS_N_PORTS_BIT            0xF
#define USB2HCE_HCSPARAMS_N_PORTS_BITWIDTH       4
// ppc bitfiled (RO) Reset=0
#define USB2HCE_HCSPARAMS_PPC_MASK               0x10
#define USB2HCE_HCSPARAMS_PPC_SHIFT              4 
#define USB2HCE_HCSPARAMS_PPC_BIT                0x1
#define USB2HCE_HCSPARAMS_PPC_BITWIDTH           1
// Reserved3 bitfiled (RO) Reset=0
#define USB2HCE_HCSPARAMS_RESERVED3_MASK         0x60
#define USB2HCE_HCSPARAMS_RESERVED3_SHIFT        5 
#define USB2HCE_HCSPARAMS_RESERVED3_BIT          0x3
#define USB2HCE_HCSPARAMS_RESERVED3_BITWIDTH     2
// port_route_rules bitfiled (RO) Reset=0
#define USB2HCE_HCSPARAMS_PORT_ROUTE_RULES_MASK  0x80
#define USB2HCE_HCSPARAMS_PORT_ROUTE_RULES_SHIFT 7 
#define USB2HCE_HCSPARAMS_PORT_ROUTE_RULES_BIT   0x1
#define USB2HCE_HCSPARAMS_PORT_ROUTE_RULES_BITWIDTH 1
// n_pcc bitfiled (RO) Reset=1
#define USB2HCE_HCSPARAMS_N_PCC_MASK             0xF00
#define USB2HCE_HCSPARAMS_N_PCC_SHIFT            8 
#define USB2HCE_HCSPARAMS_N_PCC_BIT              0xF
#define USB2HCE_HCSPARAMS_N_PCC_BITWIDTH         4
// n_cc bitfiled (RO) Reset=1
#define USB2HCE_HCSPARAMS_N_CC_MASK              0xF000
#define USB2HCE_HCSPARAMS_N_CC_SHIFT             12 
#define USB2HCE_HCSPARAMS_N_CC_BIT               0xF
#define USB2HCE_HCSPARAMS_N_CC_BITWIDTH          4
// p_indicator bitfiled (RO) Reset=0
#define USB2HCE_HCSPARAMS_P_INDICATOR_MASK       0x10000
#define USB2HCE_HCSPARAMS_P_INDICATOR_SHIFT      16 
#define USB2HCE_HCSPARAMS_P_INDICATOR_BIT        0x1
#define USB2HCE_HCSPARAMS_P_INDICATOR_BITWIDTH   1
// Reserved2 bitfiled (RO) Reset=0
#define USB2HCE_HCSPARAMS_RESERVED2_MASK         0xE0000
#define USB2HCE_HCSPARAMS_RESERVED2_SHIFT        17 
#define USB2HCE_HCSPARAMS_RESERVED2_BIT          0x7
#define USB2HCE_HCSPARAMS_RESERVED2_BITWIDTH     3
// debug_port_number bitfiled (RO) Reset=0
#define USB2HCE_HCSPARAMS_DEBUG_PORT_NUMBER_MASK 0xF00000
#define USB2HCE_HCSPARAMS_DEBUG_PORT_NUMBER_SHIFT 20 
#define USB2HCE_HCSPARAMS_DEBUG_PORT_NUMBER_BIT  0xF
#define USB2HCE_HCSPARAMS_DEBUG_PORT_NUMBER_BITWIDTH 4
// Reserved bitfiled (RO) Reset=0
#define USB2HCE_HCSPARAMS_RESERVED_MASK          0xFF000000
#define USB2HCE_HCSPARAMS_RESERVED_SHIFT         24 
#define USB2HCE_HCSPARAMS_RESERVED_BIT           0xFF
#define USB2HCE_HCSPARAMS_RESERVED_BITWIDTH      8
// HCCPARAMS Register
#define USB2HCE_HCCPARAMS_OFS                    0x00000008
// address_64bit_cap bitfiled (RO) Reset=0
#define USB2HCE_HCCPARAMS_ADDRESS_64BIT_CAP_MASK 0x1
#define USB2HCE_HCCPARAMS_ADDRESS_64BIT_CAP_SHIFT 0 
#define USB2HCE_HCCPARAMS_ADDRESS_64BIT_CAP_BIT  0x1
#define USB2HCE_HCCPARAMS_ADDRESS_64BIT_CAP_BITWIDTH 1
// frame_list_flag bitfiled (RO) Reset=0
#define USB2HCE_HCCPARAMS_FRAME_LIST_FLAG_MASK   0x2
#define USB2HCE_HCCPARAMS_FRAME_LIST_FLAG_SHIFT  1 
#define USB2HCE_HCCPARAMS_FRAME_LIST_FLAG_BIT    0x1
#define USB2HCE_HCCPARAMS_FRAME_LIST_FLAG_BITWIDTH 1
// async_schedule_park_cap bitfiled (RO) Reset=1
#define USB2HCE_HCCPARAMS_ASYNC_SCHEDULE_PARK_CAP_MASK 0x4
#define USB2HCE_HCCPARAMS_ASYNC_SCHEDULE_PARK_CAP_SHIFT 2 
#define USB2HCE_HCCPARAMS_ASYNC_SCHEDULE_PARK_CAP_BIT 0x1
#define USB2HCE_HCCPARAMS_ASYNC_SCHEDULE_PARK_CAP_BITWIDTH 1
// Reserved3 bitfiled (RO) Reset=0
#define USB2HCE_HCCPARAMS_RESERVED3_MASK         0x8
#define USB2HCE_HCCPARAMS_RESERVED3_SHIFT        3 
#define USB2HCE_HCCPARAMS_RESERVED3_BIT          0x1
#define USB2HCE_HCCPARAMS_RESERVED3_BITWIDTH     1
// isoc_schedule_threshold bitfiled (RO) Reset=1
#define USB2HCE_HCCPARAMS_ISOC_SCHEDULE_THRESHOLD_MASK 0xF0
#define USB2HCE_HCCPARAMS_ISOC_SCHEDULE_THRESHOLD_SHIFT 4 
#define USB2HCE_HCCPARAMS_ISOC_SCHEDULE_THRESHOLD_BIT 0xF
#define USB2HCE_HCCPARAMS_ISOC_SCHEDULE_THRESHOLD_BITWIDTH 4
// eecp bitfiled (RO) Reset=0
#define USB2HCE_HCCPARAMS_EECP_MASK              0xFF00
#define USB2HCE_HCCPARAMS_EECP_SHIFT             8 
#define USB2HCE_HCCPARAMS_EECP_BIT               0xFF
#define USB2HCE_HCCPARAMS_EECP_BITWIDTH          8
// Reserved2 bitfiled (RO) Reset=0
#define USB2HCE_HCCPARAMS_RESERVED2_MASK         0x10000
#define USB2HCE_HCCPARAMS_RESERVED2_SHIFT        16 
#define USB2HCE_HCCPARAMS_RESERVED2_BIT          0x1
#define USB2HCE_HCCPARAMS_RESERVED2_BITWIDTH     1
// link_power_mgmt_cap bitfiled (RO) Reset=0
#define USB2HCE_HCCPARAMS_LINK_POWER_MGMT_CAP_MASK 0x20000
#define USB2HCE_HCCPARAMS_LINK_POWER_MGMT_CAP_SHIFT 17 
#define USB2HCE_HCCPARAMS_LINK_POWER_MGMT_CAP_BIT 0x1
#define USB2HCE_HCCPARAMS_LINK_POWER_MGMT_CAP_BITWIDTH 1
// Reserved bitfiled (RO) Reset=0
#define USB2HCE_HCCPARAMS_RESERVED_MASK          0xFFFC0000
#define USB2HCE_HCCPARAMS_RESERVED_SHIFT         18 
#define USB2HCE_HCCPARAMS_RESERVED_BIT           0x3FFF
#define USB2HCE_HCCPARAMS_RESERVED_BITWIDTH      14
// USBCMD Register
#define USB2HCE_USBCMD_OFS                       0x00000010
// run_stop bitfiled (RW) Reset=0
#define USB2HCE_USBCMD_RUN_STOP_MASK             0x1
#define USB2HCE_USBCMD_RUN_STOP_SHIFT            0 
#define USB2HCE_USBCMD_RUN_STOP_BIT              0x1
#define USB2HCE_USBCMD_RUN_STOP_BITWIDTH         1
// hcreset bitfiled (RW) Reset=0
#define USB2HCE_USBCMD_HCRESET_MASK              0x2
#define USB2HCE_USBCMD_HCRESET_SHIFT             1 
#define USB2HCE_USBCMD_HCRESET_BIT               0x1
#define USB2HCE_USBCMD_HCRESET_BITWIDTH          1
// frame_list_size bitfiled (RW) Reset=0
#define USB2HCE_USBCMD_FRAME_LIST_SIZE_MASK      0xC
#define USB2HCE_USBCMD_FRAME_LIST_SIZE_SHIFT     2 
#define USB2HCE_USBCMD_FRAME_LIST_SIZE_BIT       0x3
#define USB2HCE_USBCMD_FRAME_LIST_SIZE_BITWIDTH  2
// periodic_schedule_enable bitfiled (RW) Reset=0
#define USB2HCE_USBCMD_PERIODIC_SCHEDULE_ENABLE_MASK 0x10
#define USB2HCE_USBCMD_PERIODIC_SCHEDULE_ENABLE_SHIFT 4 
#define USB2HCE_USBCMD_PERIODIC_SCHEDULE_ENABLE_BIT 0x1
#define USB2HCE_USBCMD_PERIODIC_SCHEDULE_ENABLE_BITWIDTH 1
// async_schedule_enable bitfiled (RW) Reset=0
#define USB2HCE_USBCMD_ASYNC_SCHEDULE_ENABLE_MASK 0x20
#define USB2HCE_USBCMD_ASYNC_SCHEDULE_ENABLE_SHIFT 5 
#define USB2HCE_USBCMD_ASYNC_SCHEDULE_ENABLE_BIT 0x1
#define USB2HCE_USBCMD_ASYNC_SCHEDULE_ENABLE_BITWIDTH 1
// intr_on_async_advance_drbell bitfiled (RW) Reset=0
#define USB2HCE_USBCMD_INTR_ON_ASYNC_ADVANCE_DRBELL_MASK 0x40
#define USB2HCE_USBCMD_INTR_ON_ASYNC_ADVANCE_DRBELL_SHIFT 6 
#define USB2HCE_USBCMD_INTR_ON_ASYNC_ADVANCE_DRBELL_BIT 0x1
#define USB2HCE_USBCMD_INTR_ON_ASYNC_ADVANCE_DRBELL_BITWIDTH 1
// light_hcreset bitfiled (RW) Reset=0
#define USB2HCE_USBCMD_LIGHT_HCRESET_MASK        0x80
#define USB2HCE_USBCMD_LIGHT_HCRESET_SHIFT       7 
#define USB2HCE_USBCMD_LIGHT_HCRESET_BIT         0x1
#define USB2HCE_USBCMD_LIGHT_HCRESET_BITWIDTH    1
// async_schedule_park_mode_cnt bitfiled (RW) Reset=11
#define USB2HCE_USBCMD_ASYNC_SCHEDULE_PARK_MODE_CNT_MASK 0x300
#define USB2HCE_USBCMD_ASYNC_SCHEDULE_PARK_MODE_CNT_SHIFT 8 
#define USB2HCE_USBCMD_ASYNC_SCHEDULE_PARK_MODE_CNT_BIT 0x3
#define USB2HCE_USBCMD_ASYNC_SCHEDULE_PARK_MODE_CNT_BITWIDTH 2
// Reserved3 bitfiled (RO) Reset=0
#define USB2HCE_USBCMD_RESERVED3_MASK            0x400
#define USB2HCE_USBCMD_RESERVED3_SHIFT           10 
#define USB2HCE_USBCMD_RESERVED3_BIT             0x1
#define USB2HCE_USBCMD_RESERVED3_BITWIDTH        1
// async_schedule_park_mode_enable bitfiled (RW) Reset=1
#define USB2HCE_USBCMD_ASYNC_SCHEDULE_PARK_MODE_ENABLE_MASK 0x800
#define USB2HCE_USBCMD_ASYNC_SCHEDULE_PARK_MODE_ENABLE_SHIFT 11 
#define USB2HCE_USBCMD_ASYNC_SCHEDULE_PARK_MODE_ENABLE_BIT 0x1
#define USB2HCE_USBCMD_ASYNC_SCHEDULE_PARK_MODE_ENABLE_BITWIDTH 1
// Reserved2 bitfiled (RO) Reset=0
#define USB2HCE_USBCMD_RESERVED2_MASK            0xF000
#define USB2HCE_USBCMD_RESERVED2_SHIFT           12 
#define USB2HCE_USBCMD_RESERVED2_BIT             0xF
#define USB2HCE_USBCMD_RESERVED2_BITWIDTH        4
// intr_threshold_ctrl bitfiled (RW) Reset=1000
#define USB2HCE_USBCMD_INTR_THRESHOLD_CTRL_MASK  0xFF0000
#define USB2HCE_USBCMD_INTR_THRESHOLD_CTRL_SHIFT 16 
#define USB2HCE_USBCMD_INTR_THRESHOLD_CTRL_BIT   0xFF
#define USB2HCE_USBCMD_INTR_THRESHOLD_CTRL_BITWIDTH 8
// Reserved bitfiled (RO) Reset=0
#define USB2HCE_USBCMD_RESERVED_MASK             0xFF000000
#define USB2HCE_USBCMD_RESERVED_SHIFT            24 
#define USB2HCE_USBCMD_RESERVED_BIT              0xFF
#define USB2HCE_USBCMD_RESERVED_BITWIDTH         8
// USBSTS Register
#define USB2HCE_USBSTS_OFS                       0x00000014
// usbint bitfiled (RW) Reset=0
#define USB2HCE_USBSTS_USBINT_MASK               0x1
#define USB2HCE_USBSTS_USBINT_SHIFT              0 
#define USB2HCE_USBSTS_USBINT_BIT                0x1
#define USB2HCE_USBSTS_USBINT_BITWIDTH           1
// usberrint bitfiled (RW) Reset=0
#define USB2HCE_USBSTS_USBERRINT_MASK            0x2
#define USB2HCE_USBSTS_USBERRINT_SHIFT           1 
#define USB2HCE_USBSTS_USBERRINT_BIT             0x1
#define USB2HCE_USBSTS_USBERRINT_BITWIDTH        1
// port_change_detect bitfiled (RW) Reset=0
#define USB2HCE_USBSTS_PORT_CHANGE_DETECT_MASK   0x4
#define USB2HCE_USBSTS_PORT_CHANGE_DETECT_SHIFT  2 
#define USB2HCE_USBSTS_PORT_CHANGE_DETECT_BIT    0x1
#define USB2HCE_USBSTS_PORT_CHANGE_DETECT_BITWIDTH 1
// frame_list_rollover bitfiled (RW) Reset=0
#define USB2HCE_USBSTS_FRAME_LIST_ROLLOVER_MASK  0x8
#define USB2HCE_USBSTS_FRAME_LIST_ROLLOVER_SHIFT 3 
#define USB2HCE_USBSTS_FRAME_LIST_ROLLOVER_BIT   0x1
#define USB2HCE_USBSTS_FRAME_LIST_ROLLOVER_BITWIDTH 1
// host_system_error bitfiled (RW) Reset=0
#define USB2HCE_USBSTS_HOST_SYSTEM_ERROR_MASK    0x10
#define USB2HCE_USBSTS_HOST_SYSTEM_ERROR_SHIFT   4 
#define USB2HCE_USBSTS_HOST_SYSTEM_ERROR_BIT     0x1
#define USB2HCE_USBSTS_HOST_SYSTEM_ERROR_BITWIDTH 1
// intr_on_async_advance bitfiled (RW) Reset=0
#define USB2HCE_USBSTS_INTR_ON_ASYNC_ADVANCE_MASK 0x20
#define USB2HCE_USBSTS_INTR_ON_ASYNC_ADVANCE_SHIFT 5 
#define USB2HCE_USBSTS_INTR_ON_ASYNC_ADVANCE_BIT 0x1
#define USB2HCE_USBSTS_INTR_ON_ASYNC_ADVANCE_BITWIDTH 1
// Reserved2 bitfiled (RO) Reset=0
#define USB2HCE_USBSTS_RESERVED2_MASK            0xFC0
#define USB2HCE_USBSTS_RESERVED2_SHIFT           6 
#define USB2HCE_USBSTS_RESERVED2_BIT             0x3F
#define USB2HCE_USBSTS_RESERVED2_BITWIDTH        6
// hchalted bitfiled (RO) Reset=1
#define USB2HCE_USBSTS_HCHALTED_MASK             0x1000
#define USB2HCE_USBSTS_HCHALTED_SHIFT            12 
#define USB2HCE_USBSTS_HCHALTED_BIT              0x1
#define USB2HCE_USBSTS_HCHALTED_BITWIDTH         1
// reclamation bitfiled (RO) Reset=0
#define USB2HCE_USBSTS_RECLAMATION_MASK          0x2000
#define USB2HCE_USBSTS_RECLAMATION_SHIFT         13 
#define USB2HCE_USBSTS_RECLAMATION_BIT           0x1
#define USB2HCE_USBSTS_RECLAMATION_BITWIDTH      1
// periodic_schedule_status bitfiled (RO) Reset=0
#define USB2HCE_USBSTS_PERIODIC_SCHEDULE_STATUS_MASK 0x4000
#define USB2HCE_USBSTS_PERIODIC_SCHEDULE_STATUS_SHIFT 14 
#define USB2HCE_USBSTS_PERIODIC_SCHEDULE_STATUS_BIT 0x1
#define USB2HCE_USBSTS_PERIODIC_SCHEDULE_STATUS_BITWIDTH 1
// async_schedule_status bitfiled (RO) Reset=0
#define USB2HCE_USBSTS_ASYNC_SCHEDULE_STATUS_MASK 0x8000
#define USB2HCE_USBSTS_ASYNC_SCHEDULE_STATUS_SHIFT 15 
#define USB2HCE_USBSTS_ASYNC_SCHEDULE_STATUS_BIT 0x1
#define USB2HCE_USBSTS_ASYNC_SCHEDULE_STATUS_BITWIDTH 1
// Reserved bitfiled (RO) Reset=0
#define USB2HCE_USBSTS_RESERVED_MASK             0xFFFF0000
#define USB2HCE_USBSTS_RESERVED_SHIFT            16 
#define USB2HCE_USBSTS_RESERVED_BIT              0xFFFF
#define USB2HCE_USBSTS_RESERVED_BITWIDTH         16
// USBINTR Register
#define USB2HCE_USBINTR_OFS                      0x00000018
// usbint_enable bitfiled (RW) Reset=0
#define USB2HCE_USBINTR_USBINT_ENABLE_MASK       0x1
#define USB2HCE_USBINTR_USBINT_ENABLE_SHIFT      0 
#define USB2HCE_USBINTR_USBINT_ENABLE_BIT        0x1
#define USB2HCE_USBINTR_USBINT_ENABLE_BITWIDTH   1
// usberrint_enable bitfiled (RW) Reset=0
#define USB2HCE_USBINTR_USBERRINT_ENABLE_MASK    0x2
#define USB2HCE_USBINTR_USBERRINT_ENABLE_SHIFT   1 
#define USB2HCE_USBINTR_USBERRINT_ENABLE_BIT     0x1
#define USB2HCE_USBINTR_USBERRINT_ENABLE_BITWIDTH 1
// port_change_intr_enable bitfiled (RW) Reset=0
#define USB2HCE_USBINTR_PORT_CHANGE_INTR_ENABLE_MASK 0x4
#define USB2HCE_USBINTR_PORT_CHANGE_INTR_ENABLE_SHIFT 2 
#define USB2HCE_USBINTR_PORT_CHANGE_INTR_ENABLE_BIT 0x1
#define USB2HCE_USBINTR_PORT_CHANGE_INTR_ENABLE_BITWIDTH 1
// frame_list_rollover_enable bitfiled (RW) Reset=0
#define USB2HCE_USBINTR_FRAME_LIST_ROLLOVER_ENABLE_MASK 0x8
#define USB2HCE_USBINTR_FRAME_LIST_ROLLOVER_ENABLE_SHIFT 3 
#define USB2HCE_USBINTR_FRAME_LIST_ROLLOVER_ENABLE_BIT 0x1
#define USB2HCE_USBINTR_FRAME_LIST_ROLLOVER_ENABLE_BITWIDTH 1
// host_system_err_enable bitfiled (RW) Reset=0
#define USB2HCE_USBINTR_HOST_SYSTEM_ERR_ENABLE_MASK 0x10
#define USB2HCE_USBINTR_HOST_SYSTEM_ERR_ENABLE_SHIFT 4 
#define USB2HCE_USBINTR_HOST_SYSTEM_ERR_ENABLE_BIT 0x1
#define USB2HCE_USBINTR_HOST_SYSTEM_ERR_ENABLE_BITWIDTH 1
// intr_on_async_advance_enable bitfiled (RW) Reset=0
#define USB2HCE_USBINTR_INTR_ON_ASYNC_ADVANCE_ENABLE_MASK 0x20
#define USB2HCE_USBINTR_INTR_ON_ASYNC_ADVANCE_ENABLE_SHIFT 5 
#define USB2HCE_USBINTR_INTR_ON_ASYNC_ADVANCE_ENABLE_BIT 0x1
#define USB2HCE_USBINTR_INTR_ON_ASYNC_ADVANCE_ENABLE_BITWIDTH 1
// Reserved bitfiled (RO) Reset=0
#define USB2HCE_USBINTR_RESERVED_MASK            0xFFFFFFC0
#define USB2HCE_USBINTR_RESERVED_SHIFT           6 
#define USB2HCE_USBINTR_RESERVED_BIT             0x3FFFFFF
#define USB2HCE_USBINTR_RESERVED_BITWIDTH        26
// FRINDEX Register
#define USB2HCE_FRINDEX_OFS                      0x0000001C
// frame_index bitfiled (RW) Reset=0
#define USB2HCE_FRINDEX_FRAME_INDEX_MASK         0x3FFF
#define USB2HCE_FRINDEX_FRAME_INDEX_SHIFT        0 
#define USB2HCE_FRINDEX_FRAME_INDEX_BIT          0x3FFF
#define USB2HCE_FRINDEX_FRAME_INDEX_BITWIDTH     14
// Reserved bitfiled (RO) Reset=0
#define USB2HCE_FRINDEX_RESERVED_MASK            0xFFFFC000
#define USB2HCE_FRINDEX_RESERVED_SHIFT           14 
#define USB2HCE_FRINDEX_RESERVED_BIT             0x3FFFF
#define USB2HCE_FRINDEX_RESERVED_BITWIDTH        18
// CTRLDSSEGMENT Register
#define USB2HCE_CTRLDSSEGMENT_OFS                0x00000020
// seg_4g_selector bitfiled (RW) Reset=0
#define USB2HCE_CTRLDSSEGMENT_SEG_4G_SELECTOR_MASK 0xFFFFFFFF
#define USB2HCE_CTRLDSSEGMENT_SEG_4G_SELECTOR_SHIFT 0 
#define USB2HCE_CTRLDSSEGMENT_SEG_4G_SELECTOR_BIT 0xFFFFFFFF
#define USB2HCE_CTRLDSSEGMENT_SEG_4G_SELECTOR_BITWIDTH 32
// PERIODICLISTBASE Register
#define USB2HCE_PERIODICLISTBASE_OFS             0x00000024
// Reserved bitfiled (RO) Reset=0
#define USB2HCE_PERIODICLISTBASE_RESERVED_MASK   0xFFF
#define USB2HCE_PERIODICLISTBASE_RESERVED_SHIFT  0 
#define USB2HCE_PERIODICLISTBASE_RESERVED_BIT    0xFFF
#define USB2HCE_PERIODICLISTBASE_RESERVED_BITWIDTH 12
// base_address bitfiled (RW) Reset=0
#define USB2HCE_PERIODICLISTBASE_BASE_ADDRESS_MASK 0xFFFFF000
#define USB2HCE_PERIODICLISTBASE_BASE_ADDRESS_SHIFT 12 
#define USB2HCE_PERIODICLISTBASE_BASE_ADDRESS_BIT 0xFFFFF
#define USB2HCE_PERIODICLISTBASE_BASE_ADDRESS_BITWIDTH 20
// ASYNCLISTADDR Register
#define USB2HCE_ASYNCLISTADDR_OFS                0x00000028
// Reserved bitfiled (RO) Reset=0
#define USB2HCE_ASYNCLISTADDR_RESERVED_MASK      0x1F
#define USB2HCE_ASYNCLISTADDR_RESERVED_SHIFT     0 
#define USB2HCE_ASYNCLISTADDR_RESERVED_BIT       0x1F
#define USB2HCE_ASYNCLISTADDR_RESERVED_BITWIDTH  5
// lpl bitfiled (RW) Reset=0
#define USB2HCE_ASYNCLISTADDR_LPL_MASK           0xFFFFFFE0
#define USB2HCE_ASYNCLISTADDR_LPL_SHIFT          5 
#define USB2HCE_ASYNCLISTADDR_LPL_BIT            0x7FFFFFF
#define USB2HCE_ASYNCLISTADDR_LPL_BITWIDTH       27
// CONFIGFLAG Register
#define USB2HCE_CONFIGFLAG_OFS                   0x00000050
// cf bitfiled (RW) Reset=0
#define USB2HCE_CONFIGFLAG_CF_MASK               0x1
#define USB2HCE_CONFIGFLAG_CF_SHIFT              0 
#define USB2HCE_CONFIGFLAG_CF_BIT                0x1
#define USB2HCE_CONFIGFLAG_CF_BITWIDTH           1
// Reserved bitfiled (RO) Reset=0
#define USB2HCE_CONFIGFLAG_RESERVED_MASK         0xFFFFFFFE
#define USB2HCE_CONFIGFLAG_RESERVED_SHIFT        1 
#define USB2HCE_CONFIGFLAG_RESERVED_BIT          0x7FFFFFFF
#define USB2HCE_CONFIGFLAG_RESERVED_BITWIDTH     31
// PORTSC_0 Register
#define USB2HCE_PORTSC_0_OFS                     0x00000054
// current_connect_status bitfiled (RO) Reset=0
#define USB2HCE_PORTSC_0_CURRENT_CONNECT_STATUS_MASK 0x1
#define USB2HCE_PORTSC_0_CURRENT_CONNECT_STATUS_SHIFT 0 
#define USB2HCE_PORTSC_0_CURRENT_CONNECT_STATUS_BIT 0x1
#define USB2HCE_PORTSC_0_CURRENT_CONNECT_STATUS_BITWIDTH 1
// connect_status_change bitfiled (RW) Reset=0
#define USB2HCE_PORTSC_0_CONNECT_STATUS_CHANGE_MASK 0x2
#define USB2HCE_PORTSC_0_CONNECT_STATUS_CHANGE_SHIFT 1 
#define USB2HCE_PORTSC_0_CONNECT_STATUS_CHANGE_BIT 0x1
#define USB2HCE_PORTSC_0_CONNECT_STATUS_CHANGE_BITWIDTH 1
// port_enable_disable bitfiled (RW) Reset=0
#define USB2HCE_PORTSC_0_PORT_ENABLE_DISABLE_MASK 0x4
#define USB2HCE_PORTSC_0_PORT_ENABLE_DISABLE_SHIFT 2 
#define USB2HCE_PORTSC_0_PORT_ENABLE_DISABLE_BIT 0x1
#define USB2HCE_PORTSC_0_PORT_ENABLE_DISABLE_BITWIDTH 1
// port_en_dis_change bitfiled (RW) Reset=0
#define USB2HCE_PORTSC_0_PORT_EN_DIS_CHANGE_MASK 0x8
#define USB2HCE_PORTSC_0_PORT_EN_DIS_CHANGE_SHIFT 3 
#define USB2HCE_PORTSC_0_PORT_EN_DIS_CHANGE_BIT  0x1
#define USB2HCE_PORTSC_0_PORT_EN_DIS_CHANGE_BITWIDTH 1
// over_current_active bitfiled (RO) Reset=0
#define USB2HCE_PORTSC_0_OVER_CURRENT_ACTIVE_MASK 0x10
#define USB2HCE_PORTSC_0_OVER_CURRENT_ACTIVE_SHIFT 4 
#define USB2HCE_PORTSC_0_OVER_CURRENT_ACTIVE_BIT 0x1
#define USB2HCE_PORTSC_0_OVER_CURRENT_ACTIVE_BITWIDTH 1
// over_current_change bitfiled (RW) Reset=0
#define USB2HCE_PORTSC_0_OVER_CURRENT_CHANGE_MASK 0x20
#define USB2HCE_PORTSC_0_OVER_CURRENT_CHANGE_SHIFT 5 
#define USB2HCE_PORTSC_0_OVER_CURRENT_CHANGE_BIT 0x1
#define USB2HCE_PORTSC_0_OVER_CURRENT_CHANGE_BITWIDTH 1
// force_port_resume bitfiled (RW) Reset=0
#define USB2HCE_PORTSC_0_FORCE_PORT_RESUME_MASK  0x40
#define USB2HCE_PORTSC_0_FORCE_PORT_RESUME_SHIFT 6 
#define USB2HCE_PORTSC_0_FORCE_PORT_RESUME_BIT   0x1
#define USB2HCE_PORTSC_0_FORCE_PORT_RESUME_BITWIDTH 1
// suspend bitfiled (RW) Reset=0
#define USB2HCE_PORTSC_0_SUSPEND_MASK            0x80
#define USB2HCE_PORTSC_0_SUSPEND_SHIFT           7 
#define USB2HCE_PORTSC_0_SUSPEND_BIT             0x1
#define USB2HCE_PORTSC_0_SUSPEND_BITWIDTH        1
// port_reset bitfiled (RW) Reset=0
#define USB2HCE_PORTSC_0_PORT_RESET_MASK         0x100
#define USB2HCE_PORTSC_0_PORT_RESET_SHIFT        8 
#define USB2HCE_PORTSC_0_PORT_RESET_BIT          0x1
#define USB2HCE_PORTSC_0_PORT_RESET_BITWIDTH     1
// Reserved2 bitfiled (RO) Reset=0
#define USB2HCE_PORTSC_0_RESERVED2_MASK          0x200
#define USB2HCE_PORTSC_0_RESERVED2_SHIFT         9 
#define USB2HCE_PORTSC_0_RESERVED2_BIT           0x1
#define USB2HCE_PORTSC_0_RESERVED2_BITWIDTH      1
// line_status bitfiled (RW) Reset=0
#define USB2HCE_PORTSC_0_LINE_STATUS_MASK        0xC00
#define USB2HCE_PORTSC_0_LINE_STATUS_SHIFT       10 
#define USB2HCE_PORTSC_0_LINE_STATUS_BIT         0x3
#define USB2HCE_PORTSC_0_LINE_STATUS_BITWIDTH    2
// pp bitfiled (RO) Reset=1
#define USB2HCE_PORTSC_0_PP_MASK                 0x1000
#define USB2HCE_PORTSC_0_PP_SHIFT                12 
#define USB2HCE_PORTSC_0_PP_BIT                  0x1
#define USB2HCE_PORTSC_0_PP_BITWIDTH             1
// port_owner bitfiled (RW) Reset=1
#define USB2HCE_PORTSC_0_PORT_OWNER_MASK         0x2000
#define USB2HCE_PORTSC_0_PORT_OWNER_SHIFT        13 
#define USB2HCE_PORTSC_0_PORT_OWNER_BIT          0x1
#define USB2HCE_PORTSC_0_PORT_OWNER_BITWIDTH     1
// port_indicator_ctrl bitfiled (RO) Reset=0
#define USB2HCE_PORTSC_0_PORT_INDICATOR_CTRL_MASK 0xC000
#define USB2HCE_PORTSC_0_PORT_INDICATOR_CTRL_SHIFT 14 
#define USB2HCE_PORTSC_0_PORT_INDICATOR_CTRL_BIT 0x3
#define USB2HCE_PORTSC_0_PORT_INDICATOR_CTRL_BITWIDTH 2
// port_test_ctrl bitfiled (RW) Reset=0
#define USB2HCE_PORTSC_0_PORT_TEST_CTRL_MASK     0xF0000
#define USB2HCE_PORTSC_0_PORT_TEST_CTRL_SHIFT    16 
#define USB2HCE_PORTSC_0_PORT_TEST_CTRL_BIT      0xF
#define USB2HCE_PORTSC_0_PORT_TEST_CTRL_BITWIDTH 4
// wkcnnt_e bitfiled (RW) Reset=0
#define USB2HCE_PORTSC_0_WKCNNT_E_MASK           0x100000
#define USB2HCE_PORTSC_0_WKCNNT_E_SHIFT          20 
#define USB2HCE_PORTSC_0_WKCNNT_E_BIT            0x1
#define USB2HCE_PORTSC_0_WKCNNT_E_BITWIDTH       1
// wkdscnnt_e bitfiled (RW) Reset=0
#define USB2HCE_PORTSC_0_WKDSCNNT_E_MASK         0x200000
#define USB2HCE_PORTSC_0_WKDSCNNT_E_SHIFT        21 
#define USB2HCE_PORTSC_0_WKDSCNNT_E_BIT          0x1
#define USB2HCE_PORTSC_0_WKDSCNNT_E_BITWIDTH     1
// wkoc_e bitfiled (RW) Reset=0
#define USB2HCE_PORTSC_0_WKOC_E_MASK             0x400000
#define USB2HCE_PORTSC_0_WKOC_E_SHIFT            22 
#define USB2HCE_PORTSC_0_WKOC_E_BIT              0x1
#define USB2HCE_PORTSC_0_WKOC_E_BITWIDTH         1
// Reserved bitfiled (RO) Reset=0
#define USB2HCE_PORTSC_0_RESERVED_MASK           0xFF800000
#define USB2HCE_PORTSC_0_RESERVED_SHIFT          23 
#define USB2HCE_PORTSC_0_RESERVED_BIT            0x1FF
#define USB2HCE_PORTSC_0_RESERVED_BITWIDTH       9

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* _USB2HCE_REG_DEF_H */
