/*
 * arch/arm/mach-tz2000/include/mach/regs/wconf_reg_def.h
 *
 * (C) Copyright TOSHIBA Corporation
 * Semiconductor & Storage Products Company 2013
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#ifndef _WCONF_REG_DEF_H
#define _WCONF_REG_DEF_H

#ifdef __cplusplus
extern  {
#endif /* __cplusplus */

// EMMC4SD_CFG_CAPABILITY0 Register
#define WCONF_EMMC4SD_CFG_CAPABILITY0_OFS        0x00000000
// TIMEOUTCLKFREQ bitfiled (RW) Reset=1
#define WCONF_EMMC4SD_CFG_CAPABILITY0_TIMEOUTCLKFREQ_MASK 0x3F
#define WCONF_EMMC4SD_CFG_CAPABILITY0_TIMEOUTCLKFREQ_SHIFT 0 
#define WCONF_EMMC4SD_CFG_CAPABILITY0_TIMEOUTCLKFREQ_BIT 0x3F
#define WCONF_EMMC4SD_CFG_CAPABILITY0_TIMEOUTCLKFREQ_BITWIDTH 6
// reserved1 bitfiled (RO) Reset=0
#define WCONF_EMMC4SD_CFG_CAPABILITY0_RESERVED1_MASK 0x40
#define WCONF_EMMC4SD_CFG_CAPABILITY0_RESERVED1_SHIFT 6 
#define WCONF_EMMC4SD_CFG_CAPABILITY0_RESERVED1_BIT 0x1
#define WCONF_EMMC4SD_CFG_CAPABILITY0_RESERVED1_BITWIDTH 1
// TIMEOUTCLKUNIT bitfiled (RW) Reset=1
#define WCONF_EMMC4SD_CFG_CAPABILITY0_TIMEOUTCLKUNIT_MASK 0x80
#define WCONF_EMMC4SD_CFG_CAPABILITY0_TIMEOUTCLKUNIT_SHIFT 7 
#define WCONF_EMMC4SD_CFG_CAPABILITY0_TIMEOUTCLKUNIT_BIT 0x1
#define WCONF_EMMC4SD_CFG_CAPABILITY0_TIMEOUTCLKUNIT_BITWIDTH 1
// BASECLKFREQ bitfiled (RW) Reset=1100100
#define WCONF_EMMC4SD_CFG_CAPABILITY0_BASECLKFREQ_MASK 0xFF00
#define WCONF_EMMC4SD_CFG_CAPABILITY0_BASECLKFREQ_SHIFT 8 
#define WCONF_EMMC4SD_CFG_CAPABILITY0_BASECLKFREQ_BIT 0xFF
#define WCONF_EMMC4SD_CFG_CAPABILITY0_BASECLKFREQ_BITWIDTH 8
// MAXBLKLENGTH bitfiled (RW) Reset=0
#define WCONF_EMMC4SD_CFG_CAPABILITY0_MAXBLKLENGTH_MASK 0x30000
#define WCONF_EMMC4SD_CFG_CAPABILITY0_MAXBLKLENGTH_SHIFT 16 
#define WCONF_EMMC4SD_CFG_CAPABILITY0_MAXBLKLENGTH_BIT 0x3
#define WCONF_EMMC4SD_CFG_CAPABILITY0_MAXBLKLENGTH_BITWIDTH 2
// SUPPORT8BIT bitfiled (RW) Reset=0
#define WCONF_EMMC4SD_CFG_CAPABILITY0_SUPPORT8BIT_MASK 0x40000
#define WCONF_EMMC4SD_CFG_CAPABILITY0_SUPPORT8BIT_SHIFT 18 
#define WCONF_EMMC4SD_CFG_CAPABILITY0_SUPPORT8BIT_BIT 0x1
#define WCONF_EMMC4SD_CFG_CAPABILITY0_SUPPORT8BIT_BITWIDTH 1
// ADMA2SUPPORT bitfiled (RW) Reset=1
#define WCONF_EMMC4SD_CFG_CAPABILITY0_ADMA2SUPPORT_MASK 0x80000
#define WCONF_EMMC4SD_CFG_CAPABILITY0_ADMA2SUPPORT_SHIFT 19 
#define WCONF_EMMC4SD_CFG_CAPABILITY0_ADMA2SUPPORT_BIT 0x1
#define WCONF_EMMC4SD_CFG_CAPABILITY0_ADMA2SUPPORT_BITWIDTH 1
// reserved2 bitfiled (RO) Reset=0
#define WCONF_EMMC4SD_CFG_CAPABILITY0_RESERVED2_MASK 0x100000
#define WCONF_EMMC4SD_CFG_CAPABILITY0_RESERVED2_SHIFT 20 
#define WCONF_EMMC4SD_CFG_CAPABILITY0_RESERVED2_BIT 0x1
#define WCONF_EMMC4SD_CFG_CAPABILITY0_RESERVED2_BITWIDTH 1
// HIGHSPEEDSUPPORT bitfiled (RW) Reset=1
#define WCONF_EMMC4SD_CFG_CAPABILITY0_HIGHSPEEDSUPPORT_MASK 0x200000
#define WCONF_EMMC4SD_CFG_CAPABILITY0_HIGHSPEEDSUPPORT_SHIFT 21 
#define WCONF_EMMC4SD_CFG_CAPABILITY0_HIGHSPEEDSUPPORT_BIT 0x1
#define WCONF_EMMC4SD_CFG_CAPABILITY0_HIGHSPEEDSUPPORT_BITWIDTH 1
// SDMASUPPORT bitfiled (RW) Reset=1
#define WCONF_EMMC4SD_CFG_CAPABILITY0_SDMASUPPORT_MASK 0x400000
#define WCONF_EMMC4SD_CFG_CAPABILITY0_SDMASUPPORT_SHIFT 22 
#define WCONF_EMMC4SD_CFG_CAPABILITY0_SDMASUPPORT_BIT 0x1
#define WCONF_EMMC4SD_CFG_CAPABILITY0_SDMASUPPORT_BITWIDTH 1
// SUSPRESSUPPORT bitfiled (RW) Reset=1
#define WCONF_EMMC4SD_CFG_CAPABILITY0_SUSPRESSUPPORT_MASK 0x800000
#define WCONF_EMMC4SD_CFG_CAPABILITY0_SUSPRESSUPPORT_SHIFT 23 
#define WCONF_EMMC4SD_CFG_CAPABILITY0_SUSPRESSUPPORT_BIT 0x1
#define WCONF_EMMC4SD_CFG_CAPABILITY0_SUSPRESSUPPORT_BITWIDTH 1
// SUPPORT3P3VOLT bitfiled (RW) Reset=1
#define WCONF_EMMC4SD_CFG_CAPABILITY0_SUPPORT3P3VOLT_MASK 0x1000000
#define WCONF_EMMC4SD_CFG_CAPABILITY0_SUPPORT3P3VOLT_SHIFT 24 
#define WCONF_EMMC4SD_CFG_CAPABILITY0_SUPPORT3P3VOLT_BIT 0x1
#define WCONF_EMMC4SD_CFG_CAPABILITY0_SUPPORT3P3VOLT_BITWIDTH 1
// SUPPORT3P0VOLT bitfiled (RW) Reset=0
#define WCONF_EMMC4SD_CFG_CAPABILITY0_SUPPORT3P0VOLT_MASK 0x2000000
#define WCONF_EMMC4SD_CFG_CAPABILITY0_SUPPORT3P0VOLT_SHIFT 25 
#define WCONF_EMMC4SD_CFG_CAPABILITY0_SUPPORT3P0VOLT_BIT 0x1
#define WCONF_EMMC4SD_CFG_CAPABILITY0_SUPPORT3P0VOLT_BITWIDTH 1
// SUPPORT1P8VOLT bitfiled (RW) Reset=1
#define WCONF_EMMC4SD_CFG_CAPABILITY0_SUPPORT1P8VOLT_MASK 0x4000000
#define WCONF_EMMC4SD_CFG_CAPABILITY0_SUPPORT1P8VOLT_SHIFT 26 
#define WCONF_EMMC4SD_CFG_CAPABILITY0_SUPPORT1P8VOLT_BIT 0x1
#define WCONF_EMMC4SD_CFG_CAPABILITY0_SUPPORT1P8VOLT_BITWIDTH 1
// reserved3 bitfiled (RO) Reset=0
#define WCONF_EMMC4SD_CFG_CAPABILITY0_RESERVED3_MASK 0x8000000
#define WCONF_EMMC4SD_CFG_CAPABILITY0_RESERVED3_SHIFT 27 
#define WCONF_EMMC4SD_CFG_CAPABILITY0_RESERVED3_BIT 0x1
#define WCONF_EMMC4SD_CFG_CAPABILITY0_RESERVED3_BITWIDTH 1
// SUPPORT64BIT bitfiled (RO) Reset=0
#define WCONF_EMMC4SD_CFG_CAPABILITY0_SUPPORT64BIT_MASK 0x10000000
#define WCONF_EMMC4SD_CFG_CAPABILITY0_SUPPORT64BIT_SHIFT 28 
#define WCONF_EMMC4SD_CFG_CAPABILITY0_SUPPORT64BIT_BIT 0x1
#define WCONF_EMMC4SD_CFG_CAPABILITY0_SUPPORT64BIT_BITWIDTH 1
// ASYNCINTRSUPPORT bitfiled (RW) Reset=1
#define WCONF_EMMC4SD_CFG_CAPABILITY0_ASYNCINTRSUPPORT_MASK 0x20000000
#define WCONF_EMMC4SD_CFG_CAPABILITY0_ASYNCINTRSUPPORT_SHIFT 29 
#define WCONF_EMMC4SD_CFG_CAPABILITY0_ASYNCINTRSUPPORT_BIT 0x1
#define WCONF_EMMC4SD_CFG_CAPABILITY0_ASYNCINTRSUPPORT_BITWIDTH 1
// SLOTTYPE bitfiled (RW) Reset=1
#define WCONF_EMMC4SD_CFG_CAPABILITY0_SLOTTYPE_MASK 0xC0000000
#define WCONF_EMMC4SD_CFG_CAPABILITY0_SLOTTYPE_SHIFT 30 
#define WCONF_EMMC4SD_CFG_CAPABILITY0_SLOTTYPE_BIT 0x3
#define WCONF_EMMC4SD_CFG_CAPABILITY0_SLOTTYPE_BITWIDTH 2
// EMMC4SD_CFG_CAPABILITY1 Register
#define WCONF_EMMC4SD_CFG_CAPABILITY1_OFS        0x00000008
// SDR50SUPPORT bitfiled (RW) Reset=1
#define WCONF_EMMC4SD_CFG_CAPABILITY1_SDR50SUPPORT_MASK 0x1
#define WCONF_EMMC4SD_CFG_CAPABILITY1_SDR50SUPPORT_SHIFT 0 
#define WCONF_EMMC4SD_CFG_CAPABILITY1_SDR50SUPPORT_BIT 0x1
#define WCONF_EMMC4SD_CFG_CAPABILITY1_SDR50SUPPORT_BITWIDTH 1
// SDR104SUPPORT bitfiled (RW) Reset=0
#define WCONF_EMMC4SD_CFG_CAPABILITY1_SDR104SUPPORT_MASK 0x2
#define WCONF_EMMC4SD_CFG_CAPABILITY1_SDR104SUPPORT_SHIFT 1 
#define WCONF_EMMC4SD_CFG_CAPABILITY1_SDR104SUPPORT_BIT 0x1
#define WCONF_EMMC4SD_CFG_CAPABILITY1_SDR104SUPPORT_BITWIDTH 1
// DDR50SUPPORT bitfiled (RW) Reset=1
#define WCONF_EMMC4SD_CFG_CAPABILITY1_DDR50SUPPORT_MASK 0x4
#define WCONF_EMMC4SD_CFG_CAPABILITY1_DDR50SUPPORT_SHIFT 2 
#define WCONF_EMMC4SD_CFG_CAPABILITY1_DDR50SUPPORT_BIT 0x1
#define WCONF_EMMC4SD_CFG_CAPABILITY1_DDR50SUPPORT_BITWIDTH 1
// reserved1 bitfiled (RO) Reset=0
#define WCONF_EMMC4SD_CFG_CAPABILITY1_RESERVED1_MASK 0x8
#define WCONF_EMMC4SD_CFG_CAPABILITY1_RESERVED1_SHIFT 3 
#define WCONF_EMMC4SD_CFG_CAPABILITY1_RESERVED1_BIT 0x1
#define WCONF_EMMC4SD_CFG_CAPABILITY1_RESERVED1_BITWIDTH 1
// ADRIVERSUPPORT bitfiled (RW) Reset=1
#define WCONF_EMMC4SD_CFG_CAPABILITY1_ADRIVERSUPPORT_MASK 0x10
#define WCONF_EMMC4SD_CFG_CAPABILITY1_ADRIVERSUPPORT_SHIFT 4 
#define WCONF_EMMC4SD_CFG_CAPABILITY1_ADRIVERSUPPORT_BIT 0x1
#define WCONF_EMMC4SD_CFG_CAPABILITY1_ADRIVERSUPPORT_BITWIDTH 1
// CDRIVERSUPPORT bitfiled (RW) Reset=1
#define WCONF_EMMC4SD_CFG_CAPABILITY1_CDRIVERSUPPORT_MASK 0x20
#define WCONF_EMMC4SD_CFG_CAPABILITY1_CDRIVERSUPPORT_SHIFT 5 
#define WCONF_EMMC4SD_CFG_CAPABILITY1_CDRIVERSUPPORT_BIT 0x1
#define WCONF_EMMC4SD_CFG_CAPABILITY1_CDRIVERSUPPORT_BITWIDTH 1
// DDRIVERSUPPORT bitfiled (RW) Reset=1
#define WCONF_EMMC4SD_CFG_CAPABILITY1_DDRIVERSUPPORT_MASK 0x40
#define WCONF_EMMC4SD_CFG_CAPABILITY1_DDRIVERSUPPORT_SHIFT 6 
#define WCONF_EMMC4SD_CFG_CAPABILITY1_DDRIVERSUPPORT_BIT 0x1
#define WCONF_EMMC4SD_CFG_CAPABILITY1_DDRIVERSUPPORT_BITWIDTH 1
// reserved2 bitfiled (RO) Reset=0
#define WCONF_EMMC4SD_CFG_CAPABILITY1_RESERVED2_MASK 0x80
#define WCONF_EMMC4SD_CFG_CAPABILITY1_RESERVED2_SHIFT 7 
#define WCONF_EMMC4SD_CFG_CAPABILITY1_RESERVED2_BIT 0x1
#define WCONF_EMMC4SD_CFG_CAPABILITY1_RESERVED2_BITWIDTH 1
// RETUNINGTIMERCNT bitfiled (RW) Reset=1
#define WCONF_EMMC4SD_CFG_CAPABILITY1_RETUNINGTIMERCNT_MASK 0xF00
#define WCONF_EMMC4SD_CFG_CAPABILITY1_RETUNINGTIMERCNT_SHIFT 8 
#define WCONF_EMMC4SD_CFG_CAPABILITY1_RETUNINGTIMERCNT_BIT 0xF
#define WCONF_EMMC4SD_CFG_CAPABILITY1_RETUNINGTIMERCNT_BITWIDTH 4
// reserved3 bitfiled (RO) Reset=0
#define WCONF_EMMC4SD_CFG_CAPABILITY1_RESERVED3_MASK 0x1000
#define WCONF_EMMC4SD_CFG_CAPABILITY1_RESERVED3_SHIFT 12 
#define WCONF_EMMC4SD_CFG_CAPABILITY1_RESERVED3_BIT 0x1
#define WCONF_EMMC4SD_CFG_CAPABILITY1_RESERVED3_BITWIDTH 1
// TUNINGFORSDR50 bitfiled (RW) Reset=0
#define WCONF_EMMC4SD_CFG_CAPABILITY1_TUNINGFORSDR50_MASK 0x2000
#define WCONF_EMMC4SD_CFG_CAPABILITY1_TUNINGFORSDR50_SHIFT 13 
#define WCONF_EMMC4SD_CFG_CAPABILITY1_TUNINGFORSDR50_BIT 0x1
#define WCONF_EMMC4SD_CFG_CAPABILITY1_TUNINGFORSDR50_BITWIDTH 1
// RETUNINGMODES bitfiled (RO) Reset=0
#define WCONF_EMMC4SD_CFG_CAPABILITY1_RETUNINGMODES_MASK 0xC000
#define WCONF_EMMC4SD_CFG_CAPABILITY1_RETUNINGMODES_SHIFT 14 
#define WCONF_EMMC4SD_CFG_CAPABILITY1_RETUNINGMODES_BIT 0x3
#define WCONF_EMMC4SD_CFG_CAPABILITY1_RETUNINGMODES_BITWIDTH 2
// CLKMLTPLY bitfiled (RO) Reset=0
#define WCONF_EMMC4SD_CFG_CAPABILITY1_CLKMLTPLY_MASK 0xFF0000
#define WCONF_EMMC4SD_CFG_CAPABILITY1_CLKMLTPLY_SHIFT 16 
#define WCONF_EMMC4SD_CFG_CAPABILITY1_CLKMLTPLY_BIT 0xFF
#define WCONF_EMMC4SD_CFG_CAPABILITY1_CLKMLTPLY_BITWIDTH 8
// SPISUPPORT bitfiled (RW) Reset=0
#define WCONF_EMMC4SD_CFG_CAPABILITY1_SPISUPPORT_MASK 0x1000000
#define WCONF_EMMC4SD_CFG_CAPABILITY1_SPISUPPORT_SHIFT 24 
#define WCONF_EMMC4SD_CFG_CAPABILITY1_SPISUPPORT_BIT 0x1
#define WCONF_EMMC4SD_CFG_CAPABILITY1_SPISUPPORT_BITWIDTH 1
// SPIBLKMODE bitfiled (RO) Reset=0
#define WCONF_EMMC4SD_CFG_CAPABILITY1_SPIBLKMODE_MASK 0x2000000
#define WCONF_EMMC4SD_CFG_CAPABILITY1_SPIBLKMODE_SHIFT 25 
#define WCONF_EMMC4SD_CFG_CAPABILITY1_SPIBLKMODE_BIT 0x1
#define WCONF_EMMC4SD_CFG_CAPABILITY1_SPIBLKMODE_BITWIDTH 1
// reserved4 bitfiled (RO) Reset=0
#define WCONF_EMMC4SD_CFG_CAPABILITY1_RESERVED4_MASK 0xFC000000
#define WCONF_EMMC4SD_CFG_CAPABILITY1_RESERVED4_SHIFT 26 
#define WCONF_EMMC4SD_CFG_CAPABILITY1_RESERVED4_BIT 0x3F
#define WCONF_EMMC4SD_CFG_CAPABILITY1_RESERVED4_BITWIDTH 6
// EMMC4SD_CFG_MAXCURNT Register
#define WCONF_EMMC4SD_CFG_MAXCURNT_OFS           0x00000010
// MAXCRNT3P3V bitfiled (RW) Reset=0
#define WCONF_EMMC4SD_CFG_MAXCURNT_MAXCRNT3P3V_MASK 0xFF
#define WCONF_EMMC4SD_CFG_MAXCURNT_MAXCRNT3P3V_SHIFT 0 
#define WCONF_EMMC4SD_CFG_MAXCURNT_MAXCRNT3P3V_BIT 0xFF
#define WCONF_EMMC4SD_CFG_MAXCURNT_MAXCRNT3P3V_BITWIDTH 8
// MAXCRNT3P0V bitfiled (RW) Reset=0
#define WCONF_EMMC4SD_CFG_MAXCURNT_MAXCRNT3P0V_MASK 0xFF00
#define WCONF_EMMC4SD_CFG_MAXCURNT_MAXCRNT3P0V_SHIFT 8 
#define WCONF_EMMC4SD_CFG_MAXCURNT_MAXCRNT3P0V_BIT 0xFF
#define WCONF_EMMC4SD_CFG_MAXCURNT_MAXCRNT3P0V_BITWIDTH 8
// MAXCRNT1P8V bitfiled (RW) Reset=0
#define WCONF_EMMC4SD_CFG_MAXCURNT_MAXCRNT1P8V_MASK 0xFF0000
#define WCONF_EMMC4SD_CFG_MAXCURNT_MAXCRNT1P8V_SHIFT 16 
#define WCONF_EMMC4SD_CFG_MAXCURNT_MAXCRNT1P8V_BIT 0xFF
#define WCONF_EMMC4SD_CFG_MAXCURNT_MAXCRNT1P8V_BITWIDTH 8
// reserved1 bitfiled (RO) Reset=0
#define WCONF_EMMC4SD_CFG_MAXCURNT_RESERVED1_MASK 0xFF000000
#define WCONF_EMMC4SD_CFG_MAXCURNT_RESERVED1_SHIFT 24 
#define WCONF_EMMC4SD_CFG_MAXCURNT_RESERVED1_BIT 0xFF
#define WCONF_EMMC4SD_CFG_MAXCURNT_RESERVED1_BITWIDTH 8
// EMMC4SD_CFG_PRESET0 Register
#define WCONF_EMMC4SD_CFG_PRESET0_OFS            0x00000020
// INITPRESETVAL bitfiled (RW) Reset=10000000
#define WCONF_EMMC4SD_CFG_PRESET0_INITPRESETVAL_MASK 0x1FFF
#define WCONF_EMMC4SD_CFG_PRESET0_INITPRESETVAL_SHIFT 0 
#define WCONF_EMMC4SD_CFG_PRESET0_INITPRESETVAL_BIT 0x1FFF
#define WCONF_EMMC4SD_CFG_PRESET0_INITPRESETVAL_BITWIDTH 13
// reserved1 bitfiled (RO) Reset=0
#define WCONF_EMMC4SD_CFG_PRESET0_RESERVED1_MASK 0xE000
#define WCONF_EMMC4SD_CFG_PRESET0_RESERVED1_SHIFT 13 
#define WCONF_EMMC4SD_CFG_PRESET0_RESERVED1_BIT  0x7
#define WCONF_EMMC4SD_CFG_PRESET0_RESERVED1_BITWIDTH 3
// DSPPRESETVAL bitfiled (RW) Reset=10
#define WCONF_EMMC4SD_CFG_PRESET0_DSPPRESETVAL_MASK 0x1FFF0000
#define WCONF_EMMC4SD_CFG_PRESET0_DSPPRESETVAL_SHIFT 16 
#define WCONF_EMMC4SD_CFG_PRESET0_DSPPRESETVAL_BIT 0x1FFF
#define WCONF_EMMC4SD_CFG_PRESET0_DSPPRESETVAL_BITWIDTH 13
// reserved2 bitfiled (RO) Reset=0
#define WCONF_EMMC4SD_CFG_PRESET0_RESERVED2_MASK 0xE0000000
#define WCONF_EMMC4SD_CFG_PRESET0_RESERVED2_SHIFT 29 
#define WCONF_EMMC4SD_CFG_PRESET0_RESERVED2_BIT  0x7
#define WCONF_EMMC4SD_CFG_PRESET0_RESERVED2_BITWIDTH 3
// EMMC4SD_CFG_PRESET1 Register
#define WCONF_EMMC4SD_CFG_PRESET1_OFS            0x00000028
// HSPPRESETVAL bitfiled (RW) Reset=1
#define WCONF_EMMC4SD_CFG_PRESET1_HSPPRESETVAL_MASK 0x1FFF
#define WCONF_EMMC4SD_CFG_PRESET1_HSPPRESETVAL_SHIFT 0 
#define WCONF_EMMC4SD_CFG_PRESET1_HSPPRESETVAL_BIT 0x1FFF
#define WCONF_EMMC4SD_CFG_PRESET1_HSPPRESETVAL_BITWIDTH 13
// reserved1 bitfiled (RO) Reset=0
#define WCONF_EMMC4SD_CFG_PRESET1_RESERVED1_MASK 0xE000
#define WCONF_EMMC4SD_CFG_PRESET1_RESERVED1_SHIFT 13 
#define WCONF_EMMC4SD_CFG_PRESET1_RESERVED1_BIT  0x7
#define WCONF_EMMC4SD_CFG_PRESET1_RESERVED1_BITWIDTH 3
// SDR12PRESETVAL bitfiled (RW) Reset=10
#define WCONF_EMMC4SD_CFG_PRESET1_SDR12PRESETVAL_MASK 0x1FFF0000
#define WCONF_EMMC4SD_CFG_PRESET1_SDR12PRESETVAL_SHIFT 16 
#define WCONF_EMMC4SD_CFG_PRESET1_SDR12PRESETVAL_BIT 0x1FFF
#define WCONF_EMMC4SD_CFG_PRESET1_SDR12PRESETVAL_BITWIDTH 13
// reserved2 bitfiled (RO) Reset=0
#define WCONF_EMMC4SD_CFG_PRESET1_RESERVED2_MASK 0xE0000000
#define WCONF_EMMC4SD_CFG_PRESET1_RESERVED2_SHIFT 29 
#define WCONF_EMMC4SD_CFG_PRESET1_RESERVED2_BIT  0x7
#define WCONF_EMMC4SD_CFG_PRESET1_RESERVED2_BITWIDTH 3
// EMMC4SD_CFG_PRESET2 Register
#define WCONF_EMMC4SD_CFG_PRESET2_OFS            0x00000030
// SDR25PRESETVAL bitfiled (RW) Reset=1
#define WCONF_EMMC4SD_CFG_PRESET2_SDR25PRESETVAL_MASK 0x1FFF
#define WCONF_EMMC4SD_CFG_PRESET2_SDR25PRESETVAL_SHIFT 0 
#define WCONF_EMMC4SD_CFG_PRESET2_SDR25PRESETVAL_BIT 0x1FFF
#define WCONF_EMMC4SD_CFG_PRESET2_SDR25PRESETVAL_BITWIDTH 13
// reserved1 bitfiled (RO) Reset=0
#define WCONF_EMMC4SD_CFG_PRESET2_RESERVED1_MASK 0xE000
#define WCONF_EMMC4SD_CFG_PRESET2_RESERVED1_SHIFT 13 
#define WCONF_EMMC4SD_CFG_PRESET2_RESERVED1_BIT  0x7
#define WCONF_EMMC4SD_CFG_PRESET2_RESERVED1_BITWIDTH 3
// SDR50PRESETVAL bitfiled (RW) Reset=0
#define WCONF_EMMC4SD_CFG_PRESET2_SDR50PRESETVAL_MASK 0x1FFF0000
#define WCONF_EMMC4SD_CFG_PRESET2_SDR50PRESETVAL_SHIFT 16 
#define WCONF_EMMC4SD_CFG_PRESET2_SDR50PRESETVAL_BIT 0x1FFF
#define WCONF_EMMC4SD_CFG_PRESET2_SDR50PRESETVAL_BITWIDTH 13
// reserved2 bitfiled (RO) Reset=0
#define WCONF_EMMC4SD_CFG_PRESET2_RESERVED2_MASK 0xE0000000
#define WCONF_EMMC4SD_CFG_PRESET2_RESERVED2_SHIFT 29 
#define WCONF_EMMC4SD_CFG_PRESET2_RESERVED2_BIT  0x7
#define WCONF_EMMC4SD_CFG_PRESET2_RESERVED2_BITWIDTH 3
// EMMC4SD_CFG_PRESET3 Register
#define WCONF_EMMC4SD_CFG_PRESET3_OFS            0x00000038
// SDR104PRESETVAL bitfiled (RW) Reset=0
#define WCONF_EMMC4SD_CFG_PRESET3_SDR104PRESETVAL_MASK 0x1FFF
#define WCONF_EMMC4SD_CFG_PRESET3_SDR104PRESETVAL_SHIFT 0 
#define WCONF_EMMC4SD_CFG_PRESET3_SDR104PRESETVAL_BIT 0x1FFF
#define WCONF_EMMC4SD_CFG_PRESET3_SDR104PRESETVAL_BITWIDTH 13
// reserved1 bitfiled (RO) Reset=0
#define WCONF_EMMC4SD_CFG_PRESET3_RESERVED1_MASK 0xE000
#define WCONF_EMMC4SD_CFG_PRESET3_RESERVED1_SHIFT 13 
#define WCONF_EMMC4SD_CFG_PRESET3_RESERVED1_BIT  0x7
#define WCONF_EMMC4SD_CFG_PRESET3_RESERVED1_BITWIDTH 3
// DDR50PRESETVAL bitfiled (RW) Reset=1
#define WCONF_EMMC4SD_CFG_PRESET3_DDR50PRESETVAL_MASK 0x1FFF0000
#define WCONF_EMMC4SD_CFG_PRESET3_DDR50PRESETVAL_SHIFT 16 
#define WCONF_EMMC4SD_CFG_PRESET3_DDR50PRESETVAL_BIT 0x1FFF
#define WCONF_EMMC4SD_CFG_PRESET3_DDR50PRESETVAL_BITWIDTH 13
// reserved2 bitfiled (RO) Reset=0
#define WCONF_EMMC4SD_CFG_PRESET3_RESERVED2_MASK 0xE0000000
#define WCONF_EMMC4SD_CFG_PRESET3_RESERVED2_SHIFT 29 
#define WCONF_EMMC4SD_CFG_PRESET3_RESERVED2_BIT  0x7
#define WCONF_EMMC4SD_CFG_PRESET3_RESERVED2_BITWIDTH 3
// EMMC4SD_CFG_WKUP Register
#define WCONF_EMMC4SD_CFG_WKUP_OFS               0x00000040
// ASYNCWKUPEN bitfiled (RW) Reset=1
#define WCONF_EMMC4SD_CFG_WKUP_ASYNCWKUPEN_MASK  0x1
#define WCONF_EMMC4SD_CFG_WKUP_ASYNCWKUPEN_SHIFT 0 
#define WCONF_EMMC4SD_CFG_WKUP_ASYNCWKUPEN_BIT   0x1
#define WCONF_EMMC4SD_CFG_WKUP_ASYNCWKUPEN_BITWIDTH 1
// reserved1 bitfiled (RO) Reset=0
#define WCONF_EMMC4SD_CFG_WKUP_RESERVED1_MASK    0xFFFFFFFE
#define WCONF_EMMC4SD_CFG_WKUP_RESERVED1_SHIFT   1 
#define WCONF_EMMC4SD_CFG_WKUP_RESERVED1_BIT     0x7FFFFFFF
#define WCONF_EMMC4SD_CFG_WKUP_RESERVED1_BITWIDTH 31
// EMMC4SD_CTRL_DLYCHG Register
#define WCONF_EMMC4SD_CTRL_DLYCHG_OFS            0x00000050
// TAPCHGWIN bitfiled (RW) Reset=0
#define WCONF_EMMC4SD_CTRL_DLYCHG_TAPCHGWIN_MASK 0x1
#define WCONF_EMMC4SD_CTRL_DLYCHG_TAPCHGWIN_SHIFT 0 
#define WCONF_EMMC4SD_CTRL_DLYCHG_TAPCHGWIN_BIT  0x1
#define WCONF_EMMC4SD_CTRL_DLYCHG_TAPCHGWIN_BITWIDTH 1
// reserved1 bitfiled (RO) Reset=0
#define WCONF_EMMC4SD_CTRL_DLYCHG_RESERVED1_MASK 0xFFFE
#define WCONF_EMMC4SD_CTRL_DLYCHG_RESERVED1_SHIFT 1 
#define WCONF_EMMC4SD_CTRL_DLYCHG_RESERVED1_BIT  0x7FFF
#define WCONF_EMMC4SD_CTRL_DLYCHG_RESERVED1_BITWIDTH 15
// TAPCHGWINSTS bitfiled (RO) Reset=0
#define WCONF_EMMC4SD_CTRL_DLYCHG_TAPCHGWINSTS_MASK 0x10000
#define WCONF_EMMC4SD_CTRL_DLYCHG_TAPCHGWINSTS_SHIFT 16 
#define WCONF_EMMC4SD_CTRL_DLYCHG_TAPCHGWINSTS_BIT 0x1
#define WCONF_EMMC4SD_CTRL_DLYCHG_TAPCHGWINSTS_BITWIDTH 1
// reserved2 bitfiled (RO) Reset=0
#define WCONF_EMMC4SD_CTRL_DLYCHG_RESERVED2_MASK 0xFFFE0000
#define WCONF_EMMC4SD_CTRL_DLYCHG_RESERVED2_SHIFT 17 
#define WCONF_EMMC4SD_CTRL_DLYCHG_RESERVED2_BIT  0x7FFF
#define WCONF_EMMC4SD_CTRL_DLYCHG_RESERVED2_BITWIDTH 15
// EMMC4SD_CTRL_INDLY Register
#define WCONF_EMMC4SD_CTRL_INDLY_OFS             0x00000058
// ITAPDLYEN bitfiled (RW) Reset=0
#define WCONF_EMMC4SD_CTRL_INDLY_ITAPDLYEN_MASK  0x1
#define WCONF_EMMC4SD_CTRL_INDLY_ITAPDLYEN_SHIFT 0 
#define WCONF_EMMC4SD_CTRL_INDLY_ITAPDLYEN_BIT   0x1
#define WCONF_EMMC4SD_CTRL_INDLY_ITAPDLYEN_BITWIDTH 1
// reserved1 bitfiled (RO) Reset=0
#define WCONF_EMMC4SD_CTRL_INDLY_RESERVED1_MASK  0xFE
#define WCONF_EMMC4SD_CTRL_INDLY_RESERVED1_SHIFT 1 
#define WCONF_EMMC4SD_CTRL_INDLY_RESERVED1_BIT   0x7F
#define WCONF_EMMC4SD_CTRL_INDLY_RESERVED1_BITWIDTH 7
// ITAPDLYSEL bitfiled (RW) Reset=0
#define WCONF_EMMC4SD_CTRL_INDLY_ITAPDLYSEL_MASK 0x1F00
#define WCONF_EMMC4SD_CTRL_INDLY_ITAPDLYSEL_SHIFT 8 
#define WCONF_EMMC4SD_CTRL_INDLY_ITAPDLYSEL_BIT  0x1F
#define WCONF_EMMC4SD_CTRL_INDLY_ITAPDLYSEL_BITWIDTH 5
// reserved2 bitfiled (RO) Reset=0
#define WCONF_EMMC4SD_CTRL_INDLY_RESERVED2_MASK  0xE000
#define WCONF_EMMC4SD_CTRL_INDLY_RESERVED2_SHIFT 13 
#define WCONF_EMMC4SD_CTRL_INDLY_RESERVED2_BIT   0x7
#define WCONF_EMMC4SD_CTRL_INDLY_RESERVED2_BITWIDTH 3
// ITAPDLYENSTS bitfiled (RO) Reset=0
#define WCONF_EMMC4SD_CTRL_INDLY_ITAPDLYENSTS_MASK 0x10000
#define WCONF_EMMC4SD_CTRL_INDLY_ITAPDLYENSTS_SHIFT 16 
#define WCONF_EMMC4SD_CTRL_INDLY_ITAPDLYENSTS_BIT 0x1
#define WCONF_EMMC4SD_CTRL_INDLY_ITAPDLYENSTS_BITWIDTH 1
// reserved3 bitfiled (RO) Reset=0
#define WCONF_EMMC4SD_CTRL_INDLY_RESERVED3_MASK  0xFE0000
#define WCONF_EMMC4SD_CTRL_INDLY_RESERVED3_SHIFT 17 
#define WCONF_EMMC4SD_CTRL_INDLY_RESERVED3_BIT   0x7F
#define WCONF_EMMC4SD_CTRL_INDLY_RESERVED3_BITWIDTH 7
// ITAPDLYSELSTS bitfiled (RO) Reset=0
#define WCONF_EMMC4SD_CTRL_INDLY_ITAPDLYSELSTS_MASK 0x1F000000
#define WCONF_EMMC4SD_CTRL_INDLY_ITAPDLYSELSTS_SHIFT 24 
#define WCONF_EMMC4SD_CTRL_INDLY_ITAPDLYSELSTS_BIT 0x1F
#define WCONF_EMMC4SD_CTRL_INDLY_ITAPDLYSELSTS_BITWIDTH 5
// reserved4 bitfiled (RO) Reset=0
#define WCONF_EMMC4SD_CTRL_INDLY_RESERVED4_MASK  0xE0000000
#define WCONF_EMMC4SD_CTRL_INDLY_RESERVED4_SHIFT 29 
#define WCONF_EMMC4SD_CTRL_INDLY_RESERVED4_BIT   0x7
#define WCONF_EMMC4SD_CTRL_INDLY_RESERVED4_BITWIDTH 3
// EMMC4SD_CTRL_OUTDLY Register
#define WCONF_EMMC4SD_CTRL_OUTDLY_OFS            0x00000060
// OTAPDLYEN bitfiled (RW) Reset=0
#define WCONF_EMMC4SD_CTRL_OUTDLY_OTAPDLYEN_MASK 0x1
#define WCONF_EMMC4SD_CTRL_OUTDLY_OTAPDLYEN_SHIFT 0 
#define WCONF_EMMC4SD_CTRL_OUTDLY_OTAPDLYEN_BIT  0x1
#define WCONF_EMMC4SD_CTRL_OUTDLY_OTAPDLYEN_BITWIDTH 1
// reserved1 bitfiled (RO) Reset=0
#define WCONF_EMMC4SD_CTRL_OUTDLY_RESERVED1_MASK 0xFE
#define WCONF_EMMC4SD_CTRL_OUTDLY_RESERVED1_SHIFT 1 
#define WCONF_EMMC4SD_CTRL_OUTDLY_RESERVED1_BIT  0x7F
#define WCONF_EMMC4SD_CTRL_OUTDLY_RESERVED1_BITWIDTH 7
// OTAPDLYSEL bitfiled (RW) Reset=0
#define WCONF_EMMC4SD_CTRL_OUTDLY_OTAPDLYSEL_MASK 0xF00
#define WCONF_EMMC4SD_CTRL_OUTDLY_OTAPDLYSEL_SHIFT 8 
#define WCONF_EMMC4SD_CTRL_OUTDLY_OTAPDLYSEL_BIT 0xF
#define WCONF_EMMC4SD_CTRL_OUTDLY_OTAPDLYSEL_BITWIDTH 4
// reserved2 bitfiled (RO) Reset=0
#define WCONF_EMMC4SD_CTRL_OUTDLY_RESERVED2_MASK 0xF000
#define WCONF_EMMC4SD_CTRL_OUTDLY_RESERVED2_SHIFT 12 
#define WCONF_EMMC4SD_CTRL_OUTDLY_RESERVED2_BIT  0xF
#define WCONF_EMMC4SD_CTRL_OUTDLY_RESERVED2_BITWIDTH 4
// OTAPDLYENSTS bitfiled (RO) Reset=0
#define WCONF_EMMC4SD_CTRL_OUTDLY_OTAPDLYENSTS_MASK 0x10000
#define WCONF_EMMC4SD_CTRL_OUTDLY_OTAPDLYENSTS_SHIFT 16 
#define WCONF_EMMC4SD_CTRL_OUTDLY_OTAPDLYENSTS_BIT 0x1
#define WCONF_EMMC4SD_CTRL_OUTDLY_OTAPDLYENSTS_BITWIDTH 1
// reserved3 bitfiled (RO) Reset=0
#define WCONF_EMMC4SD_CTRL_OUTDLY_RESERVED3_MASK 0xFE0000
#define WCONF_EMMC4SD_CTRL_OUTDLY_RESERVED3_SHIFT 17 
#define WCONF_EMMC4SD_CTRL_OUTDLY_RESERVED3_BIT  0x7F
#define WCONF_EMMC4SD_CTRL_OUTDLY_RESERVED3_BITWIDTH 7
// OTAPDLYSELSTS bitfiled (RO) Reset=0
#define WCONF_EMMC4SD_CTRL_OUTDLY_OTAPDLYSELSTS_MASK 0xF000000
#define WCONF_EMMC4SD_CTRL_OUTDLY_OTAPDLYSELSTS_SHIFT 24 
#define WCONF_EMMC4SD_CTRL_OUTDLY_OTAPDLYSELSTS_BIT 0xF
#define WCONF_EMMC4SD_CTRL_OUTDLY_OTAPDLYSELSTS_BITWIDTH 4
// reserved4 bitfiled (RO) Reset=0
#define WCONF_EMMC4SD_CTRL_OUTDLY_RESERVED4_MASK 0xF0000000
#define WCONF_EMMC4SD_CTRL_OUTDLY_RESERVED4_SHIFT 28 
#define WCONF_EMMC4SD_CTRL_OUTDLY_RESERVED4_BIT  0xF
#define WCONF_EMMC4SD_CTRL_OUTDLY_RESERVED4_BITWIDTH 4
// EMMC4SD_CTRL_DLL0 Register
#define WCONF_EMMC4SD_CTRL_DLL0_OFS              0x00000068
// DLLENABLE bitfiled (RW) Reset=0
#define WCONF_EMMC4SD_CTRL_DLL0_DLLENABLE_MASK   0x1
#define WCONF_EMMC4SD_CTRL_DLL0_DLLENABLE_SHIFT  0 
#define WCONF_EMMC4SD_CTRL_DLL0_DLLENABLE_BIT    0x1
#define WCONF_EMMC4SD_CTRL_DLL0_DLLENABLE_BITWIDTH 1
// reserved1 bitfiled (RO) Reset=0
#define WCONF_EMMC4SD_CTRL_DLL0_RESERVED1_MASK   0xFFFE
#define WCONF_EMMC4SD_CTRL_DLL0_RESERVED1_SHIFT  1 
#define WCONF_EMMC4SD_CTRL_DLL0_RESERVED1_BIT    0x7FFF
#define WCONF_EMMC4SD_CTRL_DLL0_RESERVED1_BITWIDTH 15
// DLLREADY bitfiled (RO) Reset=0
#define WCONF_EMMC4SD_CTRL_DLL0_DLLREADY_MASK    0x10000
#define WCONF_EMMC4SD_CTRL_DLL0_DLLREADY_SHIFT   16 
#define WCONF_EMMC4SD_CTRL_DLL0_DLLREADY_BIT     0x1
#define WCONF_EMMC4SD_CTRL_DLL0_DLLREADY_BITWIDTH 1
// reserved2 bitfiled (RO) Reset=0
#define WCONF_EMMC4SD_CTRL_DLL0_RESERVED2_MASK   0xFFFE0000
#define WCONF_EMMC4SD_CTRL_DLL0_RESERVED2_SHIFT  17 
#define WCONF_EMMC4SD_CTRL_DLL0_RESERVED2_BIT    0x7FFF
#define WCONF_EMMC4SD_CTRL_DLL0_RESERVED2_BITWIDTH 15
// EMMC4SD_CTRL_DLL1 Register
#define WCONF_EMMC4SD_CTRL_DLL1_OFS              0x00000070
// DLLCLKSEL bitfiled (RW) Reset=0
#define WCONF_EMMC4SD_CTRL_DLL1_DLLCLKSEL_MASK   0x1
#define WCONF_EMMC4SD_CTRL_DLL1_DLLCLKSEL_SHIFT  0 
#define WCONF_EMMC4SD_CTRL_DLL1_DLLCLKSEL_BIT    0x1
#define WCONF_EMMC4SD_CTRL_DLL1_DLLCLKSEL_BITWIDTH 1
// reserved1 bitfiled (RO) Reset=0
#define WCONF_EMMC4SD_CTRL_DLL1_RESERVED1_MASK   0xFFFE
#define WCONF_EMMC4SD_CTRL_DLL1_RESERVED1_SHIFT  1 
#define WCONF_EMMC4SD_CTRL_DLL1_RESERVED1_BIT    0x7FFF
#define WCONF_EMMC4SD_CTRL_DLL1_RESERVED1_BITWIDTH 15
// DLLCLKSELSTS bitfiled (RO) Reset=0
#define WCONF_EMMC4SD_CTRL_DLL1_DLLCLKSELSTS_MASK 0x10000
#define WCONF_EMMC4SD_CTRL_DLL1_DLLCLKSELSTS_SHIFT 16 
#define WCONF_EMMC4SD_CTRL_DLL1_DLLCLKSELSTS_BIT 0x1
#define WCONF_EMMC4SD_CTRL_DLL1_DLLCLKSELSTS_BITWIDTH 1
// reserved2 bitfiled (RO) Reset=0
#define WCONF_EMMC4SD_CTRL_DLL1_RESERVED2_MASK   0xFFFE0000
#define WCONF_EMMC4SD_CTRL_DLL1_RESERVED2_SHIFT  17 
#define WCONF_EMMC4SD_CTRL_DLL1_RESERVED2_BIT    0x7FFF
#define WCONF_EMMC4SD_CTRL_DLL1_RESERVED2_BITWIDTH 15
// EMMC8SD_CFG_CAPABILITY0 Register
#define WCONF_EMMC8SD_CFG_CAPABILITY0_OFS        0x00000100
// TIMEOUTCLKFREQ bitfiled (RW) Reset=1
#define WCONF_EMMC8SD_CFG_CAPABILITY0_TIMEOUTCLKFREQ_MASK 0x3F
#define WCONF_EMMC8SD_CFG_CAPABILITY0_TIMEOUTCLKFREQ_SHIFT 0 
#define WCONF_EMMC8SD_CFG_CAPABILITY0_TIMEOUTCLKFREQ_BIT 0x3F
#define WCONF_EMMC8SD_CFG_CAPABILITY0_TIMEOUTCLKFREQ_BITWIDTH 6
// reserved1 bitfiled (RO) Reset=0
#define WCONF_EMMC8SD_CFG_CAPABILITY0_RESERVED1_MASK 0x40
#define WCONF_EMMC8SD_CFG_CAPABILITY0_RESERVED1_SHIFT 6 
#define WCONF_EMMC8SD_CFG_CAPABILITY0_RESERVED1_BIT 0x1
#define WCONF_EMMC8SD_CFG_CAPABILITY0_RESERVED1_BITWIDTH 1
// TIMEOUTCLKUNIT bitfiled (RW) Reset=1
#define WCONF_EMMC8SD_CFG_CAPABILITY0_TIMEOUTCLKUNIT_MASK 0x80
#define WCONF_EMMC8SD_CFG_CAPABILITY0_TIMEOUTCLKUNIT_SHIFT 7 
#define WCONF_EMMC8SD_CFG_CAPABILITY0_TIMEOUTCLKUNIT_BIT 0x1
#define WCONF_EMMC8SD_CFG_CAPABILITY0_TIMEOUTCLKUNIT_BITWIDTH 1
// BASECLKFREQ bitfiled (RW) Reset=1100100
#define WCONF_EMMC8SD_CFG_CAPABILITY0_BASECLKFREQ_MASK 0xFF00
#define WCONF_EMMC8SD_CFG_CAPABILITY0_BASECLKFREQ_SHIFT 8 
#define WCONF_EMMC8SD_CFG_CAPABILITY0_BASECLKFREQ_BIT 0xFF
#define WCONF_EMMC8SD_CFG_CAPABILITY0_BASECLKFREQ_BITWIDTH 8
// MAXBLKLENGTH bitfiled (RW) Reset=0
#define WCONF_EMMC8SD_CFG_CAPABILITY0_MAXBLKLENGTH_MASK 0x30000
#define WCONF_EMMC8SD_CFG_CAPABILITY0_MAXBLKLENGTH_SHIFT 16 
#define WCONF_EMMC8SD_CFG_CAPABILITY0_MAXBLKLENGTH_BIT 0x3
#define WCONF_EMMC8SD_CFG_CAPABILITY0_MAXBLKLENGTH_BITWIDTH 2
// SUPPORT8BIT bitfiled (RW) Reset=0
#define WCONF_EMMC8SD_CFG_CAPABILITY0_SUPPORT8BIT_MASK 0x40000
#define WCONF_EMMC8SD_CFG_CAPABILITY0_SUPPORT8BIT_SHIFT 18 
#define WCONF_EMMC8SD_CFG_CAPABILITY0_SUPPORT8BIT_BIT 0x1
#define WCONF_EMMC8SD_CFG_CAPABILITY0_SUPPORT8BIT_BITWIDTH 1
// ADMA2SUPPORT bitfiled (RW) Reset=1
#define WCONF_EMMC8SD_CFG_CAPABILITY0_ADMA2SUPPORT_MASK 0x80000
#define WCONF_EMMC8SD_CFG_CAPABILITY0_ADMA2SUPPORT_SHIFT 19 
#define WCONF_EMMC8SD_CFG_CAPABILITY0_ADMA2SUPPORT_BIT 0x1
#define WCONF_EMMC8SD_CFG_CAPABILITY0_ADMA2SUPPORT_BITWIDTH 1
// reserved2 bitfiled (RO) Reset=0
#define WCONF_EMMC8SD_CFG_CAPABILITY0_RESERVED2_MASK 0x100000
#define WCONF_EMMC8SD_CFG_CAPABILITY0_RESERVED2_SHIFT 20 
#define WCONF_EMMC8SD_CFG_CAPABILITY0_RESERVED2_BIT 0x1
#define WCONF_EMMC8SD_CFG_CAPABILITY0_RESERVED2_BITWIDTH 1
// HIGHSPEEDSUPPORT bitfiled (RW) Reset=1
#define WCONF_EMMC8SD_CFG_CAPABILITY0_HIGHSPEEDSUPPORT_MASK 0x200000
#define WCONF_EMMC8SD_CFG_CAPABILITY0_HIGHSPEEDSUPPORT_SHIFT 21 
#define WCONF_EMMC8SD_CFG_CAPABILITY0_HIGHSPEEDSUPPORT_BIT 0x1
#define WCONF_EMMC8SD_CFG_CAPABILITY0_HIGHSPEEDSUPPORT_BITWIDTH 1
// SDMASUPPORT bitfiled (RW) Reset=1
#define WCONF_EMMC8SD_CFG_CAPABILITY0_SDMASUPPORT_MASK 0x400000
#define WCONF_EMMC8SD_CFG_CAPABILITY0_SDMASUPPORT_SHIFT 22 
#define WCONF_EMMC8SD_CFG_CAPABILITY0_SDMASUPPORT_BIT 0x1
#define WCONF_EMMC8SD_CFG_CAPABILITY0_SDMASUPPORT_BITWIDTH 1
// SUSPRESSUPPORT bitfiled (RW) Reset=1
#define WCONF_EMMC8SD_CFG_CAPABILITY0_SUSPRESSUPPORT_MASK 0x800000
#define WCONF_EMMC8SD_CFG_CAPABILITY0_SUSPRESSUPPORT_SHIFT 23 
#define WCONF_EMMC8SD_CFG_CAPABILITY0_SUSPRESSUPPORT_BIT 0x1
#define WCONF_EMMC8SD_CFG_CAPABILITY0_SUSPRESSUPPORT_BITWIDTH 1
// SUPPORT3P3VOLT bitfiled (RW) Reset=1
#define WCONF_EMMC8SD_CFG_CAPABILITY0_SUPPORT3P3VOLT_MASK 0x1000000
#define WCONF_EMMC8SD_CFG_CAPABILITY0_SUPPORT3P3VOLT_SHIFT 24 
#define WCONF_EMMC8SD_CFG_CAPABILITY0_SUPPORT3P3VOLT_BIT 0x1
#define WCONF_EMMC8SD_CFG_CAPABILITY0_SUPPORT3P3VOLT_BITWIDTH 1
// SUPPORT3P0VOLT bitfiled (RW) Reset=0
#define WCONF_EMMC8SD_CFG_CAPABILITY0_SUPPORT3P0VOLT_MASK 0x2000000
#define WCONF_EMMC8SD_CFG_CAPABILITY0_SUPPORT3P0VOLT_SHIFT 25 
#define WCONF_EMMC8SD_CFG_CAPABILITY0_SUPPORT3P0VOLT_BIT 0x1
#define WCONF_EMMC8SD_CFG_CAPABILITY0_SUPPORT3P0VOLT_BITWIDTH 1
// SUPPORT1P8VOLT bitfiled (RW) Reset=1
#define WCONF_EMMC8SD_CFG_CAPABILITY0_SUPPORT1P8VOLT_MASK 0x4000000
#define WCONF_EMMC8SD_CFG_CAPABILITY0_SUPPORT1P8VOLT_SHIFT 26 
#define WCONF_EMMC8SD_CFG_CAPABILITY0_SUPPORT1P8VOLT_BIT 0x1
#define WCONF_EMMC8SD_CFG_CAPABILITY0_SUPPORT1P8VOLT_BITWIDTH 1
// reserved3 bitfiled (RO) Reset=0
#define WCONF_EMMC8SD_CFG_CAPABILITY0_RESERVED3_MASK 0x8000000
#define WCONF_EMMC8SD_CFG_CAPABILITY0_RESERVED3_SHIFT 27 
#define WCONF_EMMC8SD_CFG_CAPABILITY0_RESERVED3_BIT 0x1
#define WCONF_EMMC8SD_CFG_CAPABILITY0_RESERVED3_BITWIDTH 1
// SUPPORT64BIT bitfiled (RO) Reset=0
#define WCONF_EMMC8SD_CFG_CAPABILITY0_SUPPORT64BIT_MASK 0x10000000
#define WCONF_EMMC8SD_CFG_CAPABILITY0_SUPPORT64BIT_SHIFT 28 
#define WCONF_EMMC8SD_CFG_CAPABILITY0_SUPPORT64BIT_BIT 0x1
#define WCONF_EMMC8SD_CFG_CAPABILITY0_SUPPORT64BIT_BITWIDTH 1
// ASYNCINTRSUPPORT bitfiled (RW) Reset=1
#define WCONF_EMMC8SD_CFG_CAPABILITY0_ASYNCINTRSUPPORT_MASK 0x20000000
#define WCONF_EMMC8SD_CFG_CAPABILITY0_ASYNCINTRSUPPORT_SHIFT 29 
#define WCONF_EMMC8SD_CFG_CAPABILITY0_ASYNCINTRSUPPORT_BIT 0x1
#define WCONF_EMMC8SD_CFG_CAPABILITY0_ASYNCINTRSUPPORT_BITWIDTH 1
// SLOTTYPE bitfiled (RW) Reset=1
#define WCONF_EMMC8SD_CFG_CAPABILITY0_SLOTTYPE_MASK 0xC0000000
#define WCONF_EMMC8SD_CFG_CAPABILITY0_SLOTTYPE_SHIFT 30 
#define WCONF_EMMC8SD_CFG_CAPABILITY0_SLOTTYPE_BIT 0x3
#define WCONF_EMMC8SD_CFG_CAPABILITY0_SLOTTYPE_BITWIDTH 2
// EMMC8SD_CFG_CAPABILITY1 Register
#define WCONF_EMMC8SD_CFG_CAPABILITY1_OFS        0x00000108
// SDR50SUPPORT bitfiled (RW) Reset=1
#define WCONF_EMMC8SD_CFG_CAPABILITY1_SDR50SUPPORT_MASK 0x1
#define WCONF_EMMC8SD_CFG_CAPABILITY1_SDR50SUPPORT_SHIFT 0 
#define WCONF_EMMC8SD_CFG_CAPABILITY1_SDR50SUPPORT_BIT 0x1
#define WCONF_EMMC8SD_CFG_CAPABILITY1_SDR50SUPPORT_BITWIDTH 1
// SDR104SUPPORT bitfiled (RW) Reset=0
#define WCONF_EMMC8SD_CFG_CAPABILITY1_SDR104SUPPORT_MASK 0x2
#define WCONF_EMMC8SD_CFG_CAPABILITY1_SDR104SUPPORT_SHIFT 1 
#define WCONF_EMMC8SD_CFG_CAPABILITY1_SDR104SUPPORT_BIT 0x1
#define WCONF_EMMC8SD_CFG_CAPABILITY1_SDR104SUPPORT_BITWIDTH 1
// DDR50SUPPORT bitfiled (RW) Reset=1
#define WCONF_EMMC8SD_CFG_CAPABILITY1_DDR50SUPPORT_MASK 0x4
#define WCONF_EMMC8SD_CFG_CAPABILITY1_DDR50SUPPORT_SHIFT 2 
#define WCONF_EMMC8SD_CFG_CAPABILITY1_DDR50SUPPORT_BIT 0x1
#define WCONF_EMMC8SD_CFG_CAPABILITY1_DDR50SUPPORT_BITWIDTH 1
// reserved1 bitfiled (RO) Reset=0
#define WCONF_EMMC8SD_CFG_CAPABILITY1_RESERVED1_MASK 0x8
#define WCONF_EMMC8SD_CFG_CAPABILITY1_RESERVED1_SHIFT 3 
#define WCONF_EMMC8SD_CFG_CAPABILITY1_RESERVED1_BIT 0x1
#define WCONF_EMMC8SD_CFG_CAPABILITY1_RESERVED1_BITWIDTH 1
// ADRIVERSUPPORT bitfiled (RW) Reset=1
#define WCONF_EMMC8SD_CFG_CAPABILITY1_ADRIVERSUPPORT_MASK 0x10
#define WCONF_EMMC8SD_CFG_CAPABILITY1_ADRIVERSUPPORT_SHIFT 4 
#define WCONF_EMMC8SD_CFG_CAPABILITY1_ADRIVERSUPPORT_BIT 0x1
#define WCONF_EMMC8SD_CFG_CAPABILITY1_ADRIVERSUPPORT_BITWIDTH 1
// CDRIVERSUPPORT bitfiled (RW) Reset=1
#define WCONF_EMMC8SD_CFG_CAPABILITY1_CDRIVERSUPPORT_MASK 0x20
#define WCONF_EMMC8SD_CFG_CAPABILITY1_CDRIVERSUPPORT_SHIFT 5 
#define WCONF_EMMC8SD_CFG_CAPABILITY1_CDRIVERSUPPORT_BIT 0x1
#define WCONF_EMMC8SD_CFG_CAPABILITY1_CDRIVERSUPPORT_BITWIDTH 1
// DDRIVERSUPPORT bitfiled (RW) Reset=1
#define WCONF_EMMC8SD_CFG_CAPABILITY1_DDRIVERSUPPORT_MASK 0x40
#define WCONF_EMMC8SD_CFG_CAPABILITY1_DDRIVERSUPPORT_SHIFT 6 
#define WCONF_EMMC8SD_CFG_CAPABILITY1_DDRIVERSUPPORT_BIT 0x1
#define WCONF_EMMC8SD_CFG_CAPABILITY1_DDRIVERSUPPORT_BITWIDTH 1
// reserved2 bitfiled (RO) Reset=0
#define WCONF_EMMC8SD_CFG_CAPABILITY1_RESERVED2_MASK 0x80
#define WCONF_EMMC8SD_CFG_CAPABILITY1_RESERVED2_SHIFT 7 
#define WCONF_EMMC8SD_CFG_CAPABILITY1_RESERVED2_BIT 0x1
#define WCONF_EMMC8SD_CFG_CAPABILITY1_RESERVED2_BITWIDTH 1
// RETUNINGTIMERCNT bitfiled (RW) Reset=1
#define WCONF_EMMC8SD_CFG_CAPABILITY1_RETUNINGTIMERCNT_MASK 0xF00
#define WCONF_EMMC8SD_CFG_CAPABILITY1_RETUNINGTIMERCNT_SHIFT 8 
#define WCONF_EMMC8SD_CFG_CAPABILITY1_RETUNINGTIMERCNT_BIT 0xF
#define WCONF_EMMC8SD_CFG_CAPABILITY1_RETUNINGTIMERCNT_BITWIDTH 4
// reserved3 bitfiled (RO) Reset=0
#define WCONF_EMMC8SD_CFG_CAPABILITY1_RESERVED3_MASK 0x1000
#define WCONF_EMMC8SD_CFG_CAPABILITY1_RESERVED3_SHIFT 12 
#define WCONF_EMMC8SD_CFG_CAPABILITY1_RESERVED3_BIT 0x1
#define WCONF_EMMC8SD_CFG_CAPABILITY1_RESERVED3_BITWIDTH 1
// TUNINGFORSDR50 bitfiled (RW) Reset=0
#define WCONF_EMMC8SD_CFG_CAPABILITY1_TUNINGFORSDR50_MASK 0x2000
#define WCONF_EMMC8SD_CFG_CAPABILITY1_TUNINGFORSDR50_SHIFT 13 
#define WCONF_EMMC8SD_CFG_CAPABILITY1_TUNINGFORSDR50_BIT 0x1
#define WCONF_EMMC8SD_CFG_CAPABILITY1_TUNINGFORSDR50_BITWIDTH 1
// RETUNINGMODES bitfiled (RO) Reset=0
#define WCONF_EMMC8SD_CFG_CAPABILITY1_RETUNINGMODES_MASK 0xC000
#define WCONF_EMMC8SD_CFG_CAPABILITY1_RETUNINGMODES_SHIFT 14 
#define WCONF_EMMC8SD_CFG_CAPABILITY1_RETUNINGMODES_BIT 0x3
#define WCONF_EMMC8SD_CFG_CAPABILITY1_RETUNINGMODES_BITWIDTH 2
// CLKMLTPLY bitfiled (RO) Reset=0
#define WCONF_EMMC8SD_CFG_CAPABILITY1_CLKMLTPLY_MASK 0xFF0000
#define WCONF_EMMC8SD_CFG_CAPABILITY1_CLKMLTPLY_SHIFT 16 
#define WCONF_EMMC8SD_CFG_CAPABILITY1_CLKMLTPLY_BIT 0xFF
#define WCONF_EMMC8SD_CFG_CAPABILITY1_CLKMLTPLY_BITWIDTH 8
// SPISUPPORT bitfiled (RW) Reset=0
#define WCONF_EMMC8SD_CFG_CAPABILITY1_SPISUPPORT_MASK 0x1000000
#define WCONF_EMMC8SD_CFG_CAPABILITY1_SPISUPPORT_SHIFT 24 
#define WCONF_EMMC8SD_CFG_CAPABILITY1_SPISUPPORT_BIT 0x1
#define WCONF_EMMC8SD_CFG_CAPABILITY1_SPISUPPORT_BITWIDTH 1
// SPIBLKMODE bitfiled (RO) Reset=0
#define WCONF_EMMC8SD_CFG_CAPABILITY1_SPIBLKMODE_MASK 0x2000000
#define WCONF_EMMC8SD_CFG_CAPABILITY1_SPIBLKMODE_SHIFT 25 
#define WCONF_EMMC8SD_CFG_CAPABILITY1_SPIBLKMODE_BIT 0x1
#define WCONF_EMMC8SD_CFG_CAPABILITY1_SPIBLKMODE_BITWIDTH 1
// reserved4 bitfiled (RO) Reset=0
#define WCONF_EMMC8SD_CFG_CAPABILITY1_RESERVED4_MASK 0xFC000000
#define WCONF_EMMC8SD_CFG_CAPABILITY1_RESERVED4_SHIFT 26 
#define WCONF_EMMC8SD_CFG_CAPABILITY1_RESERVED4_BIT 0x3F
#define WCONF_EMMC8SD_CFG_CAPABILITY1_RESERVED4_BITWIDTH 6
// EMMC8SD_CFG_MAXCURNT Register
#define WCONF_EMMC8SD_CFG_MAXCURNT_OFS           0x00000110
// MAXCRNT3P3V bitfiled (RW) Reset=0
#define WCONF_EMMC8SD_CFG_MAXCURNT_MAXCRNT3P3V_MASK 0xFF
#define WCONF_EMMC8SD_CFG_MAXCURNT_MAXCRNT3P3V_SHIFT 0 
#define WCONF_EMMC8SD_CFG_MAXCURNT_MAXCRNT3P3V_BIT 0xFF
#define WCONF_EMMC8SD_CFG_MAXCURNT_MAXCRNT3P3V_BITWIDTH 8
// MAXCRNT3P0V bitfiled (RW) Reset=0
#define WCONF_EMMC8SD_CFG_MAXCURNT_MAXCRNT3P0V_MASK 0xFF00
#define WCONF_EMMC8SD_CFG_MAXCURNT_MAXCRNT3P0V_SHIFT 8 
#define WCONF_EMMC8SD_CFG_MAXCURNT_MAXCRNT3P0V_BIT 0xFF
#define WCONF_EMMC8SD_CFG_MAXCURNT_MAXCRNT3P0V_BITWIDTH 8
// MAXCRNT1P8V bitfiled (RW) Reset=0
#define WCONF_EMMC8SD_CFG_MAXCURNT_MAXCRNT1P8V_MASK 0xFF0000
#define WCONF_EMMC8SD_CFG_MAXCURNT_MAXCRNT1P8V_SHIFT 16 
#define WCONF_EMMC8SD_CFG_MAXCURNT_MAXCRNT1P8V_BIT 0xFF
#define WCONF_EMMC8SD_CFG_MAXCURNT_MAXCRNT1P8V_BITWIDTH 8
// reserved1 bitfiled (RO) Reset=0
#define WCONF_EMMC8SD_CFG_MAXCURNT_RESERVED1_MASK 0xFF000000
#define WCONF_EMMC8SD_CFG_MAXCURNT_RESERVED1_SHIFT 24 
#define WCONF_EMMC8SD_CFG_MAXCURNT_RESERVED1_BIT 0xFF
#define WCONF_EMMC8SD_CFG_MAXCURNT_RESERVED1_BITWIDTH 8
// EMMC8SD_CFG_PRESET0 Register
#define WCONF_EMMC8SD_CFG_PRESET0_OFS            0x00000120
// INITPRESETVAL bitfiled (RW) Reset=10000000
#define WCONF_EMMC8SD_CFG_PRESET0_INITPRESETVAL_MASK 0x1FFF
#define WCONF_EMMC8SD_CFG_PRESET0_INITPRESETVAL_SHIFT 0 
#define WCONF_EMMC8SD_CFG_PRESET0_INITPRESETVAL_BIT 0x1FFF
#define WCONF_EMMC8SD_CFG_PRESET0_INITPRESETVAL_BITWIDTH 13
// reserved1 bitfiled (RO) Reset=0
#define WCONF_EMMC8SD_CFG_PRESET0_RESERVED1_MASK 0xE000
#define WCONF_EMMC8SD_CFG_PRESET0_RESERVED1_SHIFT 13 
#define WCONF_EMMC8SD_CFG_PRESET0_RESERVED1_BIT  0x7
#define WCONF_EMMC8SD_CFG_PRESET0_RESERVED1_BITWIDTH 3
// DSPPRESETVAL bitfiled (RW) Reset=10
#define WCONF_EMMC8SD_CFG_PRESET0_DSPPRESETVAL_MASK 0x1FFF0000
#define WCONF_EMMC8SD_CFG_PRESET0_DSPPRESETVAL_SHIFT 16 
#define WCONF_EMMC8SD_CFG_PRESET0_DSPPRESETVAL_BIT 0x1FFF
#define WCONF_EMMC8SD_CFG_PRESET0_DSPPRESETVAL_BITWIDTH 13
// reserved2 bitfiled (RO) Reset=0
#define WCONF_EMMC8SD_CFG_PRESET0_RESERVED2_MASK 0xE0000000
#define WCONF_EMMC8SD_CFG_PRESET0_RESERVED2_SHIFT 29 
#define WCONF_EMMC8SD_CFG_PRESET0_RESERVED2_BIT  0x7
#define WCONF_EMMC8SD_CFG_PRESET0_RESERVED2_BITWIDTH 3
// EMMC8SD_CFG_PRESET1 Register
#define WCONF_EMMC8SD_CFG_PRESET1_OFS            0x00000128
// HSPPRESETVAL bitfiled (RW) Reset=1
#define WCONF_EMMC8SD_CFG_PRESET1_HSPPRESETVAL_MASK 0x1FFF
#define WCONF_EMMC8SD_CFG_PRESET1_HSPPRESETVAL_SHIFT 0 
#define WCONF_EMMC8SD_CFG_PRESET1_HSPPRESETVAL_BIT 0x1FFF
#define WCONF_EMMC8SD_CFG_PRESET1_HSPPRESETVAL_BITWIDTH 13
// reserved1 bitfiled (RO) Reset=0
#define WCONF_EMMC8SD_CFG_PRESET1_RESERVED1_MASK 0xE000
#define WCONF_EMMC8SD_CFG_PRESET1_RESERVED1_SHIFT 13 
#define WCONF_EMMC8SD_CFG_PRESET1_RESERVED1_BIT  0x7
#define WCONF_EMMC8SD_CFG_PRESET1_RESERVED1_BITWIDTH 3
// SDR12PRESETVAL bitfiled (RW) Reset=10
#define WCONF_EMMC8SD_CFG_PRESET1_SDR12PRESETVAL_MASK 0x1FFF0000
#define WCONF_EMMC8SD_CFG_PRESET1_SDR12PRESETVAL_SHIFT 16 
#define WCONF_EMMC8SD_CFG_PRESET1_SDR12PRESETVAL_BIT 0x1FFF
#define WCONF_EMMC8SD_CFG_PRESET1_SDR12PRESETVAL_BITWIDTH 13
// reserved2 bitfiled (RO) Reset=0
#define WCONF_EMMC8SD_CFG_PRESET1_RESERVED2_MASK 0xE0000000
#define WCONF_EMMC8SD_CFG_PRESET1_RESERVED2_SHIFT 29 
#define WCONF_EMMC8SD_CFG_PRESET1_RESERVED2_BIT  0x7
#define WCONF_EMMC8SD_CFG_PRESET1_RESERVED2_BITWIDTH 3
// EMMC8SD_CFG_PRESET2 Register
#define WCONF_EMMC8SD_CFG_PRESET2_OFS            0x00000130
// SDR25PRESETVAL bitfiled (RW) Reset=1
#define WCONF_EMMC8SD_CFG_PRESET2_SDR25PRESETVAL_MASK 0x1FFF
#define WCONF_EMMC8SD_CFG_PRESET2_SDR25PRESETVAL_SHIFT 0 
#define WCONF_EMMC8SD_CFG_PRESET2_SDR25PRESETVAL_BIT 0x1FFF
#define WCONF_EMMC8SD_CFG_PRESET2_SDR25PRESETVAL_BITWIDTH 13
// reserved1 bitfiled (RO) Reset=0
#define WCONF_EMMC8SD_CFG_PRESET2_RESERVED1_MASK 0xE000
#define WCONF_EMMC8SD_CFG_PRESET2_RESERVED1_SHIFT 13 
#define WCONF_EMMC8SD_CFG_PRESET2_RESERVED1_BIT  0x7
#define WCONF_EMMC8SD_CFG_PRESET2_RESERVED1_BITWIDTH 3
// SDR50PRESETVAL bitfiled (RW) Reset=0
#define WCONF_EMMC8SD_CFG_PRESET2_SDR50PRESETVAL_MASK 0x1FFF0000
#define WCONF_EMMC8SD_CFG_PRESET2_SDR50PRESETVAL_SHIFT 16 
#define WCONF_EMMC8SD_CFG_PRESET2_SDR50PRESETVAL_BIT 0x1FFF
#define WCONF_EMMC8SD_CFG_PRESET2_SDR50PRESETVAL_BITWIDTH 13
// reserved2 bitfiled (RO) Reset=0
#define WCONF_EMMC8SD_CFG_PRESET2_RESERVED2_MASK 0xE0000000
#define WCONF_EMMC8SD_CFG_PRESET2_RESERVED2_SHIFT 29 
#define WCONF_EMMC8SD_CFG_PRESET2_RESERVED2_BIT  0x7
#define WCONF_EMMC8SD_CFG_PRESET2_RESERVED2_BITWIDTH 3
// EMMC8SD_CFG_PRESET3 Register
#define WCONF_EMMC8SD_CFG_PRESET3_OFS            0x00000138
// SDR104PRESETVAL bitfiled (RW) Reset=0
#define WCONF_EMMC8SD_CFG_PRESET3_SDR104PRESETVAL_MASK 0x1FFF
#define WCONF_EMMC8SD_CFG_PRESET3_SDR104PRESETVAL_SHIFT 0 
#define WCONF_EMMC8SD_CFG_PRESET3_SDR104PRESETVAL_BIT 0x1FFF
#define WCONF_EMMC8SD_CFG_PRESET3_SDR104PRESETVAL_BITWIDTH 13
// reserved1 bitfiled (RO) Reset=0
#define WCONF_EMMC8SD_CFG_PRESET3_RESERVED1_MASK 0xE000
#define WCONF_EMMC8SD_CFG_PRESET3_RESERVED1_SHIFT 13 
#define WCONF_EMMC8SD_CFG_PRESET3_RESERVED1_BIT  0x7
#define WCONF_EMMC8SD_CFG_PRESET3_RESERVED1_BITWIDTH 3
// DDR50PRESETVAL bitfiled (RW) Reset=1
#define WCONF_EMMC8SD_CFG_PRESET3_DDR50PRESETVAL_MASK 0x1FFF0000
#define WCONF_EMMC8SD_CFG_PRESET3_DDR50PRESETVAL_SHIFT 16 
#define WCONF_EMMC8SD_CFG_PRESET3_DDR50PRESETVAL_BIT 0x1FFF
#define WCONF_EMMC8SD_CFG_PRESET3_DDR50PRESETVAL_BITWIDTH 13
// reserved2 bitfiled (RO) Reset=0
#define WCONF_EMMC8SD_CFG_PRESET3_RESERVED2_MASK 0xE0000000
#define WCONF_EMMC8SD_CFG_PRESET3_RESERVED2_SHIFT 29 
#define WCONF_EMMC8SD_CFG_PRESET3_RESERVED2_BIT  0x7
#define WCONF_EMMC8SD_CFG_PRESET3_RESERVED2_BITWIDTH 3
// EMMC8SD_CFG_WKUP Register
#define WCONF_EMMC8SD_CFG_WKUP_OFS               0x00000140
// ASYNCWKUPEN bitfiled (RW) Reset=1
#define WCONF_EMMC8SD_CFG_WKUP_ASYNCWKUPEN_MASK  0x1
#define WCONF_EMMC8SD_CFG_WKUP_ASYNCWKUPEN_SHIFT 0 
#define WCONF_EMMC8SD_CFG_WKUP_ASYNCWKUPEN_BIT   0x1
#define WCONF_EMMC8SD_CFG_WKUP_ASYNCWKUPEN_BITWIDTH 1
// reserved1 bitfiled (RO) Reset=0
#define WCONF_EMMC8SD_CFG_WKUP_RESERVED1_MASK    0xFFFFFFFE
#define WCONF_EMMC8SD_CFG_WKUP_RESERVED1_SHIFT   1 
#define WCONF_EMMC8SD_CFG_WKUP_RESERVED1_BIT     0x7FFFFFFF
#define WCONF_EMMC8SD_CFG_WKUP_RESERVED1_BITWIDTH 31
// EMMC8SD_CTRL_DLYCHG Register
#define WCONF_EMMC8SD_CTRL_DLYCHG_OFS            0x00000150
// TAPCHGWIN bitfiled (RW) Reset=0
#define WCONF_EMMC8SD_CTRL_DLYCHG_TAPCHGWIN_MASK 0x1
#define WCONF_EMMC8SD_CTRL_DLYCHG_TAPCHGWIN_SHIFT 0 
#define WCONF_EMMC8SD_CTRL_DLYCHG_TAPCHGWIN_BIT  0x1
#define WCONF_EMMC8SD_CTRL_DLYCHG_TAPCHGWIN_BITWIDTH 1
// reserved1 bitfiled (RO) Reset=0
#define WCONF_EMMC8SD_CTRL_DLYCHG_RESERVED1_MASK 0xFFFE
#define WCONF_EMMC8SD_CTRL_DLYCHG_RESERVED1_SHIFT 1 
#define WCONF_EMMC8SD_CTRL_DLYCHG_RESERVED1_BIT  0x7FFF
#define WCONF_EMMC8SD_CTRL_DLYCHG_RESERVED1_BITWIDTH 15
// TAPCHGWINSTS bitfiled (RO) Reset=0
#define WCONF_EMMC8SD_CTRL_DLYCHG_TAPCHGWINSTS_MASK 0x10000
#define WCONF_EMMC8SD_CTRL_DLYCHG_TAPCHGWINSTS_SHIFT 16 
#define WCONF_EMMC8SD_CTRL_DLYCHG_TAPCHGWINSTS_BIT 0x1
#define WCONF_EMMC8SD_CTRL_DLYCHG_TAPCHGWINSTS_BITWIDTH 1
// reserved2 bitfiled (RO) Reset=0
#define WCONF_EMMC8SD_CTRL_DLYCHG_RESERVED2_MASK 0xFFFE0000
#define WCONF_EMMC8SD_CTRL_DLYCHG_RESERVED2_SHIFT 17 
#define WCONF_EMMC8SD_CTRL_DLYCHG_RESERVED2_BIT  0x7FFF
#define WCONF_EMMC8SD_CTRL_DLYCHG_RESERVED2_BITWIDTH 15
// EMMC8SD_CTRL_INDLY Register
#define WCONF_EMMC8SD_CTRL_INDLY_OFS             0x00000158
// ITAPDLYEN bitfiled (RW) Reset=0
#define WCONF_EMMC8SD_CTRL_INDLY_ITAPDLYEN_MASK  0x1
#define WCONF_EMMC8SD_CTRL_INDLY_ITAPDLYEN_SHIFT 0 
#define WCONF_EMMC8SD_CTRL_INDLY_ITAPDLYEN_BIT   0x1
#define WCONF_EMMC8SD_CTRL_INDLY_ITAPDLYEN_BITWIDTH 1
// reserved1 bitfiled (RO) Reset=0
#define WCONF_EMMC8SD_CTRL_INDLY_RESERVED1_MASK  0xFE
#define WCONF_EMMC8SD_CTRL_INDLY_RESERVED1_SHIFT 1 
#define WCONF_EMMC8SD_CTRL_INDLY_RESERVED1_BIT   0x7F
#define WCONF_EMMC8SD_CTRL_INDLY_RESERVED1_BITWIDTH 7
// ITAPDLYSEL bitfiled (RW) Reset=0
#define WCONF_EMMC8SD_CTRL_INDLY_ITAPDLYSEL_MASK 0x1F00
#define WCONF_EMMC8SD_CTRL_INDLY_ITAPDLYSEL_SHIFT 8 
#define WCONF_EMMC8SD_CTRL_INDLY_ITAPDLYSEL_BIT  0x1F
#define WCONF_EMMC8SD_CTRL_INDLY_ITAPDLYSEL_BITWIDTH 5
// reserved2 bitfiled (RO) Reset=0
#define WCONF_EMMC8SD_CTRL_INDLY_RESERVED2_MASK  0xE000
#define WCONF_EMMC8SD_CTRL_INDLY_RESERVED2_SHIFT 13 
#define WCONF_EMMC8SD_CTRL_INDLY_RESERVED2_BIT   0x7
#define WCONF_EMMC8SD_CTRL_INDLY_RESERVED2_BITWIDTH 3
// ITAPDLYENSTS bitfiled (RO) Reset=0
#define WCONF_EMMC8SD_CTRL_INDLY_ITAPDLYENSTS_MASK 0x10000
#define WCONF_EMMC8SD_CTRL_INDLY_ITAPDLYENSTS_SHIFT 16 
#define WCONF_EMMC8SD_CTRL_INDLY_ITAPDLYENSTS_BIT 0x1
#define WCONF_EMMC8SD_CTRL_INDLY_ITAPDLYENSTS_BITWIDTH 1
// reserved3 bitfiled (RO) Reset=0
#define WCONF_EMMC8SD_CTRL_INDLY_RESERVED3_MASK  0xFE0000
#define WCONF_EMMC8SD_CTRL_INDLY_RESERVED3_SHIFT 17 
#define WCONF_EMMC8SD_CTRL_INDLY_RESERVED3_BIT   0x7F
#define WCONF_EMMC8SD_CTRL_INDLY_RESERVED3_BITWIDTH 7
// ITAPDLYSELSTS bitfiled (RO) Reset=0
#define WCONF_EMMC8SD_CTRL_INDLY_ITAPDLYSELSTS_MASK 0x1F000000
#define WCONF_EMMC8SD_CTRL_INDLY_ITAPDLYSELSTS_SHIFT 24 
#define WCONF_EMMC8SD_CTRL_INDLY_ITAPDLYSELSTS_BIT 0x1F
#define WCONF_EMMC8SD_CTRL_INDLY_ITAPDLYSELSTS_BITWIDTH 5
// reserved4 bitfiled (RO) Reset=0
#define WCONF_EMMC8SD_CTRL_INDLY_RESERVED4_MASK  0xE0000000
#define WCONF_EMMC8SD_CTRL_INDLY_RESERVED4_SHIFT 29 
#define WCONF_EMMC8SD_CTRL_INDLY_RESERVED4_BIT   0x7
#define WCONF_EMMC8SD_CTRL_INDLY_RESERVED4_BITWIDTH 3
// EMMC8SD_CTRL_OUTDLY Register
#define WCONF_EMMC8SD_CTRL_OUTDLY_OFS            0x00000160
// OTAPDLYEN bitfiled (RW) Reset=0
#define WCONF_EMMC8SD_CTRL_OUTDLY_OTAPDLYEN_MASK 0x1
#define WCONF_EMMC8SD_CTRL_OUTDLY_OTAPDLYEN_SHIFT 0 
#define WCONF_EMMC8SD_CTRL_OUTDLY_OTAPDLYEN_BIT  0x1
#define WCONF_EMMC8SD_CTRL_OUTDLY_OTAPDLYEN_BITWIDTH 1
// reserved1 bitfiled (RO) Reset=0
#define WCONF_EMMC8SD_CTRL_OUTDLY_RESERVED1_MASK 0xFE
#define WCONF_EMMC8SD_CTRL_OUTDLY_RESERVED1_SHIFT 1 
#define WCONF_EMMC8SD_CTRL_OUTDLY_RESERVED1_BIT  0x7F
#define WCONF_EMMC8SD_CTRL_OUTDLY_RESERVED1_BITWIDTH 7
// OTAPDLYSEL bitfiled (RW) Reset=0
#define WCONF_EMMC8SD_CTRL_OUTDLY_OTAPDLYSEL_MASK 0xF00
#define WCONF_EMMC8SD_CTRL_OUTDLY_OTAPDLYSEL_SHIFT 8 
#define WCONF_EMMC8SD_CTRL_OUTDLY_OTAPDLYSEL_BIT 0xF
#define WCONF_EMMC8SD_CTRL_OUTDLY_OTAPDLYSEL_BITWIDTH 4
// reserved2 bitfiled (RO) Reset=0
#define WCONF_EMMC8SD_CTRL_OUTDLY_RESERVED2_MASK 0xF000
#define WCONF_EMMC8SD_CTRL_OUTDLY_RESERVED2_SHIFT 12 
#define WCONF_EMMC8SD_CTRL_OUTDLY_RESERVED2_BIT  0xF
#define WCONF_EMMC8SD_CTRL_OUTDLY_RESERVED2_BITWIDTH 4
// OTAPDLYENSTS bitfiled (RO) Reset=0
#define WCONF_EMMC8SD_CTRL_OUTDLY_OTAPDLYENSTS_MASK 0x10000
#define WCONF_EMMC8SD_CTRL_OUTDLY_OTAPDLYENSTS_SHIFT 16 
#define WCONF_EMMC8SD_CTRL_OUTDLY_OTAPDLYENSTS_BIT 0x1
#define WCONF_EMMC8SD_CTRL_OUTDLY_OTAPDLYENSTS_BITWIDTH 1
// reserved3 bitfiled (RO) Reset=0
#define WCONF_EMMC8SD_CTRL_OUTDLY_RESERVED3_MASK 0xFE0000
#define WCONF_EMMC8SD_CTRL_OUTDLY_RESERVED3_SHIFT 17 
#define WCONF_EMMC8SD_CTRL_OUTDLY_RESERVED3_BIT  0x7F
#define WCONF_EMMC8SD_CTRL_OUTDLY_RESERVED3_BITWIDTH 7
// OTAPDLYSELSTS bitfiled (RO) Reset=0
#define WCONF_EMMC8SD_CTRL_OUTDLY_OTAPDLYSELSTS_MASK 0xF000000
#define WCONF_EMMC8SD_CTRL_OUTDLY_OTAPDLYSELSTS_SHIFT 24 
#define WCONF_EMMC8SD_CTRL_OUTDLY_OTAPDLYSELSTS_BIT 0xF
#define WCONF_EMMC8SD_CTRL_OUTDLY_OTAPDLYSELSTS_BITWIDTH 4
// reserved4 bitfiled (RO) Reset=0
#define WCONF_EMMC8SD_CTRL_OUTDLY_RESERVED4_MASK 0xF0000000
#define WCONF_EMMC8SD_CTRL_OUTDLY_RESERVED4_SHIFT 28 
#define WCONF_EMMC8SD_CTRL_OUTDLY_RESERVED4_BIT  0xF
#define WCONF_EMMC8SD_CTRL_OUTDLY_RESERVED4_BITWIDTH 4
// EMMC8SD_CTRL_DLL0 Register
#define WCONF_EMMC8SD_CTRL_DLL0_OFS              0x00000168
// DLLENABLE bitfiled (RW) Reset=0
#define WCONF_EMMC8SD_CTRL_DLL0_DLLENABLE_MASK   0x1
#define WCONF_EMMC8SD_CTRL_DLL0_DLLENABLE_SHIFT  0 
#define WCONF_EMMC8SD_CTRL_DLL0_DLLENABLE_BIT    0x1
#define WCONF_EMMC8SD_CTRL_DLL0_DLLENABLE_BITWIDTH 1
// reserved1 bitfiled (RO) Reset=0
#define WCONF_EMMC8SD_CTRL_DLL0_RESERVED1_MASK   0xFFFE
#define WCONF_EMMC8SD_CTRL_DLL0_RESERVED1_SHIFT  1 
#define WCONF_EMMC8SD_CTRL_DLL0_RESERVED1_BIT    0x7FFF
#define WCONF_EMMC8SD_CTRL_DLL0_RESERVED1_BITWIDTH 15
// DLLREADY bitfiled (RO) Reset=0
#define WCONF_EMMC8SD_CTRL_DLL0_DLLREADY_MASK    0x10000
#define WCONF_EMMC8SD_CTRL_DLL0_DLLREADY_SHIFT   16 
#define WCONF_EMMC8SD_CTRL_DLL0_DLLREADY_BIT     0x1
#define WCONF_EMMC8SD_CTRL_DLL0_DLLREADY_BITWIDTH 1
// reserved2 bitfiled (RO) Reset=0
#define WCONF_EMMC8SD_CTRL_DLL0_RESERVED2_MASK   0xFFFE0000
#define WCONF_EMMC8SD_CTRL_DLL0_RESERVED2_SHIFT  17 
#define WCONF_EMMC8SD_CTRL_DLL0_RESERVED2_BIT    0x7FFF
#define WCONF_EMMC8SD_CTRL_DLL0_RESERVED2_BITWIDTH 15
// EMMC8SD_CTRL_DLL1 Register
#define WCONF_EMMC8SD_CTRL_DLL1_OFS              0x00000170
// DLLCLKSEL bitfiled (RW) Reset=0
#define WCONF_EMMC8SD_CTRL_DLL1_DLLCLKSEL_MASK   0x1
#define WCONF_EMMC8SD_CTRL_DLL1_DLLCLKSEL_SHIFT  0 
#define WCONF_EMMC8SD_CTRL_DLL1_DLLCLKSEL_BIT    0x1
#define WCONF_EMMC8SD_CTRL_DLL1_DLLCLKSEL_BITWIDTH 1
// reserved1 bitfiled (RO) Reset=0
#define WCONF_EMMC8SD_CTRL_DLL1_RESERVED1_MASK   0xFFFE
#define WCONF_EMMC8SD_CTRL_DLL1_RESERVED1_SHIFT  1 
#define WCONF_EMMC8SD_CTRL_DLL1_RESERVED1_BIT    0x7FFF
#define WCONF_EMMC8SD_CTRL_DLL1_RESERVED1_BITWIDTH 15
// DLLCLKSELSTS bitfiled (RO) Reset=0
#define WCONF_EMMC8SD_CTRL_DLL1_DLLCLKSELSTS_MASK 0x10000
#define WCONF_EMMC8SD_CTRL_DLL1_DLLCLKSELSTS_SHIFT 16 
#define WCONF_EMMC8SD_CTRL_DLL1_DLLCLKSELSTS_BIT 0x1
#define WCONF_EMMC8SD_CTRL_DLL1_DLLCLKSELSTS_BITWIDTH 1
// reserved2 bitfiled (RO) Reset=0
#define WCONF_EMMC8SD_CTRL_DLL1_RESERVED2_MASK   0xFFFE0000
#define WCONF_EMMC8SD_CTRL_DLL1_RESERVED2_SHIFT  17 
#define WCONF_EMMC8SD_CTRL_DLL1_RESERVED2_BIT    0x7FFF
#define WCONF_EMMC8SD_CTRL_DLL1_RESERVED2_BITWIDTH 15
// IO_DRVSTR_CTL Register
#define WCONF_IO_DRVSTR_CTL_OFS                  0x00000200
// SPI01_CTL bitfiled (RW) Reset=1
#define WCONF_IO_DRVSTR_CTL_SPI01_CTL_MASK       0x1
#define WCONF_IO_DRVSTR_CTL_SPI01_CTL_SHIFT      0 
#define WCONF_IO_DRVSTR_CTL_SPI01_CTL_BIT        0x1
#define WCONF_IO_DRVSTR_CTL_SPI01_CTL_BITWIDTH   1
// Reserved bitfiled (RO) Reset=0
#define WCONF_IO_DRVSTR_CTL_RESERVED_MASK        0x2
#define WCONF_IO_DRVSTR_CTL_RESERVED_SHIFT       1 
#define WCONF_IO_DRVSTR_CTL_RESERVED_BIT         0x1
#define WCONF_IO_DRVSTR_CTL_RESERVED_BITWIDTH    1
// SPI2_CTL bitfiled (RW) Reset=1
#define WCONF_IO_DRVSTR_CTL_SPI2_CTL_MASK        0x4
#define WCONF_IO_DRVSTR_CTL_SPI2_CTL_SHIFT       2 
#define WCONF_IO_DRVSTR_CTL_SPI2_CTL_BIT         0x1
#define WCONF_IO_DRVSTR_CTL_SPI2_CTL_BITWIDTH    1
// SPI3_CTL bitfiled (RW) Reset=1
#define WCONF_IO_DRVSTR_CTL_SPI3_CTL_MASK        0x8
#define WCONF_IO_DRVSTR_CTL_SPI3_CTL_SHIFT       3 
#define WCONF_IO_DRVSTR_CTL_SPI3_CTL_BIT         0x1
#define WCONF_IO_DRVSTR_CTL_SPI3_CTL_BITWIDTH    1
// Reserved2 bitfiled (RO) Reset=0
#define WCONF_IO_DRVSTR_CTL_RESERVED2_MASK       0xF0
#define WCONF_IO_DRVSTR_CTL_RESERVED2_SHIFT      4 
#define WCONF_IO_DRVSTR_CTL_RESERVED2_BIT        0xF
#define WCONF_IO_DRVSTR_CTL_RESERVED2_BITWIDTH   4
// UART0_CTL bitfiled (RW) Reset=0
#define WCONF_IO_DRVSTR_CTL_UART0_CTL_MASK       0x100
#define WCONF_IO_DRVSTR_CTL_UART0_CTL_SHIFT      8 
#define WCONF_IO_DRVSTR_CTL_UART0_CTL_BIT        0x1
#define WCONF_IO_DRVSTR_CTL_UART0_CTL_BITWIDTH   1
// Reserved3 bitfiled (RO) Reset=0
#define WCONF_IO_DRVSTR_CTL_RESERVED3_MASK       0x200
#define WCONF_IO_DRVSTR_CTL_RESERVED3_SHIFT      9 
#define WCONF_IO_DRVSTR_CTL_RESERVED3_BIT        0x1
#define WCONF_IO_DRVSTR_CTL_RESERVED3_BITWIDTH   1
// UART2_CTL bitfiled (RW) Reset=0
#define WCONF_IO_DRVSTR_CTL_UART2_CTL_MASK       0x400
#define WCONF_IO_DRVSTR_CTL_UART2_CTL_SHIFT      10 
#define WCONF_IO_DRVSTR_CTL_UART2_CTL_BIT        0x1
#define WCONF_IO_DRVSTR_CTL_UART2_CTL_BITWIDTH   1
// UART3_CTL bitfiled (RW) Reset=0
#define WCONF_IO_DRVSTR_CTL_UART3_CTL_MASK       0x800
#define WCONF_IO_DRVSTR_CTL_UART3_CTL_SHIFT      11 
#define WCONF_IO_DRVSTR_CTL_UART3_CTL_BIT        0x1
#define WCONF_IO_DRVSTR_CTL_UART3_CTL_BITWIDTH   1
// Reserved4 bitfiled (RO) Reset=0
#define WCONF_IO_DRVSTR_CTL_RESERVED4_MASK       0xF000
#define WCONF_IO_DRVSTR_CTL_RESERVED4_SHIFT      12 
#define WCONF_IO_DRVSTR_CTL_RESERVED4_BIT        0xF
#define WCONF_IO_DRVSTR_CTL_RESERVED4_BITWIDTH   4
// I2S_CTL bitfiled (RW) Reset=0
#define WCONF_IO_DRVSTR_CTL_I2S_CTL_MASK         0x10000
#define WCONF_IO_DRVSTR_CTL_I2S_CTL_SHIFT        16 
#define WCONF_IO_DRVSTR_CTL_I2S_CTL_BIT          0x1
#define WCONF_IO_DRVSTR_CTL_I2S_CTL_BITWIDTH     1
// PWM_CTL bitfiled (RW) Reset=0
#define WCONF_IO_DRVSTR_CTL_PWM_CTL_MASK         0x20000
#define WCONF_IO_DRVSTR_CTL_PWM_CTL_SHIFT        17 
#define WCONF_IO_DRVSTR_CTL_PWM_CTL_BIT          0x1
#define WCONF_IO_DRVSTR_CTL_PWM_CTL_BITWIDTH     1
// Reserved5 bitfiled (RO) Reset=0
#define WCONF_IO_DRVSTR_CTL_RESERVED5_MASK       0xFC0000
#define WCONF_IO_DRVSTR_CTL_RESERVED5_SHIFT      18 
#define WCONF_IO_DRVSTR_CTL_RESERVED5_BIT        0x3F
#define WCONF_IO_DRVSTR_CTL_RESERVED5_BITWIDTH   6
// ETH_CTL bitfiled (RW) Reset=1
#define WCONF_IO_DRVSTR_CTL_ETH_CTL_MASK         0x1000000
#define WCONF_IO_DRVSTR_CTL_ETH_CTL_SHIFT        24 
#define WCONF_IO_DRVSTR_CTL_ETH_CTL_BIT          0x1
#define WCONF_IO_DRVSTR_CTL_ETH_CTL_BITWIDTH     1
// Reserved6 bitfiled (RO) Reset=0
#define WCONF_IO_DRVSTR_CTL_RESERVED6_MASK       0xE000000
#define WCONF_IO_DRVSTR_CTL_RESERVED6_SHIFT      25 
#define WCONF_IO_DRVSTR_CTL_RESERVED6_BIT        0x7
#define WCONF_IO_DRVSTR_CTL_RESERVED6_BITWIDTH   3
// DISP_CTL bitfiled (RW) Reset=1
#define WCONF_IO_DRVSTR_CTL_DISP_CTL_MASK        0x10000000
#define WCONF_IO_DRVSTR_CTL_DISP_CTL_SHIFT       28 
#define WCONF_IO_DRVSTR_CTL_DISP_CTL_BIT         0x1
#define WCONF_IO_DRVSTR_CTL_DISP_CTL_BITWIDTH    1
// Reserved7 bitfiled (RO) Reset=0
#define WCONF_IO_DRVSTR_CTL_RESERVED7_MASK       0x60000000
#define WCONF_IO_DRVSTR_CTL_RESERVED7_SHIFT      29 
#define WCONF_IO_DRVSTR_CTL_RESERVED7_BIT        0x3
#define WCONF_IO_DRVSTR_CTL_RESERVED7_BITWIDTH   2
// DBG_CTL bitfiled (RW) Reset=1
#define WCONF_IO_DRVSTR_CTL_DBG_CTL_MASK         0x80000000
#define WCONF_IO_DRVSTR_CTL_DBG_CTL_SHIFT        31 
#define WCONF_IO_DRVSTR_CTL_DBG_CTL_BIT          0x1
#define WCONF_IO_DRVSTR_CTL_DBG_CTL_BITWIDTH     1
// USB2HD_FLADJ Register
#define WCONF_USB2HD_FLADJ_OFS                   0x00000500
// FLADJ bitfiled (RW) Reset=100000
#define WCONF_USB2HD_FLADJ_FLADJ_MASK            0x3F
#define WCONF_USB2HD_FLADJ_FLADJ_SHIFT           0 
#define WCONF_USB2HD_FLADJ_FLADJ_BIT             0x3F
#define WCONF_USB2HD_FLADJ_FLADJ_BITWIDTH        6
// reserved1 bitfiled (RO) Reset=0
#define WCONF_USB2HD_FLADJ_RESERVED1_MASK        0xFFFFFFC0
#define WCONF_USB2HD_FLADJ_RESERVED1_SHIFT       6 
#define WCONF_USB2HD_FLADJ_RESERVED1_BIT         0x3FFFFFF
#define WCONF_USB2HD_FLADJ_RESERVED1_BITWIDTH    26
// USB2PHY_CONFIG0 Register
#define WCONF_USB2PHY_CONFIG0_OFS                0x00000600
// CONFIG0 bitfiled (RW) Reset=0
#define WCONF_USB2PHY_CONFIG0_CONFIG0_MASK       0xFFFFFFFF
#define WCONF_USB2PHY_CONFIG0_CONFIG0_SHIFT      0 
#define WCONF_USB2PHY_CONFIG0_CONFIG0_BIT        0xFFFFFFFF
#define WCONF_USB2PHY_CONFIG0_CONFIG0_BITWIDTH   32
// USB2PHY_CONFIG1 Register
#define WCONF_USB2PHY_CONFIG1_OFS                0x00000610
// CONFIG1 bitfiled (RW) Reset=0
#define WCONF_USB2PHY_CONFIG1_CONFIG1_MASK       0x1
#define WCONF_USB2PHY_CONFIG1_CONFIG1_SHIFT      0 
#define WCONF_USB2PHY_CONFIG1_CONFIG1_BIT        0x1
#define WCONF_USB2PHY_CONFIG1_CONFIG1_BITWIDTH   1
// reserved1 bitfiled (RO) Reset=0
#define WCONF_USB2PHY_CONFIG1_RESERVED1_MASK     0xFFFFFFFE
#define WCONF_USB2PHY_CONFIG1_RESERVED1_SHIFT    1 
#define WCONF_USB2PHY_CONFIG1_RESERVED1_BIT      0x7FFFFFFF
#define WCONF_USB2PHY_CONFIG1_RESERVED1_BITWIDTH 31
// USB2HD_MUX_CTL Register
#define WCONF_USB2HD_MUX_CTL_OFS                 0x00000700
// USB2HD_MUX_HSEL bitfiled (RW) Reset=0
#define WCONF_USB2HD_MUX_CTL_USB2HD_MUX_HSEL_MASK 0x1
#define WCONF_USB2HD_MUX_CTL_USB2HD_MUX_HSEL_SHIFT 0 
#define WCONF_USB2HD_MUX_CTL_USB2HD_MUX_HSEL_BIT 0x1
#define WCONF_USB2HD_MUX_CTL_USB2HD_MUX_HSEL_BITWIDTH 1
// USB2HD_MUX_HEN bitfiled (RW) Reset=0
#define WCONF_USB2HD_MUX_CTL_USB2HD_MUX_HEN_MASK 0x2
#define WCONF_USB2HD_MUX_CTL_USB2HD_MUX_HEN_SHIFT 1 
#define WCONF_USB2HD_MUX_CTL_USB2HD_MUX_HEN_BIT  0x1
#define WCONF_USB2HD_MUX_CTL_USB2HD_MUX_HEN_BITWIDTH 1
// reserved1 bitfiled (RO) Reset=0
#define WCONF_USB2HD_MUX_CTL_RESERVED1_MASK      0xFFFFFFFC
#define WCONF_USB2HD_MUX_CTL_RESERVED1_SHIFT     2 
#define WCONF_USB2HD_MUX_CTL_RESERVED1_BIT       0x3FFFFFFF
#define WCONF_USB2HD_MUX_CTL_RESERVED1_BITWIDTH  30
// USB2HD_REFCLK Register
#define WCONF_USB2HD_REFCLK_OFS                  0x00000704
// REFCLKSEL bitfiled (RW) Reset=10
#define WCONF_USB2HD_REFCLK_REFCLKSEL_MASK       0x3
#define WCONF_USB2HD_REFCLK_REFCLKSEL_SHIFT      0 
#define WCONF_USB2HD_REFCLK_REFCLKSEL_BIT        0x3
#define WCONF_USB2HD_REFCLK_REFCLKSEL_BITWIDTH   2
// Reserved bitfiled (RO) Reset=0
#define WCONF_USB2HD_REFCLK_RESERVED_MASK        0xC
#define WCONF_USB2HD_REFCLK_RESERVED_SHIFT       2 
#define WCONF_USB2HD_REFCLK_RESERVED_BIT         0x3
#define WCONF_USB2HD_REFCLK_RESERVED_BITWIDTH    2
// REFCLKDIV bitfiled (RW) Reset=101
#define WCONF_USB2HD_REFCLK_REFCLKDIV_MASK       0x70
#define WCONF_USB2HD_REFCLK_REFCLKDIV_SHIFT      4 
#define WCONF_USB2HD_REFCLK_REFCLKDIV_BIT        0x7
#define WCONF_USB2HD_REFCLK_REFCLKDIV_BITWIDTH   3
// reserved2 bitfiled (RO) Reset=0
#define WCONF_USB2HD_REFCLK_RESERVED2_MASK       0xFFFFFF80
#define WCONF_USB2HD_REFCLK_RESERVED2_SHIFT      7 
#define WCONF_USB2HD_REFCLK_RESERVED2_BIT        0x1FFFFFF
#define WCONF_USB2HD_REFCLK_RESERVED2_BITWIDTH   25
// USB2HD_STATUS Register
#define WCONF_USB2HD_STATUS_OFS                  0x00000708
// BVALID bitfiled (RO) Reset=0
#define WCONF_USB2HD_STATUS_BVALID_MASK          0x1
#define WCONF_USB2HD_STATUS_BVALID_SHIFT         0 
#define WCONF_USB2HD_STATUS_BVALID_BIT           0x1
#define WCONF_USB2HD_STATUS_BVALID_BITWIDTH      1
// reserved1 bitfiled (RO) Reset=0
#define WCONF_USB2HD_STATUS_RESERVED1_MASK       0xFFFFFFFE
#define WCONF_USB2HD_STATUS_RESERVED1_SHIFT      1 
#define WCONF_USB2HD_STATUS_RESERVED1_BIT        0x7FFFFFFF
#define WCONF_USB2HD_STATUS_RESERVED1_BITWIDTH   31

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* _WCONF_REG_DEF_H */
