/*
 * arch/arm/mach-tz2000/include/mach/regs/yuvc_reg_def.h
 *
 * (C) Copyright TOSHIBA Corporation
 * Semiconductor & Storage Products Company 2013
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#ifndef _YUVC_REG_DEF_H
#define _YUVC_REG_DEF_H

#ifdef __cplusplus
extern  {
#endif /* __cplusplus */

// YUVC_START Register
#define YUVC_YUVC_START_OFS                      0x00000000
// yuvc_start bitfiled (RW) Reset=0
#define YUVC_YUVC_START_YUVC_START_MASK          0x1
#define YUVC_YUVC_START_YUVC_START_SHIFT         0 
#define YUVC_YUVC_START_YUVC_START_BIT           0x1
#define YUVC_YUVC_START_YUVC_START_BITWIDTH      1
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_START_RESERVED_MASK            0xFFFFFFFE
#define YUVC_YUVC_START_RESERVED_SHIFT           1 
#define YUVC_YUVC_START_RESERVED_BIT             0x7FFFFFFF
#define YUVC_YUVC_START_RESERVED_BITWIDTH        31
// YUVC_RESET Register
#define YUVC_YUVC_RESET_OFS                      0x00000004
// yuvc_reset bitfiled (RW) Reset=0
#define YUVC_YUVC_RESET_YUVC_RESET_MASK          0x1
#define YUVC_YUVC_RESET_YUVC_RESET_SHIFT         0 
#define YUVC_YUVC_RESET_YUVC_RESET_BIT           0x1
#define YUVC_YUVC_RESET_YUVC_RESET_BITWIDTH      1
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_RESET_RESERVED_MASK            0xFFFFFFFE
#define YUVC_YUVC_RESET_RESERVED_SHIFT           1 
#define YUVC_YUVC_RESET_RESERVED_BIT             0x7FFFFFFF
#define YUVC_YUVC_RESET_RESERVED_BITWIDTH        31
// YUVC_MODE Register
#define YUVC_YUVC_MODE_OFS                       0x00000008
// cf_inmode bitfiled (RW) Reset=0
#define YUVC_YUVC_MODE_CF_INMODE_MASK            0x3
#define YUVC_YUVC_MODE_CF_INMODE_SHIFT           0 
#define YUVC_YUVC_MODE_CF_INMODE_BIT             0x3
#define YUVC_YUVC_MODE_CF_INMODE_BITWIDTH        2
// reserved4 bitfiled (RO) Reset=0
#define YUVC_YUVC_MODE_RESERVED4_MASK            0xC
#define YUVC_YUVC_MODE_RESERVED4_SHIFT           2 
#define YUVC_YUVC_MODE_RESERVED4_BIT             0x3
#define YUVC_YUVC_MODE_RESERVED4_BITWIDTH        2
// cf_outmode bitfiled (RW) Reset=0
#define YUVC_YUVC_MODE_CF_OUTMODE_MASK           0x30
#define YUVC_YUVC_MODE_CF_OUTMODE_SHIFT          4 
#define YUVC_YUVC_MODE_CF_OUTMODE_BIT            0x3
#define YUVC_YUVC_MODE_CF_OUTMODE_BITWIDTH       2
// reserved3 bitfiled (RO) Reset=0
#define YUVC_YUVC_MODE_RESERVED3_MASK            0xC0
#define YUVC_YUVC_MODE_RESERVED3_SHIFT           6 
#define YUVC_YUVC_MODE_RESERVED3_BIT             0x3
#define YUVC_YUVC_MODE_RESERVED3_BITWIDTH        2
// cf_rgblimit bitfiled (RW) Reset=0
#define YUVC_YUVC_MODE_CF_RGBLIMIT_MASK          0x100
#define YUVC_YUVC_MODE_CF_RGBLIMIT_SHIFT         8 
#define YUVC_YUVC_MODE_CF_RGBLIMIT_BIT           0x1
#define YUVC_YUVC_MODE_CF_RGBLIMIT_BITWIDTH      1
// reserved2 bitfiled (RO) Reset=0
#define YUVC_YUVC_MODE_RESERVED2_MASK            0xFE00
#define YUVC_YUVC_MODE_RESERVED2_SHIFT           9 
#define YUVC_YUVC_MODE_RESERVED2_BIT             0x7F
#define YUVC_YUVC_MODE_RESERVED2_BITWIDTH        7
// cf_alpha bitfiled (RW) Reset=0
#define YUVC_YUVC_MODE_CF_ALPHA_MASK             0xFF0000
#define YUVC_YUVC_MODE_CF_ALPHA_SHIFT            16 
#define YUVC_YUVC_MODE_CF_ALPHA_BIT              0xFF
#define YUVC_YUVC_MODE_CF_ALPHA_BITWIDTH         8
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_MODE_RESERVED_MASK             0xFF000000
#define YUVC_YUVC_MODE_RESERVED_SHIFT            24 
#define YUVC_YUVC_MODE_RESERVED_BIT              0xFF
#define YUVC_YUVC_MODE_RESERVED_BITWIDTH         8
// YUVC_SIZE Register
#define YUVC_YUVC_SIZE_OFS                       0x0000000C
// cf_hsize bitfiled (RW) Reset=0
#define YUVC_YUVC_SIZE_CF_HSIZE_MASK             0x7FF
#define YUVC_YUVC_SIZE_CF_HSIZE_SHIFT            0 
#define YUVC_YUVC_SIZE_CF_HSIZE_BIT              0x7FF
#define YUVC_YUVC_SIZE_CF_HSIZE_BITWIDTH         11
// reserved2 bitfiled (RO) Reset=0
#define YUVC_YUVC_SIZE_RESERVED2_MASK            0xF800
#define YUVC_YUVC_SIZE_RESERVED2_SHIFT           11 
#define YUVC_YUVC_SIZE_RESERVED2_BIT             0x1F
#define YUVC_YUVC_SIZE_RESERVED2_BITWIDTH        5
// cf_vsize bitfiled (RW) Reset=0
#define YUVC_YUVC_SIZE_CF_VSIZE_MASK             0x7FF0000
#define YUVC_YUVC_SIZE_CF_VSIZE_SHIFT            16 
#define YUVC_YUVC_SIZE_CF_VSIZE_BIT              0x7FF
#define YUVC_YUVC_SIZE_CF_VSIZE_BITWIDTH         11
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_SIZE_RESERVED_MASK             0xF8000000
#define YUVC_YUVC_SIZE_RESERVED_SHIFT            27 
#define YUVC_YUVC_SIZE_RESERVED_BIT              0x1F
#define YUVC_YUVC_SIZE_RESERVED_BITWIDTH         5
// YUVC_OFFSET_Y Register
#define YUVC_YUVC_OFFSET_Y_OFS                   0x00000010
// cf_yoffset bitfiled (RW) Reset=0
#define YUVC_YUVC_OFFSET_Y_CF_YOFFSET_MASK       0x1FF
#define YUVC_YUVC_OFFSET_Y_CF_YOFFSET_SHIFT      0 
#define YUVC_YUVC_OFFSET_Y_CF_YOFFSET_BIT        0x1FF
#define YUVC_YUVC_OFFSET_Y_CF_YOFFSET_BITWIDTH   9
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_OFFSET_Y_RESERVED_MASK         0xFFFFFE00
#define YUVC_YUVC_OFFSET_Y_RESERVED_SHIFT        9 
#define YUVC_YUVC_OFFSET_Y_RESERVED_BIT          0x7FFFFF
#define YUVC_YUVC_OFFSET_Y_RESERVED_BITWIDTH     23
// YUVC_OFFSET_UV Register
#define YUVC_YUVC_OFFSET_UV_OFS                  0x00000014
// cf_voffset bitfiled (RW) Reset=110000000
#define YUVC_YUVC_OFFSET_UV_CF_VOFFSET_MASK      0x1FF
#define YUVC_YUVC_OFFSET_UV_CF_VOFFSET_SHIFT     0 
#define YUVC_YUVC_OFFSET_UV_CF_VOFFSET_BIT       0x1FF
#define YUVC_YUVC_OFFSET_UV_CF_VOFFSET_BITWIDTH  9
// reserved2 bitfiled (RO) Reset=0
#define YUVC_YUVC_OFFSET_UV_RESERVED2_MASK       0xFE00
#define YUVC_YUVC_OFFSET_UV_RESERVED2_SHIFT      9 
#define YUVC_YUVC_OFFSET_UV_RESERVED2_BIT        0x7F
#define YUVC_YUVC_OFFSET_UV_RESERVED2_BITWIDTH   7
// cf_uoffset bitfiled (RW) Reset=110000000
#define YUVC_YUVC_OFFSET_UV_CF_UOFFSET_MASK      0x1FF0000
#define YUVC_YUVC_OFFSET_UV_CF_UOFFSET_SHIFT     16 
#define YUVC_YUVC_OFFSET_UV_CF_UOFFSET_BIT       0x1FF
#define YUVC_YUVC_OFFSET_UV_CF_UOFFSET_BITWIDTH  9
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_OFFSET_UV_RESERVED_MASK        0xFE000000
#define YUVC_YUVC_OFFSET_UV_RESERVED_SHIFT       25 
#define YUVC_YUVC_OFFSET_UV_RESERVED_BIT         0x7F
#define YUVC_YUVC_OFFSET_UV_RESERVED_BITWIDTH    7
// YUVC_YCOEF_RG Register
#define YUVC_YUVC_YCOEF_RG_OFS                   0x00000018
// cf_ycoef_g bitfiled (RW) Reset=100000000
#define YUVC_YUVC_YCOEF_RG_CF_YCOEF_G_MASK       0x1FF
#define YUVC_YUVC_YCOEF_RG_CF_YCOEF_G_SHIFT      0 
#define YUVC_YUVC_YCOEF_RG_CF_YCOEF_G_BIT        0x1FF
#define YUVC_YUVC_YCOEF_RG_CF_YCOEF_G_BITWIDTH   9
// reserved2 bitfiled (RO) Reset=0
#define YUVC_YUVC_YCOEF_RG_RESERVED2_MASK        0xFE00
#define YUVC_YUVC_YCOEF_RG_RESERVED2_SHIFT       9 
#define YUVC_YUVC_YCOEF_RG_RESERVED2_BIT         0x7F
#define YUVC_YUVC_YCOEF_RG_RESERVED2_BITWIDTH    7
// cf_ycoef_r bitfiled (RW) Reset=100000000
#define YUVC_YUVC_YCOEF_RG_CF_YCOEF_R_MASK       0x1FF0000
#define YUVC_YUVC_YCOEF_RG_CF_YCOEF_R_SHIFT      16 
#define YUVC_YUVC_YCOEF_RG_CF_YCOEF_R_BIT        0x1FF
#define YUVC_YUVC_YCOEF_RG_CF_YCOEF_R_BITWIDTH   9
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_YCOEF_RG_RESERVED_MASK         0xFE000000
#define YUVC_YUVC_YCOEF_RG_RESERVED_SHIFT        25 
#define YUVC_YUVC_YCOEF_RG_RESERVED_BIT          0x7F
#define YUVC_YUVC_YCOEF_RG_RESERVED_BITWIDTH     7
// YUVC_YCOEF_B Register
#define YUVC_YUVC_YCOEF_B_OFS                    0x0000001C
// cf_ycoef_b bitfiled (RW) Reset=100000000
#define YUVC_YUVC_YCOEF_B_CF_YCOEF_B_MASK        0x1FF
#define YUVC_YUVC_YCOEF_B_CF_YCOEF_B_SHIFT       0 
#define YUVC_YUVC_YCOEF_B_CF_YCOEF_B_BIT         0x1FF
#define YUVC_YUVC_YCOEF_B_CF_YCOEF_B_BITWIDTH    9
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_YCOEF_B_RESERVED_MASK          0xFFFFFE00
#define YUVC_YUVC_YCOEF_B_RESERVED_SHIFT         9 
#define YUVC_YUVC_YCOEF_B_RESERVED_BIT           0x7FFFFF
#define YUVC_YUVC_YCOEF_B_RESERVED_BITWIDTH      23
// YUVC_UCOEF_RG Register
#define YUVC_YUVC_UCOEF_RG_OFS                   0x00000020
// cf_ucoef_g bitfiled (RW) Reset=1110101010
#define YUVC_YUVC_UCOEF_RG_CF_UCOEF_G_MASK       0x3FF
#define YUVC_YUVC_UCOEF_RG_CF_UCOEF_G_SHIFT      0 
#define YUVC_YUVC_UCOEF_RG_CF_UCOEF_G_BIT        0x3FF
#define YUVC_YUVC_UCOEF_RG_CF_UCOEF_G_BITWIDTH   10
// reserved2 bitfiled (RO) Reset=0
#define YUVC_YUVC_UCOEF_RG_RESERVED2_MASK        0xFC00
#define YUVC_YUVC_UCOEF_RG_RESERVED2_SHIFT       10 
#define YUVC_YUVC_UCOEF_RG_RESERVED2_BIT         0x3F
#define YUVC_YUVC_UCOEF_RG_RESERVED2_BITWIDTH    6
// cf_ucoef_r bitfiled (RW) Reset=0
#define YUVC_YUVC_UCOEF_RG_CF_UCOEF_R_MASK       0x3FF0000
#define YUVC_YUVC_UCOEF_RG_CF_UCOEF_R_SHIFT      16 
#define YUVC_YUVC_UCOEF_RG_CF_UCOEF_R_BIT        0x3FF
#define YUVC_YUVC_UCOEF_RG_CF_UCOEF_R_BITWIDTH   10
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_UCOEF_RG_RESERVED_MASK         0xFC000000
#define YUVC_YUVC_UCOEF_RG_RESERVED_SHIFT        26 
#define YUVC_YUVC_UCOEF_RG_RESERVED_BIT          0x3F
#define YUVC_YUVC_UCOEF_RG_RESERVED_BITWIDTH     6
// YUVC_UCOEF_B Register
#define YUVC_YUVC_UCOEF_B_OFS                    0x00000024
// cf_ucoef_b bitfiled (RW) Reset=110111011
#define YUVC_YUVC_UCOEF_B_CF_UCOEF_B_MASK        0x3FF
#define YUVC_YUVC_UCOEF_B_CF_UCOEF_B_SHIFT       0 
#define YUVC_YUVC_UCOEF_B_CF_UCOEF_B_BIT         0x3FF
#define YUVC_YUVC_UCOEF_B_CF_UCOEF_B_BITWIDTH    10
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_UCOEF_B_RESERVED_MASK          0xFFFFFC00
#define YUVC_YUVC_UCOEF_B_RESERVED_SHIFT         10 
#define YUVC_YUVC_UCOEF_B_RESERVED_BIT           0x3FFFFF
#define YUVC_YUVC_UCOEF_B_RESERVED_BITWIDTH      22
// YUVC_VCOEF_RG Register
#define YUVC_YUVC_VCOEF_RG_OFS                   0x00000028
// cf_vcoef_g bitfiled (RW) Reset=1101001101
#define YUVC_YUVC_VCOEF_RG_CF_VCOEF_G_MASK       0x3FF
#define YUVC_YUVC_VCOEF_RG_CF_VCOEF_G_SHIFT      0 
#define YUVC_YUVC_VCOEF_RG_CF_VCOEF_G_BIT        0x3FF
#define YUVC_YUVC_VCOEF_RG_CF_VCOEF_G_BITWIDTH   10
// reserved2 bitfiled (RO) Reset=0
#define YUVC_YUVC_VCOEF_RG_RESERVED2_MASK        0xFC00
#define YUVC_YUVC_VCOEF_RG_RESERVED2_SHIFT       10 
#define YUVC_YUVC_VCOEF_RG_RESERVED2_BIT         0x3F
#define YUVC_YUVC_VCOEF_RG_RESERVED2_BITWIDTH    6
// cf_vcoef_r bitfiled (RW) Reset=101011111
#define YUVC_YUVC_VCOEF_RG_CF_VCOEF_R_MASK       0x3FF0000
#define YUVC_YUVC_VCOEF_RG_CF_VCOEF_R_SHIFT      16 
#define YUVC_YUVC_VCOEF_RG_CF_VCOEF_R_BIT        0x3FF
#define YUVC_YUVC_VCOEF_RG_CF_VCOEF_R_BITWIDTH   10
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_VCOEF_RG_RESERVED_MASK         0xFC000000
#define YUVC_YUVC_VCOEF_RG_RESERVED_SHIFT        26 
#define YUVC_YUVC_VCOEF_RG_RESERVED_BIT          0x3F
#define YUVC_YUVC_VCOEF_RG_RESERVED_BITWIDTH     6
// YUVC_VCOEF_B Register
#define YUVC_YUVC_VCOEF_B_OFS                    0x0000002C
// cf_vcoef_b bitfiled (RW) Reset=0
#define YUVC_YUVC_VCOEF_B_CF_VCOEF_B_MASK        0x3FF
#define YUVC_YUVC_VCOEF_B_CF_VCOEF_B_SHIFT       0 
#define YUVC_YUVC_VCOEF_B_CF_VCOEF_B_BIT         0x3FF
#define YUVC_YUVC_VCOEF_B_CF_VCOEF_B_BITWIDTH    10
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_VCOEF_B_RESERVED_MASK          0xFFFFFC00
#define YUVC_YUVC_VCOEF_B_RESERVED_SHIFT         10 
#define YUVC_YUVC_VCOEF_B_RESERVED_BIT           0x3FFFFF
#define YUVC_YUVC_VCOEF_B_RESERVED_BITWIDTH      22
// YUVC_OFFSET_RG Register
#define YUVC_YUVC_OFFSET_RG_OFS                  0x00000030
// cf_goffset bitfiled (RW) Reset=0
#define YUVC_YUVC_OFFSET_RG_CF_GOFFSET_MASK      0x1FF
#define YUVC_YUVC_OFFSET_RG_CF_GOFFSET_SHIFT     0 
#define YUVC_YUVC_OFFSET_RG_CF_GOFFSET_BIT       0x1FF
#define YUVC_YUVC_OFFSET_RG_CF_GOFFSET_BITWIDTH  9
// reserved2 bitfiled (RO) Reset=0
#define YUVC_YUVC_OFFSET_RG_RESERVED2_MASK       0xFE00
#define YUVC_YUVC_OFFSET_RG_RESERVED2_SHIFT      9 
#define YUVC_YUVC_OFFSET_RG_RESERVED2_BIT        0x7F
#define YUVC_YUVC_OFFSET_RG_RESERVED2_BITWIDTH   7
// cf_roffset bitfiled (RW) Reset=0
#define YUVC_YUVC_OFFSET_RG_CF_ROFFSET_MASK      0x1FF0000
#define YUVC_YUVC_OFFSET_RG_CF_ROFFSET_SHIFT     16 
#define YUVC_YUVC_OFFSET_RG_CF_ROFFSET_BIT       0x1FF
#define YUVC_YUVC_OFFSET_RG_CF_ROFFSET_BITWIDTH  9
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_OFFSET_RG_RESERVED_MASK        0xFE000000
#define YUVC_YUVC_OFFSET_RG_RESERVED_SHIFT       25 
#define YUVC_YUVC_OFFSET_RG_RESERVED_BIT         0x7F
#define YUVC_YUVC_OFFSET_RG_RESERVED_BITWIDTH    7
// YUVC_OFFSET_B Register
#define YUVC_YUVC_OFFSET_B_OFS                   0x00000034
// cf_boffset bitfiled (RW) Reset=0
#define YUVC_YUVC_OFFSET_B_CF_BOFFSET_MASK       0x1FF
#define YUVC_YUVC_OFFSET_B_CF_BOFFSET_SHIFT      0 
#define YUVC_YUVC_OFFSET_B_CF_BOFFSET_BIT        0x1FF
#define YUVC_YUVC_OFFSET_B_CF_BOFFSET_BITWIDTH   9
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_OFFSET_B_RESERVED_MASK         0xFFFFFE00
#define YUVC_YUVC_OFFSET_B_RESERVED_SHIFT        9 
#define YUVC_YUVC_OFFSET_B_RESERVED_BIT          0x7FFFFF
#define YUVC_YUVC_OFFSET_B_RESERVED_BITWIDTH     23
// YUVC_STADR Register
#define YUVC_YUVC_STADR_OFS                      0x00000100
// cf_mb_stadr bitfiled (RW) Reset=10000000000000000000000000000000
#define YUVC_YUVC_STADR_CF_MB_STADR_MASK         0xFFFFFFFF
#define YUVC_YUVC_STADR_CF_MB_STADR_SHIFT        0 
#define YUVC_YUVC_STADR_CF_MB_STADR_BIT          0xFFFFFFFF
#define YUVC_YUVC_STADR_CF_MB_STADR_BITWIDTH     32
// YUVC_ENDADR Register
#define YUVC_YUVC_ENDADR_OFS                     0x00000104
// cf_mb_endadr bitfiled (RW) Reset=10111111111111111111111111111111
#define YUVC_YUVC_ENDADR_CF_MB_ENDADR_MASK       0xFFFFFFFF
#define YUVC_YUVC_ENDADR_CF_MB_ENDADR_SHIFT      0 
#define YUVC_YUVC_ENDADR_CF_MB_ENDADR_BIT        0xFFFFFFFF
#define YUVC_YUVC_ENDADR_CF_MB_ENDADR_BITWIDTH   32
// YUVC_DMRADR Register
#define YUVC_YUVC_DMRADR_OFS                     0x00000118
// cf_dr_adr bitfiled (RW) Reset=0
#define YUVC_YUVC_DMRADR_CF_DR_ADR_MASK          0xFFFFFFFF
#define YUVC_YUVC_DMRADR_CF_DR_ADR_SHIFT         0 
#define YUVC_YUVC_DMRADR_CF_DR_ADR_BIT           0xFFFFFFFF
#define YUVC_YUVC_DMRADR_CF_DR_ADR_BITWIDTH      32
// YUVC_CFG Register
#define YUVC_YUVC_CFG_OFS                        0x0000011C
// cf_dr_enable_g00 bitfiled (RW) Reset=0
#define YUVC_YUVC_CFG_CF_DR_ENABLE_G00_MASK      0x1
#define YUVC_YUVC_CFG_CF_DR_ENABLE_G00_SHIFT     0 
#define YUVC_YUVC_CFG_CF_DR_ENABLE_G00_BIT       0x1
#define YUVC_YUVC_CFG_CF_DR_ENABLE_G00_BITWIDTH  1
// YUVC_INT_MASK Register
#define YUVC_YUVC_INT_MASK_OFS                   0x00000120
// cf_int_mask_g00 bitfiled (RW) Reset=0
#define YUVC_YUVC_INT_MASK_CF_INT_MASK_G00_MASK  0x1
#define YUVC_YUVC_INT_MASK_CF_INT_MASK_G00_SHIFT 0 
#define YUVC_YUVC_INT_MASK_CF_INT_MASK_G00_BIT   0x1
#define YUVC_YUVC_INT_MASK_CF_INT_MASK_G00_BITWIDTH 1
// reserved2 bitfiled (RO) Reset=0
#define YUVC_YUVC_INT_MASK_RESERVED2_MASK        0x7FFE
#define YUVC_YUVC_INT_MASK_RESERVED2_SHIFT       1 
#define YUVC_YUVC_INT_MASK_RESERVED2_BIT         0x3FFF
#define YUVC_YUVC_INT_MASK_RESERVED2_BITWIDTH    14
// cf_mb_err_mask bitfiled (RW) Reset=0
#define YUVC_YUVC_INT_MASK_CF_MB_ERR_MASK_MASK   0x8000
#define YUVC_YUVC_INT_MASK_CF_MB_ERR_MASK_SHIFT  15 
#define YUVC_YUVC_INT_MASK_CF_MB_ERR_MASK_BIT    0x1
#define YUVC_YUVC_INT_MASK_CF_MB_ERR_MASK_BITWIDTH 1
// cf_abort_mask_g00 bitfiled (RW) Reset=0
#define YUVC_YUVC_INT_MASK_CF_ABORT_MASK_G00_MASK 0x10000
#define YUVC_YUVC_INT_MASK_CF_ABORT_MASK_G00_SHIFT 16 
#define YUVC_YUVC_INT_MASK_CF_ABORT_MASK_G00_BIT 0x1
#define YUVC_YUVC_INT_MASK_CF_ABORT_MASK_G00_BITWIDTH 1
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_INT_MASK_RESERVED_MASK         0xFFFE0000
#define YUVC_YUVC_INT_MASK_RESERVED_SHIFT        17 
#define YUVC_YUVC_INT_MASK_RESERVED_BIT          0x7FFF
#define YUVC_YUVC_INT_MASK_RESERVED_BITWIDTH     15
// YUVC_W_ENABLE Register
#define YUVC_YUVC_W_ENABLE_OFS                   0x00000134
// cf_enable_w00 bitfiled (RW) Reset=0
#define YUVC_YUVC_W_ENABLE_CF_ENABLE_W00_MASK    0x1
#define YUVC_YUVC_W_ENABLE_CF_ENABLE_W00_SHIFT   0 
#define YUVC_YUVC_W_ENABLE_CF_ENABLE_W00_BIT     0x1
#define YUVC_YUVC_W_ENABLE_CF_ENABLE_W00_BITWIDTH 1
// cf_enable_w01 bitfiled (RW) Reset=0
#define YUVC_YUVC_W_ENABLE_CF_ENABLE_W01_MASK    0x2
#define YUVC_YUVC_W_ENABLE_CF_ENABLE_W01_SHIFT   1 
#define YUVC_YUVC_W_ENABLE_CF_ENABLE_W01_BIT     0x1
#define YUVC_YUVC_W_ENABLE_CF_ENABLE_W01_BITWIDTH 1
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_W_ENABLE_RESERVED_MASK         0xFFFFFFFC
#define YUVC_YUVC_W_ENABLE_RESERVED_SHIFT        2 
#define YUVC_YUVC_W_ENABLE_RESERVED_BIT          0x3FFFFFFF
#define YUVC_YUVC_W_ENABLE_RESERVED_BITWIDTH     30
// YUVC_W00_STADR Register
#define YUVC_YUVC_W00_STADR_OFS                  0x00000300
// cf_stadr_w00 bitfiled (RW) Reset=0
#define YUVC_YUVC_W00_STADR_CF_STADR_W00_MASK    0xFFFFFFFF
#define YUVC_YUVC_W00_STADR_CF_STADR_W00_SHIFT   0 
#define YUVC_YUVC_W00_STADR_CF_STADR_W00_BIT     0xFFFFFFFF
#define YUVC_YUVC_W00_STADR_CF_STADR_W00_BITWIDTH 32
// YUVC_W00_ENDADR Register
#define YUVC_YUVC_W00_ENDADR_OFS                 0x00000304
// cf_endadr_w00 bitfiled (RW) Reset=0
#define YUVC_YUVC_W00_ENDADR_CF_ENDADR_W00_MASK  0xFFFFFFFF
#define YUVC_YUVC_W00_ENDADR_CF_ENDADR_W00_SHIFT 0 
#define YUVC_YUVC_W00_ENDADR_CF_ENDADR_W00_BIT   0xFFFFFFFF
#define YUVC_YUVC_W00_ENDADR_CF_ENDADR_W00_BITWIDTH 32
// YUVC_W00_HEIGHT Register
#define YUVC_YUVC_W00_HEIGHT_OFS                 0x00000308
// cf_height_w00 bitfiled (RW) Reset=0
#define YUVC_YUVC_W00_HEIGHT_CF_HEIGHT_W00_MASK  0xFFF
#define YUVC_YUVC_W00_HEIGHT_CF_HEIGHT_W00_SHIFT 0 
#define YUVC_YUVC_W00_HEIGHT_CF_HEIGHT_W00_BIT   0xFFF
#define YUVC_YUVC_W00_HEIGHT_CF_HEIGHT_W00_BITWIDTH 12
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_W00_HEIGHT_RESERVED_MASK       0xFFFFF000
#define YUVC_YUVC_W00_HEIGHT_RESERVED_SHIFT      12 
#define YUVC_YUVC_W00_HEIGHT_RESERVED_BIT        0xFFFFF
#define YUVC_YUVC_W00_HEIGHT_RESERVED_BITWIDTH   20
// YUVC_W00_PITCH Register
#define YUVC_YUVC_W00_PITCH_OFS                  0x0000030C
// cf_pitch_w00 bitfiled (RW) Reset=0
#define YUVC_YUVC_W00_PITCH_CF_PITCH_W00_MASK    0xFFFF
#define YUVC_YUVC_W00_PITCH_CF_PITCH_W00_SHIFT   0 
#define YUVC_YUVC_W00_PITCH_CF_PITCH_W00_BIT     0xFFFF
#define YUVC_YUVC_W00_PITCH_CF_PITCH_W00_BITWIDTH 16
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_W00_PITCH_RESERVED_MASK        0xFFFF0000
#define YUVC_YUVC_W00_PITCH_RESERVED_SHIFT       16 
#define YUVC_YUVC_W00_PITCH_RESERVED_BIT         0xFFFF
#define YUVC_YUVC_W00_PITCH_RESERVED_BITWIDTH    16
// YUVC_W00_CFG0 Register
#define YUVC_YUVC_W00_CFG0_OFS                   0x00000310
// reserved4 bitfiled (RO) Reset=0
#define YUVC_YUVC_W00_CFG0_RESERVED4_MASK        0xFF
#define YUVC_YUVC_W00_CFG0_RESERVED4_SHIFT       0 
#define YUVC_YUVC_W00_CFG0_RESERVED4_BIT         0xFF
#define YUVC_YUVC_W00_CFG0_RESERVED4_BITWIDTH    8
// cf_datawidth_w00 bitfiled (RW) Reset=0
#define YUVC_YUVC_W00_CFG0_CF_DATAWIDTH_W00_MASK 0x300
#define YUVC_YUVC_W00_CFG0_CF_DATAWIDTH_W00_SHIFT 8 
#define YUVC_YUVC_W00_CFG0_CF_DATAWIDTH_W00_BIT  0x3
#define YUVC_YUVC_W00_CFG0_CF_DATAWIDTH_W00_BITWIDTH 2
// YUVC_W00_SRAM_BASE Register
#define YUVC_YUVC_W00_SRAM_BASE_OFS              0x00000318
// cf_sram_base_w00 bitfiled (RW) Reset=0
#define YUVC_YUVC_W00_SRAM_BASE_CF_SRAM_BASE_W00_MASK 0x3F
#define YUVC_YUVC_W00_SRAM_BASE_CF_SRAM_BASE_W00_SHIFT 0 
#define YUVC_YUVC_W00_SRAM_BASE_CF_SRAM_BASE_W00_BIT 0x3F
#define YUVC_YUVC_W00_SRAM_BASE_CF_SRAM_BASE_W00_BITWIDTH 6
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_W00_SRAM_BASE_RESERVED_MASK    0xFFFFFFC0
#define YUVC_YUVC_W00_SRAM_BASE_RESERVED_SHIFT   6 
#define YUVC_YUVC_W00_SRAM_BASE_RESERVED_BIT     0x3FFFFFF
#define YUVC_YUVC_W00_SRAM_BASE_RESERVED_BITWIDTH 26
// YUVC_W00_SRAM_SIZE Register
#define YUVC_YUVC_W00_SRAM_SIZE_OFS              0x0000031C
// cf_sram_size_w00 bitfiled (RW) Reset=0
#define YUVC_YUVC_W00_SRAM_SIZE_CF_SRAM_SIZE_W00_MASK 0x3F
#define YUVC_YUVC_W00_SRAM_SIZE_CF_SRAM_SIZE_W00_SHIFT 0 
#define YUVC_YUVC_W00_SRAM_SIZE_CF_SRAM_SIZE_W00_BIT 0x3F
#define YUVC_YUVC_W00_SRAM_SIZE_CF_SRAM_SIZE_W00_BITWIDTH 6
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_W00_SRAM_SIZE_RESERVED_MASK    0xFFFFFFC0
#define YUVC_YUVC_W00_SRAM_SIZE_RESERVED_SHIFT   6 
#define YUVC_YUVC_W00_SRAM_SIZE_RESERVED_BIT     0x3FFFFFF
#define YUVC_YUVC_W00_SRAM_SIZE_RESERVED_BITWIDTH 26
// YUVC_W00_INTL Register
#define YUVC_YUVC_W00_INTL_OFS                   0x00000320
// cf_interval_w00 bitfiled (RW) Reset=0
#define YUVC_YUVC_W00_INTL_CF_INTERVAL_W00_MASK  0x3F
#define YUVC_YUVC_W00_INTL_CF_INTERVAL_W00_SHIFT 0 
#define YUVC_YUVC_W00_INTL_CF_INTERVAL_W00_BIT   0x3F
#define YUVC_YUVC_W00_INTL_CF_INTERVAL_W00_BITWIDTH 6
// cf_init_interval_w00 bitfiled (RW) Reset=0
#define YUVC_YUVC_W00_INTL_CF_INIT_INTERVAL_W00_MASK 0xFC0
#define YUVC_YUVC_W00_INTL_CF_INIT_INTERVAL_W00_SHIFT 6 
#define YUVC_YUVC_W00_INTL_CF_INIT_INTERVAL_W00_BIT 0x3F
#define YUVC_YUVC_W00_INTL_CF_INIT_INTERVAL_W00_BITWIDTH 6
// reserved2 bitfiled (RO) Reset=0
#define YUVC_YUVC_W00_INTL_RESERVED2_MASK        0xF000
#define YUVC_YUVC_W00_INTL_RESERVED2_SHIFT       12 
#define YUVC_YUVC_W00_INTL_RESERVED2_BIT         0xF
#define YUVC_YUVC_W00_INTL_RESERVED2_BITWIDTH    4
// cf_init_interval_period_w00 bitfiled (RW) Reset=0
#define YUVC_YUVC_W00_INTL_CF_INIT_INTERVAL_PERIOD_W00_MASK 0xFF0000
#define YUVC_YUVC_W00_INTL_CF_INIT_INTERVAL_PERIOD_W00_SHIFT 16 
#define YUVC_YUVC_W00_INTL_CF_INIT_INTERVAL_PERIOD_W00_BIT 0xFF
#define YUVC_YUVC_W00_INTL_CF_INIT_INTERVAL_PERIOD_W00_BITWIDTH 8
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_W00_INTL_RESERVED_MASK         0xFF000000
#define YUVC_YUVC_W00_INTL_RESERVED_SHIFT        24 
#define YUVC_YUVC_W00_INTL_RESERVED_BIT          0xFF
#define YUVC_YUVC_W00_INTL_RESERVED_BITWIDTH     8
// YUVC_W01_STADR Register
#define YUVC_YUVC_W01_STADR_OFS                  0x00000340
// cf_stadr_w01 bitfiled (RW) Reset=0
#define YUVC_YUVC_W01_STADR_CF_STADR_W01_MASK    0xFFFFFFFF
#define YUVC_YUVC_W01_STADR_CF_STADR_W01_SHIFT   0 
#define YUVC_YUVC_W01_STADR_CF_STADR_W01_BIT     0xFFFFFFFF
#define YUVC_YUVC_W01_STADR_CF_STADR_W01_BITWIDTH 32
// YUVC_W01_ENDADR Register
#define YUVC_YUVC_W01_ENDADR_OFS                 0x00000344
// cf_endadr_w01 bitfiled (RW) Reset=0
#define YUVC_YUVC_W01_ENDADR_CF_ENDADR_W01_MASK  0xFFFFFFFF
#define YUVC_YUVC_W01_ENDADR_CF_ENDADR_W01_SHIFT 0 
#define YUVC_YUVC_W01_ENDADR_CF_ENDADR_W01_BIT   0xFFFFFFFF
#define YUVC_YUVC_W01_ENDADR_CF_ENDADR_W01_BITWIDTH 32
// YUVC_W01_HEIGHT Register
#define YUVC_YUVC_W01_HEIGHT_OFS                 0x00000348
// cf_height_w01 bitfiled (RW) Reset=0
#define YUVC_YUVC_W01_HEIGHT_CF_HEIGHT_W01_MASK  0xFFF
#define YUVC_YUVC_W01_HEIGHT_CF_HEIGHT_W01_SHIFT 0 
#define YUVC_YUVC_W01_HEIGHT_CF_HEIGHT_W01_BIT   0xFFF
#define YUVC_YUVC_W01_HEIGHT_CF_HEIGHT_W01_BITWIDTH 12
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_W01_HEIGHT_RESERVED_MASK       0xFFFFF000
#define YUVC_YUVC_W01_HEIGHT_RESERVED_SHIFT      12 
#define YUVC_YUVC_W01_HEIGHT_RESERVED_BIT        0xFFFFF
#define YUVC_YUVC_W01_HEIGHT_RESERVED_BITWIDTH   20
// YUVC_W01_PITCH Register
#define YUVC_YUVC_W01_PITCH_OFS                  0x0000034C
// cf_pitch_w01 bitfiled (RW) Reset=0
#define YUVC_YUVC_W01_PITCH_CF_PITCH_W01_MASK    0xFFFF
#define YUVC_YUVC_W01_PITCH_CF_PITCH_W01_SHIFT   0 
#define YUVC_YUVC_W01_PITCH_CF_PITCH_W01_BIT     0xFFFF
#define YUVC_YUVC_W01_PITCH_CF_PITCH_W01_BITWIDTH 16
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_W01_PITCH_RESERVED_MASK        0xFFFF0000
#define YUVC_YUVC_W01_PITCH_RESERVED_SHIFT       16 
#define YUVC_YUVC_W01_PITCH_RESERVED_BIT         0xFFFF
#define YUVC_YUVC_W01_PITCH_RESERVED_BITWIDTH    16
// YUVC_W01_CFG0 Register
#define YUVC_YUVC_W01_CFG0_OFS                   0x00000350
// reserved4 bitfiled (RO) Reset=0
#define YUVC_YUVC_W01_CFG0_RESERVED4_MASK        0xFF
#define YUVC_YUVC_W01_CFG0_RESERVED4_SHIFT       0 
#define YUVC_YUVC_W01_CFG0_RESERVED4_BIT         0xFF
#define YUVC_YUVC_W01_CFG0_RESERVED4_BITWIDTH    8
// cf_datawidth_w01 bitfiled (RW) Reset=0
#define YUVC_YUVC_W01_CFG0_CF_DATAWIDTH_W01_MASK 0x300
#define YUVC_YUVC_W01_CFG0_CF_DATAWIDTH_W01_SHIFT 8 
#define YUVC_YUVC_W01_CFG0_CF_DATAWIDTH_W01_BIT  0x3
#define YUVC_YUVC_W01_CFG0_CF_DATAWIDTH_W01_BITWIDTH 2
// YUVC_W01_CFG1 Register
#define YUVC_YUVC_W01_CFG1_OFS                   0x00000354
// cf_maskbyte_w01 bitfiled (RW) Reset=0
#define YUVC_YUVC_W01_CFG1_CF_MASKBYTE_W01_MASK  0x7
#define YUVC_YUVC_W01_CFG1_CF_MASKBYTE_W01_SHIFT 0 
#define YUVC_YUVC_W01_CFG1_CF_MASKBYTE_W01_BIT   0x7
#define YUVC_YUVC_W01_CFG1_CF_MASKBYTE_W01_BITWIDTH 3
// reserved2 bitfiled (RO) Reset=0
#define YUVC_YUVC_W01_CFG1_RESERVED2_MASK        0xFFF8
#define YUVC_YUVC_W01_CFG1_RESERVED2_SHIFT       3 
#define YUVC_YUVC_W01_CFG1_RESERVED2_BIT         0x1FFF
#define YUVC_YUVC_W01_CFG1_RESERVED2_BITWIDTH    13
// cf_endian_w01 bitfiled (RW) Reset=1
#define YUVC_YUVC_W01_CFG1_CF_ENDIAN_W01_MASK    0x10000
#define YUVC_YUVC_W01_CFG1_CF_ENDIAN_W01_SHIFT   16 
#define YUVC_YUVC_W01_CFG1_CF_ENDIAN_W01_BIT     0x1
#define YUVC_YUVC_W01_CFG1_CF_ENDIAN_W01_BITWIDTH 1
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_W01_CFG1_RESERVED_MASK         0xFFFE0000
#define YUVC_YUVC_W01_CFG1_RESERVED_SHIFT        17 
#define YUVC_YUVC_W01_CFG1_RESERVED_BIT          0x7FFF
#define YUVC_YUVC_W01_CFG1_RESERVED_BITWIDTH     15
// YUVC_W01_SRAM_BASE Register
#define YUVC_YUVC_W01_SRAM_BASE_OFS              0x00000358
// cf_sram_base_w01 bitfiled (RW) Reset=0
#define YUVC_YUVC_W01_SRAM_BASE_CF_SRAM_BASE_W01_MASK 0x3F
#define YUVC_YUVC_W01_SRAM_BASE_CF_SRAM_BASE_W01_SHIFT 0 
#define YUVC_YUVC_W01_SRAM_BASE_CF_SRAM_BASE_W01_BIT 0x3F
#define YUVC_YUVC_W01_SRAM_BASE_CF_SRAM_BASE_W01_BITWIDTH 6
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_W01_SRAM_BASE_RESERVED_MASK    0xFFFFFFC0
#define YUVC_YUVC_W01_SRAM_BASE_RESERVED_SHIFT   6 
#define YUVC_YUVC_W01_SRAM_BASE_RESERVED_BIT     0x3FFFFFF
#define YUVC_YUVC_W01_SRAM_BASE_RESERVED_BITWIDTH 26
// YUVC_W01_SRAM_SIZE Register
#define YUVC_YUVC_W01_SRAM_SIZE_OFS              0x0000035C
// cf_sram_size_w01 bitfiled (RW) Reset=0
#define YUVC_YUVC_W01_SRAM_SIZE_CF_SRAM_SIZE_W01_MASK 0x3F
#define YUVC_YUVC_W01_SRAM_SIZE_CF_SRAM_SIZE_W01_SHIFT 0 
#define YUVC_YUVC_W01_SRAM_SIZE_CF_SRAM_SIZE_W01_BIT 0x3F
#define YUVC_YUVC_W01_SRAM_SIZE_CF_SRAM_SIZE_W01_BITWIDTH 6
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_W01_SRAM_SIZE_RESERVED_MASK    0xFFFFFFC0
#define YUVC_YUVC_W01_SRAM_SIZE_RESERVED_SHIFT   6 
#define YUVC_YUVC_W01_SRAM_SIZE_RESERVED_BIT     0x3FFFFFF
#define YUVC_YUVC_W01_SRAM_SIZE_RESERVED_BITWIDTH 26
// YUVC_W01_INTL Register
#define YUVC_YUVC_W01_INTL_OFS                   0x00000360
// cf_interval_w01 bitfiled (RW) Reset=0
#define YUVC_YUVC_W01_INTL_CF_INTERVAL_W01_MASK  0x3F
#define YUVC_YUVC_W01_INTL_CF_INTERVAL_W01_SHIFT 0 
#define YUVC_YUVC_W01_INTL_CF_INTERVAL_W01_BIT   0x3F
#define YUVC_YUVC_W01_INTL_CF_INTERVAL_W01_BITWIDTH 6
// cf_init_interval_w01 bitfiled (RW) Reset=0
#define YUVC_YUVC_W01_INTL_CF_INIT_INTERVAL_W01_MASK 0xFC0
#define YUVC_YUVC_W01_INTL_CF_INIT_INTERVAL_W01_SHIFT 6 
#define YUVC_YUVC_W01_INTL_CF_INIT_INTERVAL_W01_BIT 0x3F
#define YUVC_YUVC_W01_INTL_CF_INIT_INTERVAL_W01_BITWIDTH 6
// reserved2 bitfiled (RO) Reset=0
#define YUVC_YUVC_W01_INTL_RESERVED2_MASK        0xF000
#define YUVC_YUVC_W01_INTL_RESERVED2_SHIFT       12 
#define YUVC_YUVC_W01_INTL_RESERVED2_BIT         0xF
#define YUVC_YUVC_W01_INTL_RESERVED2_BITWIDTH    4
// cf_init_interval_period_w01 bitfiled (RW) Reset=0
#define YUVC_YUVC_W01_INTL_CF_INIT_INTERVAL_PERIOD_W01_MASK 0xFF0000
#define YUVC_YUVC_W01_INTL_CF_INIT_INTERVAL_PERIOD_W01_SHIFT 16 
#define YUVC_YUVC_W01_INTL_CF_INIT_INTERVAL_PERIOD_W01_BIT 0xFF
#define YUVC_YUVC_W01_INTL_CF_INIT_INTERVAL_PERIOD_W01_BITWIDTH 8
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_W01_INTL_RESERVED_MASK         0xFF000000
#define YUVC_YUVC_W01_INTL_RESERVED_SHIFT        24 
#define YUVC_YUVC_W01_INTL_RESERVED_BIT          0xFF
#define YUVC_YUVC_W01_INTL_RESERVED_BITWIDTH     8
// YUVC_MODE_BUF Register
#define YUVC_YUVC_MODE_BUF_OFS                   0x00000800
// cf_inmode bitfiled (RO) Reset=0
#define YUVC_YUVC_MODE_BUF_CF_INMODE_MASK        0x3
#define YUVC_YUVC_MODE_BUF_CF_INMODE_SHIFT       0 
#define YUVC_YUVC_MODE_BUF_CF_INMODE_BIT         0x3
#define YUVC_YUVC_MODE_BUF_CF_INMODE_BITWIDTH    2
// reserved4 bitfiled (RO) Reset=0
#define YUVC_YUVC_MODE_BUF_RESERVED4_MASK        0xC
#define YUVC_YUVC_MODE_BUF_RESERVED4_SHIFT       2 
#define YUVC_YUVC_MODE_BUF_RESERVED4_BIT         0x3
#define YUVC_YUVC_MODE_BUF_RESERVED4_BITWIDTH    2
// cf_outmode bitfiled (RO) Reset=0
#define YUVC_YUVC_MODE_BUF_CF_OUTMODE_MASK       0x30
#define YUVC_YUVC_MODE_BUF_CF_OUTMODE_SHIFT      4 
#define YUVC_YUVC_MODE_BUF_CF_OUTMODE_BIT        0x3
#define YUVC_YUVC_MODE_BUF_CF_OUTMODE_BITWIDTH   2
// reserved3 bitfiled (RO) Reset=0
#define YUVC_YUVC_MODE_BUF_RESERVED3_MASK        0xC0
#define YUVC_YUVC_MODE_BUF_RESERVED3_SHIFT       6 
#define YUVC_YUVC_MODE_BUF_RESERVED3_BIT         0x3
#define YUVC_YUVC_MODE_BUF_RESERVED3_BITWIDTH    2
// cf_rgblimit bitfiled (RO) Reset=0
#define YUVC_YUVC_MODE_BUF_CF_RGBLIMIT_MASK      0x100
#define YUVC_YUVC_MODE_BUF_CF_RGBLIMIT_SHIFT     8 
#define YUVC_YUVC_MODE_BUF_CF_RGBLIMIT_BIT       0x1
#define YUVC_YUVC_MODE_BUF_CF_RGBLIMIT_BITWIDTH  1
// reserved2 bitfiled (RO) Reset=0
#define YUVC_YUVC_MODE_BUF_RESERVED2_MASK        0xFE00
#define YUVC_YUVC_MODE_BUF_RESERVED2_SHIFT       9 
#define YUVC_YUVC_MODE_BUF_RESERVED2_BIT         0x7F
#define YUVC_YUVC_MODE_BUF_RESERVED2_BITWIDTH    7
// cf_alpha bitfiled (RO) Reset=0
#define YUVC_YUVC_MODE_BUF_CF_ALPHA_MASK         0xFF0000
#define YUVC_YUVC_MODE_BUF_CF_ALPHA_SHIFT        16 
#define YUVC_YUVC_MODE_BUF_CF_ALPHA_BIT          0xFF
#define YUVC_YUVC_MODE_BUF_CF_ALPHA_BITWIDTH     8
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_MODE_BUF_RESERVED_MASK         0xFF000000
#define YUVC_YUVC_MODE_BUF_RESERVED_SHIFT        24 
#define YUVC_YUVC_MODE_BUF_RESERVED_BIT          0xFF
#define YUVC_YUVC_MODE_BUF_RESERVED_BITWIDTH     8
// YUVC_SIZE_BUF Register
#define YUVC_YUVC_SIZE_BUF_OFS                   0x00000804
// cf_hsize bitfiled (RO) Reset=0
#define YUVC_YUVC_SIZE_BUF_CF_HSIZE_MASK         0x7FF
#define YUVC_YUVC_SIZE_BUF_CF_HSIZE_SHIFT        0 
#define YUVC_YUVC_SIZE_BUF_CF_HSIZE_BIT          0x7FF
#define YUVC_YUVC_SIZE_BUF_CF_HSIZE_BITWIDTH     11
// reserved2 bitfiled (RO) Reset=0
#define YUVC_YUVC_SIZE_BUF_RESERVED2_MASK        0xF800
#define YUVC_YUVC_SIZE_BUF_RESERVED2_SHIFT       11 
#define YUVC_YUVC_SIZE_BUF_RESERVED2_BIT         0x1F
#define YUVC_YUVC_SIZE_BUF_RESERVED2_BITWIDTH    5
// cf_vsize bitfiled (RO) Reset=0
#define YUVC_YUVC_SIZE_BUF_CF_VSIZE_MASK         0x7FF0000
#define YUVC_YUVC_SIZE_BUF_CF_VSIZE_SHIFT        16 
#define YUVC_YUVC_SIZE_BUF_CF_VSIZE_BIT          0x7FF
#define YUVC_YUVC_SIZE_BUF_CF_VSIZE_BITWIDTH     11
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_SIZE_BUF_RESERVED_MASK         0xF8000000
#define YUVC_YUVC_SIZE_BUF_RESERVED_SHIFT        27 
#define YUVC_YUVC_SIZE_BUF_RESERVED_BIT          0x1F
#define YUVC_YUVC_SIZE_BUF_RESERVED_BITWIDTH     5
// YUVC_OFFSET_Y_BUF Register
#define YUVC_YUVC_OFFSET_Y_BUF_OFS               0x00000808
// cf_yoffset bitfiled (RO) Reset=0
#define YUVC_YUVC_OFFSET_Y_BUF_CF_YOFFSET_MASK   0x1FF
#define YUVC_YUVC_OFFSET_Y_BUF_CF_YOFFSET_SHIFT  0 
#define YUVC_YUVC_OFFSET_Y_BUF_CF_YOFFSET_BIT    0x1FF
#define YUVC_YUVC_OFFSET_Y_BUF_CF_YOFFSET_BITWIDTH 9
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_OFFSET_Y_BUF_RESERVED_MASK     0xFFFFFE00
#define YUVC_YUVC_OFFSET_Y_BUF_RESERVED_SHIFT    9 
#define YUVC_YUVC_OFFSET_Y_BUF_RESERVED_BIT      0x7FFFFF
#define YUVC_YUVC_OFFSET_Y_BUF_RESERVED_BITWIDTH 23
// YUVC_OFFSET_UV_BUF Register
#define YUVC_YUVC_OFFSET_UV_BUF_OFS              0x0000080C
// cf_voffset bitfiled (RO) Reset=0
#define YUVC_YUVC_OFFSET_UV_BUF_CF_VOFFSET_MASK  0x1FF
#define YUVC_YUVC_OFFSET_UV_BUF_CF_VOFFSET_SHIFT 0 
#define YUVC_YUVC_OFFSET_UV_BUF_CF_VOFFSET_BIT   0x1FF
#define YUVC_YUVC_OFFSET_UV_BUF_CF_VOFFSET_BITWIDTH 9
// reserved2 bitfiled (RO) Reset=0
#define YUVC_YUVC_OFFSET_UV_BUF_RESERVED2_MASK   0xFE00
#define YUVC_YUVC_OFFSET_UV_BUF_RESERVED2_SHIFT  9 
#define YUVC_YUVC_OFFSET_UV_BUF_RESERVED2_BIT    0x7F
#define YUVC_YUVC_OFFSET_UV_BUF_RESERVED2_BITWIDTH 7
// cf_uoffset bitfiled (RO) Reset=0
#define YUVC_YUVC_OFFSET_UV_BUF_CF_UOFFSET_MASK  0x1FF0000
#define YUVC_YUVC_OFFSET_UV_BUF_CF_UOFFSET_SHIFT 16 
#define YUVC_YUVC_OFFSET_UV_BUF_CF_UOFFSET_BIT   0x1FF
#define YUVC_YUVC_OFFSET_UV_BUF_CF_UOFFSET_BITWIDTH 9
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_OFFSET_UV_BUF_RESERVED_MASK    0xFE000000
#define YUVC_YUVC_OFFSET_UV_BUF_RESERVED_SHIFT   25 
#define YUVC_YUVC_OFFSET_UV_BUF_RESERVED_BIT     0x7F
#define YUVC_YUVC_OFFSET_UV_BUF_RESERVED_BITWIDTH 7
// YUVC_YCOEF_RG_BUF Register
#define YUVC_YUVC_YCOEF_RG_BUF_OFS               0x00000810
// cf_ycoef_g bitfiled (RO) Reset=0
#define YUVC_YUVC_YCOEF_RG_BUF_CF_YCOEF_G_MASK   0x1FF
#define YUVC_YUVC_YCOEF_RG_BUF_CF_YCOEF_G_SHIFT  0 
#define YUVC_YUVC_YCOEF_RG_BUF_CF_YCOEF_G_BIT    0x1FF
#define YUVC_YUVC_YCOEF_RG_BUF_CF_YCOEF_G_BITWIDTH 9
// reserved2 bitfiled (RO) Reset=0
#define YUVC_YUVC_YCOEF_RG_BUF_RESERVED2_MASK    0xFE00
#define YUVC_YUVC_YCOEF_RG_BUF_RESERVED2_SHIFT   9 
#define YUVC_YUVC_YCOEF_RG_BUF_RESERVED2_BIT     0x7F
#define YUVC_YUVC_YCOEF_RG_BUF_RESERVED2_BITWIDTH 7
// cf_ycoef_r bitfiled (RO) Reset=0
#define YUVC_YUVC_YCOEF_RG_BUF_CF_YCOEF_R_MASK   0x1FF0000
#define YUVC_YUVC_YCOEF_RG_BUF_CF_YCOEF_R_SHIFT  16 
#define YUVC_YUVC_YCOEF_RG_BUF_CF_YCOEF_R_BIT    0x1FF
#define YUVC_YUVC_YCOEF_RG_BUF_CF_YCOEF_R_BITWIDTH 9
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_YCOEF_RG_BUF_RESERVED_MASK     0xFE000000
#define YUVC_YUVC_YCOEF_RG_BUF_RESERVED_SHIFT    25 
#define YUVC_YUVC_YCOEF_RG_BUF_RESERVED_BIT      0x7F
#define YUVC_YUVC_YCOEF_RG_BUF_RESERVED_BITWIDTH 7
// YUVC_YCOEF_B_BUF Register
#define YUVC_YUVC_YCOEF_B_BUF_OFS                0x00000814
// cf_ycoef_b bitfiled (RO) Reset=0
#define YUVC_YUVC_YCOEF_B_BUF_CF_YCOEF_B_MASK    0x1FF
#define YUVC_YUVC_YCOEF_B_BUF_CF_YCOEF_B_SHIFT   0 
#define YUVC_YUVC_YCOEF_B_BUF_CF_YCOEF_B_BIT     0x1FF
#define YUVC_YUVC_YCOEF_B_BUF_CF_YCOEF_B_BITWIDTH 9
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_YCOEF_B_BUF_RESERVED_MASK      0xFFFFFE00
#define YUVC_YUVC_YCOEF_B_BUF_RESERVED_SHIFT     9 
#define YUVC_YUVC_YCOEF_B_BUF_RESERVED_BIT       0x7FFFFF
#define YUVC_YUVC_YCOEF_B_BUF_RESERVED_BITWIDTH  23
// YUVC_UCOEF_RG_BUF Register
#define YUVC_YUVC_UCOEF_RG_BUF_OFS               0x00000818
// cf_ucoef_g bitfiled (RO) Reset=0
#define YUVC_YUVC_UCOEF_RG_BUF_CF_UCOEF_G_MASK   0x3FF
#define YUVC_YUVC_UCOEF_RG_BUF_CF_UCOEF_G_SHIFT  0 
#define YUVC_YUVC_UCOEF_RG_BUF_CF_UCOEF_G_BIT    0x3FF
#define YUVC_YUVC_UCOEF_RG_BUF_CF_UCOEF_G_BITWIDTH 10
// reserved2 bitfiled (RO) Reset=0
#define YUVC_YUVC_UCOEF_RG_BUF_RESERVED2_MASK    0xFC00
#define YUVC_YUVC_UCOEF_RG_BUF_RESERVED2_SHIFT   10 
#define YUVC_YUVC_UCOEF_RG_BUF_RESERVED2_BIT     0x3F
#define YUVC_YUVC_UCOEF_RG_BUF_RESERVED2_BITWIDTH 6
// cf_ucoef_r bitfiled (RO) Reset=0
#define YUVC_YUVC_UCOEF_RG_BUF_CF_UCOEF_R_MASK   0x3FF0000
#define YUVC_YUVC_UCOEF_RG_BUF_CF_UCOEF_R_SHIFT  16 
#define YUVC_YUVC_UCOEF_RG_BUF_CF_UCOEF_R_BIT    0x3FF
#define YUVC_YUVC_UCOEF_RG_BUF_CF_UCOEF_R_BITWIDTH 10
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_UCOEF_RG_BUF_RESERVED_MASK     0xFC000000
#define YUVC_YUVC_UCOEF_RG_BUF_RESERVED_SHIFT    26 
#define YUVC_YUVC_UCOEF_RG_BUF_RESERVED_BIT      0x3F
#define YUVC_YUVC_UCOEF_RG_BUF_RESERVED_BITWIDTH 6
// YUVC_UCOEF_B_BUF Register
#define YUVC_YUVC_UCOEF_B_BUF_OFS                0x0000081C
// cf_ucoef_b bitfiled (RO) Reset=0
#define YUVC_YUVC_UCOEF_B_BUF_CF_UCOEF_B_MASK    0x3FF
#define YUVC_YUVC_UCOEF_B_BUF_CF_UCOEF_B_SHIFT   0 
#define YUVC_YUVC_UCOEF_B_BUF_CF_UCOEF_B_BIT     0x3FF
#define YUVC_YUVC_UCOEF_B_BUF_CF_UCOEF_B_BITWIDTH 10
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_UCOEF_B_BUF_RESERVED_MASK      0xFFFFFC00
#define YUVC_YUVC_UCOEF_B_BUF_RESERVED_SHIFT     10 
#define YUVC_YUVC_UCOEF_B_BUF_RESERVED_BIT       0x3FFFFF
#define YUVC_YUVC_UCOEF_B_BUF_RESERVED_BITWIDTH  22
// YUVC_VCOEF_RG_BUF Register
#define YUVC_YUVC_VCOEF_RG_BUF_OFS               0x00000820
// cf_vcoef_g bitfiled (RO) Reset=0
#define YUVC_YUVC_VCOEF_RG_BUF_CF_VCOEF_G_MASK   0x3FF
#define YUVC_YUVC_VCOEF_RG_BUF_CF_VCOEF_G_SHIFT  0 
#define YUVC_YUVC_VCOEF_RG_BUF_CF_VCOEF_G_BIT    0x3FF
#define YUVC_YUVC_VCOEF_RG_BUF_CF_VCOEF_G_BITWIDTH 10
// reserved2 bitfiled (RO) Reset=0
#define YUVC_YUVC_VCOEF_RG_BUF_RESERVED2_MASK    0xFC00
#define YUVC_YUVC_VCOEF_RG_BUF_RESERVED2_SHIFT   10 
#define YUVC_YUVC_VCOEF_RG_BUF_RESERVED2_BIT     0x3F
#define YUVC_YUVC_VCOEF_RG_BUF_RESERVED2_BITWIDTH 6
// cf_vcoef_r bitfiled (RO) Reset=0
#define YUVC_YUVC_VCOEF_RG_BUF_CF_VCOEF_R_MASK   0x3FF0000
#define YUVC_YUVC_VCOEF_RG_BUF_CF_VCOEF_R_SHIFT  16 
#define YUVC_YUVC_VCOEF_RG_BUF_CF_VCOEF_R_BIT    0x3FF
#define YUVC_YUVC_VCOEF_RG_BUF_CF_VCOEF_R_BITWIDTH 10
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_VCOEF_RG_BUF_RESERVED_MASK     0xFC000000
#define YUVC_YUVC_VCOEF_RG_BUF_RESERVED_SHIFT    26 
#define YUVC_YUVC_VCOEF_RG_BUF_RESERVED_BIT      0x3F
#define YUVC_YUVC_VCOEF_RG_BUF_RESERVED_BITWIDTH 6
// YUVC_VCOEF_B_BUF Register
#define YUVC_YUVC_VCOEF_B_BUF_OFS                0x00000824
// cf_vcoef_b bitfiled (RO) Reset=0
#define YUVC_YUVC_VCOEF_B_BUF_CF_VCOEF_B_MASK    0x3FF
#define YUVC_YUVC_VCOEF_B_BUF_CF_VCOEF_B_SHIFT   0 
#define YUVC_YUVC_VCOEF_B_BUF_CF_VCOEF_B_BIT     0x3FF
#define YUVC_YUVC_VCOEF_B_BUF_CF_VCOEF_B_BITWIDTH 10
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_VCOEF_B_BUF_RESERVED_MASK      0xFFFFFC00
#define YUVC_YUVC_VCOEF_B_BUF_RESERVED_SHIFT     10 
#define YUVC_YUVC_VCOEF_B_BUF_RESERVED_BIT       0x3FFFFF
#define YUVC_YUVC_VCOEF_B_BUF_RESERVED_BITWIDTH  22
// YUVC_OFFSET_RG_BUF Register
#define YUVC_YUVC_OFFSET_RG_BUF_OFS              0x00000828
// cf_goffset bitfiled (RO) Reset=0
#define YUVC_YUVC_OFFSET_RG_BUF_CF_GOFFSET_MASK  0x1FF
#define YUVC_YUVC_OFFSET_RG_BUF_CF_GOFFSET_SHIFT 0 
#define YUVC_YUVC_OFFSET_RG_BUF_CF_GOFFSET_BIT   0x1FF
#define YUVC_YUVC_OFFSET_RG_BUF_CF_GOFFSET_BITWIDTH 9
// reserved2 bitfiled (RO) Reset=0
#define YUVC_YUVC_OFFSET_RG_BUF_RESERVED2_MASK   0xFE00
#define YUVC_YUVC_OFFSET_RG_BUF_RESERVED2_SHIFT  9 
#define YUVC_YUVC_OFFSET_RG_BUF_RESERVED2_BIT    0x7F
#define YUVC_YUVC_OFFSET_RG_BUF_RESERVED2_BITWIDTH 7
// cf_roffset bitfiled (RO) Reset=0
#define YUVC_YUVC_OFFSET_RG_BUF_CF_ROFFSET_MASK  0x1FF0000
#define YUVC_YUVC_OFFSET_RG_BUF_CF_ROFFSET_SHIFT 16 
#define YUVC_YUVC_OFFSET_RG_BUF_CF_ROFFSET_BIT   0x1FF
#define YUVC_YUVC_OFFSET_RG_BUF_CF_ROFFSET_BITWIDTH 9
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_OFFSET_RG_BUF_RESERVED_MASK    0xFE000000
#define YUVC_YUVC_OFFSET_RG_BUF_RESERVED_SHIFT   25 
#define YUVC_YUVC_OFFSET_RG_BUF_RESERVED_BIT     0x7F
#define YUVC_YUVC_OFFSET_RG_BUF_RESERVED_BITWIDTH 7
// YUVC_OFFSET_B_BUF Register
#define YUVC_YUVC_OFFSET_B_BUF_OFS               0x0000082C
// cf_boffset bitfiled (RO) Reset=0
#define YUVC_YUVC_OFFSET_B_BUF_CF_BOFFSET_MASK   0x1FF
#define YUVC_YUVC_OFFSET_B_BUF_CF_BOFFSET_SHIFT  0 
#define YUVC_YUVC_OFFSET_B_BUF_CF_BOFFSET_BIT    0x1FF
#define YUVC_YUVC_OFFSET_B_BUF_CF_BOFFSET_BITWIDTH 9
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_OFFSET_B_BUF_RESERVED_MASK     0xFFFFFE00
#define YUVC_YUVC_OFFSET_B_BUF_RESERVED_SHIFT    9 
#define YUVC_YUVC_OFFSET_B_BUF_RESERVED_BIT      0x7FFFFF
#define YUVC_YUVC_OFFSET_B_BUF_RESERVED_BITWIDTH 23
// YUVC_W_ENABLE_BUF Register
#define YUVC_YUVC_W_ENABLE_BUF_OFS               0x00000904
// cf_enable_w00 bitfiled (RO) Reset=0
#define YUVC_YUVC_W_ENABLE_BUF_CF_ENABLE_W00_MASK 0x1
#define YUVC_YUVC_W_ENABLE_BUF_CF_ENABLE_W00_SHIFT 0 
#define YUVC_YUVC_W_ENABLE_BUF_CF_ENABLE_W00_BIT 0x1
#define YUVC_YUVC_W_ENABLE_BUF_CF_ENABLE_W00_BITWIDTH 1
// cf_enable_w01 bitfiled (RO) Reset=0
#define YUVC_YUVC_W_ENABLE_BUF_CF_ENABLE_W01_MASK 0x2
#define YUVC_YUVC_W_ENABLE_BUF_CF_ENABLE_W01_SHIFT 1 
#define YUVC_YUVC_W_ENABLE_BUF_CF_ENABLE_W01_BIT 0x1
#define YUVC_YUVC_W_ENABLE_BUF_CF_ENABLE_W01_BITWIDTH 1
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_W_ENABLE_BUF_RESERVED_MASK     0xFFFFFFFC
#define YUVC_YUVC_W_ENABLE_BUF_RESERVED_SHIFT    2 
#define YUVC_YUVC_W_ENABLE_BUF_RESERVED_BIT      0x3FFFFFFF
#define YUVC_YUVC_W_ENABLE_BUF_RESERVED_BITWIDTH 30
// YUVC_W00_STADR_BUF Register
#define YUVC_YUVC_W00_STADR_BUF_OFS              0x00000C00
// cf_stadr_w00 bitfiled (RO) Reset=0
#define YUVC_YUVC_W00_STADR_BUF_CF_STADR_W00_MASK 0xFFFFFFFF
#define YUVC_YUVC_W00_STADR_BUF_CF_STADR_W00_SHIFT 0 
#define YUVC_YUVC_W00_STADR_BUF_CF_STADR_W00_BIT 0xFFFFFFFF
#define YUVC_YUVC_W00_STADR_BUF_CF_STADR_W00_BITWIDTH 32
// YUVC_W00_ENDADR_BUF Register
#define YUVC_YUVC_W00_ENDADR_BUF_OFS             0x00000C04
// cf_endadr_w00 bitfiled (RO) Reset=0
#define YUVC_YUVC_W00_ENDADR_BUF_CF_ENDADR_W00_MASK 0xFFFFFFFF
#define YUVC_YUVC_W00_ENDADR_BUF_CF_ENDADR_W00_SHIFT 0 
#define YUVC_YUVC_W00_ENDADR_BUF_CF_ENDADR_W00_BIT 0xFFFFFFFF
#define YUVC_YUVC_W00_ENDADR_BUF_CF_ENDADR_W00_BITWIDTH 32
// YUVC_W00_HEIGHT_BUF Register
#define YUVC_YUVC_W00_HEIGHT_BUF_OFS             0x00000C08
// cf_height_w00 bitfiled (RO) Reset=0
#define YUVC_YUVC_W00_HEIGHT_BUF_CF_HEIGHT_W00_MASK 0xFFF
#define YUVC_YUVC_W00_HEIGHT_BUF_CF_HEIGHT_W00_SHIFT 0 
#define YUVC_YUVC_W00_HEIGHT_BUF_CF_HEIGHT_W00_BIT 0xFFF
#define YUVC_YUVC_W00_HEIGHT_BUF_CF_HEIGHT_W00_BITWIDTH 12
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_W00_HEIGHT_BUF_RESERVED_MASK   0xFFFFF000
#define YUVC_YUVC_W00_HEIGHT_BUF_RESERVED_SHIFT  12 
#define YUVC_YUVC_W00_HEIGHT_BUF_RESERVED_BIT    0xFFFFF
#define YUVC_YUVC_W00_HEIGHT_BUF_RESERVED_BITWIDTH 20
// YUVC_W00_PITCH_BUF Register
#define YUVC_YUVC_W00_PITCH_BUF_OFS              0x00000C0C
// cf_pitch_w00 bitfiled (RO) Reset=0
#define YUVC_YUVC_W00_PITCH_BUF_CF_PITCH_W00_MASK 0xFFFF
#define YUVC_YUVC_W00_PITCH_BUF_CF_PITCH_W00_SHIFT 0 
#define YUVC_YUVC_W00_PITCH_BUF_CF_PITCH_W00_BIT 0xFFFF
#define YUVC_YUVC_W00_PITCH_BUF_CF_PITCH_W00_BITWIDTH 16
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_W00_PITCH_BUF_RESERVED_MASK    0xFFFF0000
#define YUVC_YUVC_W00_PITCH_BUF_RESERVED_SHIFT   16 
#define YUVC_YUVC_W00_PITCH_BUF_RESERVED_BIT     0xFFFF
#define YUVC_YUVC_W00_PITCH_BUF_RESERVED_BITWIDTH 16
// YUVC_W00_CFG0_BUF Register
#define YUVC_YUVC_W00_CFG0_BUF_OFS               0x00000C10
// reserved4 bitfiled (RO) Reset=0
#define YUVC_YUVC_W00_CFG0_BUF_RESERVED4_MASK    0xFF
#define YUVC_YUVC_W00_CFG0_BUF_RESERVED4_SHIFT   0 
#define YUVC_YUVC_W00_CFG0_BUF_RESERVED4_BIT     0xFF
#define YUVC_YUVC_W00_CFG0_BUF_RESERVED4_BITWIDTH 8
// cf_datawidth_w00 bitfiled (RO) Reset=0
#define YUVC_YUVC_W00_CFG0_BUF_CF_DATAWIDTH_W00_MASK 0x300
#define YUVC_YUVC_W00_CFG0_BUF_CF_DATAWIDTH_W00_SHIFT 8 
#define YUVC_YUVC_W00_CFG0_BUF_CF_DATAWIDTH_W00_BIT 0x3
#define YUVC_YUVC_W00_CFG0_BUF_CF_DATAWIDTH_W00_BITWIDTH 2
// YUVC_W01_STADR_BUF Register
#define YUVC_YUVC_W01_STADR_BUF_OFS              0x00000C20
// cf_stadr_w01 bitfiled (RO) Reset=0
#define YUVC_YUVC_W01_STADR_BUF_CF_STADR_W01_MASK 0xFFFFFFFF
#define YUVC_YUVC_W01_STADR_BUF_CF_STADR_W01_SHIFT 0 
#define YUVC_YUVC_W01_STADR_BUF_CF_STADR_W01_BIT 0xFFFFFFFF
#define YUVC_YUVC_W01_STADR_BUF_CF_STADR_W01_BITWIDTH 32
// YUVC_W01_ENDADR_BUF Register
#define YUVC_YUVC_W01_ENDADR_BUF_OFS             0x00000C24
// cf_endadr_w01 bitfiled (RO) Reset=0
#define YUVC_YUVC_W01_ENDADR_BUF_CF_ENDADR_W01_MASK 0xFFFFFFFF
#define YUVC_YUVC_W01_ENDADR_BUF_CF_ENDADR_W01_SHIFT 0 
#define YUVC_YUVC_W01_ENDADR_BUF_CF_ENDADR_W01_BIT 0xFFFFFFFF
#define YUVC_YUVC_W01_ENDADR_BUF_CF_ENDADR_W01_BITWIDTH 32
// YUVC_W01_HEIGHT_BUF Register
#define YUVC_YUVC_W01_HEIGHT_BUF_OFS             0x00000C28
// cf_height_w01 bitfiled (RO) Reset=0
#define YUVC_YUVC_W01_HEIGHT_BUF_CF_HEIGHT_W01_MASK 0xFFF
#define YUVC_YUVC_W01_HEIGHT_BUF_CF_HEIGHT_W01_SHIFT 0 
#define YUVC_YUVC_W01_HEIGHT_BUF_CF_HEIGHT_W01_BIT 0xFFF
#define YUVC_YUVC_W01_HEIGHT_BUF_CF_HEIGHT_W01_BITWIDTH 12
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_W01_HEIGHT_BUF_RESERVED_MASK   0xFFFFF000
#define YUVC_YUVC_W01_HEIGHT_BUF_RESERVED_SHIFT  12 
#define YUVC_YUVC_W01_HEIGHT_BUF_RESERVED_BIT    0xFFFFF
#define YUVC_YUVC_W01_HEIGHT_BUF_RESERVED_BITWIDTH 20
// YUVC_W01_PITCH_BUF Register
#define YUVC_YUVC_W01_PITCH_BUF_OFS              0x00000C2C
// cf_pitch_w01 bitfiled (RO) Reset=0
#define YUVC_YUVC_W01_PITCH_BUF_CF_PITCH_W01_MASK 0xFFFF
#define YUVC_YUVC_W01_PITCH_BUF_CF_PITCH_W01_SHIFT 0 
#define YUVC_YUVC_W01_PITCH_BUF_CF_PITCH_W01_BIT 0xFFFF
#define YUVC_YUVC_W01_PITCH_BUF_CF_PITCH_W01_BITWIDTH 16
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_W01_PITCH_BUF_RESERVED_MASK    0xFFFF0000
#define YUVC_YUVC_W01_PITCH_BUF_RESERVED_SHIFT   16 
#define YUVC_YUVC_W01_PITCH_BUF_RESERVED_BIT     0xFFFF
#define YUVC_YUVC_W01_PITCH_BUF_RESERVED_BITWIDTH 16
// YUVC_W01_CFG0_BUF Register
#define YUVC_YUVC_W01_CFG0_BUF_OFS               0x00000C30
// reserved4 bitfiled (RO) Reset=0
#define YUVC_YUVC_W01_CFG0_BUF_RESERVED4_MASK    0xFF
#define YUVC_YUVC_W01_CFG0_BUF_RESERVED4_SHIFT   0 
#define YUVC_YUVC_W01_CFG0_BUF_RESERVED4_BIT     0xFF
#define YUVC_YUVC_W01_CFG0_BUF_RESERVED4_BITWIDTH 8
// cf_datawidth_w01 bitfiled (RO) Reset=0
#define YUVC_YUVC_W01_CFG0_BUF_CF_DATAWIDTH_W01_MASK 0x300
#define YUVC_YUVC_W01_CFG0_BUF_CF_DATAWIDTH_W01_SHIFT 8 
#define YUVC_YUVC_W01_CFG0_BUF_CF_DATAWIDTH_W01_BIT 0x3
#define YUVC_YUVC_W01_CFG0_BUF_CF_DATAWIDTH_W01_BITWIDTH 2
// YUVC_STATUS Register
#define YUVC_YUVC_STATUS_OFS                     0x00000E00
// mb_error_region bitfiled (RW) Reset=0
#define YUVC_YUVC_STATUS_MB_ERROR_REGION_MASK    0x1
#define YUVC_YUVC_STATUS_MB_ERROR_REGION_SHIFT   0 
#define YUVC_YUVC_STATUS_MB_ERROR_REGION_BIT     0x1
#define YUVC_YUVC_STATUS_MB_ERROR_REGION_BITWIDTH 1
// mb_error_inband bitfiled (RW) Reset=0
#define YUVC_YUVC_STATUS_MB_ERROR_INBAND_MASK    0x2
#define YUVC_YUVC_STATUS_MB_ERROR_INBAND_SHIFT   1 
#define YUVC_YUVC_STATUS_MB_ERROR_INBAND_BIT     0x1
#define YUVC_YUVC_STATUS_MB_ERROR_INBAND_BITWIDTH 1
// reserved3 bitfiled (RO) Reset=0
#define YUVC_YUVC_STATUS_RESERVED3_MASK          0xFC
#define YUVC_YUVC_STATUS_RESERVED3_SHIFT         2 
#define YUVC_YUVC_STATUS_RESERVED3_BIT           0x3F
#define YUVC_YUVC_STATUS_RESERVED3_BITWIDTH      6
// cmd_num bitfiled (RO) Reset=0
#define YUVC_YUVC_STATUS_CMD_NUM_MASK            0x700
#define YUVC_YUVC_STATUS_CMD_NUM_SHIFT           8 
#define YUVC_YUVC_STATUS_CMD_NUM_BIT             0x7
#define YUVC_YUVC_STATUS_CMD_NUM_BITWIDTH        3
// reserved2 bitfiled (RO) Reset=0
#define YUVC_YUVC_STATUS_RESERVED2_MASK          0xF800
#define YUVC_YUVC_STATUS_RESERVED2_SHIFT         11 
#define YUVC_YUVC_STATUS_RESERVED2_BIT           0x1F
#define YUVC_YUVC_STATUS_RESERVED2_BITWIDTH      5
// accmd_num bitfiled (RO) Reset=0
#define YUVC_YUVC_STATUS_ACCMD_NUM_MASK          0xF0000
#define YUVC_YUVC_STATUS_ACCMD_NUM_SHIFT         16 
#define YUVC_YUVC_STATUS_ACCMD_NUM_BIT           0xF
#define YUVC_YUVC_STATUS_ACCMD_NUM_BITWIDTH      4
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_STATUS_RESERVED_MASK           0xFFF00000
#define YUVC_YUVC_STATUS_RESERVED_SHIFT          20 
#define YUVC_YUVC_STATUS_RESERVED_BIT            0xFFF
#define YUVC_YUVC_STATUS_RESERVED_BITWIDTH       12
// YUVC_INT Register
#define YUVC_YUVC_INT_OFS                        0x00000E04
// int_g00 bitfiled (RW) Reset=0
#define YUVC_YUVC_INT_INT_G00_MASK               0x1
#define YUVC_YUVC_INT_INT_G00_SHIFT              0 
#define YUVC_YUVC_INT_INT_G00_BIT                0x1
#define YUVC_YUVC_INT_INT_G00_BITWIDTH           1
// reserved2 bitfiled (RO) Reset=0
#define YUVC_YUVC_INT_RESERVED2_MASK             0x7FFE
#define YUVC_YUVC_INT_RESERVED2_SHIFT            1 
#define YUVC_YUVC_INT_RESERVED2_BIT              0x3FFF
#define YUVC_YUVC_INT_RESERVED2_BITWIDTH         14
// mb_err bitfiled (RW) Reset=0
#define YUVC_YUVC_INT_MB_ERR_MASK                0x8000
#define YUVC_YUVC_INT_MB_ERR_SHIFT               15 
#define YUVC_YUVC_INT_MB_ERR_BIT                 0x1
#define YUVC_YUVC_INT_MB_ERR_BITWIDTH            1
// abort_g00 bitfiled (RW) Reset=0
#define YUVC_YUVC_INT_ABORT_G00_MASK             0x10000
#define YUVC_YUVC_INT_ABORT_G00_SHIFT            16 
#define YUVC_YUVC_INT_ABORT_G00_BIT              0x1
#define YUVC_YUVC_INT_ABORT_G00_BITWIDTH         1
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_INT_RESERVED_MASK              0xFFFE0000
#define YUVC_YUVC_INT_RESERVED_SHIFT             17 
#define YUVC_YUVC_INT_RESERVED_BIT               0x7FFF
#define YUVC_YUVC_INT_RESERVED_BITWIDTH          15
// YUVC_W_SRAM Register
#define YUVC_YUVC_W_SRAM_OFS                     0x00000E0C
// full_w00 bitfiled (RO) Reset=1
#define YUVC_YUVC_W_SRAM_FULL_W00_MASK           0x1
#define YUVC_YUVC_W_SRAM_FULL_W00_SHIFT          0 
#define YUVC_YUVC_W_SRAM_FULL_W00_BIT            0x1
#define YUVC_YUVC_W_SRAM_FULL_W00_BITWIDTH       1
// full_w01 bitfiled (RO) Reset=1
#define YUVC_YUVC_W_SRAM_FULL_W01_MASK           0x2
#define YUVC_YUVC_W_SRAM_FULL_W01_SHIFT          1 
#define YUVC_YUVC_W_SRAM_FULL_W01_BIT            0x1
#define YUVC_YUVC_W_SRAM_FULL_W01_BITWIDTH       1
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_W_SRAM_RESERVED_MASK           0xFFFFFFFC
#define YUVC_YUVC_W_SRAM_RESERVED_SHIFT          2 
#define YUVC_YUVC_W_SRAM_RESERVED_BIT            0x3FFFFFFF
#define YUVC_YUVC_W_SRAM_RESERVED_BITWIDTH       30
// YUVC_W_STOP Register
#define YUVC_YUVC_W_STOP_OFS                     0x00000E14
// abort_w00 bitfiled (RW) Reset=0
#define YUVC_YUVC_W_STOP_ABORT_W00_MASK          0x1
#define YUVC_YUVC_W_STOP_ABORT_W00_SHIFT         0 
#define YUVC_YUVC_W_STOP_ABORT_W00_BIT           0x1
#define YUVC_YUVC_W_STOP_ABORT_W00_BITWIDTH      1
// abort_w01 bitfiled (RW) Reset=0
#define YUVC_YUVC_W_STOP_ABORT_W01_MASK          0x2
#define YUVC_YUVC_W_STOP_ABORT_W01_SHIFT         1 
#define YUVC_YUVC_W_STOP_ABORT_W01_BIT           0x1
#define YUVC_YUVC_W_STOP_ABORT_W01_BITWIDTH      1
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_W_STOP_RESERVED_MASK           0xFFFFFFFC
#define YUVC_YUVC_W_STOP_RESERVED_SHIFT          2 
#define YUVC_YUVC_W_STOP_RESERVED_BIT            0x3FFFFFFF
#define YUVC_YUVC_W_STOP_RESERVED_BITWIDTH       30
// YUVC_W_RUN Register
#define YUVC_YUVC_W_RUN_OFS                      0x00000E1C
// run_w00 bitfiled (RO) Reset=0
#define YUVC_YUVC_W_RUN_RUN_W00_MASK             0x1
#define YUVC_YUVC_W_RUN_RUN_W00_SHIFT            0 
#define YUVC_YUVC_W_RUN_RUN_W00_BIT              0x1
#define YUVC_YUVC_W_RUN_RUN_W00_BITWIDTH         1
// run_w01 bitfiled (RO) Reset=0
#define YUVC_YUVC_W_RUN_RUN_W01_MASK             0x2
#define YUVC_YUVC_W_RUN_RUN_W01_SHIFT            1 
#define YUVC_YUVC_W_RUN_RUN_W01_BIT              0x1
#define YUVC_YUVC_W_RUN_RUN_W01_BITWIDTH         1
// reserved bitfiled (RO) Reset=0
#define YUVC_YUVC_W_RUN_RESERVED_MASK            0xFFFFFFFC
#define YUVC_YUVC_W_RUN_RESERVED_SHIFT           2 
#define YUVC_YUVC_W_RUN_RESERVED_BIT             0x3FFFFFFF
#define YUVC_YUVC_W_RUN_RESERVED_BITWIDTH        30

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* _YUVC_REG_DEF_H */
