# App Lite Platform Support
snd-soc-applite-objs := applite-i2s.o
snd-soc-applite-pcm-objs := applite-pcm.o applite-dma.o
snd-soc-applite-tzxxx-objs := applite-tzxxx.o

obj-$(CONFIG_SND_APPLITE_SOC) += snd-soc-applite.o snd-soc-applite-pcm.o snd-soc-applite-tzxxx.o
