#
# affine driver
#

ccflags-y += -I$(obj)
ccflags-y += -I$(obj)/../common/include
ccflags-y += $(OPTIONS)

obj-${CONFIG_APPLITE_IRECOG_AFFINE}	+= affine.o
affine-objs := affine_driver.o affine_util.o

