/*
 * arch/arm/mach-tz3000/include/mach/regs/dsgate_reg_def.h
 *
 * (C) Copyright TOSHIBA Corporation
 * Semiconductor & Storage Products Company 2013
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#ifndef _DSGATE_REG_DEF_H
#define _DSGATE_REG_DEF_H

#ifdef __cplusplus
extern  {
#endif /* __cplusplus */

// DSGATE_REG_BASE_MCHADDR0 Register
#define DSGATE_DSGATE_REG_BASE_MCHADDR0_OFS      0x00000000
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_MCHADDR0_RESERVED1_MASK 0xFFF
#define DSGATE_DSGATE_REG_BASE_MCHADDR0_RESERVED1_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_MCHADDR0_RESERVED1_BIT 0xFFF
#define DSGATE_DSGATE_REG_BASE_MCHADDR0_RESERVED1_BITWIDTH 12
// MCHADDR0 bitfiled (RW) Reset=10000000000000000000
#define DSGATE_DSGATE_REG_BASE_MCHADDR0_MCHADDR0_MASK 0xFFFFF000
#define DSGATE_DSGATE_REG_BASE_MCHADDR0_MCHADDR0_SHIFT 12 
#define DSGATE_DSGATE_REG_BASE_MCHADDR0_MCHADDR0_BIT 0xFFFFF
#define DSGATE_DSGATE_REG_BASE_MCHADDR0_MCHADDR0_BITWIDTH 20
// DSGATE_REG_BASE_MCHPAT0 Register
#define DSGATE_DSGATE_REG_BASE_MCHPAT0_OFS       0x00000004
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_MCHPAT0_RESERVED1_MASK 0xFFF
#define DSGATE_DSGATE_REG_BASE_MCHPAT0_RESERVED1_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_MCHPAT0_RESERVED1_BIT 0xFFF
#define DSGATE_DSGATE_REG_BASE_MCHPAT0_RESERVED1_BITWIDTH 12
// MCHPAT0 bitfiled (RW) Reset=10000000000000000000
#define DSGATE_DSGATE_REG_BASE_MCHPAT0_MCHPAT0_MASK 0xFFFFF000
#define DSGATE_DSGATE_REG_BASE_MCHPAT0_MCHPAT0_SHIFT 12 
#define DSGATE_DSGATE_REG_BASE_MCHPAT0_MCHPAT0_BIT 0xFFFFF
#define DSGATE_DSGATE_REG_BASE_MCHPAT0_MCHPAT0_BITWIDTH 20
// DSGATE_REG_BASE_RPERMIT0 Register
#define DSGATE_DSGATE_REG_BASE_RPERMIT0_OFS      0x00000008
// RPERMIT0 bitfiled (RW) Reset=1110
#define DSGATE_DSGATE_REG_BASE_RPERMIT0_RPERMIT0_MASK 0xF
#define DSGATE_DSGATE_REG_BASE_RPERMIT0_RPERMIT0_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_RPERMIT0_RPERMIT0_BIT 0xF
#define DSGATE_DSGATE_REG_BASE_RPERMIT0_RPERMIT0_BITWIDTH 4
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_RPERMIT0_RESERVED1_MASK 0xFFFFFFF0
#define DSGATE_DSGATE_REG_BASE_RPERMIT0_RESERVED1_SHIFT 4 
#define DSGATE_DSGATE_REG_BASE_RPERMIT0_RESERVED1_BIT 0xFFFFFFF
#define DSGATE_DSGATE_REG_BASE_RPERMIT0_RESERVED1_BITWIDTH 28
// DSGATE_REG_BASE_WPERMIT0 Register
#define DSGATE_DSGATE_REG_BASE_WPERMIT0_OFS      0x0000000C
// WPERMIT0 bitfiled (RW) Reset=1110
#define DSGATE_DSGATE_REG_BASE_WPERMIT0_WPERMIT0_MASK 0xF
#define DSGATE_DSGATE_REG_BASE_WPERMIT0_WPERMIT0_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_WPERMIT0_WPERMIT0_BIT 0xF
#define DSGATE_DSGATE_REG_BASE_WPERMIT0_WPERMIT0_BITWIDTH 4
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_WPERMIT0_RESERVED1_MASK 0xFFFFFFF0
#define DSGATE_DSGATE_REG_BASE_WPERMIT0_RESERVED1_SHIFT 4 
#define DSGATE_DSGATE_REG_BASE_WPERMIT0_RESERVED1_BIT 0xFFFFFFF
#define DSGATE_DSGATE_REG_BASE_WPERMIT0_RESERVED1_BITWIDTH 28
// DSGATE_REG_BASE_MCHADDR1 Register
#define DSGATE_DSGATE_REG_BASE_MCHADDR1_OFS      0x00000010
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_MCHADDR1_RESERVED1_MASK 0xFFF
#define DSGATE_DSGATE_REG_BASE_MCHADDR1_RESERVED1_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_MCHADDR1_RESERVED1_BIT 0xFFF
#define DSGATE_DSGATE_REG_BASE_MCHADDR1_RESERVED1_BITWIDTH 12
// MCHADDR1 bitfiled (RW) Reset=10000000000000000000
#define DSGATE_DSGATE_REG_BASE_MCHADDR1_MCHADDR1_MASK 0xFFFFF000
#define DSGATE_DSGATE_REG_BASE_MCHADDR1_MCHADDR1_SHIFT 12 
#define DSGATE_DSGATE_REG_BASE_MCHADDR1_MCHADDR1_BIT 0xFFFFF
#define DSGATE_DSGATE_REG_BASE_MCHADDR1_MCHADDR1_BITWIDTH 20
// DSGATE_REG_BASE_MCHPAT1 Register
#define DSGATE_DSGATE_REG_BASE_MCHPAT1_OFS       0x00000014
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_MCHPAT1_RESERVED1_MASK 0xFFF
#define DSGATE_DSGATE_REG_BASE_MCHPAT1_RESERVED1_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_MCHPAT1_RESERVED1_BIT 0xFFF
#define DSGATE_DSGATE_REG_BASE_MCHPAT1_RESERVED1_BITWIDTH 12
// MCHPAT1 bitfiled (RW) Reset=10000000000000000000
#define DSGATE_DSGATE_REG_BASE_MCHPAT1_MCHPAT1_MASK 0xFFFFF000
#define DSGATE_DSGATE_REG_BASE_MCHPAT1_MCHPAT1_SHIFT 12 
#define DSGATE_DSGATE_REG_BASE_MCHPAT1_MCHPAT1_BIT 0xFFFFF
#define DSGATE_DSGATE_REG_BASE_MCHPAT1_MCHPAT1_BITWIDTH 20
// DSGATE_REG_BASE_RPERMIT1 Register
#define DSGATE_DSGATE_REG_BASE_RPERMIT1_OFS      0x00000018
// RPERMIT1 bitfiled (RW) Reset=1110
#define DSGATE_DSGATE_REG_BASE_RPERMIT1_RPERMIT1_MASK 0xF
#define DSGATE_DSGATE_REG_BASE_RPERMIT1_RPERMIT1_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_RPERMIT1_RPERMIT1_BIT 0xF
#define DSGATE_DSGATE_REG_BASE_RPERMIT1_RPERMIT1_BITWIDTH 4
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_RPERMIT1_RESERVED1_MASK 0xFFFFFFF0
#define DSGATE_DSGATE_REG_BASE_RPERMIT1_RESERVED1_SHIFT 4 
#define DSGATE_DSGATE_REG_BASE_RPERMIT1_RESERVED1_BIT 0xFFFFFFF
#define DSGATE_DSGATE_REG_BASE_RPERMIT1_RESERVED1_BITWIDTH 28
// DSGATE_REG_BASE_WPERMIT1 Register
#define DSGATE_DSGATE_REG_BASE_WPERMIT1_OFS      0x0000001C
// WPERMIT1 bitfiled (RW) Reset=1110
#define DSGATE_DSGATE_REG_BASE_WPERMIT1_WPERMIT1_MASK 0xF
#define DSGATE_DSGATE_REG_BASE_WPERMIT1_WPERMIT1_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_WPERMIT1_WPERMIT1_BIT 0xF
#define DSGATE_DSGATE_REG_BASE_WPERMIT1_WPERMIT1_BITWIDTH 4
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_WPERMIT1_RESERVED1_MASK 0xFFFFFFF0
#define DSGATE_DSGATE_REG_BASE_WPERMIT1_RESERVED1_SHIFT 4 
#define DSGATE_DSGATE_REG_BASE_WPERMIT1_RESERVED1_BIT 0xFFFFFFF
#define DSGATE_DSGATE_REG_BASE_WPERMIT1_RESERVED1_BITWIDTH 28
// DSGATE_REG_BASE_MCHADDR2 Register
#define DSGATE_DSGATE_REG_BASE_MCHADDR2_OFS      0x00000020
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_MCHADDR2_RESERVED1_MASK 0xFFF
#define DSGATE_DSGATE_REG_BASE_MCHADDR2_RESERVED1_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_MCHADDR2_RESERVED1_BIT 0xFFF
#define DSGATE_DSGATE_REG_BASE_MCHADDR2_RESERVED1_BITWIDTH 12
// MCHADDR2 bitfiled (RW) Reset=10000000000000000000
#define DSGATE_DSGATE_REG_BASE_MCHADDR2_MCHADDR2_MASK 0xFFFFF000
#define DSGATE_DSGATE_REG_BASE_MCHADDR2_MCHADDR2_SHIFT 12 
#define DSGATE_DSGATE_REG_BASE_MCHADDR2_MCHADDR2_BIT 0xFFFFF
#define DSGATE_DSGATE_REG_BASE_MCHADDR2_MCHADDR2_BITWIDTH 20
// DSGATE_REG_BASE_MCHPAT2 Register
#define DSGATE_DSGATE_REG_BASE_MCHPAT2_OFS       0x00000024
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_MCHPAT2_RESERVED1_MASK 0xFFF
#define DSGATE_DSGATE_REG_BASE_MCHPAT2_RESERVED1_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_MCHPAT2_RESERVED1_BIT 0xFFF
#define DSGATE_DSGATE_REG_BASE_MCHPAT2_RESERVED1_BITWIDTH 12
// MCHPAT2 bitfiled (RW) Reset=10000000000000000000
#define DSGATE_DSGATE_REG_BASE_MCHPAT2_MCHPAT2_MASK 0xFFFFF000
#define DSGATE_DSGATE_REG_BASE_MCHPAT2_MCHPAT2_SHIFT 12 
#define DSGATE_DSGATE_REG_BASE_MCHPAT2_MCHPAT2_BIT 0xFFFFF
#define DSGATE_DSGATE_REG_BASE_MCHPAT2_MCHPAT2_BITWIDTH 20
// DSGATE_REG_BASE_RPERMIT2 Register
#define DSGATE_DSGATE_REG_BASE_RPERMIT2_OFS      0x00000028
// RPERMIT2 bitfiled (RW) Reset=1110
#define DSGATE_DSGATE_REG_BASE_RPERMIT2_RPERMIT2_MASK 0xF
#define DSGATE_DSGATE_REG_BASE_RPERMIT2_RPERMIT2_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_RPERMIT2_RPERMIT2_BIT 0xF
#define DSGATE_DSGATE_REG_BASE_RPERMIT2_RPERMIT2_BITWIDTH 4
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_RPERMIT2_RESERVED1_MASK 0xFFFFFFF0
#define DSGATE_DSGATE_REG_BASE_RPERMIT2_RESERVED1_SHIFT 4 
#define DSGATE_DSGATE_REG_BASE_RPERMIT2_RESERVED1_BIT 0xFFFFFFF
#define DSGATE_DSGATE_REG_BASE_RPERMIT2_RESERVED1_BITWIDTH 28
// DSGATE_REG_BASE_WPERMIT2 Register
#define DSGATE_DSGATE_REG_BASE_WPERMIT2_OFS      0x0000002C
// WPERMIT2 bitfiled (RW) Reset=1110
#define DSGATE_DSGATE_REG_BASE_WPERMIT2_WPERMIT2_MASK 0xF
#define DSGATE_DSGATE_REG_BASE_WPERMIT2_WPERMIT2_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_WPERMIT2_WPERMIT2_BIT 0xF
#define DSGATE_DSGATE_REG_BASE_WPERMIT2_WPERMIT2_BITWIDTH 4
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_WPERMIT2_RESERVED1_MASK 0xFFFFFFF0
#define DSGATE_DSGATE_REG_BASE_WPERMIT2_RESERVED1_SHIFT 4 
#define DSGATE_DSGATE_REG_BASE_WPERMIT2_RESERVED1_BIT 0xFFFFFFF
#define DSGATE_DSGATE_REG_BASE_WPERMIT2_RESERVED1_BITWIDTH 28
// DSGATE_REG_BASE_MCHADDR3 Register
#define DSGATE_DSGATE_REG_BASE_MCHADDR3_OFS      0x00000030
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_MCHADDR3_RESERVED1_MASK 0xFFF
#define DSGATE_DSGATE_REG_BASE_MCHADDR3_RESERVED1_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_MCHADDR3_RESERVED1_BIT 0xFFF
#define DSGATE_DSGATE_REG_BASE_MCHADDR3_RESERVED1_BITWIDTH 12
// MCHADDR3 bitfiled (RW) Reset=10000000000000000000
#define DSGATE_DSGATE_REG_BASE_MCHADDR3_MCHADDR3_MASK 0xFFFFF000
#define DSGATE_DSGATE_REG_BASE_MCHADDR3_MCHADDR3_SHIFT 12 
#define DSGATE_DSGATE_REG_BASE_MCHADDR3_MCHADDR3_BIT 0xFFFFF
#define DSGATE_DSGATE_REG_BASE_MCHADDR3_MCHADDR3_BITWIDTH 20
// DSGATE_REG_BASE_MCHPAT3 Register
#define DSGATE_DSGATE_REG_BASE_MCHPAT3_OFS       0x00000034
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_MCHPAT3_RESERVED1_MASK 0xFFF
#define DSGATE_DSGATE_REG_BASE_MCHPAT3_RESERVED1_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_MCHPAT3_RESERVED1_BIT 0xFFF
#define DSGATE_DSGATE_REG_BASE_MCHPAT3_RESERVED1_BITWIDTH 12
// MCHPAT3 bitfiled (RW) Reset=10000000000000000000
#define DSGATE_DSGATE_REG_BASE_MCHPAT3_MCHPAT3_MASK 0xFFFFF000
#define DSGATE_DSGATE_REG_BASE_MCHPAT3_MCHPAT3_SHIFT 12 
#define DSGATE_DSGATE_REG_BASE_MCHPAT3_MCHPAT3_BIT 0xFFFFF
#define DSGATE_DSGATE_REG_BASE_MCHPAT3_MCHPAT3_BITWIDTH 20
// DSGATE_REG_BASE_RPERMIT3 Register
#define DSGATE_DSGATE_REG_BASE_RPERMIT3_OFS      0x00000038
// RPERMIT3 bitfiled (RW) Reset=1110
#define DSGATE_DSGATE_REG_BASE_RPERMIT3_RPERMIT3_MASK 0xF
#define DSGATE_DSGATE_REG_BASE_RPERMIT3_RPERMIT3_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_RPERMIT3_RPERMIT3_BIT 0xF
#define DSGATE_DSGATE_REG_BASE_RPERMIT3_RPERMIT3_BITWIDTH 4
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_RPERMIT3_RESERVED1_MASK 0xFFFFFFF0
#define DSGATE_DSGATE_REG_BASE_RPERMIT3_RESERVED1_SHIFT 4 
#define DSGATE_DSGATE_REG_BASE_RPERMIT3_RESERVED1_BIT 0xFFFFFFF
#define DSGATE_DSGATE_REG_BASE_RPERMIT3_RESERVED1_BITWIDTH 28
// DSGATE_REG_BASE_WPERMIT3 Register
#define DSGATE_DSGATE_REG_BASE_WPERMIT3_OFS      0x0000003C
// WPERMIT3 bitfiled (RW) Reset=1110
#define DSGATE_DSGATE_REG_BASE_WPERMIT3_WPERMIT3_MASK 0xF
#define DSGATE_DSGATE_REG_BASE_WPERMIT3_WPERMIT3_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_WPERMIT3_WPERMIT3_BIT 0xF
#define DSGATE_DSGATE_REG_BASE_WPERMIT3_WPERMIT3_BITWIDTH 4
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_WPERMIT3_RESERVED1_MASK 0xFFFFFFF0
#define DSGATE_DSGATE_REG_BASE_WPERMIT3_RESERVED1_SHIFT 4 
#define DSGATE_DSGATE_REG_BASE_WPERMIT3_RESERVED1_BIT 0xFFFFFFF
#define DSGATE_DSGATE_REG_BASE_WPERMIT3_RESERVED1_BITWIDTH 28
// DSGATE_REG_BASE_MCHADDR4 Register
#define DSGATE_DSGATE_REG_BASE_MCHADDR4_OFS      0x00000040
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_MCHADDR4_RESERVED1_MASK 0xFFF
#define DSGATE_DSGATE_REG_BASE_MCHADDR4_RESERVED1_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_MCHADDR4_RESERVED1_BIT 0xFFF
#define DSGATE_DSGATE_REG_BASE_MCHADDR4_RESERVED1_BITWIDTH 12
// MCHADDR4 bitfiled (RW) Reset=10000000000000000000
#define DSGATE_DSGATE_REG_BASE_MCHADDR4_MCHADDR4_MASK 0xFFFFF000
#define DSGATE_DSGATE_REG_BASE_MCHADDR4_MCHADDR4_SHIFT 12 
#define DSGATE_DSGATE_REG_BASE_MCHADDR4_MCHADDR4_BIT 0xFFFFF
#define DSGATE_DSGATE_REG_BASE_MCHADDR4_MCHADDR4_BITWIDTH 20
// DSGATE_REG_BASE_MCHPAT4 Register
#define DSGATE_DSGATE_REG_BASE_MCHPAT4_OFS       0x00000044
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_MCHPAT4_RESERVED1_MASK 0xFFF
#define DSGATE_DSGATE_REG_BASE_MCHPAT4_RESERVED1_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_MCHPAT4_RESERVED1_BIT 0xFFF
#define DSGATE_DSGATE_REG_BASE_MCHPAT4_RESERVED1_BITWIDTH 12
// MCHPAT4 bitfiled (RW) Reset=10000000000000000000
#define DSGATE_DSGATE_REG_BASE_MCHPAT4_MCHPAT4_MASK 0xFFFFF000
#define DSGATE_DSGATE_REG_BASE_MCHPAT4_MCHPAT4_SHIFT 12 
#define DSGATE_DSGATE_REG_BASE_MCHPAT4_MCHPAT4_BIT 0xFFFFF
#define DSGATE_DSGATE_REG_BASE_MCHPAT4_MCHPAT4_BITWIDTH 20
// DSGATE_REG_BASE_RPERMIT4 Register
#define DSGATE_DSGATE_REG_BASE_RPERMIT4_OFS      0x00000048
// RPERMIT4 bitfiled (RW) Reset=1110
#define DSGATE_DSGATE_REG_BASE_RPERMIT4_RPERMIT4_MASK 0xF
#define DSGATE_DSGATE_REG_BASE_RPERMIT4_RPERMIT4_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_RPERMIT4_RPERMIT4_BIT 0xF
#define DSGATE_DSGATE_REG_BASE_RPERMIT4_RPERMIT4_BITWIDTH 4
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_RPERMIT4_RESERVED1_MASK 0xFFFFFFF0
#define DSGATE_DSGATE_REG_BASE_RPERMIT4_RESERVED1_SHIFT 4 
#define DSGATE_DSGATE_REG_BASE_RPERMIT4_RESERVED1_BIT 0xFFFFFFF
#define DSGATE_DSGATE_REG_BASE_RPERMIT4_RESERVED1_BITWIDTH 28
// DSGATE_REG_BASE_WPERMIT4 Register
#define DSGATE_DSGATE_REG_BASE_WPERMIT4_OFS      0x0000004C
// WPERMIT4 bitfiled (RW) Reset=1110
#define DSGATE_DSGATE_REG_BASE_WPERMIT4_WPERMIT4_MASK 0xF
#define DSGATE_DSGATE_REG_BASE_WPERMIT4_WPERMIT4_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_WPERMIT4_WPERMIT4_BIT 0xF
#define DSGATE_DSGATE_REG_BASE_WPERMIT4_WPERMIT4_BITWIDTH 4
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_WPERMIT4_RESERVED1_MASK 0xFFFFFFF0
#define DSGATE_DSGATE_REG_BASE_WPERMIT4_RESERVED1_SHIFT 4 
#define DSGATE_DSGATE_REG_BASE_WPERMIT4_RESERVED1_BIT 0xFFFFFFF
#define DSGATE_DSGATE_REG_BASE_WPERMIT4_RESERVED1_BITWIDTH 28
// DSGATE_REG_BASE_MCHADDR5 Register
#define DSGATE_DSGATE_REG_BASE_MCHADDR5_OFS      0x00000050
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_MCHADDR5_RESERVED1_MASK 0xFFF
#define DSGATE_DSGATE_REG_BASE_MCHADDR5_RESERVED1_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_MCHADDR5_RESERVED1_BIT 0xFFF
#define DSGATE_DSGATE_REG_BASE_MCHADDR5_RESERVED1_BITWIDTH 12
// MCHADDR5 bitfiled (RW) Reset=10000000000000000000
#define DSGATE_DSGATE_REG_BASE_MCHADDR5_MCHADDR5_MASK 0xFFFFF000
#define DSGATE_DSGATE_REG_BASE_MCHADDR5_MCHADDR5_SHIFT 12 
#define DSGATE_DSGATE_REG_BASE_MCHADDR5_MCHADDR5_BIT 0xFFFFF
#define DSGATE_DSGATE_REG_BASE_MCHADDR5_MCHADDR5_BITWIDTH 20
// DSGATE_REG_BASE_MCHPAT5 Register
#define DSGATE_DSGATE_REG_BASE_MCHPAT5_OFS       0x00000054
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_MCHPAT5_RESERVED1_MASK 0xFFF
#define DSGATE_DSGATE_REG_BASE_MCHPAT5_RESERVED1_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_MCHPAT5_RESERVED1_BIT 0xFFF
#define DSGATE_DSGATE_REG_BASE_MCHPAT5_RESERVED1_BITWIDTH 12
// MCHPAT5 bitfiled (RW) Reset=10000000000000000000
#define DSGATE_DSGATE_REG_BASE_MCHPAT5_MCHPAT5_MASK 0xFFFFF000
#define DSGATE_DSGATE_REG_BASE_MCHPAT5_MCHPAT5_SHIFT 12 
#define DSGATE_DSGATE_REG_BASE_MCHPAT5_MCHPAT5_BIT 0xFFFFF
#define DSGATE_DSGATE_REG_BASE_MCHPAT5_MCHPAT5_BITWIDTH 20
// DSGATE_REG_BASE_RPERMIT5 Register
#define DSGATE_DSGATE_REG_BASE_RPERMIT5_OFS      0x00000058
// RPERMIT5 bitfiled (RW) Reset=1110
#define DSGATE_DSGATE_REG_BASE_RPERMIT5_RPERMIT5_MASK 0xF
#define DSGATE_DSGATE_REG_BASE_RPERMIT5_RPERMIT5_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_RPERMIT5_RPERMIT5_BIT 0xF
#define DSGATE_DSGATE_REG_BASE_RPERMIT5_RPERMIT5_BITWIDTH 4
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_RPERMIT5_RESERVED1_MASK 0xFFFFFFF0
#define DSGATE_DSGATE_REG_BASE_RPERMIT5_RESERVED1_SHIFT 4 
#define DSGATE_DSGATE_REG_BASE_RPERMIT5_RESERVED1_BIT 0xFFFFFFF
#define DSGATE_DSGATE_REG_BASE_RPERMIT5_RESERVED1_BITWIDTH 28
// DSGATE_REG_BASE_WPERMIT5 Register
#define DSGATE_DSGATE_REG_BASE_WPERMIT5_OFS      0x0000005C
// WPERMIT5 bitfiled (RW) Reset=1110
#define DSGATE_DSGATE_REG_BASE_WPERMIT5_WPERMIT5_MASK 0xF
#define DSGATE_DSGATE_REG_BASE_WPERMIT5_WPERMIT5_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_WPERMIT5_WPERMIT5_BIT 0xF
#define DSGATE_DSGATE_REG_BASE_WPERMIT5_WPERMIT5_BITWIDTH 4
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_WPERMIT5_RESERVED1_MASK 0xFFFFFFF0
#define DSGATE_DSGATE_REG_BASE_WPERMIT5_RESERVED1_SHIFT 4 
#define DSGATE_DSGATE_REG_BASE_WPERMIT5_RESERVED1_BIT 0xFFFFFFF
#define DSGATE_DSGATE_REG_BASE_WPERMIT5_RESERVED1_BITWIDTH 28
// DSGATE_REG_BASE_MCHADDR6 Register
#define DSGATE_DSGATE_REG_BASE_MCHADDR6_OFS      0x00000060
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_MCHADDR6_RESERVED1_MASK 0xFFF
#define DSGATE_DSGATE_REG_BASE_MCHADDR6_RESERVED1_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_MCHADDR6_RESERVED1_BIT 0xFFF
#define DSGATE_DSGATE_REG_BASE_MCHADDR6_RESERVED1_BITWIDTH 12
// MCHADDR6 bitfiled (RW) Reset=10000000000000000000
#define DSGATE_DSGATE_REG_BASE_MCHADDR6_MCHADDR6_MASK 0xFFFFF000
#define DSGATE_DSGATE_REG_BASE_MCHADDR6_MCHADDR6_SHIFT 12 
#define DSGATE_DSGATE_REG_BASE_MCHADDR6_MCHADDR6_BIT 0xFFFFF
#define DSGATE_DSGATE_REG_BASE_MCHADDR6_MCHADDR6_BITWIDTH 20
// DSGATE_REG_BASE_MCHPAT6 Register
#define DSGATE_DSGATE_REG_BASE_MCHPAT6_OFS       0x00000064
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_MCHPAT6_RESERVED1_MASK 0xFFF
#define DSGATE_DSGATE_REG_BASE_MCHPAT6_RESERVED1_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_MCHPAT6_RESERVED1_BIT 0xFFF
#define DSGATE_DSGATE_REG_BASE_MCHPAT6_RESERVED1_BITWIDTH 12
// MCHPAT6 bitfiled (RW) Reset=10000000000000000000
#define DSGATE_DSGATE_REG_BASE_MCHPAT6_MCHPAT6_MASK 0xFFFFF000
#define DSGATE_DSGATE_REG_BASE_MCHPAT6_MCHPAT6_SHIFT 12 
#define DSGATE_DSGATE_REG_BASE_MCHPAT6_MCHPAT6_BIT 0xFFFFF
#define DSGATE_DSGATE_REG_BASE_MCHPAT6_MCHPAT6_BITWIDTH 20
// DSGATE_REG_BASE_RPERMIT6 Register
#define DSGATE_DSGATE_REG_BASE_RPERMIT6_OFS      0x00000068
// RPERMIT6 bitfiled (RW) Reset=1110
#define DSGATE_DSGATE_REG_BASE_RPERMIT6_RPERMIT6_MASK 0xF
#define DSGATE_DSGATE_REG_BASE_RPERMIT6_RPERMIT6_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_RPERMIT6_RPERMIT6_BIT 0xF
#define DSGATE_DSGATE_REG_BASE_RPERMIT6_RPERMIT6_BITWIDTH 4
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_RPERMIT6_RESERVED1_MASK 0xFFFFFFF0
#define DSGATE_DSGATE_REG_BASE_RPERMIT6_RESERVED1_SHIFT 4 
#define DSGATE_DSGATE_REG_BASE_RPERMIT6_RESERVED1_BIT 0xFFFFFFF
#define DSGATE_DSGATE_REG_BASE_RPERMIT6_RESERVED1_BITWIDTH 28
// DSGATE_REG_BASE_WPERMIT6 Register
#define DSGATE_DSGATE_REG_BASE_WPERMIT6_OFS      0x0000006C
// WPERMIT6 bitfiled (RW) Reset=1110
#define DSGATE_DSGATE_REG_BASE_WPERMIT6_WPERMIT6_MASK 0xF
#define DSGATE_DSGATE_REG_BASE_WPERMIT6_WPERMIT6_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_WPERMIT6_WPERMIT6_BIT 0xF
#define DSGATE_DSGATE_REG_BASE_WPERMIT6_WPERMIT6_BITWIDTH 4
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_WPERMIT6_RESERVED1_MASK 0xFFFFFFF0
#define DSGATE_DSGATE_REG_BASE_WPERMIT6_RESERVED1_SHIFT 4 
#define DSGATE_DSGATE_REG_BASE_WPERMIT6_RESERVED1_BIT 0xFFFFFFF
#define DSGATE_DSGATE_REG_BASE_WPERMIT6_RESERVED1_BITWIDTH 28
// DSGATE_REG_BASE_MCHADDR7 Register
#define DSGATE_DSGATE_REG_BASE_MCHADDR7_OFS      0x00000070
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_MCHADDR7_RESERVED1_MASK 0xFFF
#define DSGATE_DSGATE_REG_BASE_MCHADDR7_RESERVED1_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_MCHADDR7_RESERVED1_BIT 0xFFF
#define DSGATE_DSGATE_REG_BASE_MCHADDR7_RESERVED1_BITWIDTH 12
// MCHADDR7 bitfiled (RW) Reset=10000000000000000000
#define DSGATE_DSGATE_REG_BASE_MCHADDR7_MCHADDR7_MASK 0xFFFFF000
#define DSGATE_DSGATE_REG_BASE_MCHADDR7_MCHADDR7_SHIFT 12 
#define DSGATE_DSGATE_REG_BASE_MCHADDR7_MCHADDR7_BIT 0xFFFFF
#define DSGATE_DSGATE_REG_BASE_MCHADDR7_MCHADDR7_BITWIDTH 20
// DSGATE_REG_BASE_MCHPAT7 Register
#define DSGATE_DSGATE_REG_BASE_MCHPAT7_OFS       0x00000074
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_MCHPAT7_RESERVED1_MASK 0xFFF
#define DSGATE_DSGATE_REG_BASE_MCHPAT7_RESERVED1_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_MCHPAT7_RESERVED1_BIT 0xFFF
#define DSGATE_DSGATE_REG_BASE_MCHPAT7_RESERVED1_BITWIDTH 12
// MCHPAT7 bitfiled (RW) Reset=10000000000000000000
#define DSGATE_DSGATE_REG_BASE_MCHPAT7_MCHPAT7_MASK 0xFFFFF000
#define DSGATE_DSGATE_REG_BASE_MCHPAT7_MCHPAT7_SHIFT 12 
#define DSGATE_DSGATE_REG_BASE_MCHPAT7_MCHPAT7_BIT 0xFFFFF
#define DSGATE_DSGATE_REG_BASE_MCHPAT7_MCHPAT7_BITWIDTH 20
// DSGATE_REG_BASE_RPERMIT7 Register
#define DSGATE_DSGATE_REG_BASE_RPERMIT7_OFS      0x00000078
// RPERMIT7 bitfiled (RW) Reset=1110
#define DSGATE_DSGATE_REG_BASE_RPERMIT7_RPERMIT7_MASK 0xF
#define DSGATE_DSGATE_REG_BASE_RPERMIT7_RPERMIT7_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_RPERMIT7_RPERMIT7_BIT 0xF
#define DSGATE_DSGATE_REG_BASE_RPERMIT7_RPERMIT7_BITWIDTH 4
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_RPERMIT7_RESERVED1_MASK 0xFFFFFFF0
#define DSGATE_DSGATE_REG_BASE_RPERMIT7_RESERVED1_SHIFT 4 
#define DSGATE_DSGATE_REG_BASE_RPERMIT7_RESERVED1_BIT 0xFFFFFFF
#define DSGATE_DSGATE_REG_BASE_RPERMIT7_RESERVED1_BITWIDTH 28
// DSGATE_REG_BASE_WPERMIT7 Register
#define DSGATE_DSGATE_REG_BASE_WPERMIT7_OFS      0x0000007C
// WPERMIT7 bitfiled (RW) Reset=1110
#define DSGATE_DSGATE_REG_BASE_WPERMIT7_WPERMIT7_MASK 0xF
#define DSGATE_DSGATE_REG_BASE_WPERMIT7_WPERMIT7_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_WPERMIT7_WPERMIT7_BIT 0xF
#define DSGATE_DSGATE_REG_BASE_WPERMIT7_WPERMIT7_BITWIDTH 4
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_WPERMIT7_RESERVED1_MASK 0xFFFFFFF0
#define DSGATE_DSGATE_REG_BASE_WPERMIT7_RESERVED1_SHIFT 4 
#define DSGATE_DSGATE_REG_BASE_WPERMIT7_RESERVED1_BIT 0xFFFFFFF
#define DSGATE_DSGATE_REG_BASE_WPERMIT7_RESERVED1_BITWIDTH 28
// DSGATE_REG_BASE_MCHADDR8 Register
#define DSGATE_DSGATE_REG_BASE_MCHADDR8_OFS      0x00000080
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_MCHADDR8_RESERVED1_MASK 0xFFF
#define DSGATE_DSGATE_REG_BASE_MCHADDR8_RESERVED1_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_MCHADDR8_RESERVED1_BIT 0xFFF
#define DSGATE_DSGATE_REG_BASE_MCHADDR8_RESERVED1_BITWIDTH 12
// MCHADDR8 bitfiled (RW) Reset=10000000000000000000
#define DSGATE_DSGATE_REG_BASE_MCHADDR8_MCHADDR8_MASK 0xFFFFF000
#define DSGATE_DSGATE_REG_BASE_MCHADDR8_MCHADDR8_SHIFT 12 
#define DSGATE_DSGATE_REG_BASE_MCHADDR8_MCHADDR8_BIT 0xFFFFF
#define DSGATE_DSGATE_REG_BASE_MCHADDR8_MCHADDR8_BITWIDTH 20
// DSGATE_REG_BASE_MCHPAT8 Register
#define DSGATE_DSGATE_REG_BASE_MCHPAT8_OFS       0x00000084
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_MCHPAT8_RESERVED1_MASK 0xFFF
#define DSGATE_DSGATE_REG_BASE_MCHPAT8_RESERVED1_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_MCHPAT8_RESERVED1_BIT 0xFFF
#define DSGATE_DSGATE_REG_BASE_MCHPAT8_RESERVED1_BITWIDTH 12
// MCHPAT8 bitfiled (RW) Reset=10000000000000000000
#define DSGATE_DSGATE_REG_BASE_MCHPAT8_MCHPAT8_MASK 0xFFFFF000
#define DSGATE_DSGATE_REG_BASE_MCHPAT8_MCHPAT8_SHIFT 12 
#define DSGATE_DSGATE_REG_BASE_MCHPAT8_MCHPAT8_BIT 0xFFFFF
#define DSGATE_DSGATE_REG_BASE_MCHPAT8_MCHPAT8_BITWIDTH 20
// DSGATE_REG_BASE_RPERMIT8 Register
#define DSGATE_DSGATE_REG_BASE_RPERMIT8_OFS      0x00000088
// RPERMIT8 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_RPERMIT8_RPERMIT8_MASK 0xF
#define DSGATE_DSGATE_REG_BASE_RPERMIT8_RPERMIT8_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_RPERMIT8_RPERMIT8_BIT 0xF
#define DSGATE_DSGATE_REG_BASE_RPERMIT8_RPERMIT8_BITWIDTH 4
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_RPERMIT8_RESERVED1_MASK 0xFFFFFFF0
#define DSGATE_DSGATE_REG_BASE_RPERMIT8_RESERVED1_SHIFT 4 
#define DSGATE_DSGATE_REG_BASE_RPERMIT8_RESERVED1_BIT 0xFFFFFFF
#define DSGATE_DSGATE_REG_BASE_RPERMIT8_RESERVED1_BITWIDTH 28
// DSGATE_REG_BASE_WPERMIT8 Register
#define DSGATE_DSGATE_REG_BASE_WPERMIT8_OFS      0x0000008C
// WPERMIT8 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_WPERMIT8_WPERMIT8_MASK 0xF
#define DSGATE_DSGATE_REG_BASE_WPERMIT8_WPERMIT8_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_WPERMIT8_WPERMIT8_BIT 0xF
#define DSGATE_DSGATE_REG_BASE_WPERMIT8_WPERMIT8_BITWIDTH 4
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_WPERMIT8_RESERVED1_MASK 0xFFFFFFF0
#define DSGATE_DSGATE_REG_BASE_WPERMIT8_RESERVED1_SHIFT 4 
#define DSGATE_DSGATE_REG_BASE_WPERMIT8_RESERVED1_BIT 0xFFFFFFF
#define DSGATE_DSGATE_REG_BASE_WPERMIT8_RESERVED1_BITWIDTH 28
// DSGATE_REG_BASE_ELOGADR0 Register
#define DSGATE_DSGATE_REG_BASE_ELOGADR0_OFS      0x00000100
// ELOGADR0 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOGADR0_ELOGADR0_MASK 0xFFFFFFFF
#define DSGATE_DSGATE_REG_BASE_ELOGADR0_ELOGADR0_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_ELOGADR0_ELOGADR0_BIT 0xFFFFFFFF
#define DSGATE_DSGATE_REG_BASE_ELOGADR0_ELOGADR0_BITWIDTH 32
// DSGATE_REG_BASE_ELOG0 Register
#define DSGATE_DSGATE_REG_BASE_ELOG0_OFS         0x00000104
// MConnID bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG0_MCONNID_MASK 0x7F
#define DSGATE_DSGATE_REG_BASE_ELOG0_MCONNID_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_ELOG0_MCONNID_BIT 0x7F
#define DSGATE_DSGATE_REG_BASE_ELOG0_MCONNID_BITWIDTH 7
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG0_RESERVED1_MASK 0x80
#define DSGATE_DSGATE_REG_BASE_ELOG0_RESERVED1_SHIFT 7 
#define DSGATE_DSGATE_REG_BASE_ELOG0_RESERVED1_BIT 0x1
#define DSGATE_DSGATE_REG_BASE_ELOG0_RESERVED1_BITWIDTH 1
// Length bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG0_LENGTH_MASK 0x700
#define DSGATE_DSGATE_REG_BASE_ELOG0_LENGTH_SHIFT 8 
#define DSGATE_DSGATE_REG_BASE_ELOG0_LENGTH_BIT  0x7
#define DSGATE_DSGATE_REG_BASE_ELOG0_LENGTH_BITWIDTH 3
// reserved2 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG0_RESERVED2_MASK 0xF800
#define DSGATE_DSGATE_REG_BASE_ELOG0_RESERVED2_SHIFT 11 
#define DSGATE_DSGATE_REG_BASE_ELOG0_RESERVED2_BIT 0x1F
#define DSGATE_DSGATE_REG_BASE_ELOG0_RESERVED2_BITWIDTH 5
// Command bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG0_COMMAND_MASK 0x70000
#define DSGATE_DSGATE_REG_BASE_ELOG0_COMMAND_SHIFT 16 
#define DSGATE_DSGATE_REG_BASE_ELOG0_COMMAND_BIT 0x7
#define DSGATE_DSGATE_REG_BASE_ELOG0_COMMAND_BITWIDTH 3
// reserved3 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG0_RESERVED3_MASK 0x80000
#define DSGATE_DSGATE_REG_BASE_ELOG0_RESERVED3_SHIFT 19 
#define DSGATE_DSGATE_REG_BASE_ELOG0_RESERVED3_BIT 0x1
#define DSGATE_DSGATE_REG_BASE_ELOG0_RESERVED3_BITWIDTH 1
// Security bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG0_SECURITY_MASK 0x300000
#define DSGATE_DSGATE_REG_BASE_ELOG0_SECURITY_SHIFT 20 
#define DSGATE_DSGATE_REG_BASE_ELOG0_SECURITY_BIT 0x3
#define DSGATE_DSGATE_REG_BASE_ELOG0_SECURITY_BITWIDTH 2
// reserved4 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG0_RESERVED4_MASK 0x7FC00000
#define DSGATE_DSGATE_REG_BASE_ELOG0_RESERVED4_SHIFT 22 
#define DSGATE_DSGATE_REG_BASE_ELOG0_RESERVED4_BIT 0x1FF
#define DSGATE_DSGATE_REG_BASE_ELOG0_RESERVED4_BITWIDTH 9
// Valid bitfiled (RW) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG0_VALID_MASK  0x80000000
#define DSGATE_DSGATE_REG_BASE_ELOG0_VALID_SHIFT 31 
#define DSGATE_DSGATE_REG_BASE_ELOG0_VALID_BIT   0x1
#define DSGATE_DSGATE_REG_BASE_ELOG0_VALID_BITWIDTH 1
// DSGATE_REG_BASE_ELOGADR1 Register
#define DSGATE_DSGATE_REG_BASE_ELOGADR1_OFS      0x00000110
// ELOGADR1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOGADR1_ELOGADR1_MASK 0xFFFFFFFF
#define DSGATE_DSGATE_REG_BASE_ELOGADR1_ELOGADR1_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_ELOGADR1_ELOGADR1_BIT 0xFFFFFFFF
#define DSGATE_DSGATE_REG_BASE_ELOGADR1_ELOGADR1_BITWIDTH 32
// DSGATE_REG_BASE_ELOG1 Register
#define DSGATE_DSGATE_REG_BASE_ELOG1_OFS         0x00000114
// MConnID bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG1_MCONNID_MASK 0x7F
#define DSGATE_DSGATE_REG_BASE_ELOG1_MCONNID_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_ELOG1_MCONNID_BIT 0x7F
#define DSGATE_DSGATE_REG_BASE_ELOG1_MCONNID_BITWIDTH 7
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG1_RESERVED1_MASK 0x80
#define DSGATE_DSGATE_REG_BASE_ELOG1_RESERVED1_SHIFT 7 
#define DSGATE_DSGATE_REG_BASE_ELOG1_RESERVED1_BIT 0x1
#define DSGATE_DSGATE_REG_BASE_ELOG1_RESERVED1_BITWIDTH 1
// Length bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG1_LENGTH_MASK 0x700
#define DSGATE_DSGATE_REG_BASE_ELOG1_LENGTH_SHIFT 8 
#define DSGATE_DSGATE_REG_BASE_ELOG1_LENGTH_BIT  0x7
#define DSGATE_DSGATE_REG_BASE_ELOG1_LENGTH_BITWIDTH 3
// reserved2 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG1_RESERVED2_MASK 0xF800
#define DSGATE_DSGATE_REG_BASE_ELOG1_RESERVED2_SHIFT 11 
#define DSGATE_DSGATE_REG_BASE_ELOG1_RESERVED2_BIT 0x1F
#define DSGATE_DSGATE_REG_BASE_ELOG1_RESERVED2_BITWIDTH 5
// Command bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG1_COMMAND_MASK 0x70000
#define DSGATE_DSGATE_REG_BASE_ELOG1_COMMAND_SHIFT 16 
#define DSGATE_DSGATE_REG_BASE_ELOG1_COMMAND_BIT 0x7
#define DSGATE_DSGATE_REG_BASE_ELOG1_COMMAND_BITWIDTH 3
// reserved3 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG1_RESERVED3_MASK 0x80000
#define DSGATE_DSGATE_REG_BASE_ELOG1_RESERVED3_SHIFT 19 
#define DSGATE_DSGATE_REG_BASE_ELOG1_RESERVED3_BIT 0x1
#define DSGATE_DSGATE_REG_BASE_ELOG1_RESERVED3_BITWIDTH 1
// Security bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG1_SECURITY_MASK 0x300000
#define DSGATE_DSGATE_REG_BASE_ELOG1_SECURITY_SHIFT 20 
#define DSGATE_DSGATE_REG_BASE_ELOG1_SECURITY_BIT 0x3
#define DSGATE_DSGATE_REG_BASE_ELOG1_SECURITY_BITWIDTH 2
// reserved4 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG1_RESERVED4_MASK 0x7FC00000
#define DSGATE_DSGATE_REG_BASE_ELOG1_RESERVED4_SHIFT 22 
#define DSGATE_DSGATE_REG_BASE_ELOG1_RESERVED4_BIT 0x1FF
#define DSGATE_DSGATE_REG_BASE_ELOG1_RESERVED4_BITWIDTH 9
// Valid bitfiled (RW) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG1_VALID_MASK  0x80000000
#define DSGATE_DSGATE_REG_BASE_ELOG1_VALID_SHIFT 31 
#define DSGATE_DSGATE_REG_BASE_ELOG1_VALID_BIT   0x1
#define DSGATE_DSGATE_REG_BASE_ELOG1_VALID_BITWIDTH 1
// DSGATE_REG_BASE_ELOGADR2 Register
#define DSGATE_DSGATE_REG_BASE_ELOGADR2_OFS      0x00000120
// ELOGADR2 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOGADR2_ELOGADR2_MASK 0xFFFFFFFF
#define DSGATE_DSGATE_REG_BASE_ELOGADR2_ELOGADR2_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_ELOGADR2_ELOGADR2_BIT 0xFFFFFFFF
#define DSGATE_DSGATE_REG_BASE_ELOGADR2_ELOGADR2_BITWIDTH 32
// DSGATE_REG_BASE_ELOG2 Register
#define DSGATE_DSGATE_REG_BASE_ELOG2_OFS         0x00000124
// MConnID bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG2_MCONNID_MASK 0x7F
#define DSGATE_DSGATE_REG_BASE_ELOG2_MCONNID_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_ELOG2_MCONNID_BIT 0x7F
#define DSGATE_DSGATE_REG_BASE_ELOG2_MCONNID_BITWIDTH 7
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG2_RESERVED1_MASK 0x80
#define DSGATE_DSGATE_REG_BASE_ELOG2_RESERVED1_SHIFT 7 
#define DSGATE_DSGATE_REG_BASE_ELOG2_RESERVED1_BIT 0x1
#define DSGATE_DSGATE_REG_BASE_ELOG2_RESERVED1_BITWIDTH 1
// Length bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG2_LENGTH_MASK 0x700
#define DSGATE_DSGATE_REG_BASE_ELOG2_LENGTH_SHIFT 8 
#define DSGATE_DSGATE_REG_BASE_ELOG2_LENGTH_BIT  0x7
#define DSGATE_DSGATE_REG_BASE_ELOG2_LENGTH_BITWIDTH 3
// reserved2 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG2_RESERVED2_MASK 0xF800
#define DSGATE_DSGATE_REG_BASE_ELOG2_RESERVED2_SHIFT 11 
#define DSGATE_DSGATE_REG_BASE_ELOG2_RESERVED2_BIT 0x1F
#define DSGATE_DSGATE_REG_BASE_ELOG2_RESERVED2_BITWIDTH 5
// Command bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG2_COMMAND_MASK 0x70000
#define DSGATE_DSGATE_REG_BASE_ELOG2_COMMAND_SHIFT 16 
#define DSGATE_DSGATE_REG_BASE_ELOG2_COMMAND_BIT 0x7
#define DSGATE_DSGATE_REG_BASE_ELOG2_COMMAND_BITWIDTH 3
// reserved3 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG2_RESERVED3_MASK 0x80000
#define DSGATE_DSGATE_REG_BASE_ELOG2_RESERVED3_SHIFT 19 
#define DSGATE_DSGATE_REG_BASE_ELOG2_RESERVED3_BIT 0x1
#define DSGATE_DSGATE_REG_BASE_ELOG2_RESERVED3_BITWIDTH 1
// Security bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG2_SECURITY_MASK 0x300000
#define DSGATE_DSGATE_REG_BASE_ELOG2_SECURITY_SHIFT 20 
#define DSGATE_DSGATE_REG_BASE_ELOG2_SECURITY_BIT 0x3
#define DSGATE_DSGATE_REG_BASE_ELOG2_SECURITY_BITWIDTH 2
// reserved4 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG2_RESERVED4_MASK 0x7FC00000
#define DSGATE_DSGATE_REG_BASE_ELOG2_RESERVED4_SHIFT 22 
#define DSGATE_DSGATE_REG_BASE_ELOG2_RESERVED4_BIT 0x1FF
#define DSGATE_DSGATE_REG_BASE_ELOG2_RESERVED4_BITWIDTH 9
// Valid bitfiled (RW) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG2_VALID_MASK  0x80000000
#define DSGATE_DSGATE_REG_BASE_ELOG2_VALID_SHIFT 31 
#define DSGATE_DSGATE_REG_BASE_ELOG2_VALID_BIT   0x1
#define DSGATE_DSGATE_REG_BASE_ELOG2_VALID_BITWIDTH 1
// DSGATE_REG_BASE_ELOGADR3 Register
#define DSGATE_DSGATE_REG_BASE_ELOGADR3_OFS      0x00000130
// ELOGADR3 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOGADR3_ELOGADR3_MASK 0xFFFFFFFF
#define DSGATE_DSGATE_REG_BASE_ELOGADR3_ELOGADR3_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_ELOGADR3_ELOGADR3_BIT 0xFFFFFFFF
#define DSGATE_DSGATE_REG_BASE_ELOGADR3_ELOGADR3_BITWIDTH 32
// DSGATE_REG_BASE_ELOG3 Register
#define DSGATE_DSGATE_REG_BASE_ELOG3_OFS         0x00000134
// MConnID bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG3_MCONNID_MASK 0x7F
#define DSGATE_DSGATE_REG_BASE_ELOG3_MCONNID_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_ELOG3_MCONNID_BIT 0x7F
#define DSGATE_DSGATE_REG_BASE_ELOG3_MCONNID_BITWIDTH 7
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG3_RESERVED1_MASK 0x80
#define DSGATE_DSGATE_REG_BASE_ELOG3_RESERVED1_SHIFT 7 
#define DSGATE_DSGATE_REG_BASE_ELOG3_RESERVED1_BIT 0x1
#define DSGATE_DSGATE_REG_BASE_ELOG3_RESERVED1_BITWIDTH 1
// Length bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG3_LENGTH_MASK 0x700
#define DSGATE_DSGATE_REG_BASE_ELOG3_LENGTH_SHIFT 8 
#define DSGATE_DSGATE_REG_BASE_ELOG3_LENGTH_BIT  0x7
#define DSGATE_DSGATE_REG_BASE_ELOG3_LENGTH_BITWIDTH 3
// reserved2 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG3_RESERVED2_MASK 0xF800
#define DSGATE_DSGATE_REG_BASE_ELOG3_RESERVED2_SHIFT 11 
#define DSGATE_DSGATE_REG_BASE_ELOG3_RESERVED2_BIT 0x1F
#define DSGATE_DSGATE_REG_BASE_ELOG3_RESERVED2_BITWIDTH 5
// Command bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG3_COMMAND_MASK 0x70000
#define DSGATE_DSGATE_REG_BASE_ELOG3_COMMAND_SHIFT 16 
#define DSGATE_DSGATE_REG_BASE_ELOG3_COMMAND_BIT 0x7
#define DSGATE_DSGATE_REG_BASE_ELOG3_COMMAND_BITWIDTH 3
// reserved3 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG3_RESERVED3_MASK 0x80000
#define DSGATE_DSGATE_REG_BASE_ELOG3_RESERVED3_SHIFT 19 
#define DSGATE_DSGATE_REG_BASE_ELOG3_RESERVED3_BIT 0x1
#define DSGATE_DSGATE_REG_BASE_ELOG3_RESERVED3_BITWIDTH 1
// Security bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG3_SECURITY_MASK 0x300000
#define DSGATE_DSGATE_REG_BASE_ELOG3_SECURITY_SHIFT 20 
#define DSGATE_DSGATE_REG_BASE_ELOG3_SECURITY_BIT 0x3
#define DSGATE_DSGATE_REG_BASE_ELOG3_SECURITY_BITWIDTH 2
// reserved4 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG3_RESERVED4_MASK 0x7FC00000
#define DSGATE_DSGATE_REG_BASE_ELOG3_RESERVED4_SHIFT 22 
#define DSGATE_DSGATE_REG_BASE_ELOG3_RESERVED4_BIT 0x1FF
#define DSGATE_DSGATE_REG_BASE_ELOG3_RESERVED4_BITWIDTH 9
// Valid bitfiled (RW) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG3_VALID_MASK  0x80000000
#define DSGATE_DSGATE_REG_BASE_ELOG3_VALID_SHIFT 31 
#define DSGATE_DSGATE_REG_BASE_ELOG3_VALID_BIT   0x1
#define DSGATE_DSGATE_REG_BASE_ELOG3_VALID_BITWIDTH 1
// DSGATE_REG_BASE_ELOGADR4 Register
#define DSGATE_DSGATE_REG_BASE_ELOGADR4_OFS      0x00000140
// ELOGADR4 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOGADR4_ELOGADR4_MASK 0xFFFFFFFF
#define DSGATE_DSGATE_REG_BASE_ELOGADR4_ELOGADR4_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_ELOGADR4_ELOGADR4_BIT 0xFFFFFFFF
#define DSGATE_DSGATE_REG_BASE_ELOGADR4_ELOGADR4_BITWIDTH 32
// DSGATE_REG_BASE_ELOG4 Register
#define DSGATE_DSGATE_REG_BASE_ELOG4_OFS         0x00000144
// MConnID bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG4_MCONNID_MASK 0x7F
#define DSGATE_DSGATE_REG_BASE_ELOG4_MCONNID_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_ELOG4_MCONNID_BIT 0x7F
#define DSGATE_DSGATE_REG_BASE_ELOG4_MCONNID_BITWIDTH 7
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG4_RESERVED1_MASK 0x80
#define DSGATE_DSGATE_REG_BASE_ELOG4_RESERVED1_SHIFT 7 
#define DSGATE_DSGATE_REG_BASE_ELOG4_RESERVED1_BIT 0x1
#define DSGATE_DSGATE_REG_BASE_ELOG4_RESERVED1_BITWIDTH 1
// Length bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG4_LENGTH_MASK 0x700
#define DSGATE_DSGATE_REG_BASE_ELOG4_LENGTH_SHIFT 8 
#define DSGATE_DSGATE_REG_BASE_ELOG4_LENGTH_BIT  0x7
#define DSGATE_DSGATE_REG_BASE_ELOG4_LENGTH_BITWIDTH 3
// reserved2 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG4_RESERVED2_MASK 0xF800
#define DSGATE_DSGATE_REG_BASE_ELOG4_RESERVED2_SHIFT 11 
#define DSGATE_DSGATE_REG_BASE_ELOG4_RESERVED2_BIT 0x1F
#define DSGATE_DSGATE_REG_BASE_ELOG4_RESERVED2_BITWIDTH 5
// Command bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG4_COMMAND_MASK 0x70000
#define DSGATE_DSGATE_REG_BASE_ELOG4_COMMAND_SHIFT 16 
#define DSGATE_DSGATE_REG_BASE_ELOG4_COMMAND_BIT 0x7
#define DSGATE_DSGATE_REG_BASE_ELOG4_COMMAND_BITWIDTH 3
// reserved3 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG4_RESERVED3_MASK 0x80000
#define DSGATE_DSGATE_REG_BASE_ELOG4_RESERVED3_SHIFT 19 
#define DSGATE_DSGATE_REG_BASE_ELOG4_RESERVED3_BIT 0x1
#define DSGATE_DSGATE_REG_BASE_ELOG4_RESERVED3_BITWIDTH 1
// Security bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG4_SECURITY_MASK 0x300000
#define DSGATE_DSGATE_REG_BASE_ELOG4_SECURITY_SHIFT 20 
#define DSGATE_DSGATE_REG_BASE_ELOG4_SECURITY_BIT 0x3
#define DSGATE_DSGATE_REG_BASE_ELOG4_SECURITY_BITWIDTH 2
// reserved4 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG4_RESERVED4_MASK 0x7FC00000
#define DSGATE_DSGATE_REG_BASE_ELOG4_RESERVED4_SHIFT 22 
#define DSGATE_DSGATE_REG_BASE_ELOG4_RESERVED4_BIT 0x1FF
#define DSGATE_DSGATE_REG_BASE_ELOG4_RESERVED4_BITWIDTH 9
// Valid bitfiled (RW) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG4_VALID_MASK  0x80000000
#define DSGATE_DSGATE_REG_BASE_ELOG4_VALID_SHIFT 31 
#define DSGATE_DSGATE_REG_BASE_ELOG4_VALID_BIT   0x1
#define DSGATE_DSGATE_REG_BASE_ELOG4_VALID_BITWIDTH 1
// DSGATE_REG_BASE_ELOGADR5 Register
#define DSGATE_DSGATE_REG_BASE_ELOGADR5_OFS      0x00000150
// ELOGADR5 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOGADR5_ELOGADR5_MASK 0xFFFFFFFF
#define DSGATE_DSGATE_REG_BASE_ELOGADR5_ELOGADR5_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_ELOGADR5_ELOGADR5_BIT 0xFFFFFFFF
#define DSGATE_DSGATE_REG_BASE_ELOGADR5_ELOGADR5_BITWIDTH 32
// DSGATE_REG_BASE_ELOG5 Register
#define DSGATE_DSGATE_REG_BASE_ELOG5_OFS         0x00000154
// MConnID bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG5_MCONNID_MASK 0x7F
#define DSGATE_DSGATE_REG_BASE_ELOG5_MCONNID_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_ELOG5_MCONNID_BIT 0x7F
#define DSGATE_DSGATE_REG_BASE_ELOG5_MCONNID_BITWIDTH 7
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG5_RESERVED1_MASK 0x80
#define DSGATE_DSGATE_REG_BASE_ELOG5_RESERVED1_SHIFT 7 
#define DSGATE_DSGATE_REG_BASE_ELOG5_RESERVED1_BIT 0x1
#define DSGATE_DSGATE_REG_BASE_ELOG5_RESERVED1_BITWIDTH 1
// Length bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG5_LENGTH_MASK 0x700
#define DSGATE_DSGATE_REG_BASE_ELOG5_LENGTH_SHIFT 8 
#define DSGATE_DSGATE_REG_BASE_ELOG5_LENGTH_BIT  0x7
#define DSGATE_DSGATE_REG_BASE_ELOG5_LENGTH_BITWIDTH 3
// reserved2 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG5_RESERVED2_MASK 0xF800
#define DSGATE_DSGATE_REG_BASE_ELOG5_RESERVED2_SHIFT 11 
#define DSGATE_DSGATE_REG_BASE_ELOG5_RESERVED2_BIT 0x1F
#define DSGATE_DSGATE_REG_BASE_ELOG5_RESERVED2_BITWIDTH 5
// Command bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG5_COMMAND_MASK 0x70000
#define DSGATE_DSGATE_REG_BASE_ELOG5_COMMAND_SHIFT 16 
#define DSGATE_DSGATE_REG_BASE_ELOG5_COMMAND_BIT 0x7
#define DSGATE_DSGATE_REG_BASE_ELOG5_COMMAND_BITWIDTH 3
// reserved3 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG5_RESERVED3_MASK 0x80000
#define DSGATE_DSGATE_REG_BASE_ELOG5_RESERVED3_SHIFT 19 
#define DSGATE_DSGATE_REG_BASE_ELOG5_RESERVED3_BIT 0x1
#define DSGATE_DSGATE_REG_BASE_ELOG5_RESERVED3_BITWIDTH 1
// Security bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG5_SECURITY_MASK 0x300000
#define DSGATE_DSGATE_REG_BASE_ELOG5_SECURITY_SHIFT 20 
#define DSGATE_DSGATE_REG_BASE_ELOG5_SECURITY_BIT 0x3
#define DSGATE_DSGATE_REG_BASE_ELOG5_SECURITY_BITWIDTH 2
// reserved4 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG5_RESERVED4_MASK 0x7FC00000
#define DSGATE_DSGATE_REG_BASE_ELOG5_RESERVED4_SHIFT 22 
#define DSGATE_DSGATE_REG_BASE_ELOG5_RESERVED4_BIT 0x1FF
#define DSGATE_DSGATE_REG_BASE_ELOG5_RESERVED4_BITWIDTH 9
// Valid bitfiled (RW) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG5_VALID_MASK  0x80000000
#define DSGATE_DSGATE_REG_BASE_ELOG5_VALID_SHIFT 31 
#define DSGATE_DSGATE_REG_BASE_ELOG5_VALID_BIT   0x1
#define DSGATE_DSGATE_REG_BASE_ELOG5_VALID_BITWIDTH 1
// DSGATE_REG_BASE_ELOGADR6 Register
#define DSGATE_DSGATE_REG_BASE_ELOGADR6_OFS      0x00000160
// ELOGADR6 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOGADR6_ELOGADR6_MASK 0xFFFFFFFF
#define DSGATE_DSGATE_REG_BASE_ELOGADR6_ELOGADR6_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_ELOGADR6_ELOGADR6_BIT 0xFFFFFFFF
#define DSGATE_DSGATE_REG_BASE_ELOGADR6_ELOGADR6_BITWIDTH 32
// DSGATE_REG_BASE_ELOG6 Register
#define DSGATE_DSGATE_REG_BASE_ELOG6_OFS         0x00000164
// MConnID bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG6_MCONNID_MASK 0x7F
#define DSGATE_DSGATE_REG_BASE_ELOG6_MCONNID_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_ELOG6_MCONNID_BIT 0x7F
#define DSGATE_DSGATE_REG_BASE_ELOG6_MCONNID_BITWIDTH 7
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG6_RESERVED1_MASK 0x80
#define DSGATE_DSGATE_REG_BASE_ELOG6_RESERVED1_SHIFT 7 
#define DSGATE_DSGATE_REG_BASE_ELOG6_RESERVED1_BIT 0x1
#define DSGATE_DSGATE_REG_BASE_ELOG6_RESERVED1_BITWIDTH 1
// Length bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG6_LENGTH_MASK 0x700
#define DSGATE_DSGATE_REG_BASE_ELOG6_LENGTH_SHIFT 8 
#define DSGATE_DSGATE_REG_BASE_ELOG6_LENGTH_BIT  0x7
#define DSGATE_DSGATE_REG_BASE_ELOG6_LENGTH_BITWIDTH 3
// reserved2 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG6_RESERVED2_MASK 0xF800
#define DSGATE_DSGATE_REG_BASE_ELOG6_RESERVED2_SHIFT 11 
#define DSGATE_DSGATE_REG_BASE_ELOG6_RESERVED2_BIT 0x1F
#define DSGATE_DSGATE_REG_BASE_ELOG6_RESERVED2_BITWIDTH 5
// Command bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG6_COMMAND_MASK 0x70000
#define DSGATE_DSGATE_REG_BASE_ELOG6_COMMAND_SHIFT 16 
#define DSGATE_DSGATE_REG_BASE_ELOG6_COMMAND_BIT 0x7
#define DSGATE_DSGATE_REG_BASE_ELOG6_COMMAND_BITWIDTH 3
// reserved3 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG6_RESERVED3_MASK 0x80000
#define DSGATE_DSGATE_REG_BASE_ELOG6_RESERVED3_SHIFT 19 
#define DSGATE_DSGATE_REG_BASE_ELOG6_RESERVED3_BIT 0x1
#define DSGATE_DSGATE_REG_BASE_ELOG6_RESERVED3_BITWIDTH 1
// Security bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG6_SECURITY_MASK 0x300000
#define DSGATE_DSGATE_REG_BASE_ELOG6_SECURITY_SHIFT 20 
#define DSGATE_DSGATE_REG_BASE_ELOG6_SECURITY_BIT 0x3
#define DSGATE_DSGATE_REG_BASE_ELOG6_SECURITY_BITWIDTH 2
// reserved4 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG6_RESERVED4_MASK 0x7FC00000
#define DSGATE_DSGATE_REG_BASE_ELOG6_RESERVED4_SHIFT 22 
#define DSGATE_DSGATE_REG_BASE_ELOG6_RESERVED4_BIT 0x1FF
#define DSGATE_DSGATE_REG_BASE_ELOG6_RESERVED4_BITWIDTH 9
// Valid bitfiled (RW) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG6_VALID_MASK  0x80000000
#define DSGATE_DSGATE_REG_BASE_ELOG6_VALID_SHIFT 31 
#define DSGATE_DSGATE_REG_BASE_ELOG6_VALID_BIT   0x1
#define DSGATE_DSGATE_REG_BASE_ELOG6_VALID_BITWIDTH 1
// DSGATE_REG_BASE_ELOGADR7 Register
#define DSGATE_DSGATE_REG_BASE_ELOGADR7_OFS      0x00000170
// ELOGADR7 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOGADR7_ELOGADR7_MASK 0xFFFFFFFF
#define DSGATE_DSGATE_REG_BASE_ELOGADR7_ELOGADR7_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_ELOGADR7_ELOGADR7_BIT 0xFFFFFFFF
#define DSGATE_DSGATE_REG_BASE_ELOGADR7_ELOGADR7_BITWIDTH 32
// DSGATE_REG_BASE_ELOG7 Register
#define DSGATE_DSGATE_REG_BASE_ELOG7_OFS         0x00000174
// MConnID bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG7_MCONNID_MASK 0x7F
#define DSGATE_DSGATE_REG_BASE_ELOG7_MCONNID_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_ELOG7_MCONNID_BIT 0x7F
#define DSGATE_DSGATE_REG_BASE_ELOG7_MCONNID_BITWIDTH 7
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG7_RESERVED1_MASK 0x80
#define DSGATE_DSGATE_REG_BASE_ELOG7_RESERVED1_SHIFT 7 
#define DSGATE_DSGATE_REG_BASE_ELOG7_RESERVED1_BIT 0x1
#define DSGATE_DSGATE_REG_BASE_ELOG7_RESERVED1_BITWIDTH 1
// Length bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG7_LENGTH_MASK 0x700
#define DSGATE_DSGATE_REG_BASE_ELOG7_LENGTH_SHIFT 8 
#define DSGATE_DSGATE_REG_BASE_ELOG7_LENGTH_BIT  0x7
#define DSGATE_DSGATE_REG_BASE_ELOG7_LENGTH_BITWIDTH 3
// reserved2 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG7_RESERVED2_MASK 0xF800
#define DSGATE_DSGATE_REG_BASE_ELOG7_RESERVED2_SHIFT 11 
#define DSGATE_DSGATE_REG_BASE_ELOG7_RESERVED2_BIT 0x1F
#define DSGATE_DSGATE_REG_BASE_ELOG7_RESERVED2_BITWIDTH 5
// Command bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG7_COMMAND_MASK 0x70000
#define DSGATE_DSGATE_REG_BASE_ELOG7_COMMAND_SHIFT 16 
#define DSGATE_DSGATE_REG_BASE_ELOG7_COMMAND_BIT 0x7
#define DSGATE_DSGATE_REG_BASE_ELOG7_COMMAND_BITWIDTH 3
// reserved3 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG7_RESERVED3_MASK 0x80000
#define DSGATE_DSGATE_REG_BASE_ELOG7_RESERVED3_SHIFT 19 
#define DSGATE_DSGATE_REG_BASE_ELOG7_RESERVED3_BIT 0x1
#define DSGATE_DSGATE_REG_BASE_ELOG7_RESERVED3_BITWIDTH 1
// Security bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG7_SECURITY_MASK 0x300000
#define DSGATE_DSGATE_REG_BASE_ELOG7_SECURITY_SHIFT 20 
#define DSGATE_DSGATE_REG_BASE_ELOG7_SECURITY_BIT 0x3
#define DSGATE_DSGATE_REG_BASE_ELOG7_SECURITY_BITWIDTH 2
// reserved4 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG7_RESERVED4_MASK 0x7FC00000
#define DSGATE_DSGATE_REG_BASE_ELOG7_RESERVED4_SHIFT 22 
#define DSGATE_DSGATE_REG_BASE_ELOG7_RESERVED4_BIT 0x1FF
#define DSGATE_DSGATE_REG_BASE_ELOG7_RESERVED4_BITWIDTH 9
// Valid bitfiled (RW) Reset=0
#define DSGATE_DSGATE_REG_BASE_ELOG7_VALID_MASK  0x80000000
#define DSGATE_DSGATE_REG_BASE_ELOG7_VALID_SHIFT 31 
#define DSGATE_DSGATE_REG_BASE_ELOG7_VALID_BIT   0x1
#define DSGATE_DSGATE_REG_BASE_ELOG7_VALID_BITWIDTH 1
// DSGATE_REG_BASE_ERREN Register
#define DSGATE_DSGATE_REG_BASE_ERREN_OFS         0x00000200
// Enable bitfiled (RW) Reset=111111111
#define DSGATE_DSGATE_REG_BASE_ERREN_ENABLE_MASK 0x1FF
#define DSGATE_DSGATE_REG_BASE_ERREN_ENABLE_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_ERREN_ENABLE_BIT  0x1FF
#define DSGATE_DSGATE_REG_BASE_ERREN_ENABLE_BITWIDTH 9
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ERREN_RESERVED1_MASK 0xFFFFFE00
#define DSGATE_DSGATE_REG_BASE_ERREN_RESERVED1_SHIFT 9 
#define DSGATE_DSGATE_REG_BASE_ERREN_RESERVED1_BIT 0x7FFFFF
#define DSGATE_DSGATE_REG_BASE_ERREN_RESERVED1_BITWIDTH 23
// DSGATE_REG_BASE_ERRMASK Register
#define DSGATE_DSGATE_REG_BASE_ERRMASK_OFS       0x00000204
// Mask bitfiled (RW) Reset=11111111
#define DSGATE_DSGATE_REG_BASE_ERRMASK_MASK_MASK 0xFF
#define DSGATE_DSGATE_REG_BASE_ERRMASK_MASK_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_ERRMASK_MASK_BIT  0xFF
#define DSGATE_DSGATE_REG_BASE_ERRMASK_MASK_BITWIDTH 8
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ERRMASK_RESERVED1_MASK 0xFFFFFF00
#define DSGATE_DSGATE_REG_BASE_ERRMASK_RESERVED1_SHIFT 8 
#define DSGATE_DSGATE_REG_BASE_ERRMASK_RESERVED1_BIT 0xFFFFFF
#define DSGATE_DSGATE_REG_BASE_ERRMASK_RESERVED1_BITWIDTH 24
// DSGATE_REG_BASE_ERRRESP Register
#define DSGATE_DSGATE_REG_BASE_ERRRESP_OFS       0x00000208
// ERRRESP bitfiled (RW) Reset=0
#define DSGATE_DSGATE_REG_BASE_ERRRESP_ERRRESP_MASK 0x1
#define DSGATE_DSGATE_REG_BASE_ERRRESP_ERRRESP_SHIFT 0 
#define DSGATE_DSGATE_REG_BASE_ERRRESP_ERRRESP_BIT 0x1
#define DSGATE_DSGATE_REG_BASE_ERRRESP_ERRRESP_BITWIDTH 1
// reserved1 bitfiled (RO) Reset=0
#define DSGATE_DSGATE_REG_BASE_ERRRESP_RESERVED1_MASK 0xFFFFFFFE
#define DSGATE_DSGATE_REG_BASE_ERRRESP_RESERVED1_SHIFT 1 
#define DSGATE_DSGATE_REG_BASE_ERRRESP_RESERVED1_BIT 0x7FFFFFFF
#define DSGATE_DSGATE_REG_BASE_ERRRESP_RESERVED1_BITWIDTH 31

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* _DSGATE_REG_DEF_H */
