/*
 * arch/arm/mach-tz3000/include/mach/regs/fdramc_reg_def.h
 *
 * (C) Copyright TOSHIBA Corporation
 * Semiconductor & Storage Products Company 2013
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#ifndef _FDRAMC_REG_DEF_H
#define _FDRAMC_REG_DEF_H

#ifdef __cplusplus
extern  {
#endif /* __cplusplus */

// DRAMType Register
#define FDRAMC_DRAMTYPE_OFS                      0x0000041C
// DRAMType bitfiled (RW) Reset=10
#define FDRAMC_DRAMTYPE_DRAMTYPE_MASK            0xFF
#define FDRAMC_DRAMTYPE_DRAMTYPE_SHIFT           0 
#define FDRAMC_DRAMTYPE_DRAMTYPE_BIT             0xFF
#define FDRAMC_DRAMTYPE_DRAMTYPE_BITWIDTH        8
// reserved bitfiled (RO) Reset=0
#define FDRAMC_DRAMTYPE_RESERVED_MASK            0xFFFFFF00
#define FDRAMC_DRAMTYPE_RESERVED_SHIFT           8 
#define FDRAMC_DRAMTYPE_RESERVED_BIT             0xFFFFFF
#define FDRAMC_DRAMTYPE_RESERVED_BITWIDTH        24
// AddressConfig_CS Register
#define FDRAMC_ADDRESSCONFIG_CS_OFS              0x00000420
// Chip_Select_Bit_Location bitfiled (RW) Reset=0
#define FDRAMC_ADDRESSCONFIG_CS_CHIP_SELECT_BIT_LOCATION_MASK 0x3F
#define FDRAMC_ADDRESSCONFIG_CS_CHIP_SELECT_BIT_LOCATION_SHIFT 0 
#define FDRAMC_ADDRESSCONFIG_CS_CHIP_SELECT_BIT_LOCATION_BIT 0x3F
#define FDRAMC_ADDRESSCONFIG_CS_CHIP_SELECT_BIT_LOCATION_BITWIDTH 6
// reserved1 bitfiled (RO) Reset=0
#define FDRAMC_ADDRESSCONFIG_CS_RESERVED1_MASK   0xC0
#define FDRAMC_ADDRESSCONFIG_CS_RESERVED1_SHIFT  6 
#define FDRAMC_ADDRESSCONFIG_CS_RESERVED1_BIT    0x3
#define FDRAMC_ADDRESSCONFIG_CS_RESERVED1_BITWIDTH 2
// Chip_Select_Width bitfiled (RW) Reset=0
#define FDRAMC_ADDRESSCONFIG_CS_CHIP_SELECT_WIDTH_MASK 0x300
#define FDRAMC_ADDRESSCONFIG_CS_CHIP_SELECT_WIDTH_SHIFT 8 
#define FDRAMC_ADDRESSCONFIG_CS_CHIP_SELECT_WIDTH_BIT 0x3
#define FDRAMC_ADDRESSCONFIG_CS_CHIP_SELECT_WIDTH_BITWIDTH 2
// reserved2 bitfiled (RO) Reset=0
#define FDRAMC_ADDRESSCONFIG_CS_RESERVED2_MASK   0xFFFFFC00
#define FDRAMC_ADDRESSCONFIG_CS_RESERVED2_SHIFT  10 
#define FDRAMC_ADDRESSCONFIG_CS_RESERVED2_BIT    0x3FFFFF
#define FDRAMC_ADDRESSCONFIG_CS_RESERVED2_BITWIDTH 22
// AddressConfig_Row Register
#define FDRAMC_ADDRESSCONFIG_ROW_OFS             0x00000424
// Row_Bit_Location bitfiled (RW) Reset=1110
#define FDRAMC_ADDRESSCONFIG_ROW_ROW_BIT_LOCATION_MASK 0x1F
#define FDRAMC_ADDRESSCONFIG_ROW_ROW_BIT_LOCATION_SHIFT 0 
#define FDRAMC_ADDRESSCONFIG_ROW_ROW_BIT_LOCATION_BIT 0x1F
#define FDRAMC_ADDRESSCONFIG_ROW_ROW_BIT_LOCATION_BITWIDTH 5
// reserved1 bitfiled (RO) Reset=0
#define FDRAMC_ADDRESSCONFIG_ROW_RESERVED1_MASK  0xE0
#define FDRAMC_ADDRESSCONFIG_ROW_RESERVED1_SHIFT 5 
#define FDRAMC_ADDRESSCONFIG_ROW_RESERVED1_BIT   0x7
#define FDRAMC_ADDRESSCONFIG_ROW_RESERVED1_BITWIDTH 3
// Row_Address_Width bitfiled (RW) Reset=10000
#define FDRAMC_ADDRESSCONFIG_ROW_ROW_ADDRESS_WIDTH_MASK 0x1F00
#define FDRAMC_ADDRESSCONFIG_ROW_ROW_ADDRESS_WIDTH_SHIFT 8 
#define FDRAMC_ADDRESSCONFIG_ROW_ROW_ADDRESS_WIDTH_BIT 0x1F
#define FDRAMC_ADDRESSCONFIG_ROW_ROW_ADDRESS_WIDTH_BITWIDTH 5
// reserved2 bitfiled (RO) Reset=0
#define FDRAMC_ADDRESSCONFIG_ROW_RESERVED2_MASK  0xFFFFE000
#define FDRAMC_ADDRESSCONFIG_ROW_RESERVED2_SHIFT 13 
#define FDRAMC_ADDRESSCONFIG_ROW_RESERVED2_BIT   0x7FFFF
#define FDRAMC_ADDRESSCONFIG_ROW_RESERVED2_BITWIDTH 19
// AddressConfig_Bank Register
#define FDRAMC_ADDRESSCONFIG_BANK_OFS            0x00000428
// Bank_Bit_Location bitfiled (RW) Reset=1100
#define FDRAMC_ADDRESSCONFIG_BANK_BANK_BIT_LOCATION_MASK 0x1F
#define FDRAMC_ADDRESSCONFIG_BANK_BANK_BIT_LOCATION_SHIFT 0 
#define FDRAMC_ADDRESSCONFIG_BANK_BANK_BIT_LOCATION_BIT 0x1F
#define FDRAMC_ADDRESSCONFIG_BANK_BANK_BIT_LOCATION_BITWIDTH 5
// reserved1 bitfiled (RO) Reset=0
#define FDRAMC_ADDRESSCONFIG_BANK_RESERVED1_MASK 0xE0
#define FDRAMC_ADDRESSCONFIG_BANK_RESERVED1_SHIFT 5 
#define FDRAMC_ADDRESSCONFIG_BANK_RESERVED1_BIT  0x7
#define FDRAMC_ADDRESSCONFIG_BANK_RESERVED1_BITWIDTH 3
// Bank_Width bitfiled (RW) Reset=10
#define FDRAMC_ADDRESSCONFIG_BANK_BANK_WIDTH_MASK 0x300
#define FDRAMC_ADDRESSCONFIG_BANK_BANK_WIDTH_SHIFT 8 
#define FDRAMC_ADDRESSCONFIG_BANK_BANK_WIDTH_BIT 0x3
#define FDRAMC_ADDRESSCONFIG_BANK_BANK_WIDTH_BITWIDTH 2
// reserved2 bitfiled (RO) Reset=0
#define FDRAMC_ADDRESSCONFIG_BANK_RESERVED2_MASK 0xFFFFFC00
#define FDRAMC_ADDRESSCONFIG_BANK_RESERVED2_SHIFT 10 
#define FDRAMC_ADDRESSCONFIG_BANK_RESERVED2_BIT  0x3FFFFF
#define FDRAMC_ADDRESSCONFIG_BANK_RESERVED2_BITWIDTH 22
// AddressConfig_Col Register
#define FDRAMC_ADDRESSCONFIG_COL_OFS             0x0000042C
// Column_Bit_Location_0 bitfiled (RW) Reset=10
#define FDRAMC_ADDRESSCONFIG_COL_COLUMN_BIT_LOCATION_0_MASK 0x1F
#define FDRAMC_ADDRESSCONFIG_COL_COLUMN_BIT_LOCATION_0_SHIFT 0 
#define FDRAMC_ADDRESSCONFIG_COL_COLUMN_BIT_LOCATION_0_BIT 0x1F
#define FDRAMC_ADDRESSCONFIG_COL_COLUMN_BIT_LOCATION_0_BITWIDTH 5
// reserved1 bitfiled (RO) Reset=0
#define FDRAMC_ADDRESSCONFIG_COL_RESERVED1_MASK  0xE0
#define FDRAMC_ADDRESSCONFIG_COL_RESERVED1_SHIFT 5 
#define FDRAMC_ADDRESSCONFIG_COL_RESERVED1_BIT   0x7
#define FDRAMC_ADDRESSCONFIG_COL_RESERVED1_BITWIDTH 3
// Column_Address_Width_0 bitfiled (RW) Reset=1010
#define FDRAMC_ADDRESSCONFIG_COL_COLUMN_ADDRESS_WIDTH_0_MASK 0xF00
#define FDRAMC_ADDRESSCONFIG_COL_COLUMN_ADDRESS_WIDTH_0_SHIFT 8 
#define FDRAMC_ADDRESSCONFIG_COL_COLUMN_ADDRESS_WIDTH_0_BIT 0xF
#define FDRAMC_ADDRESSCONFIG_COL_COLUMN_ADDRESS_WIDTH_0_BITWIDTH 4
// reserved2 bitfiled (RO) Reset=0
#define FDRAMC_ADDRESSCONFIG_COL_RESERVED2_MASK  0xF000
#define FDRAMC_ADDRESSCONFIG_COL_RESERVED2_SHIFT 12 
#define FDRAMC_ADDRESSCONFIG_COL_RESERVED2_BIT   0xF
#define FDRAMC_ADDRESSCONFIG_COL_RESERVED2_BITWIDTH 4
// Column_Bit_Location_1 bitfiled (RW) Reset=10
#define FDRAMC_ADDRESSCONFIG_COL_COLUMN_BIT_LOCATION_1_MASK 0x1F0000
#define FDRAMC_ADDRESSCONFIG_COL_COLUMN_BIT_LOCATION_1_SHIFT 16 
#define FDRAMC_ADDRESSCONFIG_COL_COLUMN_BIT_LOCATION_1_BIT 0x1F
#define FDRAMC_ADDRESSCONFIG_COL_COLUMN_BIT_LOCATION_1_BITWIDTH 5
// reserved3 bitfiled (RO) Reset=0
#define FDRAMC_ADDRESSCONFIG_COL_RESERVED3_MASK  0xE00000
#define FDRAMC_ADDRESSCONFIG_COL_RESERVED3_SHIFT 21 
#define FDRAMC_ADDRESSCONFIG_COL_RESERVED3_BIT   0x7
#define FDRAMC_ADDRESSCONFIG_COL_RESERVED3_BITWIDTH 3
// Column_Address_Width_1 bitfiled (RW) Reset=0
#define FDRAMC_ADDRESSCONFIG_COL_COLUMN_ADDRESS_WIDTH_1_MASK 0xF000000
#define FDRAMC_ADDRESSCONFIG_COL_COLUMN_ADDRESS_WIDTH_1_SHIFT 24 
#define FDRAMC_ADDRESSCONFIG_COL_COLUMN_ADDRESS_WIDTH_1_BIT 0xF
#define FDRAMC_ADDRESSCONFIG_COL_COLUMN_ADDRESS_WIDTH_1_BITWIDTH 4
// reserved4 bitfiled (RO) Reset=0
#define FDRAMC_ADDRESSCONFIG_COL_RESERVED4_MASK  0xF0000000
#define FDRAMC_ADDRESSCONFIG_COL_RESERVED4_SHIFT 28 
#define FDRAMC_ADDRESSCONFIG_COL_RESERVED4_BIT   0xF
#define FDRAMC_ADDRESSCONFIG_COL_RESERVED4_BITWIDTH 4
// DataConfig Register
#define FDRAMC_DATACONFIG_OFS                    0x00000438
// DataConfig bitfiled (RW) Reset=0
#define FDRAMC_DATACONFIG_DATACONFIG_MASK        0x1
#define FDRAMC_DATACONFIG_DATACONFIG_SHIFT       0 
#define FDRAMC_DATACONFIG_DATACONFIG_BIT         0x1
#define FDRAMC_DATACONFIG_DATACONFIG_BITWIDTH    1
// reserved bitfiled (RO) Reset=0
#define FDRAMC_DATACONFIG_RESERVED_MASK          0xFFFFFFFE
#define FDRAMC_DATACONFIG_RESERVED_SHIFT         1 
#define FDRAMC_DATACONFIG_RESERVED_BIT           0x7FFFFFFF
#define FDRAMC_DATACONFIG_RESERVED_BITWIDTH      31
// BstLenLog Register
#define FDRAMC_BSTLENLOG_OFS                     0x00000440
// BstLenLog bitfiled (RW) Reset=0
#define FDRAMC_BSTLENLOG_BSTLENLOG_MASK          0x3
#define FDRAMC_BSTLENLOG_BSTLENLOG_SHIFT         0 
#define FDRAMC_BSTLENLOG_BSTLENLOG_BIT           0x3
#define FDRAMC_BSTLENLOG_BSTLENLOG_BITWIDTH      2
// reserved bitfiled (RO) Reset=0
#define FDRAMC_BSTLENLOG_RESERVED_MASK           0xFFFFFFFC
#define FDRAMC_BSTLENLOG_RESERVED_SHIFT          2 
#define FDRAMC_BSTLENLOG_RESERVED_BIT            0x3FFFFFFF
#define FDRAMC_BSTLENLOG_RESERVED_BITWIDTH       30
// MRRBstLenLog Register
#define FDRAMC_MRRBSTLENLOG_OFS                  0x00000444
// MRRBstLenLog bitfiled (RW) Reset=0
#define FDRAMC_MRRBSTLENLOG_MRRBSTLENLOG_MASK    0x3
#define FDRAMC_MRRBSTLENLOG_MRRBSTLENLOG_SHIFT   0 
#define FDRAMC_MRRBSTLENLOG_MRRBSTLENLOG_BIT     0x3
#define FDRAMC_MRRBSTLENLOG_MRRBSTLENLOG_BITWIDTH 2
// reserved bitfiled (RO) Reset=0
#define FDRAMC_MRRBSTLENLOG_RESERVED_MASK        0xFFFFFFFC
#define FDRAMC_MRRBSTLENLOG_RESERVED_SHIFT       2 
#define FDRAMC_MRRBSTLENLOG_RESERVED_BIT         0x3FFFFFFF
#define FDRAMC_MRRBSTLENLOG_RESERVED_BITWIDTH    30
// BWHalfMode Register
#define FDRAMC_BWHALFMODE_OFS                    0x00000450
// BWHalfMode bitfiled (RW) Reset=0
#define FDRAMC_BWHALFMODE_BWHALFMODE_MASK        0x1
#define FDRAMC_BWHALFMODE_BWHALFMODE_SHIFT       0 
#define FDRAMC_BWHALFMODE_BWHALFMODE_BIT         0x1
#define FDRAMC_BWHALFMODE_BWHALFMODE_BITWIDTH    1
// reserved bitfiled (RO) Reset=0
#define FDRAMC_BWHALFMODE_RESERVED_MASK          0xFFFFFFFE
#define FDRAMC_BWHALFMODE_RESERVED_SHIFT         1 
#define FDRAMC_BWHALFMODE_RESERVED_BIT           0x7FFFFFFF
#define FDRAMC_BWHALFMODE_RESERVED_BITWIDTH      31
// APwrDWtPd Register
#define FDRAMC_APWRDWTPD_OFS                     0x0000049C
// APwrDWtPd bitfiled (RW) Reset=10000000
#define FDRAMC_APWRDWTPD_APWRDWTPD_MASK          0xFFF
#define FDRAMC_APWRDWTPD_APWRDWTPD_SHIFT         0 
#define FDRAMC_APWRDWTPD_APWRDWTPD_BIT           0xFFF
#define FDRAMC_APWRDWTPD_APWRDWTPD_BITWIDTH      12
// reserved bitfiled (RO) Reset=0
#define FDRAMC_APWRDWTPD_RESERVED_MASK           0xFFFFF000
#define FDRAMC_APWRDWTPD_RESERVED_SHIFT          12 
#define FDRAMC_APWRDWTPD_RESERVED_BIT            0xFFFFF
#define FDRAMC_APWRDWTPD_RESERVED_BITWIDTH       20
// RftoRfMax Register
#define FDRAMC_RFTORFMAX_OFS                     0x00000504
// RftoRfMax bitfiled (RW) Reset=11000011000
#define FDRAMC_RFTORFMAX_RFTORFMAX_MASK          0x3FFF
#define FDRAMC_RFTORFMAX_RFTORFMAX_SHIFT         0 
#define FDRAMC_RFTORFMAX_RFTORFMAX_BIT           0x3FFF
#define FDRAMC_RFTORFMAX_RFTORFMAX_BITWIDTH      14
// reserved bitfiled (RO) Reset=0
#define FDRAMC_RFTORFMAX_RESERVED_MASK           0xFFFFC000
#define FDRAMC_RFTORFMAX_RESERVED_SHIFT          14 
#define FDRAMC_RFTORFMAX_RESERVED_BIT            0x3FFFF
#define FDRAMC_RFTORFMAX_RESERVED_BITWIDTH       18
// PAlltoANYPd Register
#define FDRAMC_PALLTOANYPD_OFS                   0x0000050C
// PAlltoANYPd bitfiled (RW) Reset=10
#define FDRAMC_PALLTOANYPD_PALLTOANYPD_MASK      0x7
#define FDRAMC_PALLTOANYPD_PALLTOANYPD_SHIFT     0 
#define FDRAMC_PALLTOANYPD_PALLTOANYPD_BIT       0x7
#define FDRAMC_PALLTOANYPD_PALLTOANYPD_BITWIDTH  3
// reserved bitfiled (RO) Reset=0
#define FDRAMC_PALLTOANYPD_RESERVED_MASK         0x7FFFFFF8
#define FDRAMC_PALLTOANYPD_RESERVED_SHIFT        3 
#define FDRAMC_PALLTOANYPD_RESERVED_BIT          0xFFFFFFF
#define FDRAMC_PALLTOANYPD_RESERVED_BITWIDTH     28
// reserved2 bitfiled (RO) Reset=0
#define FDRAMC_PALLTOANYPD_RESERVED2_MASK        0x80000000
#define FDRAMC_PALLTOANYPD_RESERVED2_SHIFT       31 
#define FDRAMC_PALLTOANYPD_RESERVED2_BIT         0x1
#define FDRAMC_PALLTOANYPD_RESERVED2_BITWIDTH    1
// InitMtoMPd Register
#define FDRAMC_INITMTOMPD_OFS                    0x00000514
// InitMtoMPd bitfiled (RW) Reset=0
#define FDRAMC_INITMTOMPD_INITMTOMPD_MASK        0x7
#define FDRAMC_INITMTOMPD_INITMTOMPD_SHIFT       0 
#define FDRAMC_INITMTOMPD_INITMTOMPD_BIT         0x7
#define FDRAMC_INITMTOMPD_INITMTOMPD_BITWIDTH    3
// reserved bitfiled (RO) Reset=0
#define FDRAMC_INITMTOMPD_RESERVED_MASK          0xFFFFFFF8
#define FDRAMC_INITMTOMPD_RESERVED_SHIFT         3 
#define FDRAMC_INITMTOMPD_RESERVED_BIT           0x1FFFFFFF
#define FDRAMC_INITMTOMPD_RESERVED_BITWIDTH      29
// ReftoANYPd Register
#define FDRAMC_REFTOANYPD_OFS                    0x0000051C
// ReftoANYPd bitfiled (RW) Reset=10011
#define FDRAMC_REFTOANYPD_REFTOANYPD_MASK        0x1FF
#define FDRAMC_REFTOANYPD_REFTOANYPD_SHIFT       0 
#define FDRAMC_REFTOANYPD_REFTOANYPD_BIT         0x1FF
#define FDRAMC_REFTOANYPD_REFTOANYPD_BITWIDTH    9
// reserved bitfiled (RO) Reset=0
#define FDRAMC_REFTOANYPD_RESERVED_MASK          0xFFFFFE00
#define FDRAMC_REFTOANYPD_RESERVED_SHIFT         9 
#define FDRAMC_REFTOANYPD_RESERVED_BIT           0x7FFFFF
#define FDRAMC_REFTOANYPD_RESERVED_BITWIDTH      23
// BkAtoRWPd Register
#define FDRAMC_BKATORWPD_OFS                     0x00000524
// BkAtoRWPd bitfiled (RW) Reset=0
#define FDRAMC_BKATORWPD_BKATORWPD_MASK          0x1F
#define FDRAMC_BKATORWPD_BKATORWPD_SHIFT         0 
#define FDRAMC_BKATORWPD_BKATORWPD_BIT           0x1F
#define FDRAMC_BKATORWPD_BKATORWPD_BITWIDTH      5
// reserved bitfiled (RO) Reset=0
#define FDRAMC_BKATORWPD_RESERVED_MASK           0xFFFFFFE0
#define FDRAMC_BKATORWPD_RESERVED_SHIFT          5 
#define FDRAMC_BKATORWPD_RESERVED_BIT            0x7FFFFFF
#define FDRAMC_BKATORWPD_RESERVED_BITWIDTH       27
// AtoAPd Register
#define FDRAMC_ATOAPD_OFS                        0x0000052C
// AtoAPd bitfiled (RW) Reset=1
#define FDRAMC_ATOAPD_ATOAPD_MASK                0xF
#define FDRAMC_ATOAPD_ATOAPD_SHIFT               0 
#define FDRAMC_ATOAPD_ATOAPD_BIT                 0xF
#define FDRAMC_ATOAPD_ATOAPD_BITWIDTH            4
// reserved bitfiled (RO) Reset=0
#define FDRAMC_ATOAPD_RESERVED_MASK              0xFFFFFFF0
#define FDRAMC_ATOAPD_RESERVED_SHIFT             4 
#define FDRAMC_ATOAPD_RESERVED_BIT               0xFFFFFFF
#define FDRAMC_ATOAPD_RESERVED_BITWIDTH          28
// BkRtoPPd Register
#define FDRAMC_BKRTOPPD_OFS                      0x00000530
// BkRtoPPd bitfiled (RW) Reset=11
#define FDRAMC_BKRTOPPD_BKRTOPPD_MASK            0x1F
#define FDRAMC_BKRTOPPD_BKRTOPPD_SHIFT           0 
#define FDRAMC_BKRTOPPD_BKRTOPPD_BIT             0x1F
#define FDRAMC_BKRTOPPD_BKRTOPPD_BITWIDTH        5
// reserved bitfiled (RO) Reset=0
#define FDRAMC_BKRTOPPD_RESERVED_MASK            0xFFFFFFE0
#define FDRAMC_BKRTOPPD_RESERVED_SHIFT           5 
#define FDRAMC_BKRTOPPD_RESERVED_BIT             0x7FFFFFF
#define FDRAMC_BKRTOPPD_RESERVED_BITWIDTH        27
// BkWtoPPd Register
#define FDRAMC_BKWTOPPD_OFS                      0x00000534
// BkWtoPPd bitfiled (RW) Reset=1000
#define FDRAMC_BKWTOPPD_BKWTOPPD_MASK            0x3F
#define FDRAMC_BKWTOPPD_BKWTOPPD_SHIFT           0 
#define FDRAMC_BKWTOPPD_BKWTOPPD_BIT             0x3F
#define FDRAMC_BKWTOPPD_BKWTOPPD_BITWIDTH        6
// reserved bitfiled (RO) Reset=0
#define FDRAMC_BKWTOPPD_RESERVED_MASK            0xFFFFFFC0
#define FDRAMC_BKWTOPPD_RESERVED_SHIFT           6 
#define FDRAMC_BKWTOPPD_RESERVED_BIT             0x3FFFFFF
#define FDRAMC_BKWTOPPD_RESERVED_BITWIDTH        26
// BkPtoANYPd Register
#define FDRAMC_BKPTOANYPD_OFS                    0x0000053C
// BkPtoANYPd bitfiled (RW) Reset=0
#define FDRAMC_BKPTOANYPD_BKPTOANYPD_MASK        0x1F
#define FDRAMC_BKPTOANYPD_BKPTOANYPD_SHIFT       0 
#define FDRAMC_BKPTOANYPD_BKPTOANYPD_BIT         0x1F
#define FDRAMC_BKPTOANYPD_BKPTOANYPD_BITWIDTH    5
// reserved bitfiled (RO) Reset=0
#define FDRAMC_BKPTOANYPD_RESERVED_MASK          0xFFFFFFE0
#define FDRAMC_BKPTOANYPD_RESERVED_SHIFT         5 
#define FDRAMC_BKPTOANYPD_RESERVED_BIT           0x7FFFFFF
#define FDRAMC_BKPTOANYPD_RESERVED_BITWIDTH      27
// RtoWPd Register
#define FDRAMC_RTOWPD_OFS                        0x00000544
// RtoWPd bitfiled (RW) Reset=10
#define FDRAMC_RTOWPD_RTOWPD_MASK                0x1F
#define FDRAMC_RTOWPD_RTOWPD_SHIFT               0 
#define FDRAMC_RTOWPD_RTOWPD_BIT                 0x1F
#define FDRAMC_RTOWPD_RTOWPD_BITWIDTH            5
// reserved bitfiled (RO) Reset=0
#define FDRAMC_RTOWPD_RESERVED_MASK              0xFFFFFFE0
#define FDRAMC_RTOWPD_RESERVED_SHIFT             5 
#define FDRAMC_RTOWPD_RESERVED_BIT               0x7FFFFFF
#define FDRAMC_RTOWPD_RESERVED_BITWIDTH          27
// InitCkeUptoANYPd Register
#define FDRAMC_INITCKEUPTOANYPD_OFS              0x0000054C
// InitCkeUptoANYPd bitfiled (RW) Reset=100111000100000000
#define FDRAMC_INITCKEUPTOANYPD_INITCKEUPTOANYPD_MASK 0x3FFFF
#define FDRAMC_INITCKEUPTOANYPD_INITCKEUPTOANYPD_SHIFT 0 
#define FDRAMC_INITCKEUPTOANYPD_INITCKEUPTOANYPD_BIT 0x3FFFF
#define FDRAMC_INITCKEUPTOANYPD_INITCKEUPTOANYPD_BITWIDTH 18
// reserved bitfiled (RO) Reset=0
#define FDRAMC_INITCKEUPTOANYPD_RESERVED_MASK    0xFFFC0000
#define FDRAMC_INITCKEUPTOANYPD_RESERVED_SHIFT   18 
#define FDRAMC_INITCKEUPTOANYPD_RESERVED_BIT     0x3FFF
#define FDRAMC_INITCKEUPTOANYPD_RESERVED_BITWIDTH 14
// BkAtoAPd Register
#define FDRAMC_BKATOAPD_OFS                      0x00000550
// BkAtoAPd bitfiled (RW) Reset=111
#define FDRAMC_BKATOAPD_BKATOAPD_MASK            0x3F
#define FDRAMC_BKATOAPD_BKATOAPD_SHIFT           0 
#define FDRAMC_BKATOAPD_BKATOAPD_BIT             0x3F
#define FDRAMC_BKATOAPD_BKATOAPD_BITWIDTH        6
// reserved bitfiled (RO) Reset=0
#define FDRAMC_BKATOAPD_RESERVED_MASK            0xFFFFFFC0
#define FDRAMC_BKATOAPD_RESERVED_SHIFT           6 
#define FDRAMC_BKATOAPD_RESERVED_BIT             0x3FFFFFF
#define FDRAMC_BKATOAPD_RESERVED_BITWIDTH        26
// InitOITPd Register
#define FDRAMC_INITOITPD_OFS                     0x00000554
// InitOITPd bitfiled (RW) Reset=0
#define FDRAMC_INITOITPD_INITOITPD_MASK          0x7
#define FDRAMC_INITOITPD_INITOITPD_SHIFT         0 
#define FDRAMC_INITOITPD_INITOITPD_BIT           0x7
#define FDRAMC_INITOITPD_INITOITPD_BITWIDTH      3
// reserved bitfiled (RO) Reset=0
#define FDRAMC_INITOITPD_RESERVED_MASK           0xFFFFFFF8
#define FDRAMC_INITOITPD_RESERVED_SHIFT          3 
#define FDRAMC_INITOITPD_RESERVED_BIT            0x1FFFFFFF
#define FDRAMC_INITOITPD_RESERVED_BITWIDTH       29
// BkAtoPPd Register
#define FDRAMC_BKATOPPD_OFS                      0x0000055C
// BkAtoPPd bitfiled (RW) Reset=111
#define FDRAMC_BKATOPPD_BKATOPPD_MASK            0x3F
#define FDRAMC_BKATOPPD_BKATOPPD_SHIFT           0 
#define FDRAMC_BKATOPPD_BKATOPPD_BIT             0x3F
#define FDRAMC_BKATOPPD_BKATOPPD_BITWIDTH        6
// reserved bitfiled (RO) Reset=0
#define FDRAMC_BKATOPPD_RESERVED_MASK            0xFFFFFFC0
#define FDRAMC_BKATOPPD_RESERVED_SHIFT           6 
#define FDRAMC_BKATOPPD_RESERVED_BIT             0x3FFFFFF
#define FDRAMC_BKATOPPD_RESERVED_BITWIDTH        26
// BkRAtoANYPd Register
#define FDRAMC_BKRATOANYPD_OFS                   0x00000560
// BkRAtoANYPd bitfiled (RW) Reset=11
#define FDRAMC_BKRATOANYPD_BKRATOANYPD_MASK      0x1F
#define FDRAMC_BKRATOANYPD_BKRATOANYPD_SHIFT     0 
#define FDRAMC_BKRATOANYPD_BKRATOANYPD_BIT       0x1F
#define FDRAMC_BKRATOANYPD_BKRATOANYPD_BITWIDTH  5
// reserved bitfiled (RO) Reset=0
#define FDRAMC_BKRATOANYPD_RESERVED_MASK         0xFFFFFFE0
#define FDRAMC_BKRATOANYPD_RESERVED_SHIFT        5 
#define FDRAMC_BKRATOANYPD_RESERVED_BIT          0x7FFFFFF
#define FDRAMC_BKRATOANYPD_RESERVED_BITWIDTH     27
// BkWAtoANYPd Register
#define FDRAMC_BKWATOANYPD_OFS                   0x00000564
// BkWAtoANYPd bitfiled (RW) Reset=1000
#define FDRAMC_BKWATOANYPD_BKWATOANYPD_MASK      0x3F
#define FDRAMC_BKWATOANYPD_BKWATOANYPD_SHIFT     0 
#define FDRAMC_BKWATOANYPD_BKWATOANYPD_BIT       0x3F
#define FDRAMC_BKWATOANYPD_BKWATOANYPD_BITWIDTH  6
// reserved bitfiled (RO) Reset=0
#define FDRAMC_BKWATOANYPD_RESERVED_MASK         0xFFFFFFC0
#define FDRAMC_BKWATOANYPD_RESERVED_SHIFT        6 
#define FDRAMC_BKWATOANYPD_RESERVED_BIT          0x3FFFFFF
#define FDRAMC_BKWATOANYPD_RESERVED_BITWIDTH     26
// TAWPd Register
#define FDRAMC_TAWPD_OFS                         0x00000568
// TAWPd bitfiled (RW) Reset=1000
#define FDRAMC_TAWPD_TAWPD_MASK                  0x3F
#define FDRAMC_TAWPD_TAWPD_SHIFT                 0 
#define FDRAMC_TAWPD_TAWPD_BIT                   0x3F
#define FDRAMC_TAWPD_TAWPD_BITWIDTH              6
// reserved bitfiled (RO) Reset=0
#define FDRAMC_TAWPD_RESERVED_MASK               0xFFFFFFC0
#define FDRAMC_TAWPD_RESERVED_SHIFT              6 
#define FDRAMC_TAWPD_RESERVED_BIT                0x3FFFFFF
#define FDRAMC_TAWPD_RESERVED_BITWIDTH           26
// FAWPd Register
#define FDRAMC_FAWPD_OFS                         0x0000056C
// FAWPd bitfiled (RW) Reset=1000
#define FDRAMC_FAWPD_FAWPD_MASK                  0x3F
#define FDRAMC_FAWPD_FAWPD_SHIFT                 0 
#define FDRAMC_FAWPD_FAWPD_BIT                   0x3F
#define FDRAMC_FAWPD_FAWPD_BITWIDTH              6
// reserved bitfiled (RO) Reset=0
#define FDRAMC_FAWPD_RESERVED_MASK               0x7FFFFFC0
#define FDRAMC_FAWPD_RESERVED_SHIFT              6 
#define FDRAMC_FAWPD_RESERVED_BIT                0x1FFFFFF
#define FDRAMC_FAWPD_RESERVED_BITWIDTH           25
// reserved2 bitfiled (RO) Reset=0
#define FDRAMC_FAWPD_RESERVED2_MASK              0x80000000
#define FDRAMC_FAWPD_RESERVED2_SHIFT             31 
#define FDRAMC_FAWPD_RESERVED2_BIT               0x1
#define FDRAMC_FAWPD_RESERVED2_BITWIDTH          1
// WtoRPd Register
#define FDRAMC_WTORPD_OFS                        0x00000584
// WtoRPd bitfiled (RW) Reset=100
#define FDRAMC_WTORPD_WTORPD_MASK                0x1F
#define FDRAMC_WTORPD_WTORPD_SHIFT               0 
#define FDRAMC_WTORPD_WTORPD_BIT                 0x1F
#define FDRAMC_WTORPD_WTORPD_BITWIDTH            5
// reserved bitfiled (RO) Reset=0
#define FDRAMC_WTORPD_RESERVED_MASK              0xFFFFFFE0
#define FDRAMC_WTORPD_RESERVED_SHIFT             5 
#define FDRAMC_WTORPD_RESERVED_BIT               0x7FFFFFF
#define FDRAMC_WTORPD_RESERVED_BITWIDTH          27
// InitDLLKPd Register
#define FDRAMC_INITDLLKPD_OFS                    0x0000058C
// InitDLLKPd bitfiled (RW) Reset=1100011
#define FDRAMC_INITDLLKPD_INITDLLKPD_MASK        0x3FF
#define FDRAMC_INITDLLKPD_INITDLLKPD_SHIFT       0 
#define FDRAMC_INITDLLKPD_INITDLLKPD_BIT         0x3FF
#define FDRAMC_INITDLLKPD_INITDLLKPD_BITWIDTH    10
// reserved bitfiled (RO) Reset=0
#define FDRAMC_INITDLLKPD_RESERVED_MASK          0xFFFFFC00
#define FDRAMC_INITDLLKPD_RESERVED_SHIFT         10 
#define FDRAMC_INITDLLKPD_RESERVED_BIT           0x3FFFFF
#define FDRAMC_INITDLLKPD_RESERVED_BITWIDTH      22
// SrxtoANYPd Register
#define FDRAMC_SRXTOANYPD_OFS                    0x000005B4
// SrxtoANYPd bitfiled (RW) Reset=10110
#define FDRAMC_SRXTOANYPD_SRXTOANYPD_MASK        0x1FF
#define FDRAMC_SRXTOANYPD_SRXTOANYPD_SHIFT       0 
#define FDRAMC_SRXTOANYPD_SRXTOANYPD_BIT         0x1FF
#define FDRAMC_SRXTOANYPD_SRXTOANYPD_BITWIDTH    9
// reserved bitfiled (RO) Reset=0
#define FDRAMC_SRXTOANYPD_RESERVED_MASK          0xFFFFFE00
#define FDRAMC_SRXTOANYPD_RESERVED_SHIFT         9 
#define FDRAMC_SRXTOANYPD_RESERVED_BIT           0x7FFFFF
#define FDRAMC_SRXTOANYPD_RESERVED_BITWIDTH      23
// SrxtoRWPd Register
#define FDRAMC_SRXTORWPD_OFS                     0x000005BC
// SrxtoRWPd bitfiled (RW) Reset=1100011
#define FDRAMC_SRXTORWPD_SRXTORWPD_MASK          0x3FF
#define FDRAMC_SRXTORWPD_SRXTORWPD_SHIFT         0 
#define FDRAMC_SRXTORWPD_SRXTORWPD_BIT           0x3FF
#define FDRAMC_SRXTORWPD_SRXTORWPD_BITWIDTH      10
// reserved bitfiled (RO) Reset=0
#define FDRAMC_SRXTORWPD_RESERVED_MASK           0xFFFFFC00
#define FDRAMC_SRXTORWPD_RESERVED_SHIFT          10 
#define FDRAMC_SRXTORWPD_RESERVED_BIT            0x3FFFFF
#define FDRAMC_SRXTORWPD_RESERVED_BITWIDTH       22
// PdxtoANYPd Register
#define FDRAMC_PDXTOANYPD_OFS                    0x000005C0
// PdxtoANYPd bitfiled (RW) Reset=0
#define FDRAMC_PDXTOANYPD_PDXTOANYPD_MASK        0x7
#define FDRAMC_PDXTOANYPD_PDXTOANYPD_SHIFT       0 
#define FDRAMC_PDXTOANYPD_PDXTOANYPD_BIT         0x7
#define FDRAMC_PDXTOANYPD_PDXTOANYPD_BITWIDTH    3
// reserved bitfiled (RO) Reset=0
#define FDRAMC_PDXTOANYPD_RESERVED_MASK          0xFFFFFFF8
#define FDRAMC_PDXTOANYPD_RESERVED_SHIFT         3 
#define FDRAMC_PDXTOANYPD_RESERVED_BIT           0x1FFFFFFF
#define FDRAMC_PDXTOANYPD_RESERVED_BITWIDTH      29
// PdxtoRWPd Register
#define FDRAMC_PDXTORWPD_OFS                     0x000005C4
// PdxtoRWPd bitfiled (RW) Reset=0
#define FDRAMC_PDXTORWPD_PDXTORWPD_MASK          0x1F
#define FDRAMC_PDXTORWPD_PDXTORWPD_SHIFT         0 
#define FDRAMC_PDXTORWPD_PDXTORWPD_BIT           0x1F
#define FDRAMC_PDXTORWPD_PDXTORWPD_BITWIDTH      5
// reserved bitfiled (RO) Reset=0
#define FDRAMC_PDXTORWPD_RESERVED_MASK           0xFFFFFFE0
#define FDRAMC_PDXTORWPD_RESERVED_SHIFT          5 
#define FDRAMC_PDXTORWPD_RESERVED_BIT            0x7FFFFFF
#define FDRAMC_PDXTORWPD_RESERVED_BITWIDTH       27
// MtoANYPd Register
#define FDRAMC_MTOANYPD_OFS                      0x000005CC
// MtoANYPd bitfiled (RW) Reset=101
#define FDRAMC_MTOANYPD_MTOANYPD_MASK            0xF
#define FDRAMC_MTOANYPD_MTOANYPD_SHIFT           0 
#define FDRAMC_MTOANYPD_MTOANYPD_BIT             0xF
#define FDRAMC_MTOANYPD_MTOANYPD_BITWIDTH        4
// reserved bitfiled (RO) Reset=0
#define FDRAMC_MTOANYPD_RESERVED_MASK            0xFFFFFFF0
#define FDRAMC_MTOANYPD_RESERVED_SHIFT           4 
#define FDRAMC_MTOANYPD_RESERVED_BIT             0xFFFFFFF
#define FDRAMC_MTOANYPD_RESERVED_BITWIDTH        28
// ZQCLtoANYPd Register
#define FDRAMC_ZQCLTOANYPD_OFS                   0x000005D0
// ZQCLtoANYPd bitfiled (RW) Reset=1111101
#define FDRAMC_ZQCLTOANYPD_ZQCLTOANYPD_MASK      0x1FF
#define FDRAMC_ZQCLTOANYPD_ZQCLTOANYPD_SHIFT     0 
#define FDRAMC_ZQCLTOANYPD_ZQCLTOANYPD_BIT       0x1FF
#define FDRAMC_ZQCLTOANYPD_ZQCLTOANYPD_BITWIDTH  9
// reserved bitfiled (RO) Reset=0
#define FDRAMC_ZQCLTOANYPD_RESERVED_MASK         0xFFFFFE00
#define FDRAMC_ZQCLTOANYPD_RESERVED_SHIFT        9 
#define FDRAMC_ZQCLTOANYPD_RESERVED_BIT          0x7FFFFF
#define FDRAMC_ZQCLTOANYPD_RESERVED_BITWIDTH     23
// InitZQCLtoANYPd Register
#define FDRAMC_INITZQCLTOANYPD_OFS               0x000005D4
// InitZQCLtoANYPd bitfiled (RW) Reset=11111111
#define FDRAMC_INITZQCLTOANYPD_INITZQCLTOANYPD_MASK 0x3FF
#define FDRAMC_INITZQCLTOANYPD_INITZQCLTOANYPD_SHIFT 0 
#define FDRAMC_INITZQCLTOANYPD_INITZQCLTOANYPD_BIT 0x3FF
#define FDRAMC_INITZQCLTOANYPD_INITZQCLTOANYPD_BITWIDTH 10
// reserved bitfiled (RO) Reset=0
#define FDRAMC_INITZQCLTOANYPD_RESERVED_MASK     0xFFFFFC00
#define FDRAMC_INITZQCLTOANYPD_RESERVED_SHIFT    10 
#define FDRAMC_INITZQCLTOANYPD_RESERVED_BIT      0x3FFFFF
#define FDRAMC_INITZQCLTOANYPD_RESERVED_BITWIDTH 22
// ZQCStoANYPd Register
#define FDRAMC_ZQCSTOANYPD_OFS                   0x000005DC
// ZQCStoANYPd bitfiled (RW) Reset=11111
#define FDRAMC_ZQCSTOANYPD_ZQCSTOANYPD_MASK      0x7F
#define FDRAMC_ZQCSTOANYPD_ZQCSTOANYPD_SHIFT     0 
#define FDRAMC_ZQCSTOANYPD_ZQCSTOANYPD_BIT       0x7F
#define FDRAMC_ZQCSTOANYPD_ZQCSTOANYPD_BITWIDTH  7
// reserved bitfiled (RO) Reset=0
#define FDRAMC_ZQCSTOANYPD_RESERVED_MASK         0xFFFFFF80
#define FDRAMC_ZQCSTOANYPD_RESERVED_SHIFT        7 
#define FDRAMC_ZQCSTOANYPD_RESERVED_BIT          0x1FFFFFF
#define FDRAMC_ZQCSTOANYPD_RESERVED_BITWIDTH     25
// RtoPWDPd Register
#define FDRAMC_RTOPWDPD_OFS                      0x000005FC
// RtoPWDPd bitfiled (RW) Reset=1011
#define FDRAMC_RTOPWDPD_RTOPWDPD_MASK            0x1F
#define FDRAMC_RTOPWDPD_RTOPWDPD_SHIFT           0 
#define FDRAMC_RTOPWDPD_RTOPWDPD_BIT             0x1F
#define FDRAMC_RTOPWDPD_RTOPWDPD_BITWIDTH        5
// reserved bitfiled (RO) Reset=0
#define FDRAMC_RTOPWDPD_RESERVED_MASK            0xFFFFFFE0
#define FDRAMC_RTOPWDPD_RESERVED_SHIFT           5 
#define FDRAMC_RTOPWDPD_RESERVED_BIT             0x7FFFFFF
#define FDRAMC_RTOPWDPD_RESERVED_BITWIDTH        27
// PdxtoPWDPd Register
#define FDRAMC_PDXTOPWDPD_OFS                    0x00000618
// PdxtoPWDPd bitfiled (RW) Reset=0
#define FDRAMC_PDXTOPWDPD_PDXTOPWDPD_MASK        0x1F
#define FDRAMC_PDXTOPWDPD_PDXTOPWDPD_SHIFT       0 
#define FDRAMC_PDXTOPWDPD_PDXTOPWDPD_BIT         0x1F
#define FDRAMC_PDXTOPWDPD_PDXTOPWDPD_BITWIDTH    5
// reserved bitfiled (RO) Reset=0
#define FDRAMC_PDXTOPWDPD_RESERVED_MASK          0xFFFFFFE0
#define FDRAMC_PDXTOPWDPD_RESERVED_SHIFT         5 
#define FDRAMC_PDXTOPWDPD_RESERVED_BIT           0x7FFFFFF
#define FDRAMC_PDXTOPWDPD_RESERVED_BITWIDTH      27
// SrxtoPWDPd Register
#define FDRAMC_SRXTOPWDPD_OFS                    0x0000061C
// SrxtoPWDPd bitfiled (RW) Reset=1100011
#define FDRAMC_SRXTOPWDPD_SRXTOPWDPD_MASK        0x3FF
#define FDRAMC_SRXTOPWDPD_SRXTOPWDPD_SHIFT       0 
#define FDRAMC_SRXTOPWDPD_SRXTOPWDPD_BIT         0x3FF
#define FDRAMC_SRXTOPWDPD_SRXTOPWDPD_BITWIDTH    10
// reserved bitfiled (RO) Reset=0
#define FDRAMC_SRXTOPWDPD_RESERVED_MASK          0xFFFFFC00
#define FDRAMC_SRXTOPWDPD_RESERVED_SHIFT         10 
#define FDRAMC_SRXTOPWDPD_RESERVED_BIT           0x3FFFFF
#define FDRAMC_SRXTOPWDPD_RESERVED_BITWIDTH      22
// SretoSrxPd Register
#define FDRAMC_SRETOSRXPD_OFS                    0x00000620
// SretoSrxPd bitfiled (RW) Reset=10
#define FDRAMC_SRETOSRXPD_SRETOSRXPD_MASK        0xF
#define FDRAMC_SRETOSRXPD_SRETOSRXPD_SHIFT       0 
#define FDRAMC_SRETOSRXPD_SRETOSRXPD_BIT         0xF
#define FDRAMC_SRETOSRXPD_SRETOSRXPD_BITWIDTH    4
// reserved bitfiled (RO) Reset=0
#define FDRAMC_SRETOSRXPD_RESERVED_MASK          0xFFFFFFF0
#define FDRAMC_SRETOSRXPD_RESERVED_SHIFT         4 
#define FDRAMC_SRETOSRXPD_RESERVED_BIT           0xFFFFFFF
#define FDRAMC_SRETOSRXPD_RESERVED_BITWIDTH      28
// PdetoPdxPd Register
#define FDRAMC_PDETOPDXPD_OFS                    0x00000628
// PdetoPdxPd bitfiled (RW) Reset=10
#define FDRAMC_PDETOPDXPD_PDETOPDXPD_MASK        0x7
#define FDRAMC_PDETOPDXPD_PDETOPDXPD_SHIFT       0 
#define FDRAMC_PDETOPDXPD_PDETOPDXPD_BIT         0x7
#define FDRAMC_PDETOPDXPD_PDETOPDXPD_BITWIDTH    3
// reserved bitfiled (RO) Reset=0
#define FDRAMC_PDETOPDXPD_RESERVED_MASK          0xFFFFFFF8
#define FDRAMC_PDETOPDXPD_RESERVED_SHIFT         3 
#define FDRAMC_PDETOPDXPD_RESERVED_BIT           0x1FFFFFFF
#define FDRAMC_PDETOPDXPD_RESERVED_BITWIDTH      29
// DRkWtoWPd Register
#define FDRAMC_DRKWTOWPD_OFS                     0x00000634
// DRkWtoWPd bitfiled (RW) Reset=0
#define FDRAMC_DRKWTOWPD_DRKWTOWPD_MASK          0xF
#define FDRAMC_DRKWTOWPD_DRKWTOWPD_SHIFT         0 
#define FDRAMC_DRKWTOWPD_DRKWTOWPD_BIT           0xF
#define FDRAMC_DRKWTOWPD_DRKWTOWPD_BITWIDTH      4
// reserved bitfiled (RO) Reset=0
#define FDRAMC_DRKWTOWPD_RESERVED_MASK           0xFFFFFFF0
#define FDRAMC_DRKWTOWPD_RESERVED_SHIFT          4 
#define FDRAMC_DRKWTOWPD_RESERVED_BIT            0xFFFFFFF
#define FDRAMC_DRKWTOWPD_RESERVED_BITWIDTH       28
// DRkRtoRPd Register
#define FDRAMC_DRKRTORPD_OFS                     0x00000638
// DRkRtoRPd bitfiled (RW) Reset=0
#define FDRAMC_DRKRTORPD_DRKRTORPD_MASK          0xF
#define FDRAMC_DRKRTORPD_DRKRTORPD_SHIFT         0 
#define FDRAMC_DRKRTORPD_DRKRTORPD_BIT           0xF
#define FDRAMC_DRKRTORPD_DRKRTORPD_BITWIDTH      4
// reserved bitfiled (RO) Reset=0
#define FDRAMC_DRKRTORPD_RESERVED_MASK           0xFFFFFFF0
#define FDRAMC_DRKRTORPD_RESERVED_SHIFT          4 
#define FDRAMC_DRKRTORPD_RESERVED_BIT            0xFFFFFFF
#define FDRAMC_DRKRTORPD_RESERVED_BITWIDTH       28
// WRDataLat Register
#define FDRAMC_WRDATALAT_OFS                     0x00000704
// WRDataLat bitfiled (RW) Reset=101
#define FDRAMC_WRDATALAT_WRDATALAT_MASK          0xF
#define FDRAMC_WRDATALAT_WRDATALAT_SHIFT         0 
#define FDRAMC_WRDATALAT_WRDATALAT_BIT           0xF
#define FDRAMC_WRDATALAT_WRDATALAT_BITWIDTH      4
// reserved bitfiled (RO) Reset=0
#define FDRAMC_WRDATALAT_RESERVED_MASK           0xFFFFFFF0
#define FDRAMC_WRDATALAT_RESERVED_SHIFT          4 
#define FDRAMC_WRDATALAT_RESERVED_BIT            0xFFFFFFF
#define FDRAMC_WRDATALAT_RESERVED_BITWIDTH       28
// WRDataEnLat Register
#define FDRAMC_WRDATAENLAT_OFS                   0x0000070C
// WRDataEnLat_p0 bitfiled (RW) Reset=100
#define FDRAMC_WRDATAENLAT_WRDATAENLAT_P0_MASK   0xF
#define FDRAMC_WRDATAENLAT_WRDATAENLAT_P0_SHIFT  0 
#define FDRAMC_WRDATAENLAT_WRDATAENLAT_P0_BIT    0xF
#define FDRAMC_WRDATAENLAT_WRDATAENLAT_P0_BITWIDTH 4
// reserved1 bitfiled (RO) Reset=0
#define FDRAMC_WRDATAENLAT_RESERVED1_MASK        0xF0
#define FDRAMC_WRDATAENLAT_RESERVED1_SHIFT       4 
#define FDRAMC_WRDATAENLAT_RESERVED1_BIT         0xF
#define FDRAMC_WRDATAENLAT_RESERVED1_BITWIDTH    4
// WRDataEnLat_p1 bitfiled (RW) Reset=100
#define FDRAMC_WRDATAENLAT_WRDATAENLAT_P1_MASK   0xF00
#define FDRAMC_WRDATAENLAT_WRDATAENLAT_P1_SHIFT  8 
#define FDRAMC_WRDATAENLAT_WRDATAENLAT_P1_BIT    0xF
#define FDRAMC_WRDATAENLAT_WRDATAENLAT_P1_BITWIDTH 4
// reserved2 bitfiled (RO) Reset=0
#define FDRAMC_WRDATAENLAT_RESERVED2_MASK        0xF000
#define FDRAMC_WRDATAENLAT_RESERVED2_SHIFT       12 
#define FDRAMC_WRDATAENLAT_RESERVED2_BIT         0xF
#define FDRAMC_WRDATAENLAT_RESERVED2_BITWIDTH    4
// WRDataEnLat_p2 bitfiled (RW) Reset=100
#define FDRAMC_WRDATAENLAT_WRDATAENLAT_P2_MASK   0xF0000
#define FDRAMC_WRDATAENLAT_WRDATAENLAT_P2_SHIFT  16 
#define FDRAMC_WRDATAENLAT_WRDATAENLAT_P2_BIT    0xF
#define FDRAMC_WRDATAENLAT_WRDATAENLAT_P2_BITWIDTH 4
// reserved3 bitfiled (RO) Reset=0
#define FDRAMC_WRDATAENLAT_RESERVED3_MASK        0xF00000
#define FDRAMC_WRDATAENLAT_RESERVED3_SHIFT       20 
#define FDRAMC_WRDATAENLAT_RESERVED3_BIT         0xF
#define FDRAMC_WRDATAENLAT_RESERVED3_BITWIDTH    4
// WRDataEnLat_p3 bitfiled (RW) Reset=100
#define FDRAMC_WRDATAENLAT_WRDATAENLAT_P3_MASK   0xF000000
#define FDRAMC_WRDATAENLAT_WRDATAENLAT_P3_SHIFT  24 
#define FDRAMC_WRDATAENLAT_WRDATAENLAT_P3_BIT    0xF
#define FDRAMC_WRDATAENLAT_WRDATAENLAT_P3_BITWIDTH 4
// reserved4 bitfiled (RO) Reset=0
#define FDRAMC_WRDATAENLAT_RESERVED4_MASK        0xF0000000
#define FDRAMC_WRDATAENLAT_RESERVED4_SHIFT       28 
#define FDRAMC_WRDATAENLAT_RESERVED4_BIT         0xF
#define FDRAMC_WRDATAENLAT_RESERVED4_BITWIDTH    4
// RDDataLat Register
#define FDRAMC_RDDATALAT_OFS                     0x0000071C
// RDDataLat bitfiled (RW) Reset=10001
#define FDRAMC_RDDATALAT_RDDATALAT_MASK          0x1F
#define FDRAMC_RDDATALAT_RDDATALAT_SHIFT         0 
#define FDRAMC_RDDATALAT_RDDATALAT_BIT           0x1F
#define FDRAMC_RDDATALAT_RDDATALAT_BITWIDTH      5
// reserved bitfiled (RO) Reset=0
#define FDRAMC_RDDATALAT_RESERVED_MASK           0xFFFFFFE0
#define FDRAMC_RDDATALAT_RESERVED_SHIFT          5 
#define FDRAMC_RDDATALAT_RESERVED_BIT            0x7FFFFFF
#define FDRAMC_RDDATALAT_RESERVED_BITWIDTH       27
// CTRLUPD Register
#define FDRAMC_CTRLUPD_OFS                       0x00000728
// CTRLUPD bitfiled (RW) Reset=0
#define FDRAMC_CTRLUPD_CTRLUPD_MASK              0xFFFF
#define FDRAMC_CTRLUPD_CTRLUPD_SHIFT             0 
#define FDRAMC_CTRLUPD_CTRLUPD_BIT               0xFFFF
#define FDRAMC_CTRLUPD_CTRLUPD_BITWIDTH          16
// reserved bitfiled (RO) Reset=0
#define FDRAMC_CTRLUPD_RESERVED_MASK             0xFFFF0000
#define FDRAMC_CTRLUPD_RESERVED_SHIFT            16 
#define FDRAMC_CTRLUPD_RESERVED_BIT              0xFFFF
#define FDRAMC_CTRLUPD_RESERVED_BITWIDTH         16
// RDtoCTRLUPDPd Register
#define FDRAMC_RDTOCTRLUPDPD_OFS                 0x0000072C
// RDtoCTRLUPDPd bitfiled (RW) Reset=10001
#define FDRAMC_RDTOCTRLUPDPD_RDTOCTRLUPDPD_MASK  0x3F
#define FDRAMC_RDTOCTRLUPDPD_RDTOCTRLUPDPD_SHIFT 0 
#define FDRAMC_RDTOCTRLUPDPD_RDTOCTRLUPDPD_BIT   0x3F
#define FDRAMC_RDTOCTRLUPDPD_RDTOCTRLUPDPD_BITWIDTH 6
// reserved bitfiled (RO) Reset=0
#define FDRAMC_RDTOCTRLUPDPD_RESERVED_MASK       0xFFFFFFC0
#define FDRAMC_RDTOCTRLUPDPD_RESERVED_SHIFT      6 
#define FDRAMC_RDTOCTRLUPDPD_RESERVED_BIT        0x3FFFFFF
#define FDRAMC_RDTOCTRLUPDPD_RESERVED_BITWIDTH   26
// CmdTiming Register
#define FDRAMC_CMDTIMING_OFS                     0x00000744
// CmdTiming bitfiled (RW) Reset=1
#define FDRAMC_CMDTIMING_CMDTIMING_MASK          0x3
#define FDRAMC_CMDTIMING_CMDTIMING_SHIFT         0 
#define FDRAMC_CMDTIMING_CMDTIMING_BIT           0x3
#define FDRAMC_CMDTIMING_CMDTIMING_BITWIDTH      2
// reserved bitfiled (RO) Reset=0
#define FDRAMC_CMDTIMING_RESERVED_MASK           0xFFFFFFFC
#define FDRAMC_CMDTIMING_RESERVED_SHIFT          2 
#define FDRAMC_CMDTIMING_RESERVED_BIT            0x3FFFFFFF
#define FDRAMC_CMDTIMING_RESERVED_BITWIDTH       30
// RDTiming Register
#define FDRAMC_RDTIMING_OFS                      0x00000748
// RDTiming bitfiled (RW) Reset=0
#define FDRAMC_RDTIMING_RDTIMING_MASK            0x1
#define FDRAMC_RDTIMING_RDTIMING_SHIFT           0 
#define FDRAMC_RDTIMING_RDTIMING_BIT             0x1
#define FDRAMC_RDTIMING_RDTIMING_BITWIDTH        1
// reserved bitfiled (RO) Reset=0
#define FDRAMC_RDTIMING_RESERVED_MASK            0xFFFFFFFE
#define FDRAMC_RDTIMING_RESERVED_SHIFT           1 
#define FDRAMC_RDTIMING_RESERVED_BIT             0x7FFFFFFF
#define FDRAMC_RDTIMING_RESERVED_BITWIDTH        31
// ODTMode_CS0 Register
#define FDRAMC_ODTMODE_CS0_OFS                   0x00000780
// ODTMode_CS0 bitfiled (RW) Reset=10
#define FDRAMC_ODTMODE_CS0_ODTMODE_CS0_MASK      0x3
#define FDRAMC_ODTMODE_CS0_ODTMODE_CS0_SHIFT     0 
#define FDRAMC_ODTMODE_CS0_ODTMODE_CS0_BIT       0x3
#define FDRAMC_ODTMODE_CS0_ODTMODE_CS0_BITWIDTH  2
// reserved1 bitfiled (RO) Reset=0
#define FDRAMC_ODTMODE_CS0_RESERVED1_MASK        0xFFFC
#define FDRAMC_ODTMODE_CS0_RESERVED1_SHIFT       2 
#define FDRAMC_ODTMODE_CS0_RESERVED1_BIT         0x3FFF
#define FDRAMC_ODTMODE_CS0_RESERVED1_BITWIDTH    14
// ODTMultiRankWR_CS0 bitfiled (RW) Reset=0
#define FDRAMC_ODTMODE_CS0_ODTMULTIRANKWR_CS0_MASK 0x30000
#define FDRAMC_ODTMODE_CS0_ODTMULTIRANKWR_CS0_SHIFT 16 
#define FDRAMC_ODTMODE_CS0_ODTMULTIRANKWR_CS0_BIT 0x3
#define FDRAMC_ODTMODE_CS0_ODTMULTIRANKWR_CS0_BITWIDTH 2
// reserved2 bitfiled (RO) Reset=0
#define FDRAMC_ODTMODE_CS0_RESERVED2_MASK        0xFC0000
#define FDRAMC_ODTMODE_CS0_RESERVED2_SHIFT       18 
#define FDRAMC_ODTMODE_CS0_RESERVED2_BIT         0x3F
#define FDRAMC_ODTMODE_CS0_RESERVED2_BITWIDTH    6
// ODTMultiRankRD_CS0 bitfiled (RW) Reset=0
#define FDRAMC_ODTMODE_CS0_ODTMULTIRANKRD_CS0_MASK 0x3000000
#define FDRAMC_ODTMODE_CS0_ODTMULTIRANKRD_CS0_SHIFT 24 
#define FDRAMC_ODTMODE_CS0_ODTMULTIRANKRD_CS0_BIT 0x3
#define FDRAMC_ODTMODE_CS0_ODTMULTIRANKRD_CS0_BITWIDTH 2
// reserved3 bitfiled (RO) Reset=0
#define FDRAMC_ODTMODE_CS0_RESERVED3_MASK        0xFC000000
#define FDRAMC_ODTMODE_CS0_RESERVED3_SHIFT       26 
#define FDRAMC_ODTMODE_CS0_RESERVED3_BIT         0x3F
#define FDRAMC_ODTMODE_CS0_RESERVED3_BITWIDTH    6
// ODTMode_CS1 Register
#define FDRAMC_ODTMODE_CS1_OFS                   0x00000784
// ODTMode_CS1 bitfiled (RW) Reset=10
#define FDRAMC_ODTMODE_CS1_ODTMODE_CS1_MASK      0x3
#define FDRAMC_ODTMODE_CS1_ODTMODE_CS1_SHIFT     0 
#define FDRAMC_ODTMODE_CS1_ODTMODE_CS1_BIT       0x3
#define FDRAMC_ODTMODE_CS1_ODTMODE_CS1_BITWIDTH  2
// reserved1 bitfiled (RO) Reset=0
#define FDRAMC_ODTMODE_CS1_RESERVED1_MASK        0xFFFC
#define FDRAMC_ODTMODE_CS1_RESERVED1_SHIFT       2 
#define FDRAMC_ODTMODE_CS1_RESERVED1_BIT         0x3FFF
#define FDRAMC_ODTMODE_CS1_RESERVED1_BITWIDTH    14
// ODTMultiRankWR_CS1 bitfiled (RW) Reset=0
#define FDRAMC_ODTMODE_CS1_ODTMULTIRANKWR_CS1_MASK 0x30000
#define FDRAMC_ODTMODE_CS1_ODTMULTIRANKWR_CS1_SHIFT 16 
#define FDRAMC_ODTMODE_CS1_ODTMULTIRANKWR_CS1_BIT 0x3
#define FDRAMC_ODTMODE_CS1_ODTMULTIRANKWR_CS1_BITWIDTH 2
// reserved2 bitfiled (RO) Reset=0
#define FDRAMC_ODTMODE_CS1_RESERVED2_MASK        0xFC0000
#define FDRAMC_ODTMODE_CS1_RESERVED2_SHIFT       18 
#define FDRAMC_ODTMODE_CS1_RESERVED2_BIT         0x3F
#define FDRAMC_ODTMODE_CS1_RESERVED2_BITWIDTH    6
// ODTMultiRankRD_CS1 bitfiled (RW) Reset=0
#define FDRAMC_ODTMODE_CS1_ODTMULTIRANKRD_CS1_MASK 0x3000000
#define FDRAMC_ODTMODE_CS1_ODTMULTIRANKRD_CS1_SHIFT 24 
#define FDRAMC_ODTMODE_CS1_ODTMULTIRANKRD_CS1_BIT 0x3
#define FDRAMC_ODTMODE_CS1_ODTMULTIRANKRD_CS1_BITWIDTH 2
// reserved3 bitfiled (RO) Reset=0
#define FDRAMC_ODTMODE_CS1_RESERVED3_MASK        0xFC000000
#define FDRAMC_ODTMODE_CS1_RESERVED3_SHIFT       26 
#define FDRAMC_ODTMODE_CS1_RESERVED3_BIT         0x3F
#define FDRAMC_ODTMODE_CS1_RESERVED3_BITWIDTH    6

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* _FDRAMC_REG_DEF_H */
