/*
 * arch/arm/mach-tz3000/include/mach/regs/mboot_reg_def.h
 *
 * (C) Copyright TOSHIBA Corporation
 * Semiconductor & Storage Products Company 2013
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#ifndef _MBOOT_REG_DEF_H
#define _MBOOT_REG_DEF_H

#ifdef __cplusplus
extern  {
#endif /* __cplusplus */

// BOOTREG0L Register
#define MBOOT_BOOTREG0L_OFS                      0x00000000
// BOOTREG0L bitfiled (RW) Reset=11100101100111111111000000011000
#define MBOOT_BOOTREG0L_BOOTREG0L_MASK           0xFFFFFFFF
#define MBOOT_BOOTREG0L_BOOTREG0L_SHIFT          0 
#define MBOOT_BOOTREG0L_BOOTREG0L_BIT            0xFFFFFFFF
#define MBOOT_BOOTREG0L_BOOTREG0L_BITWIDTH       32
// BOOTREG0H Register
#define MBOOT_BOOTREG0H_OFS                      0x00000004
// BOOTREG0H bitfiled (RW) Reset=11100101100111111111000000011000
#define MBOOT_BOOTREG0H_BOOTREG0H_MASK           0xFFFFFFFF
#define MBOOT_BOOTREG0H_BOOTREG0H_SHIFT          0 
#define MBOOT_BOOTREG0H_BOOTREG0H_BIT            0xFFFFFFFF
#define MBOOT_BOOTREG0H_BOOTREG0H_BITWIDTH       32
// BOOTREG1L Register
#define MBOOT_BOOTREG1L_OFS                      0x00000008
// BOOTREG1L bitfiled (RW) Reset=11100101100111111111000000011000
#define MBOOT_BOOTREG1L_BOOTREG1L_MASK           0xFFFFFFFF
#define MBOOT_BOOTREG1L_BOOTREG1L_SHIFT          0 
#define MBOOT_BOOTREG1L_BOOTREG1L_BIT            0xFFFFFFFF
#define MBOOT_BOOTREG1L_BOOTREG1L_BITWIDTH       32
// BOOTREG1H Register
#define MBOOT_BOOTREG1H_OFS                      0x0000000C
// BOOTREG1H bitfiled (RW) Reset=11100101100111111111000000011000
#define MBOOT_BOOTREG1H_BOOTREG1H_MASK           0xFFFFFFFF
#define MBOOT_BOOTREG1H_BOOTREG1H_SHIFT          0 
#define MBOOT_BOOTREG1H_BOOTREG1H_BIT            0xFFFFFFFF
#define MBOOT_BOOTREG1H_BOOTREG1H_BITWIDTH       32
// BOOTREG2L Register
#define MBOOT_BOOTREG2L_OFS                      0x00000010
// BOOTREG2L bitfiled (RW) Reset=11100101100111111111000000011000
#define MBOOT_BOOTREG2L_BOOTREG2L_MASK           0xFFFFFFFF
#define MBOOT_BOOTREG2L_BOOTREG2L_SHIFT          0 
#define MBOOT_BOOTREG2L_BOOTREG2L_BIT            0xFFFFFFFF
#define MBOOT_BOOTREG2L_BOOTREG2L_BITWIDTH       32
// BOOTREG2H Register
#define MBOOT_BOOTREG2H_OFS                      0x00000014
// BOOTREG2H bitfiled (RW) Reset=11100101100111111111000000011000
#define MBOOT_BOOTREG2H_BOOTREG2H_MASK           0xFFFFFFFF
#define MBOOT_BOOTREG2H_BOOTREG2H_SHIFT          0 
#define MBOOT_BOOTREG2H_BOOTREG2H_BIT            0xFFFFFFFF
#define MBOOT_BOOTREG2H_BOOTREG2H_BITWIDTH       32
// BOOTREG3L Register
#define MBOOT_BOOTREG3L_OFS                      0x00000018
// BOOTREG3L bitfiled (RW) Reset=11100101100111111111000000011000
#define MBOOT_BOOTREG3L_BOOTREG3L_MASK           0xFFFFFFFF
#define MBOOT_BOOTREG3L_BOOTREG3L_SHIFT          0 
#define MBOOT_BOOTREG3L_BOOTREG3L_BIT            0xFFFFFFFF
#define MBOOT_BOOTREG3L_BOOTREG3L_BITWIDTH       32
// BOOTREG3H Register
#define MBOOT_BOOTREG3H_OFS                      0x0000001C
// BOOTREG3H bitfiled (RW) Reset=11100101100111111111000000011000
#define MBOOT_BOOTREG3H_BOOTREG3H_MASK           0xFFFFFFFF
#define MBOOT_BOOTREG3H_BOOTREG3H_SHIFT          0 
#define MBOOT_BOOTREG3H_BOOTREG3H_BIT            0xFFFFFFFF
#define MBOOT_BOOTREG3H_BOOTREG3H_BITWIDTH       32
// BOOTREG4L Register
#define MBOOT_BOOTREG4L_OFS                      0x00000020
// BOOTREG4L bitfiled (RW) Reset=0
#define MBOOT_BOOTREG4L_BOOTREG4L_MASK           0xFFFFFFFF
#define MBOOT_BOOTREG4L_BOOTREG4L_SHIFT          0 
#define MBOOT_BOOTREG4L_BOOTREG4L_BIT            0xFFFFFFFF
#define MBOOT_BOOTREG4L_BOOTREG4L_BITWIDTH       32
// BOOTREG4H Register
#define MBOOT_BOOTREG4H_OFS                      0x00000024
// BOOTREG4H bitfiled (RW) Reset=1000100
#define MBOOT_BOOTREG4H_BOOTREG4H_MASK           0xFFFFFFFF
#define MBOOT_BOOTREG4H_BOOTREG4H_SHIFT          0 
#define MBOOT_BOOTREG4H_BOOTREG4H_BIT            0xFFFFFFFF
#define MBOOT_BOOTREG4H_BOOTREG4H_BITWIDTH       32
// BOOTREG5L Register
#define MBOOT_BOOTREG5L_OFS                      0x00000028
// BOOTREG5L bitfiled (RW) Reset=1000100
#define MBOOT_BOOTREG5L_BOOTREG5L_MASK           0xFFFFFFFF
#define MBOOT_BOOTREG5L_BOOTREG5L_SHIFT          0 
#define MBOOT_BOOTREG5L_BOOTREG5L_BIT            0xFFFFFFFF
#define MBOOT_BOOTREG5L_BOOTREG5L_BITWIDTH       32
// BOOTREG5H Register
#define MBOOT_BOOTREG5H_OFS                      0x0000002C
// BOOTREG5H bitfiled (RW) Reset=1000100
#define MBOOT_BOOTREG5H_BOOTREG5H_MASK           0xFFFFFFFF
#define MBOOT_BOOTREG5H_BOOTREG5H_SHIFT          0 
#define MBOOT_BOOTREG5H_BOOTREG5H_BIT            0xFFFFFFFF
#define MBOOT_BOOTREG5H_BOOTREG5H_BITWIDTH       32
// BOOTREG6L Register
#define MBOOT_BOOTREG6L_OFS                      0x00000030
// BOOTREG6L bitfiled (RW) Reset=1000100
#define MBOOT_BOOTREG6L_BOOTREG6L_MASK           0xFFFFFFFF
#define MBOOT_BOOTREG6L_BOOTREG6L_SHIFT          0 
#define MBOOT_BOOTREG6L_BOOTREG6L_BIT            0xFFFFFFFF
#define MBOOT_BOOTREG6L_BOOTREG6L_BITWIDTH       32
// BOOTREG6H Register
#define MBOOT_BOOTREG6H_OFS                      0x00000034
// BOOTREG6H bitfiled (RW) Reset=1000100
#define MBOOT_BOOTREG6H_BOOTREG6H_MASK           0xFFFFFFFF
#define MBOOT_BOOTREG6H_BOOTREG6H_SHIFT          0 
#define MBOOT_BOOTREG6H_BOOTREG6H_BIT            0xFFFFFFFF
#define MBOOT_BOOTREG6H_BOOTREG6H_BITWIDTH       32
// BOOTREG7L Register
#define MBOOT_BOOTREG7L_OFS                      0x00000038
// BOOTREG7L bitfiled (RW) Reset=1000100
#define MBOOT_BOOTREG7L_BOOTREG7L_MASK           0xFFFFFFFF
#define MBOOT_BOOTREG7L_BOOTREG7L_SHIFT          0 
#define MBOOT_BOOTREG7L_BOOTREG7L_BIT            0xFFFFFFFF
#define MBOOT_BOOTREG7L_BOOTREG7L_BITWIDTH       32
// BOOTREG7H Register
#define MBOOT_BOOTREG7H_OFS                      0x0000003C
// BOOTREG7H bitfiled (RW) Reset=1000100
#define MBOOT_BOOTREG7H_BOOTREG7H_MASK           0xFFFFFFFF
#define MBOOT_BOOTREG7H_BOOTREG7H_SHIFT          0 
#define MBOOT_BOOTREG7H_BOOTREG7H_BIT            0xFFFFFFFF
#define MBOOT_BOOTREG7H_BOOTREG7H_BITWIDTH       32
// BOOTREG8L Register
#define MBOOT_BOOTREG8L_OFS                      0x00000040
// BOOTREG8L bitfiled (RW) Reset=11100011001000001111000000000011
#define MBOOT_BOOTREG8L_BOOTREG8L_MASK           0xFFFFFFFF
#define MBOOT_BOOTREG8L_BOOTREG8L_SHIFT          0 
#define MBOOT_BOOTREG8L_BOOTREG8L_BIT            0xFFFFFFFF
#define MBOOT_BOOTREG8L_BOOTREG8L_BITWIDTH       32
// BOOTREG8H Register
#define MBOOT_BOOTREG8H_OFS                      0x00000044
// BOOTREG8H bitfiled (RW) Reset=11100101000111111111000000000100
#define MBOOT_BOOTREG8H_BOOTREG8H_MASK           0xFFFFFFFF
#define MBOOT_BOOTREG8H_BOOTREG8H_SHIFT          0 
#define MBOOT_BOOTREG8H_BOOTREG8H_BIT            0xFFFFFFFF
#define MBOOT_BOOTREG8H_BOOTREG8H_BITWIDTH       32
// BOOTREG9L Register
#define MBOOT_BOOTREG9L_OFS                      0x00000048
// BOOTREG9L bitfiled (RW) Reset=0
#define MBOOT_BOOTREG9L_BOOTREG9L_MASK           0xFFFFFFFF
#define MBOOT_BOOTREG9L_BOOTREG9L_SHIFT          0 
#define MBOOT_BOOTREG9L_BOOTREG9L_BIT            0xFFFFFFFF
#define MBOOT_BOOTREG9L_BOOTREG9L_BITWIDTH       32
// BOOTREG9H Register
#define MBOOT_BOOTREG9H_OFS                      0x0000004C
// BOOTREG9H bitfiled (RW) Reset=0
#define MBOOT_BOOTREG9H_BOOTREG9H_MASK           0xFFFFFFFF
#define MBOOT_BOOTREG9H_BOOTREG9H_SHIFT          0 
#define MBOOT_BOOTREG9H_BOOTREG9H_BIT            0xFFFFFFFF
#define MBOOT_BOOTREG9H_BOOTREG9H_BITWIDTH       32
// BOOTREGAL Register
#define MBOOT_BOOTREGAL_OFS                      0x00000050
// BOOTREGAL bitfiled (RW) Reset=0
#define MBOOT_BOOTREGAL_BOOTREGAL_MASK           0xFFFFFFFF
#define MBOOT_BOOTREGAL_BOOTREGAL_SHIFT          0 
#define MBOOT_BOOTREGAL_BOOTREGAL_BIT            0xFFFFFFFF
#define MBOOT_BOOTREGAL_BOOTREGAL_BITWIDTH       32
// BOOTREGAH Register
#define MBOOT_BOOTREGAH_OFS                      0x00000054
// BOOTREGAH bitfiled (RW) Reset=0
#define MBOOT_BOOTREGAH_BOOTREGAH_MASK           0xFFFFFFFF
#define MBOOT_BOOTREGAH_BOOTREGAH_SHIFT          0 
#define MBOOT_BOOTREGAH_BOOTREGAH_BIT            0xFFFFFFFF
#define MBOOT_BOOTREGAH_BOOTREGAH_BITWIDTH       32
// BOOTREGBL Register
#define MBOOT_BOOTREGBL_OFS                      0x00000058
// BOOTREGBL bitfiled (RW) Reset=0
#define MBOOT_BOOTREGBL_BOOTREGBL_MASK           0xFFFFFFFF
#define MBOOT_BOOTREGBL_BOOTREGBL_SHIFT          0 
#define MBOOT_BOOTREGBL_BOOTREGBL_BIT            0xFFFFFFFF
#define MBOOT_BOOTREGBL_BOOTREGBL_BITWIDTH       32
// BOOTREGBH Register
#define MBOOT_BOOTREGBH_OFS                      0x0000005C
// BOOTREGBH bitfiled (RW) Reset=0
#define MBOOT_BOOTREGBH_BOOTREGBH_MASK           0xFFFFFFFF
#define MBOOT_BOOTREGBH_BOOTREGBH_SHIFT          0 
#define MBOOT_BOOTREGBH_BOOTREGBH_BIT            0xFFFFFFFF
#define MBOOT_BOOTREGBH_BOOTREGBH_BITWIDTH       32
// BOOTREGCL Register
#define MBOOT_BOOTREGCL_OFS                      0x00000060
// BOOTREGCL bitfiled (RW) Reset=0
#define MBOOT_BOOTREGCL_BOOTREGCL_MASK           0xFFFFFFFF
#define MBOOT_BOOTREGCL_BOOTREGCL_SHIFT          0 
#define MBOOT_BOOTREGCL_BOOTREGCL_BIT            0xFFFFFFFF
#define MBOOT_BOOTREGCL_BOOTREGCL_BITWIDTH       32
// BOOTREGCH Register
#define MBOOT_BOOTREGCH_OFS                      0x00000064
// BOOTREGCH bitfiled (RW) Reset=0
#define MBOOT_BOOTREGCH_BOOTREGCH_MASK           0xFFFFFFFF
#define MBOOT_BOOTREGCH_BOOTREGCH_SHIFT          0 
#define MBOOT_BOOTREGCH_BOOTREGCH_BIT            0xFFFFFFFF
#define MBOOT_BOOTREGCH_BOOTREGCH_BITWIDTH       32
// BOOTREGDL Register
#define MBOOT_BOOTREGDL_OFS                      0x00000068
// BOOTREGDL bitfiled (RW) Reset=0
#define MBOOT_BOOTREGDL_BOOTREGDL_MASK           0xFFFFFFFF
#define MBOOT_BOOTREGDL_BOOTREGDL_SHIFT          0 
#define MBOOT_BOOTREGDL_BOOTREGDL_BIT            0xFFFFFFFF
#define MBOOT_BOOTREGDL_BOOTREGDL_BITWIDTH       32
// BOOTREGDH Register
#define MBOOT_BOOTREGDH_OFS                      0x0000006C
// BOOTREGDH bitfiled (RW) Reset=0
#define MBOOT_BOOTREGDH_BOOTREGDH_MASK           0xFFFFFFFF
#define MBOOT_BOOTREGDH_BOOTREGDH_SHIFT          0 
#define MBOOT_BOOTREGDH_BOOTREGDH_BIT            0xFFFFFFFF
#define MBOOT_BOOTREGDH_BOOTREGDH_BITWIDTH       32
// BOOTREGEL Register
#define MBOOT_BOOTREGEL_OFS                      0x00000070
// BOOTREGEL bitfiled (RW) Reset=0
#define MBOOT_BOOTREGEL_BOOTREGEL_MASK           0xFFFFFFFF
#define MBOOT_BOOTREGEL_BOOTREGEL_SHIFT          0 
#define MBOOT_BOOTREGEL_BOOTREGEL_BIT            0xFFFFFFFF
#define MBOOT_BOOTREGEL_BOOTREGEL_BITWIDTH       32
// BOOTREGEH Register
#define MBOOT_BOOTREGEH_OFS                      0x00000074
// BOOTREGEH bitfiled (RW) Reset=0
#define MBOOT_BOOTREGEH_BOOTREGEH_MASK           0xFFFFFFFF
#define MBOOT_BOOTREGEH_BOOTREGEH_SHIFT          0 
#define MBOOT_BOOTREGEH_BOOTREGEH_BIT            0xFFFFFFFF
#define MBOOT_BOOTREGEH_BOOTREGEH_BITWIDTH       32
// BOOTREGFL Register
#define MBOOT_BOOTREGFL_OFS                      0x00000078
// BOOTREGFL bitfiled (RW) Reset=0
#define MBOOT_BOOTREGFL_BOOTREGFL_MASK           0xFFFFFFFF
#define MBOOT_BOOTREGFL_BOOTREGFL_SHIFT          0 
#define MBOOT_BOOTREGFL_BOOTREGFL_BIT            0xFFFFFFFF
#define MBOOT_BOOTREGFL_BOOTREGFL_BITWIDTH       32
// BOOTREGFH Register
#define MBOOT_BOOTREGFH_OFS                      0x0000007C
// BOOTREGFH bitfiled (RW) Reset=0
#define MBOOT_BOOTREGFH_BOOTREGFH_MASK           0xFFFFFFFF
#define MBOOT_BOOTREGFH_BOOTREGFH_SHIFT          0 
#define MBOOT_BOOTREGFH_BOOTREGFH_BIT            0xFFFFFFFF
#define MBOOT_BOOTREGFH_BOOTREGFH_BITWIDTH       32

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* _MBOOT_REG_DEF_H */
