/*
 * arch/arm/mach-tz3000/include/mach/regs/si2c1_reg_def.h
 *
 * (C) Copyright TOSHIBA Corporation
 * Semiconductor & Storage Products Company 2013
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#ifndef _SI2C1_REG_DEF_H
#define _SI2C1_REG_DEF_H

#ifdef __cplusplus
extern  {
#endif /* __cplusplus */

// SIC1_IC_CON Register
#define SI2C1_SIC1_IC_CON_OFS                    0x00000000
// MASTER_MODE bitfiled (RW) Reset=1
#define SI2C1_SIC1_IC_CON_MASTER_MODE_MASK       0x1
#define SI2C1_SIC1_IC_CON_MASTER_MODE_SHIFT      0 
#define SI2C1_SIC1_IC_CON_MASTER_MODE_BIT        0x1
#define SI2C1_SIC1_IC_CON_MASTER_MODE_BITWIDTH   1
// SPEED bitfiled (RW) Reset=10
#define SI2C1_SIC1_IC_CON_SPEED_MASK             0x6
#define SI2C1_SIC1_IC_CON_SPEED_SHIFT            1 
#define SI2C1_SIC1_IC_CON_SPEED_BIT              0x3
#define SI2C1_SIC1_IC_CON_SPEED_BITWIDTH         2
// IC_10BITADDR_SLAVE bitfiled (RW) Reset=1
#define SI2C1_SIC1_IC_CON_IC_10BITADDR_SLAVE_MASK 0x8
#define SI2C1_SIC1_IC_CON_IC_10BITADDR_SLAVE_SHIFT 3 
#define SI2C1_SIC1_IC_CON_IC_10BITADDR_SLAVE_BIT 0x1
#define SI2C1_SIC1_IC_CON_IC_10BITADDR_SLAVE_BITWIDTH 1
// IC_10BITADDR_MASTER bitfiled (RO) Reset=1
#define SI2C1_SIC1_IC_CON_IC_10BITADDR_MASTER_MASK 0x10
#define SI2C1_SIC1_IC_CON_IC_10BITADDR_MASTER_SHIFT 4 
#define SI2C1_SIC1_IC_CON_IC_10BITADDR_MASTER_BIT 0x1
#define SI2C1_SIC1_IC_CON_IC_10BITADDR_MASTER_BITWIDTH 1
// IC_RESTART_EN bitfiled (RW) Reset=1
#define SI2C1_SIC1_IC_CON_IC_RESTART_EN_MASK     0x20
#define SI2C1_SIC1_IC_CON_IC_RESTART_EN_SHIFT    5 
#define SI2C1_SIC1_IC_CON_IC_RESTART_EN_BIT      0x1
#define SI2C1_SIC1_IC_CON_IC_RESTART_EN_BITWIDTH 1
// IC_SLAVE_DISABLE bitfiled (RW) Reset=1
#define SI2C1_SIC1_IC_CON_IC_SLAVE_DISABLE_MASK  0x40
#define SI2C1_SIC1_IC_CON_IC_SLAVE_DISABLE_SHIFT 6 
#define SI2C1_SIC1_IC_CON_IC_SLAVE_DISABLE_BIT   0x1
#define SI2C1_SIC1_IC_CON_IC_SLAVE_DISABLE_BITWIDTH 1
// reserved bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_CON_RESERVED_MASK          0xFFFFFF80
#define SI2C1_SIC1_IC_CON_RESERVED_SHIFT         7 
#define SI2C1_SIC1_IC_CON_RESERVED_BIT           0x1FFFFFF
#define SI2C1_SIC1_IC_CON_RESERVED_BITWIDTH      25
// SIC1_IC_TAR Register
#define SI2C1_SIC1_IC_TAR_OFS                    0x00000004
// IC_TAR bitfiled (RW) Reset=1010101
#define SI2C1_SIC1_IC_TAR_IC_TAR_MASK            0x3FF
#define SI2C1_SIC1_IC_TAR_IC_TAR_SHIFT           0 
#define SI2C1_SIC1_IC_TAR_IC_TAR_BIT             0x3FF
#define SI2C1_SIC1_IC_TAR_IC_TAR_BITWIDTH        10
// GC_OR_START bitfiled (RW) Reset=0
#define SI2C1_SIC1_IC_TAR_GC_OR_START_MASK       0x400
#define SI2C1_SIC1_IC_TAR_GC_OR_START_SHIFT      10 
#define SI2C1_SIC1_IC_TAR_GC_OR_START_BIT        0x1
#define SI2C1_SIC1_IC_TAR_GC_OR_START_BITWIDTH   1
// SPECIAL bitfiled (RW) Reset=0
#define SI2C1_SIC1_IC_TAR_SPECIAL_MASK           0x800
#define SI2C1_SIC1_IC_TAR_SPECIAL_SHIFT          11 
#define SI2C1_SIC1_IC_TAR_SPECIAL_BIT            0x1
#define SI2C1_SIC1_IC_TAR_SPECIAL_BITWIDTH       1
// IC_10BITADDR_MASTER bitfiled (RW) Reset=1
#define SI2C1_SIC1_IC_TAR_IC_10BITADDR_MASTER_MASK 0x1000
#define SI2C1_SIC1_IC_TAR_IC_10BITADDR_MASTER_SHIFT 12 
#define SI2C1_SIC1_IC_TAR_IC_10BITADDR_MASTER_BIT 0x1
#define SI2C1_SIC1_IC_TAR_IC_10BITADDR_MASTER_BITWIDTH 1
// reserved bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_TAR_RESERVED_MASK          0xFFFFE000
#define SI2C1_SIC1_IC_TAR_RESERVED_SHIFT         13 
#define SI2C1_SIC1_IC_TAR_RESERVED_BIT           0x7FFFF
#define SI2C1_SIC1_IC_TAR_RESERVED_BITWIDTH      19
// SIC1_IC_SAR Register
#define SI2C1_SIC1_IC_SAR_OFS                    0x00000008
// IC_TAR bitfiled (RW) Reset=1010101
#define SI2C1_SIC1_IC_SAR_IC_TAR_MASK            0x3FF
#define SI2C1_SIC1_IC_SAR_IC_TAR_SHIFT           0 
#define SI2C1_SIC1_IC_SAR_IC_TAR_BIT             0x3FF
#define SI2C1_SIC1_IC_SAR_IC_TAR_BITWIDTH        10
// reserved bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_SAR_RESERVED_MASK          0xFFFFFC00
#define SI2C1_SIC1_IC_SAR_RESERVED_SHIFT         10 
#define SI2C1_SIC1_IC_SAR_RESERVED_BIT           0x3FFFFF
#define SI2C1_SIC1_IC_SAR_RESERVED_BITWIDTH      22
// SIC1_IC_DATA_CMD Register
#define SI2C1_SIC1_IC_DATA_CMD_OFS               0x00000010
// DAT bitfiled (RW) Reset=0
#define SI2C1_SIC1_IC_DATA_CMD_DAT_MASK          0xFF
#define SI2C1_SIC1_IC_DATA_CMD_DAT_SHIFT         0 
#define SI2C1_SIC1_IC_DATA_CMD_DAT_BIT           0xFF
#define SI2C1_SIC1_IC_DATA_CMD_DAT_BITWIDTH      8
// CMD bitfiled (RW) Reset=0
#define SI2C1_SIC1_IC_DATA_CMD_CMD_MASK          0x100
#define SI2C1_SIC1_IC_DATA_CMD_CMD_SHIFT         8 
#define SI2C1_SIC1_IC_DATA_CMD_CMD_BIT           0x1
#define SI2C1_SIC1_IC_DATA_CMD_CMD_BITWIDTH      1
// STOP bitfiled (RW) Reset=0
#define SI2C1_SIC1_IC_DATA_CMD_STOP_MASK         0x200
#define SI2C1_SIC1_IC_DATA_CMD_STOP_SHIFT        9 
#define SI2C1_SIC1_IC_DATA_CMD_STOP_BIT          0x1
#define SI2C1_SIC1_IC_DATA_CMD_STOP_BITWIDTH     1
// RESTART bitfiled (RW) Reset=0
#define SI2C1_SIC1_IC_DATA_CMD_RESTART_MASK      0x400
#define SI2C1_SIC1_IC_DATA_CMD_RESTART_SHIFT     10 
#define SI2C1_SIC1_IC_DATA_CMD_RESTART_BIT       0x1
#define SI2C1_SIC1_IC_DATA_CMD_RESTART_BITWIDTH  1
// reserved bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_DATA_CMD_RESERVED_MASK     0xFFFFF800
#define SI2C1_SIC1_IC_DATA_CMD_RESERVED_SHIFT    11 
#define SI2C1_SIC1_IC_DATA_CMD_RESERVED_BIT      0x1FFFFF
#define SI2C1_SIC1_IC_DATA_CMD_RESERVED_BITWIDTH 21
// SIC1_IC_SS_SCL_HCNT Register
#define SI2C1_SIC1_IC_SS_SCL_HCNT_OFS            0x00000014
// IC_SS_SCL_HCNT bitfiled (RW) Reset=11001000
#define SI2C1_SIC1_IC_SS_SCL_HCNT_IC_SS_SCL_HCNT_MASK 0xFFFF
#define SI2C1_SIC1_IC_SS_SCL_HCNT_IC_SS_SCL_HCNT_SHIFT 0 
#define SI2C1_SIC1_IC_SS_SCL_HCNT_IC_SS_SCL_HCNT_BIT 0xFFFF
#define SI2C1_SIC1_IC_SS_SCL_HCNT_IC_SS_SCL_HCNT_BITWIDTH 16
// reserved bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_SS_SCL_HCNT_RESERVED_MASK  0xFFFF0000
#define SI2C1_SIC1_IC_SS_SCL_HCNT_RESERVED_SHIFT 16 
#define SI2C1_SIC1_IC_SS_SCL_HCNT_RESERVED_BIT   0xFFFF
#define SI2C1_SIC1_IC_SS_SCL_HCNT_RESERVED_BITWIDTH 16
// SIC1_IC_SS_SCL_LCNT Register
#define SI2C1_SIC1_IC_SS_SCL_LCNT_OFS            0x00000018
// IC_SS_SCL_LCNT bitfiled (RW) Reset=11101011
#define SI2C1_SIC1_IC_SS_SCL_LCNT_IC_SS_SCL_LCNT_MASK 0xFFFF
#define SI2C1_SIC1_IC_SS_SCL_LCNT_IC_SS_SCL_LCNT_SHIFT 0 
#define SI2C1_SIC1_IC_SS_SCL_LCNT_IC_SS_SCL_LCNT_BIT 0xFFFF
#define SI2C1_SIC1_IC_SS_SCL_LCNT_IC_SS_SCL_LCNT_BITWIDTH 16
// reserved bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_SS_SCL_LCNT_RESERVED_MASK  0xFFFF0000
#define SI2C1_SIC1_IC_SS_SCL_LCNT_RESERVED_SHIFT 16 
#define SI2C1_SIC1_IC_SS_SCL_LCNT_RESERVED_BIT   0xFFFF
#define SI2C1_SIC1_IC_SS_SCL_LCNT_RESERVED_BITWIDTH 16
// SIC1_IC_FS_SCL_HCNT Register
#define SI2C1_SIC1_IC_FS_SCL_HCNT_OFS            0x0000001C
// IC_FS_SCL_HCNT bitfiled (RW) Reset=11110
#define SI2C1_SIC1_IC_FS_SCL_HCNT_IC_FS_SCL_HCNT_MASK 0xFFFF
#define SI2C1_SIC1_IC_FS_SCL_HCNT_IC_FS_SCL_HCNT_SHIFT 0 
#define SI2C1_SIC1_IC_FS_SCL_HCNT_IC_FS_SCL_HCNT_BIT 0xFFFF
#define SI2C1_SIC1_IC_FS_SCL_HCNT_IC_FS_SCL_HCNT_BITWIDTH 16
// reserved bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_FS_SCL_HCNT_RESERVED_MASK  0xFFFF0000
#define SI2C1_SIC1_IC_FS_SCL_HCNT_RESERVED_SHIFT 16 
#define SI2C1_SIC1_IC_FS_SCL_HCNT_RESERVED_BIT   0xFFFF
#define SI2C1_SIC1_IC_FS_SCL_HCNT_RESERVED_BITWIDTH 16
// SIC1_IC_FS_SCL_LCNT Register
#define SI2C1_SIC1_IC_FS_SCL_LCNT_OFS            0x00000020
// IC_FS_SCL_LCNT bitfiled (RW) Reset=1000001
#define SI2C1_SIC1_IC_FS_SCL_LCNT_IC_FS_SCL_LCNT_MASK 0xFFFF
#define SI2C1_SIC1_IC_FS_SCL_LCNT_IC_FS_SCL_LCNT_SHIFT 0 
#define SI2C1_SIC1_IC_FS_SCL_LCNT_IC_FS_SCL_LCNT_BIT 0xFFFF
#define SI2C1_SIC1_IC_FS_SCL_LCNT_IC_FS_SCL_LCNT_BITWIDTH 16
// reserved bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_FS_SCL_LCNT_RESERVED_MASK  0xFFFF0000
#define SI2C1_SIC1_IC_FS_SCL_LCNT_RESERVED_SHIFT 16 
#define SI2C1_SIC1_IC_FS_SCL_LCNT_RESERVED_BIT   0xFFFF
#define SI2C1_SIC1_IC_FS_SCL_LCNT_RESERVED_BITWIDTH 16
// SIC1_IC_INTR_STAT Register
#define SI2C1_SIC1_IC_INTR_STAT_OFS              0x0000002C
// R_RX_UNDER bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_INTR_STAT_R_RX_UNDER_MASK  0x1
#define SI2C1_SIC1_IC_INTR_STAT_R_RX_UNDER_SHIFT 0 
#define SI2C1_SIC1_IC_INTR_STAT_R_RX_UNDER_BIT   0x1
#define SI2C1_SIC1_IC_INTR_STAT_R_RX_UNDER_BITWIDTH 1
// R_RX_OVER bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_INTR_STAT_R_RX_OVER_MASK   0x2
#define SI2C1_SIC1_IC_INTR_STAT_R_RX_OVER_SHIFT  1 
#define SI2C1_SIC1_IC_INTR_STAT_R_RX_OVER_BIT    0x1
#define SI2C1_SIC1_IC_INTR_STAT_R_RX_OVER_BITWIDTH 1
// R_RX_FULL bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_INTR_STAT_R_RX_FULL_MASK   0x4
#define SI2C1_SIC1_IC_INTR_STAT_R_RX_FULL_SHIFT  2 
#define SI2C1_SIC1_IC_INTR_STAT_R_RX_FULL_BIT    0x1
#define SI2C1_SIC1_IC_INTR_STAT_R_RX_FULL_BITWIDTH 1
// R_TX_OVER bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_INTR_STAT_R_TX_OVER_MASK   0x8
#define SI2C1_SIC1_IC_INTR_STAT_R_TX_OVER_SHIFT  3 
#define SI2C1_SIC1_IC_INTR_STAT_R_TX_OVER_BIT    0x1
#define SI2C1_SIC1_IC_INTR_STAT_R_TX_OVER_BITWIDTH 1
// R_TX_EMPTY bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_INTR_STAT_R_TX_EMPTY_MASK  0x10
#define SI2C1_SIC1_IC_INTR_STAT_R_TX_EMPTY_SHIFT 4 
#define SI2C1_SIC1_IC_INTR_STAT_R_TX_EMPTY_BIT   0x1
#define SI2C1_SIC1_IC_INTR_STAT_R_TX_EMPTY_BITWIDTH 1
// R_RD_REQ bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_INTR_STAT_R_RD_REQ_MASK    0x20
#define SI2C1_SIC1_IC_INTR_STAT_R_RD_REQ_SHIFT   5 
#define SI2C1_SIC1_IC_INTR_STAT_R_RD_REQ_BIT     0x1
#define SI2C1_SIC1_IC_INTR_STAT_R_RD_REQ_BITWIDTH 1
// R_TX_ABRT bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_INTR_STAT_R_TX_ABRT_MASK   0x40
#define SI2C1_SIC1_IC_INTR_STAT_R_TX_ABRT_SHIFT  6 
#define SI2C1_SIC1_IC_INTR_STAT_R_TX_ABRT_BIT    0x1
#define SI2C1_SIC1_IC_INTR_STAT_R_TX_ABRT_BITWIDTH 1
// R_RX_DONE bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_INTR_STAT_R_RX_DONE_MASK   0x80
#define SI2C1_SIC1_IC_INTR_STAT_R_RX_DONE_SHIFT  7 
#define SI2C1_SIC1_IC_INTR_STAT_R_RX_DONE_BIT    0x1
#define SI2C1_SIC1_IC_INTR_STAT_R_RX_DONE_BITWIDTH 1
// R_ACTIVITY bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_INTR_STAT_R_ACTIVITY_MASK  0x100
#define SI2C1_SIC1_IC_INTR_STAT_R_ACTIVITY_SHIFT 8 
#define SI2C1_SIC1_IC_INTR_STAT_R_ACTIVITY_BIT   0x1
#define SI2C1_SIC1_IC_INTR_STAT_R_ACTIVITY_BITWIDTH 1
// R_STOP_DET bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_INTR_STAT_R_STOP_DET_MASK  0x200
#define SI2C1_SIC1_IC_INTR_STAT_R_STOP_DET_SHIFT 9 
#define SI2C1_SIC1_IC_INTR_STAT_R_STOP_DET_BIT   0x1
#define SI2C1_SIC1_IC_INTR_STAT_R_STOP_DET_BITWIDTH 1
// R_START_DET bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_INTR_STAT_R_START_DET_MASK 0x400
#define SI2C1_SIC1_IC_INTR_STAT_R_START_DET_SHIFT 10 
#define SI2C1_SIC1_IC_INTR_STAT_R_START_DET_BIT  0x1
#define SI2C1_SIC1_IC_INTR_STAT_R_START_DET_BITWIDTH 1
// R_GEN_CALL bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_INTR_STAT_R_GEN_CALL_MASK  0x800
#define SI2C1_SIC1_IC_INTR_STAT_R_GEN_CALL_SHIFT 11 
#define SI2C1_SIC1_IC_INTR_STAT_R_GEN_CALL_BIT   0x1
#define SI2C1_SIC1_IC_INTR_STAT_R_GEN_CALL_BITWIDTH 1
// reserved bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_INTR_STAT_RESERVED_MASK    0xFFFFF000
#define SI2C1_SIC1_IC_INTR_STAT_RESERVED_SHIFT   12 
#define SI2C1_SIC1_IC_INTR_STAT_RESERVED_BIT     0xFFFFF
#define SI2C1_SIC1_IC_INTR_STAT_RESERVED_BITWIDTH 20
// SIC1_IC_INTR_MASK Register
#define SI2C1_SIC1_IC_INTR_MASK_OFS              0x00000030
// M_RX_UNDER bitfiled (RW) Reset=1
#define SI2C1_SIC1_IC_INTR_MASK_M_RX_UNDER_MASK  0x1
#define SI2C1_SIC1_IC_INTR_MASK_M_RX_UNDER_SHIFT 0 
#define SI2C1_SIC1_IC_INTR_MASK_M_RX_UNDER_BIT   0x1
#define SI2C1_SIC1_IC_INTR_MASK_M_RX_UNDER_BITWIDTH 1
// M_RX_OVER bitfiled (RW) Reset=1
#define SI2C1_SIC1_IC_INTR_MASK_M_RX_OVER_MASK   0x2
#define SI2C1_SIC1_IC_INTR_MASK_M_RX_OVER_SHIFT  1 
#define SI2C1_SIC1_IC_INTR_MASK_M_RX_OVER_BIT    0x1
#define SI2C1_SIC1_IC_INTR_MASK_M_RX_OVER_BITWIDTH 1
// M_RX_FULL bitfiled (RW) Reset=1
#define SI2C1_SIC1_IC_INTR_MASK_M_RX_FULL_MASK   0x4
#define SI2C1_SIC1_IC_INTR_MASK_M_RX_FULL_SHIFT  2 
#define SI2C1_SIC1_IC_INTR_MASK_M_RX_FULL_BIT    0x1
#define SI2C1_SIC1_IC_INTR_MASK_M_RX_FULL_BITWIDTH 1
// M_TX_OVER bitfiled (RW) Reset=1
#define SI2C1_SIC1_IC_INTR_MASK_M_TX_OVER_MASK   0x8
#define SI2C1_SIC1_IC_INTR_MASK_M_TX_OVER_SHIFT  3 
#define SI2C1_SIC1_IC_INTR_MASK_M_TX_OVER_BIT    0x1
#define SI2C1_SIC1_IC_INTR_MASK_M_TX_OVER_BITWIDTH 1
// M_TX_EMPTY bitfiled (RW) Reset=1
#define SI2C1_SIC1_IC_INTR_MASK_M_TX_EMPTY_MASK  0x10
#define SI2C1_SIC1_IC_INTR_MASK_M_TX_EMPTY_SHIFT 4 
#define SI2C1_SIC1_IC_INTR_MASK_M_TX_EMPTY_BIT   0x1
#define SI2C1_SIC1_IC_INTR_MASK_M_TX_EMPTY_BITWIDTH 1
// M_RD_REQ bitfiled (RW) Reset=1
#define SI2C1_SIC1_IC_INTR_MASK_M_RD_REQ_MASK    0x20
#define SI2C1_SIC1_IC_INTR_MASK_M_RD_REQ_SHIFT   5 
#define SI2C1_SIC1_IC_INTR_MASK_M_RD_REQ_BIT     0x1
#define SI2C1_SIC1_IC_INTR_MASK_M_RD_REQ_BITWIDTH 1
// M_TX_ABRT bitfiled (RW) Reset=1
#define SI2C1_SIC1_IC_INTR_MASK_M_TX_ABRT_MASK   0x40
#define SI2C1_SIC1_IC_INTR_MASK_M_TX_ABRT_SHIFT  6 
#define SI2C1_SIC1_IC_INTR_MASK_M_TX_ABRT_BIT    0x1
#define SI2C1_SIC1_IC_INTR_MASK_M_TX_ABRT_BITWIDTH 1
// M_RX_DONE bitfiled (RW) Reset=1
#define SI2C1_SIC1_IC_INTR_MASK_M_RX_DONE_MASK   0x80
#define SI2C1_SIC1_IC_INTR_MASK_M_RX_DONE_SHIFT  7 
#define SI2C1_SIC1_IC_INTR_MASK_M_RX_DONE_BIT    0x1
#define SI2C1_SIC1_IC_INTR_MASK_M_RX_DONE_BITWIDTH 1
// M_ACTIVITY bitfiled (RW) Reset=0
#define SI2C1_SIC1_IC_INTR_MASK_M_ACTIVITY_MASK  0x100
#define SI2C1_SIC1_IC_INTR_MASK_M_ACTIVITY_SHIFT 8 
#define SI2C1_SIC1_IC_INTR_MASK_M_ACTIVITY_BIT   0x1
#define SI2C1_SIC1_IC_INTR_MASK_M_ACTIVITY_BITWIDTH 1
// M_STOP_DET bitfiled (RW) Reset=0
#define SI2C1_SIC1_IC_INTR_MASK_M_STOP_DET_MASK  0x200
#define SI2C1_SIC1_IC_INTR_MASK_M_STOP_DET_SHIFT 9 
#define SI2C1_SIC1_IC_INTR_MASK_M_STOP_DET_BIT   0x1
#define SI2C1_SIC1_IC_INTR_MASK_M_STOP_DET_BITWIDTH 1
// M_START_DET bitfiled (RW) Reset=0
#define SI2C1_SIC1_IC_INTR_MASK_M_START_DET_MASK 0x400
#define SI2C1_SIC1_IC_INTR_MASK_M_START_DET_SHIFT 10 
#define SI2C1_SIC1_IC_INTR_MASK_M_START_DET_BIT  0x1
#define SI2C1_SIC1_IC_INTR_MASK_M_START_DET_BITWIDTH 1
// M_GEN_CALL bitfiled (RW) Reset=1
#define SI2C1_SIC1_IC_INTR_MASK_M_GEN_CALL_MASK  0x800
#define SI2C1_SIC1_IC_INTR_MASK_M_GEN_CALL_SHIFT 11 
#define SI2C1_SIC1_IC_INTR_MASK_M_GEN_CALL_BIT   0x1
#define SI2C1_SIC1_IC_INTR_MASK_M_GEN_CALL_BITWIDTH 1
// reserved bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_INTR_MASK_RESERVED_MASK    0xFFFFF000
#define SI2C1_SIC1_IC_INTR_MASK_RESERVED_SHIFT   12 
#define SI2C1_SIC1_IC_INTR_MASK_RESERVED_BIT     0xFFFFF
#define SI2C1_SIC1_IC_INTR_MASK_RESERVED_BITWIDTH 20
// SIC1_IC_RAW_INTR_STAT Register
#define SI2C1_SIC1_IC_RAW_INTR_STAT_OFS          0x00000034
// RX_UNDER bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_RAW_INTR_STAT_RX_UNDER_MASK 0x1
#define SI2C1_SIC1_IC_RAW_INTR_STAT_RX_UNDER_SHIFT 0 
#define SI2C1_SIC1_IC_RAW_INTR_STAT_RX_UNDER_BIT 0x1
#define SI2C1_SIC1_IC_RAW_INTR_STAT_RX_UNDER_BITWIDTH 1
// RX_OVER bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_RAW_INTR_STAT_RX_OVER_MASK 0x2
#define SI2C1_SIC1_IC_RAW_INTR_STAT_RX_OVER_SHIFT 1 
#define SI2C1_SIC1_IC_RAW_INTR_STAT_RX_OVER_BIT  0x1
#define SI2C1_SIC1_IC_RAW_INTR_STAT_RX_OVER_BITWIDTH 1
// RX_FULL bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_RAW_INTR_STAT_RX_FULL_MASK 0x4
#define SI2C1_SIC1_IC_RAW_INTR_STAT_RX_FULL_SHIFT 2 
#define SI2C1_SIC1_IC_RAW_INTR_STAT_RX_FULL_BIT  0x1
#define SI2C1_SIC1_IC_RAW_INTR_STAT_RX_FULL_BITWIDTH 1
// TX_OVER bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_RAW_INTR_STAT_TX_OVER_MASK 0x8
#define SI2C1_SIC1_IC_RAW_INTR_STAT_TX_OVER_SHIFT 3 
#define SI2C1_SIC1_IC_RAW_INTR_STAT_TX_OVER_BIT  0x1
#define SI2C1_SIC1_IC_RAW_INTR_STAT_TX_OVER_BITWIDTH 1
// TX_EMPTY bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_RAW_INTR_STAT_TX_EMPTY_MASK 0x10
#define SI2C1_SIC1_IC_RAW_INTR_STAT_TX_EMPTY_SHIFT 4 
#define SI2C1_SIC1_IC_RAW_INTR_STAT_TX_EMPTY_BIT 0x1
#define SI2C1_SIC1_IC_RAW_INTR_STAT_TX_EMPTY_BITWIDTH 1
// RD_REQ bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_RAW_INTR_STAT_RD_REQ_MASK  0x20
#define SI2C1_SIC1_IC_RAW_INTR_STAT_RD_REQ_SHIFT 5 
#define SI2C1_SIC1_IC_RAW_INTR_STAT_RD_REQ_BIT   0x1
#define SI2C1_SIC1_IC_RAW_INTR_STAT_RD_REQ_BITWIDTH 1
// TX_ABRT bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_RAW_INTR_STAT_TX_ABRT_MASK 0x40
#define SI2C1_SIC1_IC_RAW_INTR_STAT_TX_ABRT_SHIFT 6 
#define SI2C1_SIC1_IC_RAW_INTR_STAT_TX_ABRT_BIT  0x1
#define SI2C1_SIC1_IC_RAW_INTR_STAT_TX_ABRT_BITWIDTH 1
// RX_DONE bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_RAW_INTR_STAT_RX_DONE_MASK 0x80
#define SI2C1_SIC1_IC_RAW_INTR_STAT_RX_DONE_SHIFT 7 
#define SI2C1_SIC1_IC_RAW_INTR_STAT_RX_DONE_BIT  0x1
#define SI2C1_SIC1_IC_RAW_INTR_STAT_RX_DONE_BITWIDTH 1
// ACTIVITY bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_RAW_INTR_STAT_ACTIVITY_MASK 0x100
#define SI2C1_SIC1_IC_RAW_INTR_STAT_ACTIVITY_SHIFT 8 
#define SI2C1_SIC1_IC_RAW_INTR_STAT_ACTIVITY_BIT 0x1
#define SI2C1_SIC1_IC_RAW_INTR_STAT_ACTIVITY_BITWIDTH 1
// STOP_DET bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_RAW_INTR_STAT_STOP_DET_MASK 0x200
#define SI2C1_SIC1_IC_RAW_INTR_STAT_STOP_DET_SHIFT 9 
#define SI2C1_SIC1_IC_RAW_INTR_STAT_STOP_DET_BIT 0x1
#define SI2C1_SIC1_IC_RAW_INTR_STAT_STOP_DET_BITWIDTH 1
// START_DET bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_RAW_INTR_STAT_START_DET_MASK 0x400
#define SI2C1_SIC1_IC_RAW_INTR_STAT_START_DET_SHIFT 10 
#define SI2C1_SIC1_IC_RAW_INTR_STAT_START_DET_BIT 0x1
#define SI2C1_SIC1_IC_RAW_INTR_STAT_START_DET_BITWIDTH 1
// GEN_CALL bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_RAW_INTR_STAT_GEN_CALL_MASK 0x800
#define SI2C1_SIC1_IC_RAW_INTR_STAT_GEN_CALL_SHIFT 11 
#define SI2C1_SIC1_IC_RAW_INTR_STAT_GEN_CALL_BIT 0x1
#define SI2C1_SIC1_IC_RAW_INTR_STAT_GEN_CALL_BITWIDTH 1
// reserved bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_RAW_INTR_STAT_RESERVED_MASK 0xFFFFF000
#define SI2C1_SIC1_IC_RAW_INTR_STAT_RESERVED_SHIFT 12 
#define SI2C1_SIC1_IC_RAW_INTR_STAT_RESERVED_BIT 0xFFFFF
#define SI2C1_SIC1_IC_RAW_INTR_STAT_RESERVED_BITWIDTH 20
// SIC1_IC_RX_TL Register
#define SI2C1_SIC1_IC_RX_TL_OFS                  0x00000038
// RX_TL bitfiled (RW) Reset=1000
#define SI2C1_SIC1_IC_RX_TL_RX_TL_MASK           0xFF
#define SI2C1_SIC1_IC_RX_TL_RX_TL_SHIFT          0 
#define SI2C1_SIC1_IC_RX_TL_RX_TL_BIT            0xFF
#define SI2C1_SIC1_IC_RX_TL_RX_TL_BITWIDTH       8
// reserved bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_RX_TL_RESERVED_MASK        0xFFFFFF00
#define SI2C1_SIC1_IC_RX_TL_RESERVED_SHIFT       8 
#define SI2C1_SIC1_IC_RX_TL_RESERVED_BIT         0xFFFFFF
#define SI2C1_SIC1_IC_RX_TL_RESERVED_BITWIDTH    24
// SIC1_IC_TX_TL Register
#define SI2C1_SIC1_IC_TX_TL_OFS                  0x0000003C
// TX_TL bitfiled (RW) Reset=1000
#define SI2C1_SIC1_IC_TX_TL_TX_TL_MASK           0xFF
#define SI2C1_SIC1_IC_TX_TL_TX_TL_SHIFT          0 
#define SI2C1_SIC1_IC_TX_TL_TX_TL_BIT            0xFF
#define SI2C1_SIC1_IC_TX_TL_TX_TL_BITWIDTH       8
// reserved bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_TX_TL_RESERVED_MASK        0xFFFFFF00
#define SI2C1_SIC1_IC_TX_TL_RESERVED_SHIFT       8 
#define SI2C1_SIC1_IC_TX_TL_RESERVED_BIT         0xFFFFFF
#define SI2C1_SIC1_IC_TX_TL_RESERVED_BITWIDTH    24
// SIC1_IC_CLR_INTR Register
#define SI2C1_SIC1_IC_CLR_INTR_OFS               0x00000040
// CLR_INTR bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_CLR_INTR_CLR_INTR_MASK     0x1
#define SI2C1_SIC1_IC_CLR_INTR_CLR_INTR_SHIFT    0 
#define SI2C1_SIC1_IC_CLR_INTR_CLR_INTR_BIT      0x1
#define SI2C1_SIC1_IC_CLR_INTR_CLR_INTR_BITWIDTH 1
// reserved bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_CLR_INTR_RESERVED_MASK     0xFFFFFFFE
#define SI2C1_SIC1_IC_CLR_INTR_RESERVED_SHIFT    1 
#define SI2C1_SIC1_IC_CLR_INTR_RESERVED_BIT      0x7FFFFFFF
#define SI2C1_SIC1_IC_CLR_INTR_RESERVED_BITWIDTH 31
// SIC1_IC_CLR_RX_UNDER Register
#define SI2C1_SIC1_IC_CLR_RX_UNDER_OFS           0x00000044
// CLR_RX_UNDER bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_CLR_RX_UNDER_CLR_RX_UNDER_MASK 0x1
#define SI2C1_SIC1_IC_CLR_RX_UNDER_CLR_RX_UNDER_SHIFT 0 
#define SI2C1_SIC1_IC_CLR_RX_UNDER_CLR_RX_UNDER_BIT 0x1
#define SI2C1_SIC1_IC_CLR_RX_UNDER_CLR_RX_UNDER_BITWIDTH 1
// reserved bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_CLR_RX_UNDER_RESERVED_MASK 0xFFFFFFFE
#define SI2C1_SIC1_IC_CLR_RX_UNDER_RESERVED_SHIFT 1 
#define SI2C1_SIC1_IC_CLR_RX_UNDER_RESERVED_BIT  0x7FFFFFFF
#define SI2C1_SIC1_IC_CLR_RX_UNDER_RESERVED_BITWIDTH 31
// SIC1_IC_CLR_RX_OVER Register
#define SI2C1_SIC1_IC_CLR_RX_OVER_OFS            0x00000048
// CLR_RX_OVER bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_CLR_RX_OVER_CLR_RX_OVER_MASK 0x1
#define SI2C1_SIC1_IC_CLR_RX_OVER_CLR_RX_OVER_SHIFT 0 
#define SI2C1_SIC1_IC_CLR_RX_OVER_CLR_RX_OVER_BIT 0x1
#define SI2C1_SIC1_IC_CLR_RX_OVER_CLR_RX_OVER_BITWIDTH 1
// reserved bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_CLR_RX_OVER_RESERVED_MASK  0xFFFFFFFE
#define SI2C1_SIC1_IC_CLR_RX_OVER_RESERVED_SHIFT 1 
#define SI2C1_SIC1_IC_CLR_RX_OVER_RESERVED_BIT   0x7FFFFFFF
#define SI2C1_SIC1_IC_CLR_RX_OVER_RESERVED_BITWIDTH 31
// SIC1_IC_CLR_TX_OVER Register
#define SI2C1_SIC1_IC_CLR_TX_OVER_OFS            0x0000004C
// CLR_TX_OVER bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_CLR_TX_OVER_CLR_TX_OVER_MASK 0x1
#define SI2C1_SIC1_IC_CLR_TX_OVER_CLR_TX_OVER_SHIFT 0 
#define SI2C1_SIC1_IC_CLR_TX_OVER_CLR_TX_OVER_BIT 0x1
#define SI2C1_SIC1_IC_CLR_TX_OVER_CLR_TX_OVER_BITWIDTH 1
// reserved bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_CLR_TX_OVER_RESERVED_MASK  0xFFFFFFFE
#define SI2C1_SIC1_IC_CLR_TX_OVER_RESERVED_SHIFT 1 
#define SI2C1_SIC1_IC_CLR_TX_OVER_RESERVED_BIT   0x7FFFFFFF
#define SI2C1_SIC1_IC_CLR_TX_OVER_RESERVED_BITWIDTH 31
// SIC1_IC_CLR_RD_REQ Register
#define SI2C1_SIC1_IC_CLR_RD_REQ_OFS             0x00000050
// CLR_RD_REQ bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_CLR_RD_REQ_CLR_RD_REQ_MASK 0x1
#define SI2C1_SIC1_IC_CLR_RD_REQ_CLR_RD_REQ_SHIFT 0 
#define SI2C1_SIC1_IC_CLR_RD_REQ_CLR_RD_REQ_BIT  0x1
#define SI2C1_SIC1_IC_CLR_RD_REQ_CLR_RD_REQ_BITWIDTH 1
// reserved bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_CLR_RD_REQ_RESERVED_MASK   0xFFFFFFFE
#define SI2C1_SIC1_IC_CLR_RD_REQ_RESERVED_SHIFT  1 
#define SI2C1_SIC1_IC_CLR_RD_REQ_RESERVED_BIT    0x7FFFFFFF
#define SI2C1_SIC1_IC_CLR_RD_REQ_RESERVED_BITWIDTH 31
// SIC1_IC_CLR_TX_ABRT Register
#define SI2C1_SIC1_IC_CLR_TX_ABRT_OFS            0x00000054
// CLR_TX_ABRT bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_CLR_TX_ABRT_CLR_TX_ABRT_MASK 0x1
#define SI2C1_SIC1_IC_CLR_TX_ABRT_CLR_TX_ABRT_SHIFT 0 
#define SI2C1_SIC1_IC_CLR_TX_ABRT_CLR_TX_ABRT_BIT 0x1
#define SI2C1_SIC1_IC_CLR_TX_ABRT_CLR_TX_ABRT_BITWIDTH 1
// reserved bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_CLR_TX_ABRT_RESERVED_MASK  0xFFFFFFFE
#define SI2C1_SIC1_IC_CLR_TX_ABRT_RESERVED_SHIFT 1 
#define SI2C1_SIC1_IC_CLR_TX_ABRT_RESERVED_BIT   0x7FFFFFFF
#define SI2C1_SIC1_IC_CLR_TX_ABRT_RESERVED_BITWIDTH 31
// SIC1_IC_CLR_RX_DONE Register
#define SI2C1_SIC1_IC_CLR_RX_DONE_OFS            0x00000058
// CLR_RX_DONE bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_CLR_RX_DONE_CLR_RX_DONE_MASK 0x1
#define SI2C1_SIC1_IC_CLR_RX_DONE_CLR_RX_DONE_SHIFT 0 
#define SI2C1_SIC1_IC_CLR_RX_DONE_CLR_RX_DONE_BIT 0x1
#define SI2C1_SIC1_IC_CLR_RX_DONE_CLR_RX_DONE_BITWIDTH 1
// reserved bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_CLR_RX_DONE_RESERVED_MASK  0xFFFFFFFE
#define SI2C1_SIC1_IC_CLR_RX_DONE_RESERVED_SHIFT 1 
#define SI2C1_SIC1_IC_CLR_RX_DONE_RESERVED_BIT   0x7FFFFFFF
#define SI2C1_SIC1_IC_CLR_RX_DONE_RESERVED_BITWIDTH 31
// SIC1_IC_CLR_ACTIVITY Register
#define SI2C1_SIC1_IC_CLR_ACTIVITY_OFS           0x0000005C
// CLR_ACTIVITY bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_CLR_ACTIVITY_CLR_ACTIVITY_MASK 0x1
#define SI2C1_SIC1_IC_CLR_ACTIVITY_CLR_ACTIVITY_SHIFT 0 
#define SI2C1_SIC1_IC_CLR_ACTIVITY_CLR_ACTIVITY_BIT 0x1
#define SI2C1_SIC1_IC_CLR_ACTIVITY_CLR_ACTIVITY_BITWIDTH 1
// reserved bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_CLR_ACTIVITY_RESERVED_MASK 0xFFFFFFFE
#define SI2C1_SIC1_IC_CLR_ACTIVITY_RESERVED_SHIFT 1 
#define SI2C1_SIC1_IC_CLR_ACTIVITY_RESERVED_BIT  0x7FFFFFFF
#define SI2C1_SIC1_IC_CLR_ACTIVITY_RESERVED_BITWIDTH 31
// SIC1_IC_CLR_STOP_DET Register
#define SI2C1_SIC1_IC_CLR_STOP_DET_OFS           0x00000060
// CLR_STOP_DET bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_CLR_STOP_DET_CLR_STOP_DET_MASK 0x1
#define SI2C1_SIC1_IC_CLR_STOP_DET_CLR_STOP_DET_SHIFT 0 
#define SI2C1_SIC1_IC_CLR_STOP_DET_CLR_STOP_DET_BIT 0x1
#define SI2C1_SIC1_IC_CLR_STOP_DET_CLR_STOP_DET_BITWIDTH 1
// reserved bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_CLR_STOP_DET_RESERVED_MASK 0xFFFFFFFE
#define SI2C1_SIC1_IC_CLR_STOP_DET_RESERVED_SHIFT 1 
#define SI2C1_SIC1_IC_CLR_STOP_DET_RESERVED_BIT  0x7FFFFFFF
#define SI2C1_SIC1_IC_CLR_STOP_DET_RESERVED_BITWIDTH 31
// SIC1_IC_CLR_START_DET Register
#define SI2C1_SIC1_IC_CLR_START_DET_OFS          0x00000064
// CLR_START_DET bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_CLR_START_DET_CLR_START_DET_MASK 0x1
#define SI2C1_SIC1_IC_CLR_START_DET_CLR_START_DET_SHIFT 0 
#define SI2C1_SIC1_IC_CLR_START_DET_CLR_START_DET_BIT 0x1
#define SI2C1_SIC1_IC_CLR_START_DET_CLR_START_DET_BITWIDTH 1
// reserved bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_CLR_START_DET_RESERVED_MASK 0xFFFFFFFE
#define SI2C1_SIC1_IC_CLR_START_DET_RESERVED_SHIFT 1 
#define SI2C1_SIC1_IC_CLR_START_DET_RESERVED_BIT 0x7FFFFFFF
#define SI2C1_SIC1_IC_CLR_START_DET_RESERVED_BITWIDTH 31
// SIC1_IC_CLR_GEN_CALL Register
#define SI2C1_SIC1_IC_CLR_GEN_CALL_OFS           0x00000068
// CLR_GEN_CALL bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_CLR_GEN_CALL_CLR_GEN_CALL_MASK 0x1
#define SI2C1_SIC1_IC_CLR_GEN_CALL_CLR_GEN_CALL_SHIFT 0 
#define SI2C1_SIC1_IC_CLR_GEN_CALL_CLR_GEN_CALL_BIT 0x1
#define SI2C1_SIC1_IC_CLR_GEN_CALL_CLR_GEN_CALL_BITWIDTH 1
// reserved bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_CLR_GEN_CALL_RESERVED_MASK 0xFFFFFFFE
#define SI2C1_SIC1_IC_CLR_GEN_CALL_RESERVED_SHIFT 1 
#define SI2C1_SIC1_IC_CLR_GEN_CALL_RESERVED_BIT  0x7FFFFFFF
#define SI2C1_SIC1_IC_CLR_GEN_CALL_RESERVED_BITWIDTH 31
// SIC1_IC_ENABLE Register
#define SI2C1_SIC1_IC_ENABLE_OFS                 0x0000006C
// ENABLE bitfiled (RW) Reset=0
#define SI2C1_SIC1_IC_ENABLE_ENABLE_MASK         0x1
#define SI2C1_SIC1_IC_ENABLE_ENABLE_SHIFT        0 
#define SI2C1_SIC1_IC_ENABLE_ENABLE_BIT          0x1
#define SI2C1_SIC1_IC_ENABLE_ENABLE_BITWIDTH     1
// ABORT bitfiled (RW) Reset=0
#define SI2C1_SIC1_IC_ENABLE_ABORT_MASK          0x2
#define SI2C1_SIC1_IC_ENABLE_ABORT_SHIFT         1 
#define SI2C1_SIC1_IC_ENABLE_ABORT_BIT           0x1
#define SI2C1_SIC1_IC_ENABLE_ABORT_BITWIDTH      1
// reserved bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_ENABLE_RESERVED_MASK       0xFFFFFFFC
#define SI2C1_SIC1_IC_ENABLE_RESERVED_SHIFT      2 
#define SI2C1_SIC1_IC_ENABLE_RESERVED_BIT        0x3FFFFFFF
#define SI2C1_SIC1_IC_ENABLE_RESERVED_BITWIDTH   30
// SIC1_IC_STATUS Register
#define SI2C1_SIC1_IC_STATUS_OFS                 0x00000070
// ACTIVITY bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_STATUS_ACTIVITY_MASK       0x1
#define SI2C1_SIC1_IC_STATUS_ACTIVITY_SHIFT      0 
#define SI2C1_SIC1_IC_STATUS_ACTIVITY_BIT        0x1
#define SI2C1_SIC1_IC_STATUS_ACTIVITY_BITWIDTH   1
// TFNF bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_STATUS_TFNF_MASK           0x2
#define SI2C1_SIC1_IC_STATUS_TFNF_SHIFT          1 
#define SI2C1_SIC1_IC_STATUS_TFNF_BIT            0x1
#define SI2C1_SIC1_IC_STATUS_TFNF_BITWIDTH       1
// TFE bitfiled (RO) Reset=1
#define SI2C1_SIC1_IC_STATUS_TFE_MASK            0x4
#define SI2C1_SIC1_IC_STATUS_TFE_SHIFT           2 
#define SI2C1_SIC1_IC_STATUS_TFE_BIT             0x1
#define SI2C1_SIC1_IC_STATUS_TFE_BITWIDTH        1
// RFNE bitfiled (RO) Reset=1
#define SI2C1_SIC1_IC_STATUS_RFNE_MASK           0x8
#define SI2C1_SIC1_IC_STATUS_RFNE_SHIFT          3 
#define SI2C1_SIC1_IC_STATUS_RFNE_BIT            0x1
#define SI2C1_SIC1_IC_STATUS_RFNE_BITWIDTH       1
// RFF bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_STATUS_RFF_MASK            0x10
#define SI2C1_SIC1_IC_STATUS_RFF_SHIFT           4 
#define SI2C1_SIC1_IC_STATUS_RFF_BIT             0x1
#define SI2C1_SIC1_IC_STATUS_RFF_BITWIDTH        1
// MST_ACTIVITY bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_STATUS_MST_ACTIVITY_MASK   0x20
#define SI2C1_SIC1_IC_STATUS_MST_ACTIVITY_SHIFT  5 
#define SI2C1_SIC1_IC_STATUS_MST_ACTIVITY_BIT    0x1
#define SI2C1_SIC1_IC_STATUS_MST_ACTIVITY_BITWIDTH 1
// SLV_ACTIVITY bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_STATUS_SLV_ACTIVITY_MASK   0x40
#define SI2C1_SIC1_IC_STATUS_SLV_ACTIVITY_SHIFT  6 
#define SI2C1_SIC1_IC_STATUS_SLV_ACTIVITY_BIT    0x1
#define SI2C1_SIC1_IC_STATUS_SLV_ACTIVITY_BITWIDTH 1
// reserved bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_STATUS_RESERVED_MASK       0xFFFFFF80
#define SI2C1_SIC1_IC_STATUS_RESERVED_SHIFT      7 
#define SI2C1_SIC1_IC_STATUS_RESERVED_BIT        0x1FFFFFF
#define SI2C1_SIC1_IC_STATUS_RESERVED_BITWIDTH   25
// SIC1_IC_TXFLR Register
#define SI2C1_SIC1_IC_TXFLR_OFS                  0x00000074
// TXFLR bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_TXFLR_TXFLR_MASK           0x1F
#define SI2C1_SIC1_IC_TXFLR_TXFLR_SHIFT          0 
#define SI2C1_SIC1_IC_TXFLR_TXFLR_BIT            0x1F
#define SI2C1_SIC1_IC_TXFLR_TXFLR_BITWIDTH       5
// reserved bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_TXFLR_RESERVED_MASK        0xFFFFFFE0
#define SI2C1_SIC1_IC_TXFLR_RESERVED_SHIFT       5 
#define SI2C1_SIC1_IC_TXFLR_RESERVED_BIT         0x7FFFFFF
#define SI2C1_SIC1_IC_TXFLR_RESERVED_BITWIDTH    27
// SIC1_IC_RXFLR Register
#define SI2C1_SIC1_IC_RXFLR_OFS                  0x00000078
// RXFLR bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_RXFLR_RXFLR_MASK           0x1F
#define SI2C1_SIC1_IC_RXFLR_RXFLR_SHIFT          0 
#define SI2C1_SIC1_IC_RXFLR_RXFLR_BIT            0x1F
#define SI2C1_SIC1_IC_RXFLR_RXFLR_BITWIDTH       5
// reserved bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_RXFLR_RESERVED_MASK        0xFFFFFFE0
#define SI2C1_SIC1_IC_RXFLR_RESERVED_SHIFT       5 
#define SI2C1_SIC1_IC_RXFLR_RESERVED_BIT         0x7FFFFFF
#define SI2C1_SIC1_IC_RXFLR_RESERVED_BITWIDTH    27
// SIC1_IC_SDA_HOLD Register
#define SI2C1_SIC1_IC_SDA_HOLD_OFS               0x0000007C
// IC_SDA_HOLD bitfiled (RO) Reset=1111
#define SI2C1_SIC1_IC_SDA_HOLD_IC_SDA_HOLD_MASK  0xFFFF
#define SI2C1_SIC1_IC_SDA_HOLD_IC_SDA_HOLD_SHIFT 0 
#define SI2C1_SIC1_IC_SDA_HOLD_IC_SDA_HOLD_BIT   0xFFFF
#define SI2C1_SIC1_IC_SDA_HOLD_IC_SDA_HOLD_BITWIDTH 16
// reserved bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_SDA_HOLD_RESERVED_MASK     0xFFFF0000
#define SI2C1_SIC1_IC_SDA_HOLD_RESERVED_SHIFT    16 
#define SI2C1_SIC1_IC_SDA_HOLD_RESERVED_BIT      0xFFFF
#define SI2C1_SIC1_IC_SDA_HOLD_RESERVED_BITWIDTH 16
// SIC1_IC_TX_ABRT_SOURCE Register
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_OFS         0x00000080
// ABRT_7B_ADDR_NOACK bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_7B_ADDR_NOACK_MASK 0x1
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_7B_ADDR_NOACK_SHIFT 0 
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_7B_ADDR_NOACK_BIT 0x1
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_7B_ADDR_NOACK_BITWIDTH 1
// ABRT_10ADDR1_NOACK bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_10ADDR1_NOACK_MASK 0x2
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_10ADDR1_NOACK_SHIFT 1 
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_10ADDR1_NOACK_BIT 0x1
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_10ADDR1_NOACK_BITWIDTH 1
// ABRT_10ADDR2_NOACK bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_10ADDR2_NOACK_MASK 0x4
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_10ADDR2_NOACK_SHIFT 2 
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_10ADDR2_NOACK_BIT 0x1
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_10ADDR2_NOACK_BITWIDTH 1
// ABRT_TXDATA_NOACK bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_TXDATA_NOACK_MASK 0x8
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_TXDATA_NOACK_SHIFT 3 
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_TXDATA_NOACK_BIT 0x1
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_TXDATA_NOACK_BITWIDTH 1
// ABRT_GCALL_NOACK bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_GCALL_NOACK_MASK 0x10
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_GCALL_NOACK_SHIFT 4 
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_GCALL_NOACK_BIT 0x1
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_GCALL_NOACK_BITWIDTH 1
// ABRT_GCALL_READ bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_GCALL_READ_MASK 0x20
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_GCALL_READ_SHIFT 5 
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_GCALL_READ_BIT 0x1
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_GCALL_READ_BITWIDTH 1
// ABRT_HS_ACKDET bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_HS_ACKDET_MASK 0x40
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_HS_ACKDET_SHIFT 6 
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_HS_ACKDET_BIT 0x1
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_HS_ACKDET_BITWIDTH 1
// ABRT_SBYTE_ACKDET bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_SBYTE_ACKDET_MASK 0x80
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_SBYTE_ACKDET_SHIFT 7 
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_SBYTE_ACKDET_BIT 0x1
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_SBYTE_ACKDET_BITWIDTH 1
// ABRT_HS_NORSTRT bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_HS_NORSTRT_MASK 0x100
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_HS_NORSTRT_SHIFT 8 
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_HS_NORSTRT_BIT 0x1
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_HS_NORSTRT_BITWIDTH 1
// ABRT_SBYTE_NORSTRT bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_SBYTE_NORSTRT_MASK 0x200
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_SBYTE_NORSTRT_SHIFT 9 
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_SBYTE_NORSTRT_BIT 0x1
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_SBYTE_NORSTRT_BITWIDTH 1
// ABRT_10B_RD_NORSTRT bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_10B_RD_NORSTRT_MASK 0x400
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_10B_RD_NORSTRT_SHIFT 10 
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_10B_RD_NORSTRT_BIT 0x1
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_10B_RD_NORSTRT_BITWIDTH 1
// ABRT_MASTER_DIS bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_MASTER_DIS_MASK 0x800
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_MASTER_DIS_SHIFT 11 
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_MASTER_DIS_BIT 0x1
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_MASTER_DIS_BITWIDTH 1
// ARB_LOST bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ARB_LOST_MASK 0x1000
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ARB_LOST_SHIFT 12 
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ARB_LOST_BIT 0x1
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ARB_LOST_BITWIDTH 1
// ABRT_SLVFLUSH_TXFIFO bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_SLVFLUSH_TXFIFO_MASK 0x2000
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_SLVFLUSH_TXFIFO_SHIFT 13 
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_SLVFLUSH_TXFIFO_BIT 0x1
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_SLVFLUSH_TXFIFO_BITWIDTH 1
// ABRT_SLV_ARBLOST bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_SLV_ARBLOST_MASK 0x4000
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_SLV_ARBLOST_SHIFT 14 
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_SLV_ARBLOST_BIT 0x1
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_SLV_ARBLOST_BITWIDTH 1
// ABRT_SLVRD_INTX bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_SLVRD_INTX_MASK 0x8000
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_SLVRD_INTX_SHIFT 15 
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_SLVRD_INTX_BIT 0x1
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_ABRT_SLVRD_INTX_BITWIDTH 1
// reserved bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_RESERVED_MASK 0xFFFF0000
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_RESERVED_SHIFT 16 
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_RESERVED_BIT 0xFFFF
#define SI2C1_SIC1_IC_TX_ABRT_SOURCE_RESERVED_BITWIDTH 16
// SIC1_IC_SLV_DATA_NACK_ONLY Register
#define SI2C1_SIC1_IC_SLV_DATA_NACK_ONLY_OFS     0x00000084
// NACK bitfiled (RW) Reset=0
#define SI2C1_SIC1_IC_SLV_DATA_NACK_ONLY_NACK_MASK 0x1
#define SI2C1_SIC1_IC_SLV_DATA_NACK_ONLY_NACK_SHIFT 0 
#define SI2C1_SIC1_IC_SLV_DATA_NACK_ONLY_NACK_BIT 0x1
#define SI2C1_SIC1_IC_SLV_DATA_NACK_ONLY_NACK_BITWIDTH 1
// reserved bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_SLV_DATA_NACK_ONLY_RESERVED_MASK 0xFFFFFFFE
#define SI2C1_SIC1_IC_SLV_DATA_NACK_ONLY_RESERVED_SHIFT 1 
#define SI2C1_SIC1_IC_SLV_DATA_NACK_ONLY_RESERVED_BIT 0x7FFFFFFF
#define SI2C1_SIC1_IC_SLV_DATA_NACK_ONLY_RESERVED_BITWIDTH 31
// SIC1_IC_SDA_SETUP Register
#define SI2C1_SIC1_IC_SDA_SETUP_OFS              0x00000094
// SDA_SETUP bitfiled (RW) Reset=111111
#define SI2C1_SIC1_IC_SDA_SETUP_SDA_SETUP_MASK   0xFF
#define SI2C1_SIC1_IC_SDA_SETUP_SDA_SETUP_SHIFT  0 
#define SI2C1_SIC1_IC_SDA_SETUP_SDA_SETUP_BIT    0xFF
#define SI2C1_SIC1_IC_SDA_SETUP_SDA_SETUP_BITWIDTH 8
// reserved bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_SDA_SETUP_RESERVED_MASK    0xFFFFFF00
#define SI2C1_SIC1_IC_SDA_SETUP_RESERVED_SHIFT   8 
#define SI2C1_SIC1_IC_SDA_SETUP_RESERVED_BIT     0xFFFFFF
#define SI2C1_SIC1_IC_SDA_SETUP_RESERVED_BITWIDTH 24
// SIC1_IC_ACK_GENERAL_CALL Register
#define SI2C1_SIC1_IC_ACK_GENERAL_CALL_OFS       0x00000098
// ACK_GEN_CALL bitfiled (RW) Reset=1
#define SI2C1_SIC1_IC_ACK_GENERAL_CALL_ACK_GEN_CALL_MASK 0x1
#define SI2C1_SIC1_IC_ACK_GENERAL_CALL_ACK_GEN_CALL_SHIFT 0 
#define SI2C1_SIC1_IC_ACK_GENERAL_CALL_ACK_GEN_CALL_BIT 0x1
#define SI2C1_SIC1_IC_ACK_GENERAL_CALL_ACK_GEN_CALL_BITWIDTH 1
// reserved bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_ACK_GENERAL_CALL_RESERVED_MASK 0xFFFFFFFE
#define SI2C1_SIC1_IC_ACK_GENERAL_CALL_RESERVED_SHIFT 1 
#define SI2C1_SIC1_IC_ACK_GENERAL_CALL_RESERVED_BIT 0x7FFFFFFF
#define SI2C1_SIC1_IC_ACK_GENERAL_CALL_RESERVED_BITWIDTH 31
// SIC1_IC_ENABLE_STATUS Register
#define SI2C1_SIC1_IC_ENABLE_STATUS_OFS          0x0000009C
// IC_EN bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_ENABLE_STATUS_IC_EN_MASK   0x1
#define SI2C1_SIC1_IC_ENABLE_STATUS_IC_EN_SHIFT  0 
#define SI2C1_SIC1_IC_ENABLE_STATUS_IC_EN_BIT    0x1
#define SI2C1_SIC1_IC_ENABLE_STATUS_IC_EN_BITWIDTH 1
// SLV_DISABLED_WHILE_BUSY bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_ENABLE_STATUS_SLV_DISABLED_WHILE_BUSY_MASK 0x2
#define SI2C1_SIC1_IC_ENABLE_STATUS_SLV_DISABLED_WHILE_BUSY_SHIFT 1 
#define SI2C1_SIC1_IC_ENABLE_STATUS_SLV_DISABLED_WHILE_BUSY_BIT 0x1
#define SI2C1_SIC1_IC_ENABLE_STATUS_SLV_DISABLED_WHILE_BUSY_BITWIDTH 1
// SLV_RX_DATA_LOST bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_ENABLE_STATUS_SLV_RX_DATA_LOST_MASK 0x4
#define SI2C1_SIC1_IC_ENABLE_STATUS_SLV_RX_DATA_LOST_SHIFT 2 
#define SI2C1_SIC1_IC_ENABLE_STATUS_SLV_RX_DATA_LOST_BIT 0x1
#define SI2C1_SIC1_IC_ENABLE_STATUS_SLV_RX_DATA_LOST_BITWIDTH 1
// reserved bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_ENABLE_STATUS_RESERVED_MASK 0xFFFFFFF8
#define SI2C1_SIC1_IC_ENABLE_STATUS_RESERVED_SHIFT 3 
#define SI2C1_SIC1_IC_ENABLE_STATUS_RESERVED_BIT 0x1FFFFFFF
#define SI2C1_SIC1_IC_ENABLE_STATUS_RESERVED_BITWIDTH 29
// SIC1_IC_FS_SPKLEN Register
#define SI2C1_SIC1_IC_FS_SPKLEN_OFS              0x000000A0
// IC_FS_SPKLEN bitfiled (RW) Reset=11
#define SI2C1_SIC1_IC_FS_SPKLEN_IC_FS_SPKLEN_MASK 0xFF
#define SI2C1_SIC1_IC_FS_SPKLEN_IC_FS_SPKLEN_SHIFT 0 
#define SI2C1_SIC1_IC_FS_SPKLEN_IC_FS_SPKLEN_BIT 0xFF
#define SI2C1_SIC1_IC_FS_SPKLEN_IC_FS_SPKLEN_BITWIDTH 8
// reserved bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_FS_SPKLEN_RESERVED_MASK    0xFFFFFF00
#define SI2C1_SIC1_IC_FS_SPKLEN_RESERVED_SHIFT   8 
#define SI2C1_SIC1_IC_FS_SPKLEN_RESERVED_BIT     0xFFFFFF
#define SI2C1_SIC1_IC_FS_SPKLEN_RESERVED_BITWIDTH 24
// SIC1_IC_COMP_PARAM_1 Register
#define SI2C1_SIC1_IC_COMP_PARAM_1_OFS           0x000000F4
// APB_DATA_WIDTH bitfiled (RO) Reset=10
#define SI2C1_SIC1_IC_COMP_PARAM_1_APB_DATA_WIDTH_MASK 0x3
#define SI2C1_SIC1_IC_COMP_PARAM_1_APB_DATA_WIDTH_SHIFT 0 
#define SI2C1_SIC1_IC_COMP_PARAM_1_APB_DATA_WIDTH_BIT 0x3
#define SI2C1_SIC1_IC_COMP_PARAM_1_APB_DATA_WIDTH_BITWIDTH 2
// MAX_SPEED_MODE bitfiled (RO) Reset=10
#define SI2C1_SIC1_IC_COMP_PARAM_1_MAX_SPEED_MODE_MASK 0xC
#define SI2C1_SIC1_IC_COMP_PARAM_1_MAX_SPEED_MODE_SHIFT 2 
#define SI2C1_SIC1_IC_COMP_PARAM_1_MAX_SPEED_MODE_BIT 0x3
#define SI2C1_SIC1_IC_COMP_PARAM_1_MAX_SPEED_MODE_BITWIDTH 2
// HC_COUNT_VALUES bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_COMP_PARAM_1_HC_COUNT_VALUES_MASK 0x10
#define SI2C1_SIC1_IC_COMP_PARAM_1_HC_COUNT_VALUES_SHIFT 4 
#define SI2C1_SIC1_IC_COMP_PARAM_1_HC_COUNT_VALUES_BIT 0x1
#define SI2C1_SIC1_IC_COMP_PARAM_1_HC_COUNT_VALUES_BITWIDTH 1
// INTR_IO bitfiled (RO) Reset=1
#define SI2C1_SIC1_IC_COMP_PARAM_1_INTR_IO_MASK  0x20
#define SI2C1_SIC1_IC_COMP_PARAM_1_INTR_IO_SHIFT 5 
#define SI2C1_SIC1_IC_COMP_PARAM_1_INTR_IO_BIT   0x1
#define SI2C1_SIC1_IC_COMP_PARAM_1_INTR_IO_BITWIDTH 1
// HAS_DMA bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_COMP_PARAM_1_HAS_DMA_MASK  0x40
#define SI2C1_SIC1_IC_COMP_PARAM_1_HAS_DMA_SHIFT 6 
#define SI2C1_SIC1_IC_COMP_PARAM_1_HAS_DMA_BIT   0x1
#define SI2C1_SIC1_IC_COMP_PARAM_1_HAS_DMA_BITWIDTH 1
// ADD_ENCODED_PARAMS bitfiled (RO) Reset=1
#define SI2C1_SIC1_IC_COMP_PARAM_1_ADD_ENCODED_PARAMS_MASK 0x80
#define SI2C1_SIC1_IC_COMP_PARAM_1_ADD_ENCODED_PARAMS_SHIFT 7 
#define SI2C1_SIC1_IC_COMP_PARAM_1_ADD_ENCODED_PARAMS_BIT 0x1
#define SI2C1_SIC1_IC_COMP_PARAM_1_ADD_ENCODED_PARAMS_BITWIDTH 1
// RX_BUFFER_DEPTH bitfiled (RO) Reset=1111
#define SI2C1_SIC1_IC_COMP_PARAM_1_RX_BUFFER_DEPTH_MASK 0xFF00
#define SI2C1_SIC1_IC_COMP_PARAM_1_RX_BUFFER_DEPTH_SHIFT 8 
#define SI2C1_SIC1_IC_COMP_PARAM_1_RX_BUFFER_DEPTH_BIT 0xFF
#define SI2C1_SIC1_IC_COMP_PARAM_1_RX_BUFFER_DEPTH_BITWIDTH 8
// TX_BUFFER_DEPTH bitfiled (RO) Reset=1111
#define SI2C1_SIC1_IC_COMP_PARAM_1_TX_BUFFER_DEPTH_MASK 0xFF0000
#define SI2C1_SIC1_IC_COMP_PARAM_1_TX_BUFFER_DEPTH_SHIFT 16 
#define SI2C1_SIC1_IC_COMP_PARAM_1_TX_BUFFER_DEPTH_BIT 0xFF
#define SI2C1_SIC1_IC_COMP_PARAM_1_TX_BUFFER_DEPTH_BITWIDTH 8
// reserved bitfiled (RO) Reset=0
#define SI2C1_SIC1_IC_COMP_PARAM_1_RESERVED_MASK 0xFF000000
#define SI2C1_SIC1_IC_COMP_PARAM_1_RESERVED_SHIFT 24 
#define SI2C1_SIC1_IC_COMP_PARAM_1_RESERVED_BIT  0xFF
#define SI2C1_SIC1_IC_COMP_PARAM_1_RESERVED_BITWIDTH 8
// SIC1_IC_COMP_VERSION Register
#define SI2C1_SIC1_IC_COMP_VERSION_OFS           0x000000F8
// IC_COMP_VERSION bitfiled (RO) Reset=110001001100100011000000101010
#define SI2C1_SIC1_IC_COMP_VERSION_IC_COMP_VERSION_MASK 0xFFFFFFFF
#define SI2C1_SIC1_IC_COMP_VERSION_IC_COMP_VERSION_SHIFT 0 
#define SI2C1_SIC1_IC_COMP_VERSION_IC_COMP_VERSION_BIT 0xFFFFFFFF
#define SI2C1_SIC1_IC_COMP_VERSION_IC_COMP_VERSION_BITWIDTH 32
// SIC1_IC_COMP_TYPE Register
#define SI2C1_SIC1_IC_COMP_TYPE_OFS              0x000000FC
// IC_COMP_TYPE bitfiled (RO) Reset=1000100010101110000000101000000
#define SI2C1_SIC1_IC_COMP_TYPE_IC_COMP_TYPE_MASK 0xFFFFFFFF
#define SI2C1_SIC1_IC_COMP_TYPE_IC_COMP_TYPE_SHIFT 0 
#define SI2C1_SIC1_IC_COMP_TYPE_IC_COMP_TYPE_BIT 0xFFFFFFFF
#define SI2C1_SIC1_IC_COMP_TYPE_IC_COMP_TYPE_BITWIDTH 32

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* _SI2C1_REG_DEF_H */
