/*
 * arch/arm/mach-tz3000/include/mach/regs/spib_reg_def.h
 *
 * (C) Copyright TOSHIBA Corporation
 * Semiconductor & Storage Products Company 2013
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#ifndef _SPIB_REG_DEF_H
#define _SPIB_REG_DEF_H

#ifdef __cplusplus
extern  {
#endif /* __cplusplus */

// SPIB0_FlshMemMap0 Register
#define SPIB_SPIB0_FLSHMEMMAP0_OFS               0x00000000
// RE bitfiled (RW) Reset=1
#define SPIB_SPIB0_FLSHMEMMAP0_RE_MASK           0x1
#define SPIB_SPIB0_FLSHMEMMAP0_RE_SHIFT          0 
#define SPIB_SPIB0_FLSHMEMMAP0_RE_BIT            0x1
#define SPIB_SPIB0_FLSHMEMMAP0_RE_BITWIDTH       1
// reserved2 bitfiled (RO) Reset=0
#define SPIB_SPIB0_FLSHMEMMAP0_RESERVED2_MASK    0x2
#define SPIB_SPIB0_FLSHMEMMAP0_RESERVED2_SHIFT   1 
#define SPIB_SPIB0_FLSHMEMMAP0_RESERVED2_BIT     0x1
#define SPIB_SPIB0_FLSHMEMMAP0_RESERVED2_BITWIDTH 1
// FDEN bitfiled (RW) Reset=1000
#define SPIB_SPIB0_FLSHMEMMAP0_FDEN_MASK         0x3C
#define SPIB_SPIB0_FLSHMEMMAP0_FDEN_SHIFT        2 
#define SPIB_SPIB0_FLSHMEMMAP0_FDEN_BIT          0xF
#define SPIB_SPIB0_FLSHMEMMAP0_FDEN_BITWIDTH     4
// reserved bitfiled (RO) Reset=0
#define SPIB_SPIB0_FLSHMEMMAP0_RESERVED_MASK     0xFFC0
#define SPIB_SPIB0_FLSHMEMMAP0_RESERVED_SHIFT    6 
#define SPIB_SPIB0_FLSHMEMMAP0_RESERVED_BIT      0x3FF
#define SPIB_SPIB0_FLSHMEMMAP0_RESERVED_BITWIDTH 10
// FBA bitfiled (RW) Reset=1011000000000000
#define SPIB_SPIB0_FLSHMEMMAP0_FBA_MASK          0xFFFF0000
#define SPIB_SPIB0_FLSHMEMMAP0_FBA_SHIFT         16 
#define SPIB_SPIB0_FLSHMEMMAP0_FBA_BIT           0xFFFF
#define SPIB_SPIB0_FLSHMEMMAP0_FBA_BITWIDTH      16
// SPIB0_FlshMemMap1 Register
#define SPIB_SPIB0_FLSHMEMMAP1_OFS               0x00000004
// RE bitfiled (RW) Reset=0
#define SPIB_SPIB0_FLSHMEMMAP1_RE_MASK           0x1
#define SPIB_SPIB0_FLSHMEMMAP1_RE_SHIFT          0 
#define SPIB_SPIB0_FLSHMEMMAP1_RE_BIT            0x1
#define SPIB_SPIB0_FLSHMEMMAP1_RE_BITWIDTH       1
// reserved2 bitfiled (RO) Reset=0
#define SPIB_SPIB0_FLSHMEMMAP1_RESERVED2_MASK    0x2
#define SPIB_SPIB0_FLSHMEMMAP1_RESERVED2_SHIFT   1 
#define SPIB_SPIB0_FLSHMEMMAP1_RESERVED2_BIT     0x1
#define SPIB_SPIB0_FLSHMEMMAP1_RESERVED2_BITWIDTH 1
// FDEN bitfiled (RW) Reset=1000
#define SPIB_SPIB0_FLSHMEMMAP1_FDEN_MASK         0x3C
#define SPIB_SPIB0_FLSHMEMMAP1_FDEN_SHIFT        2 
#define SPIB_SPIB0_FLSHMEMMAP1_FDEN_BIT          0xF
#define SPIB_SPIB0_FLSHMEMMAP1_FDEN_BITWIDTH     4
// reserved bitfiled (RO) Reset=0
#define SPIB_SPIB0_FLSHMEMMAP1_RESERVED_MASK     0xFFC0
#define SPIB_SPIB0_FLSHMEMMAP1_RESERVED_SHIFT    6 
#define SPIB_SPIB0_FLSHMEMMAP1_RESERVED_BIT      0x3FF
#define SPIB_SPIB0_FLSHMEMMAP1_RESERVED_BITWIDTH 10
// FBA bitfiled (RW) Reset=1011000000000000
#define SPIB_SPIB0_FLSHMEMMAP1_FBA_MASK          0xFFFF0000
#define SPIB_SPIB0_FLSHMEMMAP1_FBA_SHIFT         16 
#define SPIB_SPIB0_FLSHMEMMAP1_FBA_BIT           0xFFFF
#define SPIB_SPIB0_FLSHMEMMAP1_FBA_BITWIDTH      16
// SPIB0_DirAccCtrl0 Register
#define SPIB_SPIB0_DIRACCCTRL0_OFS               0x00000008
// SMOD bitfiled (RO) Reset=0
#define SPIB_SPIB0_DIRACCCTRL0_SMOD_MASK         0x3
#define SPIB_SPIB0_DIRACCCTRL0_SMOD_SHIFT        0 
#define SPIB_SPIB0_DIRACCCTRL0_SMOD_BIT          0x3
#define SPIB_SPIB0_DIRACCCTRL0_SMOD_BITWIDTH     2
// SDCE bitfiled (RW) Reset=0
#define SPIB_SPIB0_DIRACCCTRL0_SDCE_MASK         0x3C
#define SPIB_SPIB0_DIRACCCTRL0_SDCE_SHIFT        2 
#define SPIB_SPIB0_DIRACCCTRL0_SDCE_BIT          0xF
#define SPIB_SPIB0_DIRACCCTRL0_SDCE_BITWIDTH     4
// PollWIP bitfiled (RW) Reset=0
#define SPIB_SPIB0_DIRACCCTRL0_POLLWIP_MASK      0x40
#define SPIB_SPIB0_DIRACCCTRL0_POLLWIP_SHIFT     6 
#define SPIB_SPIB0_DIRACCCTRL0_POLLWIP_BIT       0x1
#define SPIB_SPIB0_DIRACCCTRL0_POLLWIP_BITWIDTH  1
// reserved2 bitfiled (RO) Reset=0
#define SPIB_SPIB0_DIRACCCTRL0_RESERVED2_MASK    0x80
#define SPIB_SPIB0_DIRACCCTRL0_RESERVED2_SHIFT   7 
#define SPIB_SPIB0_DIRACCCTRL0_RESERVED2_BIT     0x1
#define SPIB_SPIB0_DIRACCCTRL0_RESERVED2_BITWIDTH 1
// SCSD bitfiled (RW) Reset=11111
#define SPIB_SPIB0_DIRACCCTRL0_SCSD_MASK         0xFF00
#define SPIB_SPIB0_DIRACCCTRL0_SCSD_SHIFT        8 
#define SPIB_SPIB0_DIRACCCTRL0_SCSD_BIT          0xFF
#define SPIB_SPIB0_DIRACCCTRL0_SCSD_BITWIDTH     8
// SPR bitfiled (RW) Reset=11111
#define SPIB_SPIB0_DIRACCCTRL0_SPR_MASK          0x1F0000
#define SPIB_SPIB0_DIRACCCTRL0_SPR_SHIFT         16 
#define SPIB_SPIB0_DIRACCCTRL0_SPR_BIT           0x1F
#define SPIB_SPIB0_DIRACCCTRL0_SPR_BITWIDTH      5
// reserved bitfiled (RO) Reset=0
#define SPIB_SPIB0_DIRACCCTRL0_RESERVED_MASK     0xFFE00000
#define SPIB_SPIB0_DIRACCCTRL0_RESERVED_SHIFT    21 
#define SPIB_SPIB0_DIRACCCTRL0_RESERVED_BIT      0x7FF
#define SPIB_SPIB0_DIRACCCTRL0_RESERVED_BITWIDTH 11
// SPIB0_DirAccCtrl1 Register
#define SPIB_SPIB0_DIRACCCTRL1_OFS               0x0000000C
// SMOD bitfiled (RO) Reset=0
#define SPIB_SPIB0_DIRACCCTRL1_SMOD_MASK         0x3
#define SPIB_SPIB0_DIRACCCTRL1_SMOD_SHIFT        0 
#define SPIB_SPIB0_DIRACCCTRL1_SMOD_BIT          0x3
#define SPIB_SPIB0_DIRACCCTRL1_SMOD_BITWIDTH     2
// SDCE bitfiled (RW) Reset=0
#define SPIB_SPIB0_DIRACCCTRL1_SDCE_MASK         0x3C
#define SPIB_SPIB0_DIRACCCTRL1_SDCE_SHIFT        2 
#define SPIB_SPIB0_DIRACCCTRL1_SDCE_BIT          0xF
#define SPIB_SPIB0_DIRACCCTRL1_SDCE_BITWIDTH     4
// PollWIP bitfiled (RW) Reset=0
#define SPIB_SPIB0_DIRACCCTRL1_POLLWIP_MASK      0x40
#define SPIB_SPIB0_DIRACCCTRL1_POLLWIP_SHIFT     6 
#define SPIB_SPIB0_DIRACCCTRL1_POLLWIP_BIT       0x1
#define SPIB_SPIB0_DIRACCCTRL1_POLLWIP_BITWIDTH  1
// reserved2 bitfiled (RO) Reset=0
#define SPIB_SPIB0_DIRACCCTRL1_RESERVED2_MASK    0x80
#define SPIB_SPIB0_DIRACCCTRL1_RESERVED2_SHIFT   7 
#define SPIB_SPIB0_DIRACCCTRL1_RESERVED2_BIT     0x1
#define SPIB_SPIB0_DIRACCCTRL1_RESERVED2_BITWIDTH 1
// SCSD bitfiled (RW) Reset=11111
#define SPIB_SPIB0_DIRACCCTRL1_SCSD_MASK         0xFF00
#define SPIB_SPIB0_DIRACCCTRL1_SCSD_SHIFT        8 
#define SPIB_SPIB0_DIRACCCTRL1_SCSD_BIT          0xFF
#define SPIB_SPIB0_DIRACCCTRL1_SCSD_BITWIDTH     8
// SPR bitfiled (RW) Reset=11111
#define SPIB_SPIB0_DIRACCCTRL1_SPR_MASK          0x1F0000
#define SPIB_SPIB0_DIRACCCTRL1_SPR_SHIFT         16 
#define SPIB_SPIB0_DIRACCCTRL1_SPR_BIT           0x1F
#define SPIB_SPIB0_DIRACCCTRL1_SPR_BITWIDTH      5
// reserved bitfiled (RO) Reset=0
#define SPIB_SPIB0_DIRACCCTRL1_RESERVED_MASK     0xFFE00000
#define SPIB_SPIB0_DIRACCCTRL1_RESERVED_SHIFT    21 
#define SPIB_SPIB0_DIRACCCTRL1_RESERVED_BIT      0x7FF
#define SPIB_SPIB0_DIRACCCTRL1_RESERVED_BITWIDTH 11
// SPIB0_DirRdCtrl0 Register
#define SPIB_SPIB0_DIRRDCTRL0_OFS                0x00000010
// SpiCmdIOCtrl bitfiled (RW) Reset=0
#define SPIB_SPIB0_DIRRDCTRL0_SPICMDIOCTRL_MASK  0x3
#define SPIB_SPIB0_DIRRDCTRL0_SPICMDIOCTRL_SHIFT 0 
#define SPIB_SPIB0_DIRRDCTRL0_SPICMDIOCTRL_BIT   0x3
#define SPIB_SPIB0_DIRRDCTRL0_SPICMDIOCTRL_BITWIDTH 2
// SpiAdrIOCtrl bitfiled (RW) Reset=0
#define SPIB_SPIB0_DIRRDCTRL0_SPIADRIOCTRL_MASK  0xC
#define SPIB_SPIB0_DIRRDCTRL0_SPIADRIOCTRL_SHIFT 2 
#define SPIB_SPIB0_DIRRDCTRL0_SPIADRIOCTRL_BIT   0x3
#define SPIB_SPIB0_DIRRDCTRL0_SPIADRIOCTRL_BITWIDTH 2
// SpiDmyIOCtrl bitfiled (RW) Reset=0
#define SPIB_SPIB0_DIRRDCTRL0_SPIDMYIOCTRL_MASK  0x30
#define SPIB_SPIB0_DIRRDCTRL0_SPIDMYIOCTRL_SHIFT 4 
#define SPIB_SPIB0_DIRRDCTRL0_SPIDMYIOCTRL_BIT   0x3
#define SPIB_SPIB0_DIRRDCTRL0_SPIDMYIOCTRL_BITWIDTH 2
// SpiDatIOCtrl bitfiled (RW) Reset=0
#define SPIB_SPIB0_DIRRDCTRL0_SPIDATIOCTRL_MASK  0xC0
#define SPIB_SPIB0_DIRRDCTRL0_SPIDATIOCTRL_SHIFT 6 
#define SPIB_SPIB0_DIRRDCTRL0_SPIDATIOCTRL_BIT   0x3
#define SPIB_SPIB0_DIRRDCTRL0_SPIDATIOCTRL_BITWIDTH 2
// reserved2 bitfiled (RO) Reset=0
#define SPIB_SPIB0_DIRRDCTRL0_RESERVED2_MASK     0x700
#define SPIB_SPIB0_DIRRDCTRL0_RESERVED2_SHIFT    8 
#define SPIB_SPIB0_DIRRDCTRL0_RESERVED2_BIT      0x7
#define SPIB_SPIB0_DIRRDCTRL0_RESERVED2_BITWIDTH 3
// SpiAddrByteCnt bitfiled (RW) Reset=0
#define SPIB_SPIB0_DIRRDCTRL0_SPIADDRBYTECNT_MASK 0x800
#define SPIB_SPIB0_DIRRDCTRL0_SPIADDRBYTECNT_SHIFT 11 
#define SPIB_SPIB0_DIRRDCTRL0_SPIADDRBYTECNT_BIT 0x1
#define SPIB_SPIB0_DIRRDCTRL0_SPIADDRBYTECNT_BITWIDTH 1
// SpiDmyByteCnt bitfiled (RW) Reset=1
#define SPIB_SPIB0_DIRRDCTRL0_SPIDMYBYTECNT_MASK 0xF000
#define SPIB_SPIB0_DIRRDCTRL0_SPIDMYBYTECNT_SHIFT 12 
#define SPIB_SPIB0_DIRRDCTRL0_SPIDMYBYTECNT_BIT  0xF
#define SPIB_SPIB0_DIRRDCTRL0_SPIDMYBYTECNT_BITWIDTH 4
// reserved bitfiled (RO) Reset=0
#define SPIB_SPIB0_DIRRDCTRL0_RESERVED_MASK      0xFF0000
#define SPIB_SPIB0_DIRRDCTRL0_RESERVED_SHIFT     16 
#define SPIB_SPIB0_DIRRDCTRL0_RESERVED_BIT       0xFF
#define SPIB_SPIB0_DIRRDCTRL0_RESERVED_BITWIDTH  8
// SpiCmdOp bitfiled (RW) Reset=1011
#define SPIB_SPIB0_DIRRDCTRL0_SPICMDOP_MASK      0xFF000000
#define SPIB_SPIB0_DIRRDCTRL0_SPICMDOP_SHIFT     24 
#define SPIB_SPIB0_DIRRDCTRL0_SPICMDOP_BIT       0xFF
#define SPIB_SPIB0_DIRRDCTRL0_SPICMDOP_BITWIDTH  8
// SPIB0_DirRdCtrl1 Register
#define SPIB_SPIB0_DIRRDCTRL1_OFS                0x00000014
// SpiCmdIOCtrl bitfiled (RW) Reset=0
#define SPIB_SPIB0_DIRRDCTRL1_SPICMDIOCTRL_MASK  0x3
#define SPIB_SPIB0_DIRRDCTRL1_SPICMDIOCTRL_SHIFT 0 
#define SPIB_SPIB0_DIRRDCTRL1_SPICMDIOCTRL_BIT   0x3
#define SPIB_SPIB0_DIRRDCTRL1_SPICMDIOCTRL_BITWIDTH 2
// SpiAdrIOCtrl bitfiled (RW) Reset=0
#define SPIB_SPIB0_DIRRDCTRL1_SPIADRIOCTRL_MASK  0xC
#define SPIB_SPIB0_DIRRDCTRL1_SPIADRIOCTRL_SHIFT 2 
#define SPIB_SPIB0_DIRRDCTRL1_SPIADRIOCTRL_BIT   0x3
#define SPIB_SPIB0_DIRRDCTRL1_SPIADRIOCTRL_BITWIDTH 2
// SpiDmyIOCtrl bitfiled (RW) Reset=0
#define SPIB_SPIB0_DIRRDCTRL1_SPIDMYIOCTRL_MASK  0x30
#define SPIB_SPIB0_DIRRDCTRL1_SPIDMYIOCTRL_SHIFT 4 
#define SPIB_SPIB0_DIRRDCTRL1_SPIDMYIOCTRL_BIT   0x3
#define SPIB_SPIB0_DIRRDCTRL1_SPIDMYIOCTRL_BITWIDTH 2
// SpiDatIOCtrl bitfiled (RW) Reset=0
#define SPIB_SPIB0_DIRRDCTRL1_SPIDATIOCTRL_MASK  0xC0
#define SPIB_SPIB0_DIRRDCTRL1_SPIDATIOCTRL_SHIFT 6 
#define SPIB_SPIB0_DIRRDCTRL1_SPIDATIOCTRL_BIT   0x3
#define SPIB_SPIB0_DIRRDCTRL1_SPIDATIOCTRL_BITWIDTH 2
// reserved2 bitfiled (RO) Reset=0
#define SPIB_SPIB0_DIRRDCTRL1_RESERVED2_MASK     0x700
#define SPIB_SPIB0_DIRRDCTRL1_RESERVED2_SHIFT    8 
#define SPIB_SPIB0_DIRRDCTRL1_RESERVED2_BIT      0x7
#define SPIB_SPIB0_DIRRDCTRL1_RESERVED2_BITWIDTH 3
// SpiAddrByteCnt bitfiled (RW) Reset=0
#define SPIB_SPIB0_DIRRDCTRL1_SPIADDRBYTECNT_MASK 0x800
#define SPIB_SPIB0_DIRRDCTRL1_SPIADDRBYTECNT_SHIFT 11 
#define SPIB_SPIB0_DIRRDCTRL1_SPIADDRBYTECNT_BIT 0x1
#define SPIB_SPIB0_DIRRDCTRL1_SPIADDRBYTECNT_BITWIDTH 1
// SpiDmyByteCnt bitfiled (RW) Reset=1
#define SPIB_SPIB0_DIRRDCTRL1_SPIDMYBYTECNT_MASK 0xF000
#define SPIB_SPIB0_DIRRDCTRL1_SPIDMYBYTECNT_SHIFT 12 
#define SPIB_SPIB0_DIRRDCTRL1_SPIDMYBYTECNT_BIT  0xF
#define SPIB_SPIB0_DIRRDCTRL1_SPIDMYBYTECNT_BITWIDTH 4
// reserved bitfiled (RO) Reset=0
#define SPIB_SPIB0_DIRRDCTRL1_RESERVED_MASK      0xFF0000
#define SPIB_SPIB0_DIRRDCTRL1_RESERVED_SHIFT     16 
#define SPIB_SPIB0_DIRRDCTRL1_RESERVED_BIT       0xFF
#define SPIB_SPIB0_DIRRDCTRL1_RESERVED_BITWIDTH  8
// SpiCmdOp bitfiled (RW) Reset=1011
#define SPIB_SPIB0_DIRRDCTRL1_SPICMDOP_MASK      0xFF000000
#define SPIB_SPIB0_DIRRDCTRL1_SPICMDOP_SHIFT     24 
#define SPIB_SPIB0_DIRRDCTRL1_SPICMDOP_BIT       0xFF
#define SPIB_SPIB0_DIRRDCTRL1_SPICMDOP_BITWIDTH  8
// SPIB0_PrgAccCtrl0 Register
#define SPIB_SPIB0_PRGACCCTRL0_OFS               0x00000400
// SMOD bitfiled (RO) Reset=0
#define SPIB_SPIB0_PRGACCCTRL0_SMOD_MASK         0x3
#define SPIB_SPIB0_PRGACCCTRL0_SMOD_SHIFT        0 
#define SPIB_SPIB0_PRGACCCTRL0_SMOD_BIT          0x3
#define SPIB_SPIB0_PRGACCCTRL0_SMOD_BITWIDTH     2
// SDCE bitfiled (RW) Reset=0
#define SPIB_SPIB0_PRGACCCTRL0_SDCE_MASK         0x3C
#define SPIB_SPIB0_PRGACCCTRL0_SDCE_SHIFT        2 
#define SPIB_SPIB0_PRGACCCTRL0_SDCE_BIT          0xF
#define SPIB_SPIB0_PRGACCCTRL0_SDCE_BITWIDTH     4
// reserved2 bitfiled (RO) Reset=0
#define SPIB_SPIB0_PRGACCCTRL0_RESERVED2_MASK    0xC0
#define SPIB_SPIB0_PRGACCCTRL0_RESERVED2_SHIFT   6 
#define SPIB_SPIB0_PRGACCCTRL0_RESERVED2_BIT     0x3
#define SPIB_SPIB0_PRGACCCTRL0_RESERVED2_BITWIDTH 2
// SCSD bitfiled (RW) Reset=11111
#define SPIB_SPIB0_PRGACCCTRL0_SCSD_MASK         0xFF00
#define SPIB_SPIB0_PRGACCCTRL0_SCSD_SHIFT        8 
#define SPIB_SPIB0_PRGACCCTRL0_SCSD_BIT          0xFF
#define SPIB_SPIB0_PRGACCCTRL0_SCSD_BITWIDTH     8
// SPR bitfiled (RW) Reset=11111
#define SPIB_SPIB0_PRGACCCTRL0_SPR_MASK          0x1F0000
#define SPIB_SPIB0_PRGACCCTRL0_SPR_SHIFT         16 
#define SPIB_SPIB0_PRGACCCTRL0_SPR_BIT           0x1F
#define SPIB_SPIB0_PRGACCCTRL0_SPR_BITWIDTH      5
// reserved bitfiled (RO) Reset=0
#define SPIB_SPIB0_PRGACCCTRL0_RESERVED_MASK     0xFFE00000
#define SPIB_SPIB0_PRGACCCTRL0_RESERVED_SHIFT    21 
#define SPIB_SPIB0_PRGACCCTRL0_RESERVED_BIT      0x7FF
#define SPIB_SPIB0_PRGACCCTRL0_RESERVED_BITWIDTH 11
// SPIB0_PrgAccCtrl1 Register
#define SPIB_SPIB0_PRGACCCTRL1_OFS               0x00000404
// SpiCycGo bitfiled (RW) Reset=0
#define SPIB_SPIB0_PRGACCCTRL1_SPICYCGO_MASK     0x1
#define SPIB_SPIB0_PRGACCCTRL1_SPICYCGO_SHIFT    0 
#define SPIB_SPIB0_PRGACCCTRL1_SPICYCGO_BIT      0x1
#define SPIB_SPIB0_PRGACCCTRL1_SPICYCGO_BITWIDTH 1
// SpiCsNum bitfiled (RW) Reset=0
#define SPIB_SPIB0_PRGACCCTRL1_SPICSNUM_MASK     0x2
#define SPIB_SPIB0_PRGACCCTRL1_SPICSNUM_SHIFT    1 
#define SPIB_SPIB0_PRGACCCTRL1_SPICSNUM_BIT      0x1
#define SPIB_SPIB0_PRGACCCTRL1_SPICSNUM_BITWIDTH 1
// reserved3 bitfiled (RO) Reset=0
#define SPIB_SPIB0_PRGACCCTRL1_RESERVED3_MASK    0xC
#define SPIB_SPIB0_PRGACCCTRL1_RESERVED3_SHIFT   2 
#define SPIB_SPIB0_PRGACCCTRL1_RESERVED3_BIT     0x3
#define SPIB_SPIB0_PRGACCCTRL1_RESERVED3_BITWIDTH 2
// PriBufEn bitfiled (RW) Reset=0
#define SPIB_SPIB0_PRGACCCTRL1_PRIBUFEN_MASK     0x10
#define SPIB_SPIB0_PRGACCCTRL1_PRIBUFEN_SHIFT    4 
#define SPIB_SPIB0_PRGACCCTRL1_PRIBUFEN_BIT      0x1
#define SPIB_SPIB0_PRGACCCTRL1_PRIBUFEN_BITWIDTH 1
// SecBufEn bitfiled (RW) Reset=0
#define SPIB_SPIB0_PRGACCCTRL1_SECBUFEN_MASK     0x20
#define SPIB_SPIB0_PRGACCCTRL1_SECBUFEN_SHIFT    5 
#define SPIB_SPIB0_PRGACCCTRL1_SECBUFEN_BIT      0x1
#define SPIB_SPIB0_PRGACCCTRL1_SECBUFEN_BITWIDTH 1
// reserved2 bitfiled (RO) Reset=0
#define SPIB_SPIB0_PRGACCCTRL1_RESERVED2_MASK    0xFFC0
#define SPIB_SPIB0_PRGACCCTRL1_RESERVED2_SHIFT   6 
#define SPIB_SPIB0_PRGACCCTRL1_RESERVED2_BIT     0x3FF
#define SPIB_SPIB0_PRGACCCTRL1_RESERVED2_BITWIDTH 10
// PriBufDatByteCnt bitfiled (RW) Reset=0
#define SPIB_SPIB0_PRGACCCTRL1_PRIBUFDATBYTECNT_MASK 0x70000
#define SPIB_SPIB0_PRGACCCTRL1_PRIBUFDATBYTECNT_SHIFT 16 
#define SPIB_SPIB0_PRGACCCTRL1_PRIBUFDATBYTECNT_BIT 0x7
#define SPIB_SPIB0_PRGACCCTRL1_PRIBUFDATBYTECNT_BITWIDTH 3
// reserved bitfiled (RO) Reset=0
#define SPIB_SPIB0_PRGACCCTRL1_RESERVED_MASK     0xF80000
#define SPIB_SPIB0_PRGACCCTRL1_RESERVED_SHIFT    19 
#define SPIB_SPIB0_PRGACCCTRL1_RESERVED_BIT      0x1F
#define SPIB_SPIB0_PRGACCCTRL1_RESERVED_BITWIDTH 5
// SecBufDatByteCnt bitfiled (RW) Reset=0
#define SPIB_SPIB0_PRGACCCTRL1_SECBUFDATBYTECNT_MASK 0xFF000000
#define SPIB_SPIB0_PRGACCCTRL1_SECBUFDATBYTECNT_SHIFT 24 
#define SPIB_SPIB0_PRGACCCTRL1_SECBUFDATBYTECNT_BIT 0xFF
#define SPIB_SPIB0_PRGACCCTRL1_SECBUFDATBYTECNT_BITWIDTH 8
// SPIB0_PrgAccIntEn Register
#define SPIB_SPIB0_PRGACCINTEN_OFS               0x00000408
// SpiIntEn bitfiled (RW) Reset=0
#define SPIB_SPIB0_PRGACCINTEN_SPIINTEN_MASK     0x1
#define SPIB_SPIB0_PRGACCINTEN_SPIINTEN_SHIFT    0 
#define SPIB_SPIB0_PRGACCINTEN_SPIINTEN_BIT      0x1
#define SPIB_SPIB0_PRGACCINTEN_SPIINTEN_BITWIDTH 1
// reserved bitfiled (RO) Reset=0
#define SPIB_SPIB0_PRGACCINTEN_RESERVED_MASK     0xFFFFFFFE
#define SPIB_SPIB0_PRGACCINTEN_RESERVED_SHIFT    1 
#define SPIB_SPIB0_PRGACCINTEN_RESERVED_BIT      0x7FFFFFFF
#define SPIB_SPIB0_PRGACCINTEN_RESERVED_BITWIDTH 31
// SPIB0_PrgAccStat Register
#define SPIB_SPIB0_PRGACCSTAT_OFS                0x0000040C
// SpiCycDone bitfiled (RW) Reset=0
#define SPIB_SPIB0_PRGACCSTAT_SPICYCDONE_MASK    0x1
#define SPIB_SPIB0_PRGACCSTAT_SPICYCDONE_SHIFT   0 
#define SPIB_SPIB0_PRGACCSTAT_SPICYCDONE_BIT     0x1
#define SPIB_SPIB0_PRGACCSTAT_SPICYCDONE_BITWIDTH 1
// SpiCycInPrgrs bitfiled (RO) Reset=0
#define SPIB_SPIB0_PRGACCSTAT_SPICYCINPRGRS_MASK 0x2
#define SPIB_SPIB0_PRGACCSTAT_SPICYCINPRGRS_SHIFT 1 
#define SPIB_SPIB0_PRGACCSTAT_SPICYCINPRGRS_BIT  0x1
#define SPIB_SPIB0_PRGACCSTAT_SPICYCINPRGRS_BITWIDTH 1
// reserved bitfiled (RO) Reset=0
#define SPIB_SPIB0_PRGACCSTAT_RESERVED_MASK      0xFFFFFFFC
#define SPIB_SPIB0_PRGACCSTAT_RESERVED_SHIFT     2 
#define SPIB_SPIB0_PRGACCSTAT_RESERVED_BIT       0x3FFFFFFF
#define SPIB_SPIB0_PRGACCSTAT_RESERVED_BITWIDTH  30
// SPIB1_FlshMemMap0 Register
#define SPIB_SPIB1_FLSHMEMMAP0_OFS               0x00001000
// RE bitfiled (RW) Reset=1
#define SPIB_SPIB1_FLSHMEMMAP0_RE_MASK           0x1
#define SPIB_SPIB1_FLSHMEMMAP0_RE_SHIFT          0 
#define SPIB_SPIB1_FLSHMEMMAP0_RE_BIT            0x1
#define SPIB_SPIB1_FLSHMEMMAP0_RE_BITWIDTH       1
// reserved2 bitfiled (RO) Reset=0
#define SPIB_SPIB1_FLSHMEMMAP0_RESERVED2_MASK    0x2
#define SPIB_SPIB1_FLSHMEMMAP0_RESERVED2_SHIFT   1 
#define SPIB_SPIB1_FLSHMEMMAP0_RESERVED2_BIT     0x1
#define SPIB_SPIB1_FLSHMEMMAP0_RESERVED2_BITWIDTH 1
// FDEN bitfiled (RW) Reset=1000
#define SPIB_SPIB1_FLSHMEMMAP0_FDEN_MASK         0x3C
#define SPIB_SPIB1_FLSHMEMMAP0_FDEN_SHIFT        2 
#define SPIB_SPIB1_FLSHMEMMAP0_FDEN_BIT          0xF
#define SPIB_SPIB1_FLSHMEMMAP0_FDEN_BITWIDTH     4
// reserved bitfiled (RO) Reset=0
#define SPIB_SPIB1_FLSHMEMMAP0_RESERVED_MASK     0xFFC0
#define SPIB_SPIB1_FLSHMEMMAP0_RESERVED_SHIFT    6 
#define SPIB_SPIB1_FLSHMEMMAP0_RESERVED_BIT      0x3FF
#define SPIB_SPIB1_FLSHMEMMAP0_RESERVED_BITWIDTH 10
// FBA bitfiled (RW) Reset=1011000000000000
#define SPIB_SPIB1_FLSHMEMMAP0_FBA_MASK          0xFFFF0000
#define SPIB_SPIB1_FLSHMEMMAP0_FBA_SHIFT         16 
#define SPIB_SPIB1_FLSHMEMMAP0_FBA_BIT           0xFFFF
#define SPIB_SPIB1_FLSHMEMMAP0_FBA_BITWIDTH      16
// SPIB1_FlshMemMap1 Register
#define SPIB_SPIB1_FLSHMEMMAP1_OFS               0x00001004
// RE bitfiled (RW) Reset=0
#define SPIB_SPIB1_FLSHMEMMAP1_RE_MASK           0x1
#define SPIB_SPIB1_FLSHMEMMAP1_RE_SHIFT          0 
#define SPIB_SPIB1_FLSHMEMMAP1_RE_BIT            0x1
#define SPIB_SPIB1_FLSHMEMMAP1_RE_BITWIDTH       1
// reserved2 bitfiled (RO) Reset=0
#define SPIB_SPIB1_FLSHMEMMAP1_RESERVED2_MASK    0x2
#define SPIB_SPIB1_FLSHMEMMAP1_RESERVED2_SHIFT   1 
#define SPIB_SPIB1_FLSHMEMMAP1_RESERVED2_BIT     0x1
#define SPIB_SPIB1_FLSHMEMMAP1_RESERVED2_BITWIDTH 1
// FDEN bitfiled (RW) Reset=1000
#define SPIB_SPIB1_FLSHMEMMAP1_FDEN_MASK         0x3C
#define SPIB_SPIB1_FLSHMEMMAP1_FDEN_SHIFT        2 
#define SPIB_SPIB1_FLSHMEMMAP1_FDEN_BIT          0xF
#define SPIB_SPIB1_FLSHMEMMAP1_FDEN_BITWIDTH     4
// reserved bitfiled (RO) Reset=0
#define SPIB_SPIB1_FLSHMEMMAP1_RESERVED_MASK     0xFFC0
#define SPIB_SPIB1_FLSHMEMMAP1_RESERVED_SHIFT    6 
#define SPIB_SPIB1_FLSHMEMMAP1_RESERVED_BIT      0x3FF
#define SPIB_SPIB1_FLSHMEMMAP1_RESERVED_BITWIDTH 10
// FBA bitfiled (RW) Reset=1011000000000000
#define SPIB_SPIB1_FLSHMEMMAP1_FBA_MASK          0xFFFF0000
#define SPIB_SPIB1_FLSHMEMMAP1_FBA_SHIFT         16 
#define SPIB_SPIB1_FLSHMEMMAP1_FBA_BIT           0xFFFF
#define SPIB_SPIB1_FLSHMEMMAP1_FBA_BITWIDTH      16
// SPIB1_DirAccCtrl0 Register
#define SPIB_SPIB1_DIRACCCTRL0_OFS               0x00001008
// SMOD bitfiled (RO) Reset=0
#define SPIB_SPIB1_DIRACCCTRL0_SMOD_MASK         0x3
#define SPIB_SPIB1_DIRACCCTRL0_SMOD_SHIFT        0 
#define SPIB_SPIB1_DIRACCCTRL0_SMOD_BIT          0x3
#define SPIB_SPIB1_DIRACCCTRL0_SMOD_BITWIDTH     2
// SDCE bitfiled (RW) Reset=0
#define SPIB_SPIB1_DIRACCCTRL0_SDCE_MASK         0x3C
#define SPIB_SPIB1_DIRACCCTRL0_SDCE_SHIFT        2 
#define SPIB_SPIB1_DIRACCCTRL0_SDCE_BIT          0xF
#define SPIB_SPIB1_DIRACCCTRL0_SDCE_BITWIDTH     4
// PollWIP bitfiled (RW) Reset=0
#define SPIB_SPIB1_DIRACCCTRL0_POLLWIP_MASK      0x40
#define SPIB_SPIB1_DIRACCCTRL0_POLLWIP_SHIFT     6 
#define SPIB_SPIB1_DIRACCCTRL0_POLLWIP_BIT       0x1
#define SPIB_SPIB1_DIRACCCTRL0_POLLWIP_BITWIDTH  1
// reserved2 bitfiled (RO) Reset=0
#define SPIB_SPIB1_DIRACCCTRL0_RESERVED2_MASK    0x80
#define SPIB_SPIB1_DIRACCCTRL0_RESERVED2_SHIFT   7 
#define SPIB_SPIB1_DIRACCCTRL0_RESERVED2_BIT     0x1
#define SPIB_SPIB1_DIRACCCTRL0_RESERVED2_BITWIDTH 1
// SCSD bitfiled (RW) Reset=11111
#define SPIB_SPIB1_DIRACCCTRL0_SCSD_MASK         0xFF00
#define SPIB_SPIB1_DIRACCCTRL0_SCSD_SHIFT        8 
#define SPIB_SPIB1_DIRACCCTRL0_SCSD_BIT          0xFF
#define SPIB_SPIB1_DIRACCCTRL0_SCSD_BITWIDTH     8
// SPR bitfiled (RW) Reset=11111
#define SPIB_SPIB1_DIRACCCTRL0_SPR_MASK          0x1F0000
#define SPIB_SPIB1_DIRACCCTRL0_SPR_SHIFT         16 
#define SPIB_SPIB1_DIRACCCTRL0_SPR_BIT           0x1F
#define SPIB_SPIB1_DIRACCCTRL0_SPR_BITWIDTH      5
// reserved bitfiled (RO) Reset=0
#define SPIB_SPIB1_DIRACCCTRL0_RESERVED_MASK     0xFFE00000
#define SPIB_SPIB1_DIRACCCTRL0_RESERVED_SHIFT    21 
#define SPIB_SPIB1_DIRACCCTRL0_RESERVED_BIT      0x7FF
#define SPIB_SPIB1_DIRACCCTRL0_RESERVED_BITWIDTH 11
// SPIB1_DirAccCtrl1 Register
#define SPIB_SPIB1_DIRACCCTRL1_OFS               0x0000100C
// SMOD bitfiled (RO) Reset=0
#define SPIB_SPIB1_DIRACCCTRL1_SMOD_MASK         0x3
#define SPIB_SPIB1_DIRACCCTRL1_SMOD_SHIFT        0 
#define SPIB_SPIB1_DIRACCCTRL1_SMOD_BIT          0x3
#define SPIB_SPIB1_DIRACCCTRL1_SMOD_BITWIDTH     2
// SDCE bitfiled (RW) Reset=0
#define SPIB_SPIB1_DIRACCCTRL1_SDCE_MASK         0x3C
#define SPIB_SPIB1_DIRACCCTRL1_SDCE_SHIFT        2 
#define SPIB_SPIB1_DIRACCCTRL1_SDCE_BIT          0xF
#define SPIB_SPIB1_DIRACCCTRL1_SDCE_BITWIDTH     4
// PollWIP bitfiled (RW) Reset=0
#define SPIB_SPIB1_DIRACCCTRL1_POLLWIP_MASK      0x40
#define SPIB_SPIB1_DIRACCCTRL1_POLLWIP_SHIFT     6 
#define SPIB_SPIB1_DIRACCCTRL1_POLLWIP_BIT       0x1
#define SPIB_SPIB1_DIRACCCTRL1_POLLWIP_BITWIDTH  1
// reserved2 bitfiled (RO) Reset=0
#define SPIB_SPIB1_DIRACCCTRL1_RESERVED2_MASK    0x80
#define SPIB_SPIB1_DIRACCCTRL1_RESERVED2_SHIFT   7 
#define SPIB_SPIB1_DIRACCCTRL1_RESERVED2_BIT     0x1
#define SPIB_SPIB1_DIRACCCTRL1_RESERVED2_BITWIDTH 1
// SCSD bitfiled (RW) Reset=11111
#define SPIB_SPIB1_DIRACCCTRL1_SCSD_MASK         0xFF00
#define SPIB_SPIB1_DIRACCCTRL1_SCSD_SHIFT        8 
#define SPIB_SPIB1_DIRACCCTRL1_SCSD_BIT          0xFF
#define SPIB_SPIB1_DIRACCCTRL1_SCSD_BITWIDTH     8
// SPR bitfiled (RW) Reset=11111
#define SPIB_SPIB1_DIRACCCTRL1_SPR_MASK          0x1F0000
#define SPIB_SPIB1_DIRACCCTRL1_SPR_SHIFT         16 
#define SPIB_SPIB1_DIRACCCTRL1_SPR_BIT           0x1F
#define SPIB_SPIB1_DIRACCCTRL1_SPR_BITWIDTH      5
// reserved bitfiled (RO) Reset=0
#define SPIB_SPIB1_DIRACCCTRL1_RESERVED_MASK     0xFFE00000
#define SPIB_SPIB1_DIRACCCTRL1_RESERVED_SHIFT    21 
#define SPIB_SPIB1_DIRACCCTRL1_RESERVED_BIT      0x7FF
#define SPIB_SPIB1_DIRACCCTRL1_RESERVED_BITWIDTH 11
// SPIB1_DirRdCtrl0 Register
#define SPIB_SPIB1_DIRRDCTRL0_OFS                0x00001010
// SpiCmdIOCtrl bitfiled (RW) Reset=0
#define SPIB_SPIB1_DIRRDCTRL0_SPICMDIOCTRL_MASK  0x3
#define SPIB_SPIB1_DIRRDCTRL0_SPICMDIOCTRL_SHIFT 0 
#define SPIB_SPIB1_DIRRDCTRL0_SPICMDIOCTRL_BIT   0x3
#define SPIB_SPIB1_DIRRDCTRL0_SPICMDIOCTRL_BITWIDTH 2
// SpiAdrIOCtrl bitfiled (RW) Reset=0
#define SPIB_SPIB1_DIRRDCTRL0_SPIADRIOCTRL_MASK  0xC
#define SPIB_SPIB1_DIRRDCTRL0_SPIADRIOCTRL_SHIFT 2 
#define SPIB_SPIB1_DIRRDCTRL0_SPIADRIOCTRL_BIT   0x3
#define SPIB_SPIB1_DIRRDCTRL0_SPIADRIOCTRL_BITWIDTH 2
// SpiDmyIOCtrl bitfiled (RW) Reset=0
#define SPIB_SPIB1_DIRRDCTRL0_SPIDMYIOCTRL_MASK  0x30
#define SPIB_SPIB1_DIRRDCTRL0_SPIDMYIOCTRL_SHIFT 4 
#define SPIB_SPIB1_DIRRDCTRL0_SPIDMYIOCTRL_BIT   0x3
#define SPIB_SPIB1_DIRRDCTRL0_SPIDMYIOCTRL_BITWIDTH 2
// SpiDatIOCtrl bitfiled (RW) Reset=0
#define SPIB_SPIB1_DIRRDCTRL0_SPIDATIOCTRL_MASK  0xC0
#define SPIB_SPIB1_DIRRDCTRL0_SPIDATIOCTRL_SHIFT 6 
#define SPIB_SPIB1_DIRRDCTRL0_SPIDATIOCTRL_BIT   0x3
#define SPIB_SPIB1_DIRRDCTRL0_SPIDATIOCTRL_BITWIDTH 2
// reserved2 bitfiled (RO) Reset=0
#define SPIB_SPIB1_DIRRDCTRL0_RESERVED2_MASK     0x700
#define SPIB_SPIB1_DIRRDCTRL0_RESERVED2_SHIFT    8 
#define SPIB_SPIB1_DIRRDCTRL0_RESERVED2_BIT      0x7
#define SPIB_SPIB1_DIRRDCTRL0_RESERVED2_BITWIDTH 3
// SpiAddrByteCnt bitfiled (RW) Reset=0
#define SPIB_SPIB1_DIRRDCTRL0_SPIADDRBYTECNT_MASK 0x800
#define SPIB_SPIB1_DIRRDCTRL0_SPIADDRBYTECNT_SHIFT 11 
#define SPIB_SPIB1_DIRRDCTRL0_SPIADDRBYTECNT_BIT 0x1
#define SPIB_SPIB1_DIRRDCTRL0_SPIADDRBYTECNT_BITWIDTH 1
// SpiDmyByteCnt bitfiled (RW) Reset=1
#define SPIB_SPIB1_DIRRDCTRL0_SPIDMYBYTECNT_MASK 0xF000
#define SPIB_SPIB1_DIRRDCTRL0_SPIDMYBYTECNT_SHIFT 12 
#define SPIB_SPIB1_DIRRDCTRL0_SPIDMYBYTECNT_BIT  0xF
#define SPIB_SPIB1_DIRRDCTRL0_SPIDMYBYTECNT_BITWIDTH 4
// reserved bitfiled (RO) Reset=0
#define SPIB_SPIB1_DIRRDCTRL0_RESERVED_MASK      0xFF0000
#define SPIB_SPIB1_DIRRDCTRL0_RESERVED_SHIFT     16 
#define SPIB_SPIB1_DIRRDCTRL0_RESERVED_BIT       0xFF
#define SPIB_SPIB1_DIRRDCTRL0_RESERVED_BITWIDTH  8
// SpiCmdOp bitfiled (RW) Reset=1011
#define SPIB_SPIB1_DIRRDCTRL0_SPICMDOP_MASK      0xFF000000
#define SPIB_SPIB1_DIRRDCTRL0_SPICMDOP_SHIFT     24 
#define SPIB_SPIB1_DIRRDCTRL0_SPICMDOP_BIT       0xFF
#define SPIB_SPIB1_DIRRDCTRL0_SPICMDOP_BITWIDTH  8
// SPIB1_DirRdCtrl1 Register
#define SPIB_SPIB1_DIRRDCTRL1_OFS                0x00001014
// SpiCmdIOCtrl bitfiled (RW) Reset=0
#define SPIB_SPIB1_DIRRDCTRL1_SPICMDIOCTRL_MASK  0x3
#define SPIB_SPIB1_DIRRDCTRL1_SPICMDIOCTRL_SHIFT 0 
#define SPIB_SPIB1_DIRRDCTRL1_SPICMDIOCTRL_BIT   0x3
#define SPIB_SPIB1_DIRRDCTRL1_SPICMDIOCTRL_BITWIDTH 2
// SpiAdrIOCtrl bitfiled (RW) Reset=0
#define SPIB_SPIB1_DIRRDCTRL1_SPIADRIOCTRL_MASK  0xC
#define SPIB_SPIB1_DIRRDCTRL1_SPIADRIOCTRL_SHIFT 2 
#define SPIB_SPIB1_DIRRDCTRL1_SPIADRIOCTRL_BIT   0x3
#define SPIB_SPIB1_DIRRDCTRL1_SPIADRIOCTRL_BITWIDTH 2
// SpiDmyIOCtrl bitfiled (RW) Reset=0
#define SPIB_SPIB1_DIRRDCTRL1_SPIDMYIOCTRL_MASK  0x30
#define SPIB_SPIB1_DIRRDCTRL1_SPIDMYIOCTRL_SHIFT 4 
#define SPIB_SPIB1_DIRRDCTRL1_SPIDMYIOCTRL_BIT   0x3
#define SPIB_SPIB1_DIRRDCTRL1_SPIDMYIOCTRL_BITWIDTH 2
// SpiDatIOCtrl bitfiled (RW) Reset=0
#define SPIB_SPIB1_DIRRDCTRL1_SPIDATIOCTRL_MASK  0xC0
#define SPIB_SPIB1_DIRRDCTRL1_SPIDATIOCTRL_SHIFT 6 
#define SPIB_SPIB1_DIRRDCTRL1_SPIDATIOCTRL_BIT   0x3
#define SPIB_SPIB1_DIRRDCTRL1_SPIDATIOCTRL_BITWIDTH 2
// reserved2 bitfiled (RO) Reset=0
#define SPIB_SPIB1_DIRRDCTRL1_RESERVED2_MASK     0x700
#define SPIB_SPIB1_DIRRDCTRL1_RESERVED2_SHIFT    8 
#define SPIB_SPIB1_DIRRDCTRL1_RESERVED2_BIT      0x7
#define SPIB_SPIB1_DIRRDCTRL1_RESERVED2_BITWIDTH 3
// SpiAddrByteCnt bitfiled (RW) Reset=0
#define SPIB_SPIB1_DIRRDCTRL1_SPIADDRBYTECNT_MASK 0x800
#define SPIB_SPIB1_DIRRDCTRL1_SPIADDRBYTECNT_SHIFT 11 
#define SPIB_SPIB1_DIRRDCTRL1_SPIADDRBYTECNT_BIT 0x1
#define SPIB_SPIB1_DIRRDCTRL1_SPIADDRBYTECNT_BITWIDTH 1
// SpiDmyByteCnt bitfiled (RW) Reset=1
#define SPIB_SPIB1_DIRRDCTRL1_SPIDMYBYTECNT_MASK 0xF000
#define SPIB_SPIB1_DIRRDCTRL1_SPIDMYBYTECNT_SHIFT 12 
#define SPIB_SPIB1_DIRRDCTRL1_SPIDMYBYTECNT_BIT  0xF
#define SPIB_SPIB1_DIRRDCTRL1_SPIDMYBYTECNT_BITWIDTH 4
// reserved bitfiled (RO) Reset=0
#define SPIB_SPIB1_DIRRDCTRL1_RESERVED_MASK      0xFF0000
#define SPIB_SPIB1_DIRRDCTRL1_RESERVED_SHIFT     16 
#define SPIB_SPIB1_DIRRDCTRL1_RESERVED_BIT       0xFF
#define SPIB_SPIB1_DIRRDCTRL1_RESERVED_BITWIDTH  8
// SpiCmdOp bitfiled (RW) Reset=1011
#define SPIB_SPIB1_DIRRDCTRL1_SPICMDOP_MASK      0xFF000000
#define SPIB_SPIB1_DIRRDCTRL1_SPICMDOP_SHIFT     24 
#define SPIB_SPIB1_DIRRDCTRL1_SPICMDOP_BIT       0xFF
#define SPIB_SPIB1_DIRRDCTRL1_SPICMDOP_BITWIDTH  8
// SPIB1_PrgAccCtrl0 Register
#define SPIB_SPIB1_PRGACCCTRL0_OFS               0x00001400
// SMOD bitfiled (RO) Reset=0
#define SPIB_SPIB1_PRGACCCTRL0_SMOD_MASK         0x3
#define SPIB_SPIB1_PRGACCCTRL0_SMOD_SHIFT        0 
#define SPIB_SPIB1_PRGACCCTRL0_SMOD_BIT          0x3
#define SPIB_SPIB1_PRGACCCTRL0_SMOD_BITWIDTH     2
// SDCE bitfiled (RW) Reset=0
#define SPIB_SPIB1_PRGACCCTRL0_SDCE_MASK         0x3C
#define SPIB_SPIB1_PRGACCCTRL0_SDCE_SHIFT        2 
#define SPIB_SPIB1_PRGACCCTRL0_SDCE_BIT          0xF
#define SPIB_SPIB1_PRGACCCTRL0_SDCE_BITWIDTH     4
// reserved2 bitfiled (RO) Reset=0
#define SPIB_SPIB1_PRGACCCTRL0_RESERVED2_MASK    0xC0
#define SPIB_SPIB1_PRGACCCTRL0_RESERVED2_SHIFT   6 
#define SPIB_SPIB1_PRGACCCTRL0_RESERVED2_BIT     0x3
#define SPIB_SPIB1_PRGACCCTRL0_RESERVED2_BITWIDTH 2
// SCSD bitfiled (RW) Reset=11111
#define SPIB_SPIB1_PRGACCCTRL0_SCSD_MASK         0xFF00
#define SPIB_SPIB1_PRGACCCTRL0_SCSD_SHIFT        8 
#define SPIB_SPIB1_PRGACCCTRL0_SCSD_BIT          0xFF
#define SPIB_SPIB1_PRGACCCTRL0_SCSD_BITWIDTH     8
// SPR bitfiled (RW) Reset=11111
#define SPIB_SPIB1_PRGACCCTRL0_SPR_MASK          0x1F0000
#define SPIB_SPIB1_PRGACCCTRL0_SPR_SHIFT         16 
#define SPIB_SPIB1_PRGACCCTRL0_SPR_BIT           0x1F
#define SPIB_SPIB1_PRGACCCTRL0_SPR_BITWIDTH      5
// reserved bitfiled (RO) Reset=0
#define SPIB_SPIB1_PRGACCCTRL0_RESERVED_MASK     0xFFE00000
#define SPIB_SPIB1_PRGACCCTRL0_RESERVED_SHIFT    21 
#define SPIB_SPIB1_PRGACCCTRL0_RESERVED_BIT      0x7FF
#define SPIB_SPIB1_PRGACCCTRL0_RESERVED_BITWIDTH 11
// SPIB1_PrgAccCtrl1 Register
#define SPIB_SPIB1_PRGACCCTRL1_OFS               0x00001404
// SpiCycGo bitfiled (RW) Reset=0
#define SPIB_SPIB1_PRGACCCTRL1_SPICYCGO_MASK     0x1
#define SPIB_SPIB1_PRGACCCTRL1_SPICYCGO_SHIFT    0 
#define SPIB_SPIB1_PRGACCCTRL1_SPICYCGO_BIT      0x1
#define SPIB_SPIB1_PRGACCCTRL1_SPICYCGO_BITWIDTH 1
// SpiCsNum bitfiled (RW) Reset=0
#define SPIB_SPIB1_PRGACCCTRL1_SPICSNUM_MASK     0x2
#define SPIB_SPIB1_PRGACCCTRL1_SPICSNUM_SHIFT    1 
#define SPIB_SPIB1_PRGACCCTRL1_SPICSNUM_BIT      0x1
#define SPIB_SPIB1_PRGACCCTRL1_SPICSNUM_BITWIDTH 1
// reserved3 bitfiled (RO) Reset=0
#define SPIB_SPIB1_PRGACCCTRL1_RESERVED3_MASK    0xC
#define SPIB_SPIB1_PRGACCCTRL1_RESERVED3_SHIFT   2 
#define SPIB_SPIB1_PRGACCCTRL1_RESERVED3_BIT     0x3
#define SPIB_SPIB1_PRGACCCTRL1_RESERVED3_BITWIDTH 2
// PriBufEn bitfiled (RW) Reset=0
#define SPIB_SPIB1_PRGACCCTRL1_PRIBUFEN_MASK     0x10
#define SPIB_SPIB1_PRGACCCTRL1_PRIBUFEN_SHIFT    4 
#define SPIB_SPIB1_PRGACCCTRL1_PRIBUFEN_BIT      0x1
#define SPIB_SPIB1_PRGACCCTRL1_PRIBUFEN_BITWIDTH 1
// SecBufEn bitfiled (RW) Reset=0
#define SPIB_SPIB1_PRGACCCTRL1_SECBUFEN_MASK     0x20
#define SPIB_SPIB1_PRGACCCTRL1_SECBUFEN_SHIFT    5 
#define SPIB_SPIB1_PRGACCCTRL1_SECBUFEN_BIT      0x1
#define SPIB_SPIB1_PRGACCCTRL1_SECBUFEN_BITWIDTH 1
// reserved2 bitfiled (RO) Reset=0
#define SPIB_SPIB1_PRGACCCTRL1_RESERVED2_MASK    0xFFC0
#define SPIB_SPIB1_PRGACCCTRL1_RESERVED2_SHIFT   6 
#define SPIB_SPIB1_PRGACCCTRL1_RESERVED2_BIT     0x3FF
#define SPIB_SPIB1_PRGACCCTRL1_RESERVED2_BITWIDTH 10
// PriBufDatByteCnt bitfiled (RW) Reset=0
#define SPIB_SPIB1_PRGACCCTRL1_PRIBUFDATBYTECNT_MASK 0x70000
#define SPIB_SPIB1_PRGACCCTRL1_PRIBUFDATBYTECNT_SHIFT 16 
#define SPIB_SPIB1_PRGACCCTRL1_PRIBUFDATBYTECNT_BIT 0x7
#define SPIB_SPIB1_PRGACCCTRL1_PRIBUFDATBYTECNT_BITWIDTH 3
// reserved bitfiled (RO) Reset=0
#define SPIB_SPIB1_PRGACCCTRL1_RESERVED_MASK     0xF80000
#define SPIB_SPIB1_PRGACCCTRL1_RESERVED_SHIFT    19 
#define SPIB_SPIB1_PRGACCCTRL1_RESERVED_BIT      0x1F
#define SPIB_SPIB1_PRGACCCTRL1_RESERVED_BITWIDTH 5
// SecBufDatByteCnt bitfiled (RW) Reset=0
#define SPIB_SPIB1_PRGACCCTRL1_SECBUFDATBYTECNT_MASK 0xFF000000
#define SPIB_SPIB1_PRGACCCTRL1_SECBUFDATBYTECNT_SHIFT 24 
#define SPIB_SPIB1_PRGACCCTRL1_SECBUFDATBYTECNT_BIT 0xFF
#define SPIB_SPIB1_PRGACCCTRL1_SECBUFDATBYTECNT_BITWIDTH 8
// SPIB1_PrgAccIntEn Register
#define SPIB_SPIB1_PRGACCINTEN_OFS               0x00001408
// SpiIntEn bitfiled (RW) Reset=0
#define SPIB_SPIB1_PRGACCINTEN_SPIINTEN_MASK     0x1
#define SPIB_SPIB1_PRGACCINTEN_SPIINTEN_SHIFT    0 
#define SPIB_SPIB1_PRGACCINTEN_SPIINTEN_BIT      0x1
#define SPIB_SPIB1_PRGACCINTEN_SPIINTEN_BITWIDTH 1
// reserved bitfiled (RO) Reset=0
#define SPIB_SPIB1_PRGACCINTEN_RESERVED_MASK     0xFFFFFFFE
#define SPIB_SPIB1_PRGACCINTEN_RESERVED_SHIFT    1 
#define SPIB_SPIB1_PRGACCINTEN_RESERVED_BIT      0x7FFFFFFF
#define SPIB_SPIB1_PRGACCINTEN_RESERVED_BITWIDTH 31
// SPIB1_PrgAccStat Register
#define SPIB_SPIB1_PRGACCSTAT_OFS                0x0000140C
// SpiCycDone bitfiled (RW) Reset=0
#define SPIB_SPIB1_PRGACCSTAT_SPICYCDONE_MASK    0x1
#define SPIB_SPIB1_PRGACCSTAT_SPICYCDONE_SHIFT   0 
#define SPIB_SPIB1_PRGACCSTAT_SPICYCDONE_BIT     0x1
#define SPIB_SPIB1_PRGACCSTAT_SPICYCDONE_BITWIDTH 1
// SpiCycInPrgrs bitfiled (RO) Reset=0
#define SPIB_SPIB1_PRGACCSTAT_SPICYCINPRGRS_MASK 0x2
#define SPIB_SPIB1_PRGACCSTAT_SPICYCINPRGRS_SHIFT 1 
#define SPIB_SPIB1_PRGACCSTAT_SPICYCINPRGRS_BIT  0x1
#define SPIB_SPIB1_PRGACCSTAT_SPICYCINPRGRS_BITWIDTH 1
// reserved bitfiled (RO) Reset=0
#define SPIB_SPIB1_PRGACCSTAT_RESERVED_MASK      0xFFFFFFFC
#define SPIB_SPIB1_PRGACCSTAT_RESERVED_SHIFT     2 
#define SPIB_SPIB1_PRGACCSTAT_RESERVED_BIT       0x3FFFFFFF
#define SPIB_SPIB1_PRGACCSTAT_RESERVED_BITWIDTH  30

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* _SPIB_REG_DEF_H */
