/*
 * arch/arm/mach-tz3000/include/mach/regs/vconv_reg_def.h
 *
 * (C) Copyright TOSHIBA Corporation
 * Semiconductor & Storage Products Company 2013
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#ifndef _VCONV_REG_DEF_H
#define _VCONV_REG_DEF_H

#ifdef __cplusplus
extern  {
#endif /* __cplusplus */

// VCONV_START Register
#define VCONV_VCONV_START_OFS                    0x00000000
// START bitfiled (RW) Reset=0
#define VCONV_VCONV_START_START_MASK             0x1
#define VCONV_VCONV_START_START_SHIFT            0 
#define VCONV_VCONV_START_START_BIT              0x1
#define VCONV_VCONV_START_START_BITWIDTH         1
// CHANNEL bitfiled (RW) Reset=0
#define VCONV_VCONV_START_CHANNEL_MASK           0x2
#define VCONV_VCONV_START_CHANNEL_SHIFT          1 
#define VCONV_VCONV_START_CHANNEL_BIT            0x1
#define VCONV_VCONV_START_CHANNEL_BITWIDTH       1
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_START_RESERVED_MASK          0xFFFFFFFC
#define VCONV_VCONV_START_RESERVED_SHIFT         2 
#define VCONV_VCONV_START_RESERVED_BIT           0x3FFFFFFF
#define VCONV_VCONV_START_RESERVED_BITWIDTH      30
// VCONV_ABORT Register
#define VCONV_VCONV_ABORT_OFS                    0x00000004
// ABORT bitfiled (RW) Reset=0
#define VCONV_VCONV_ABORT_ABORT_MASK             0x1
#define VCONV_VCONV_ABORT_ABORT_SHIFT            0 
#define VCONV_VCONV_ABORT_ABORT_BIT              0x1
#define VCONV_VCONV_ABORT_ABORT_BITWIDTH         1
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_ABORT_RESERVED_MASK          0xFFFFFFFE
#define VCONV_VCONV_ABORT_RESERVED_SHIFT         1 
#define VCONV_VCONV_ABORT_RESERVED_BIT           0x7FFFFFFF
#define VCONV_VCONV_ABORT_RESERVED_BITWIDTH      31
// VCONV_SET_DUMMY_READ Register
#define VCONV_VCONV_SET_DUMMY_READ_OFS           0x00000010
// DUMMY_READ bitfiled (RW) Reset=1
#define VCONV_VCONV_SET_DUMMY_READ_DUMMY_READ_MASK 0xF
#define VCONV_VCONV_SET_DUMMY_READ_DUMMY_READ_SHIFT 0 
#define VCONV_VCONV_SET_DUMMY_READ_DUMMY_READ_BIT 0xF
#define VCONV_VCONV_SET_DUMMY_READ_DUMMY_READ_BITWIDTH 4
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_DUMMY_READ_RESERVED_MASK 0xFFFFFFF0
#define VCONV_VCONV_SET_DUMMY_READ_RESERVED_SHIFT 4 
#define VCONV_VCONV_SET_DUMMY_READ_RESERVED_BIT  0xFFFFFFF
#define VCONV_VCONV_SET_DUMMY_READ_RESERVED_BITWIDTH 28
// VCONV_SET_BUSIF Register
#define VCONV_VCONV_SET_BUSIF_OFS                0x00000014
// OUTSTAND_CMD bitfiled (RW) Reset=1000
#define VCONV_VCONV_SET_BUSIF_OUTSTAND_CMD_MASK  0xF
#define VCONV_VCONV_SET_BUSIF_OUTSTAND_CMD_SHIFT 0 
#define VCONV_VCONV_SET_BUSIF_OUTSTAND_CMD_BIT   0xF
#define VCONV_VCONV_SET_BUSIF_OUTSTAND_CMD_BITWIDTH 4
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_BUSIF_RESERVED_MASK      0xFFFFFFF0
#define VCONV_VCONV_SET_BUSIF_RESERVED_SHIFT     4 
#define VCONV_VCONV_SET_BUSIF_RESERVED_BIT       0xFFFFFFF
#define VCONV_VCONV_SET_BUSIF_RESERVED_BITWIDTH  28
// VCONV_SET_SEL_ALPHA Register
#define VCONV_VCONV_SET_SEL_ALPHA_OFS            0x00000018
// SEL_ALPHA bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_SEL_ALPHA_SEL_ALPHA_MASK 0x1
#define VCONV_VCONV_SET_SEL_ALPHA_SEL_ALPHA_SHIFT 0 
#define VCONV_VCONV_SET_SEL_ALPHA_SEL_ALPHA_BIT  0x1
#define VCONV_VCONV_SET_SEL_ALPHA_SEL_ALPHA_BITWIDTH 1
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_SEL_ALPHA_RESERVED_MASK  0xFFFFFFFE
#define VCONV_VCONV_SET_SEL_ALPHA_RESERVED_SHIFT 1 
#define VCONV_VCONV_SET_SEL_ALPHA_RESERVED_BIT   0x7FFFFFFF
#define VCONV_VCONV_SET_SEL_ALPHA_RESERVED_BITWIDTH 31
// VCONV_IRQ Register
#define VCONV_VCONV_IRQ_OFS                      0x00000020
// FRAME_END_IRQ bitfiled (RW) Reset=0
#define VCONV_VCONV_IRQ_FRAME_END_IRQ_MASK       0x1
#define VCONV_VCONV_IRQ_FRAME_END_IRQ_SHIFT      0 
#define VCONV_VCONV_IRQ_FRAME_END_IRQ_BIT        0x1
#define VCONV_VCONV_IRQ_FRAME_END_IRQ_BITWIDTH   1
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_IRQ_RESERVED_MASK            0xE
#define VCONV_VCONV_IRQ_RESERVED_SHIFT           1 
#define VCONV_VCONV_IRQ_RESERVED_BIT             0x7
#define VCONV_VCONV_IRQ_RESERVED_BITWIDTH        3
// START_ERROR_IRQ bitfiled (RW) Reset=0
#define VCONV_VCONV_IRQ_START_ERROR_IRQ_MASK     0x10
#define VCONV_VCONV_IRQ_START_ERROR_IRQ_SHIFT    4 
#define VCONV_VCONV_IRQ_START_ERROR_IRQ_BIT      0x1
#define VCONV_VCONV_IRQ_START_ERROR_IRQ_BITWIDTH 1
// REG_ERROR_IRQ bitfiled (RW) Reset=0
#define VCONV_VCONV_IRQ_REG_ERROR_IRQ_MASK       0x20
#define VCONV_VCONV_IRQ_REG_ERROR_IRQ_SHIFT      5 
#define VCONV_VCONV_IRQ_REG_ERROR_IRQ_BIT        0x1
#define VCONV_VCONV_IRQ_REG_ERROR_IRQ_BITWIDTH   1
// DISP_ERROR_IRQ bitfiled (RW) Reset=0
#define VCONV_VCONV_IRQ_DISP_ERROR_IRQ_MASK      0x40
#define VCONV_VCONV_IRQ_DISP_ERROR_IRQ_SHIFT     6 
#define VCONV_VCONV_IRQ_DISP_ERROR_IRQ_BIT       0x1
#define VCONV_VCONV_IRQ_DISP_ERROR_IRQ_BITWIDTH  1
// MERGE_ERROR_IRQ bitfiled (RW) Reset=0
#define VCONV_VCONV_IRQ_MERGE_ERROR_IRQ_MASK     0x80
#define VCONV_VCONV_IRQ_MERGE_ERROR_IRQ_SHIFT    7 
#define VCONV_VCONV_IRQ_MERGE_ERROR_IRQ_BIT      0x1
#define VCONV_VCONV_IRQ_MERGE_ERROR_IRQ_BITWIDTH 1
// Reserved2 bitfiled (RO) Reset=0
#define VCONV_VCONV_IRQ_RESERVED2_MASK           0xFFFFFF00
#define VCONV_VCONV_IRQ_RESERVED2_SHIFT          8 
#define VCONV_VCONV_IRQ_RESERVED2_BIT            0xFFFFFF
#define VCONV_VCONV_IRQ_RESERVED2_BITWIDTH       24
// VCONV_SET_IRQ_MASK Register
#define VCONV_VCONV_SET_IRQ_MASK_OFS             0x00000024
// FRAME_END_MASK bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_IRQ_MASK_FRAME_END_MASK_MASK 0x1
#define VCONV_VCONV_SET_IRQ_MASK_FRAME_END_MASK_SHIFT 0 
#define VCONV_VCONV_SET_IRQ_MASK_FRAME_END_MASK_BIT 0x1
#define VCONV_VCONV_SET_IRQ_MASK_FRAME_END_MASK_BITWIDTH 1
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_IRQ_MASK_RESERVED_MASK   0xE
#define VCONV_VCONV_SET_IRQ_MASK_RESERVED_SHIFT  1 
#define VCONV_VCONV_SET_IRQ_MASK_RESERVED_BIT    0x7
#define VCONV_VCONV_SET_IRQ_MASK_RESERVED_BITWIDTH 3
// START_ERROR_MASK bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_IRQ_MASK_START_ERROR_MASK_MASK 0x10
#define VCONV_VCONV_SET_IRQ_MASK_START_ERROR_MASK_SHIFT 4 
#define VCONV_VCONV_SET_IRQ_MASK_START_ERROR_MASK_BIT 0x1
#define VCONV_VCONV_SET_IRQ_MASK_START_ERROR_MASK_BITWIDTH 1
// REG_ERROR_MASK bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_IRQ_MASK_REG_ERROR_MASK_MASK 0x20
#define VCONV_VCONV_SET_IRQ_MASK_REG_ERROR_MASK_SHIFT 5 
#define VCONV_VCONV_SET_IRQ_MASK_REG_ERROR_MASK_BIT 0x1
#define VCONV_VCONV_SET_IRQ_MASK_REG_ERROR_MASK_BITWIDTH 1
// DISP_ERROR_MASK bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_IRQ_MASK_DISP_ERROR_MASK_MASK 0x40
#define VCONV_VCONV_SET_IRQ_MASK_DISP_ERROR_MASK_SHIFT 6 
#define VCONV_VCONV_SET_IRQ_MASK_DISP_ERROR_MASK_BIT 0x1
#define VCONV_VCONV_SET_IRQ_MASK_DISP_ERROR_MASK_BITWIDTH 1
// MERGE_ERROR_MASK bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_IRQ_MASK_MERGE_ERROR_MASK_MASK 0x80
#define VCONV_VCONV_SET_IRQ_MASK_MERGE_ERROR_MASK_SHIFT 7 
#define VCONV_VCONV_SET_IRQ_MASK_MERGE_ERROR_MASK_BIT 0x1
#define VCONV_VCONV_SET_IRQ_MASK_MERGE_ERROR_MASK_BITWIDTH 1
// Reserved2 bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_IRQ_MASK_RESERVED2_MASK  0xFFFFFF00
#define VCONV_VCONV_SET_IRQ_MASK_RESERVED2_SHIFT 8 
#define VCONV_VCONV_SET_IRQ_MASK_RESERVED2_BIT   0xFFFFFF
#define VCONV_VCONV_SET_IRQ_MASK_RESERVED2_BITWIDTH 24
// VCONV_SET_Y2RMTX_OFFSET Register
#define VCONV_VCONV_SET_Y2RMTX_OFFSET_OFS        0x00000040
// Y2R_YOFFSET bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_Y2RMTX_OFFSET_Y2R_YOFFSET_MASK 0xFF
#define VCONV_VCONV_SET_Y2RMTX_OFFSET_Y2R_YOFFSET_SHIFT 0 
#define VCONV_VCONV_SET_Y2RMTX_OFFSET_Y2R_YOFFSET_BIT 0xFF
#define VCONV_VCONV_SET_Y2RMTX_OFFSET_Y2R_YOFFSET_BITWIDTH 8
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_Y2RMTX_OFFSET_RESERVED_MASK 0xFF00
#define VCONV_VCONV_SET_Y2RMTX_OFFSET_RESERVED_SHIFT 8 
#define VCONV_VCONV_SET_Y2RMTX_OFFSET_RESERVED_BIT 0xFF
#define VCONV_VCONV_SET_Y2RMTX_OFFSET_RESERVED_BITWIDTH 8
// Y2R_COFFSET bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_Y2RMTX_OFFSET_Y2R_COFFSET_MASK 0xFF0000
#define VCONV_VCONV_SET_Y2RMTX_OFFSET_Y2R_COFFSET_SHIFT 16 
#define VCONV_VCONV_SET_Y2RMTX_OFFSET_Y2R_COFFSET_BIT 0xFF
#define VCONV_VCONV_SET_Y2RMTX_OFFSET_Y2R_COFFSET_BITWIDTH 8
// Reserved2 bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_Y2RMTX_OFFSET_RESERVED2_MASK 0xFF000000
#define VCONV_VCONV_SET_Y2RMTX_OFFSET_RESERVED2_SHIFT 24 
#define VCONV_VCONV_SET_Y2RMTX_OFFSET_RESERVED2_BIT 0xFF
#define VCONV_VCONV_SET_Y2RMTX_OFFSET_RESERVED2_BITWIDTH 8
// VCONV_SET_Y2RMTX_COEF00 Register
#define VCONV_VCONV_SET_Y2RMTX_COEF00_OFS        0x00000044
// Y2R_COEF00 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_Y2RMTX_COEF00_Y2R_COEF00_MASK 0x3FF
#define VCONV_VCONV_SET_Y2RMTX_COEF00_Y2R_COEF00_SHIFT 0 
#define VCONV_VCONV_SET_Y2RMTX_COEF00_Y2R_COEF00_BIT 0x3FF
#define VCONV_VCONV_SET_Y2RMTX_COEF00_Y2R_COEF00_BITWIDTH 10
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_Y2RMTX_COEF00_RESERVED_MASK 0xFFFFFC00
#define VCONV_VCONV_SET_Y2RMTX_COEF00_RESERVED_SHIFT 10 
#define VCONV_VCONV_SET_Y2RMTX_COEF00_RESERVED_BIT 0x3FFFFF
#define VCONV_VCONV_SET_Y2RMTX_COEF00_RESERVED_BITWIDTH 22
// VCONV_SET_Y2RMTX_COEF01 Register
#define VCONV_VCONV_SET_Y2RMTX_COEF01_OFS        0x00000048
// Y2R_COEF01 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_Y2RMTX_COEF01_Y2R_COEF01_MASK 0x3FF
#define VCONV_VCONV_SET_Y2RMTX_COEF01_Y2R_COEF01_SHIFT 0 
#define VCONV_VCONV_SET_Y2RMTX_COEF01_Y2R_COEF01_BIT 0x3FF
#define VCONV_VCONV_SET_Y2RMTX_COEF01_Y2R_COEF01_BITWIDTH 10
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_Y2RMTX_COEF01_RESERVED_MASK 0xFFFFFC00
#define VCONV_VCONV_SET_Y2RMTX_COEF01_RESERVED_SHIFT 10 
#define VCONV_VCONV_SET_Y2RMTX_COEF01_RESERVED_BIT 0x3FFFFF
#define VCONV_VCONV_SET_Y2RMTX_COEF01_RESERVED_BITWIDTH 22
// VCONV_SET_Y2RMTX_COEF02 Register
#define VCONV_VCONV_SET_Y2RMTX_COEF02_OFS        0x0000004C
// Y2R_COEF02 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_Y2RMTX_COEF02_Y2R_COEF02_MASK 0x3FF
#define VCONV_VCONV_SET_Y2RMTX_COEF02_Y2R_COEF02_SHIFT 0 
#define VCONV_VCONV_SET_Y2RMTX_COEF02_Y2R_COEF02_BIT 0x3FF
#define VCONV_VCONV_SET_Y2RMTX_COEF02_Y2R_COEF02_BITWIDTH 10
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_Y2RMTX_COEF02_RESERVED_MASK 0xFFFFFC00
#define VCONV_VCONV_SET_Y2RMTX_COEF02_RESERVED_SHIFT 10 
#define VCONV_VCONV_SET_Y2RMTX_COEF02_RESERVED_BIT 0x3FFFFF
#define VCONV_VCONV_SET_Y2RMTX_COEF02_RESERVED_BITWIDTH 22
// VCONV_SET_Y2RMTX_COEF10 Register
#define VCONV_VCONV_SET_Y2RMTX_COEF10_OFS        0x00000050
// Y2R_COEF10 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_Y2RMTX_COEF10_Y2R_COEF10_MASK 0x3FF
#define VCONV_VCONV_SET_Y2RMTX_COEF10_Y2R_COEF10_SHIFT 0 
#define VCONV_VCONV_SET_Y2RMTX_COEF10_Y2R_COEF10_BIT 0x3FF
#define VCONV_VCONV_SET_Y2RMTX_COEF10_Y2R_COEF10_BITWIDTH 10
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_Y2RMTX_COEF10_RESERVED_MASK 0xFFFFFC00
#define VCONV_VCONV_SET_Y2RMTX_COEF10_RESERVED_SHIFT 10 
#define VCONV_VCONV_SET_Y2RMTX_COEF10_RESERVED_BIT 0x3FFFFF
#define VCONV_VCONV_SET_Y2RMTX_COEF10_RESERVED_BITWIDTH 22
// VCONV_SET_Y2RMTX_COEF11 Register
#define VCONV_VCONV_SET_Y2RMTX_COEF11_OFS        0x00000054
// Y2R_COEF11 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_Y2RMTX_COEF11_Y2R_COEF11_MASK 0x3FF
#define VCONV_VCONV_SET_Y2RMTX_COEF11_Y2R_COEF11_SHIFT 0 
#define VCONV_VCONV_SET_Y2RMTX_COEF11_Y2R_COEF11_BIT 0x3FF
#define VCONV_VCONV_SET_Y2RMTX_COEF11_Y2R_COEF11_BITWIDTH 10
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_Y2RMTX_COEF11_RESERVED_MASK 0xFFFFFC00
#define VCONV_VCONV_SET_Y2RMTX_COEF11_RESERVED_SHIFT 10 
#define VCONV_VCONV_SET_Y2RMTX_COEF11_RESERVED_BIT 0x3FFFFF
#define VCONV_VCONV_SET_Y2RMTX_COEF11_RESERVED_BITWIDTH 22
// VCONV_SET_Y2RMTX_COEF12 Register
#define VCONV_VCONV_SET_Y2RMTX_COEF12_OFS        0x00000058
// Y2R_COEF12 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_Y2RMTX_COEF12_Y2R_COEF12_MASK 0x3FF
#define VCONV_VCONV_SET_Y2RMTX_COEF12_Y2R_COEF12_SHIFT 0 
#define VCONV_VCONV_SET_Y2RMTX_COEF12_Y2R_COEF12_BIT 0x3FF
#define VCONV_VCONV_SET_Y2RMTX_COEF12_Y2R_COEF12_BITWIDTH 10
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_Y2RMTX_COEF12_RESERVED_MASK 0xFFFFFC00
#define VCONV_VCONV_SET_Y2RMTX_COEF12_RESERVED_SHIFT 10 
#define VCONV_VCONV_SET_Y2RMTX_COEF12_RESERVED_BIT 0x3FFFFF
#define VCONV_VCONV_SET_Y2RMTX_COEF12_RESERVED_BITWIDTH 22
// VCONV_SET_Y2RMTX_COEF20 Register
#define VCONV_VCONV_SET_Y2RMTX_COEF20_OFS        0x0000005C
// Y2R_COEF20 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_Y2RMTX_COEF20_Y2R_COEF20_MASK 0x3FF
#define VCONV_VCONV_SET_Y2RMTX_COEF20_Y2R_COEF20_SHIFT 0 
#define VCONV_VCONV_SET_Y2RMTX_COEF20_Y2R_COEF20_BIT 0x3FF
#define VCONV_VCONV_SET_Y2RMTX_COEF20_Y2R_COEF20_BITWIDTH 10
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_Y2RMTX_COEF20_RESERVED_MASK 0xFFFFFC00
#define VCONV_VCONV_SET_Y2RMTX_COEF20_RESERVED_SHIFT 10 
#define VCONV_VCONV_SET_Y2RMTX_COEF20_RESERVED_BIT 0x3FFFFF
#define VCONV_VCONV_SET_Y2RMTX_COEF20_RESERVED_BITWIDTH 22
// VCONV_SET_Y2RMTX_COEF21 Register
#define VCONV_VCONV_SET_Y2RMTX_COEF21_OFS        0x00000060
// Y2R_COEF21 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_Y2RMTX_COEF21_Y2R_COEF21_MASK 0x3FF
#define VCONV_VCONV_SET_Y2RMTX_COEF21_Y2R_COEF21_SHIFT 0 
#define VCONV_VCONV_SET_Y2RMTX_COEF21_Y2R_COEF21_BIT 0x3FF
#define VCONV_VCONV_SET_Y2RMTX_COEF21_Y2R_COEF21_BITWIDTH 10
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_Y2RMTX_COEF21_RESERVED_MASK 0xFFFFFC00
#define VCONV_VCONV_SET_Y2RMTX_COEF21_RESERVED_SHIFT 10 
#define VCONV_VCONV_SET_Y2RMTX_COEF21_RESERVED_BIT 0x3FFFFF
#define VCONV_VCONV_SET_Y2RMTX_COEF21_RESERVED_BITWIDTH 22
// VCONV_SET_Y2RMTX_COEF22 Register
#define VCONV_VCONV_SET_Y2RMTX_COEF22_OFS        0x00000064
// Y2R_COEF22 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_Y2RMTX_COEF22_Y2R_COEF22_MASK 0x3FF
#define VCONV_VCONV_SET_Y2RMTX_COEF22_Y2R_COEF22_SHIFT 0 
#define VCONV_VCONV_SET_Y2RMTX_COEF22_Y2R_COEF22_BIT 0x3FF
#define VCONV_VCONV_SET_Y2RMTX_COEF22_Y2R_COEF22_BITWIDTH 10
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_Y2RMTX_COEF22_RESERVED_MASK 0xFFFFFC00
#define VCONV_VCONV_SET_Y2RMTX_COEF22_RESERVED_SHIFT 10 
#define VCONV_VCONV_SET_Y2RMTX_COEF22_RESERVED_BIT 0x3FFFFF
#define VCONV_VCONV_SET_Y2RMTX_COEF22_RESERVED_BITWIDTH 22
// VCONV_SET_RGBLIMIT Register
#define VCONV_VCONV_SET_RGBLIMIT_OFS             0x00000068
// Y2R_RGBMAX_LIMIT bitfiled (RW) Reset=11111111
#define VCONV_VCONV_SET_RGBLIMIT_Y2R_RGBMAX_LIMIT_MASK 0xFF
#define VCONV_VCONV_SET_RGBLIMIT_Y2R_RGBMAX_LIMIT_SHIFT 0 
#define VCONV_VCONV_SET_RGBLIMIT_Y2R_RGBMAX_LIMIT_BIT 0xFF
#define VCONV_VCONV_SET_RGBLIMIT_Y2R_RGBMAX_LIMIT_BITWIDTH 8
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_RGBLIMIT_RESERVED_MASK   0xFF00
#define VCONV_VCONV_SET_RGBLIMIT_RESERVED_SHIFT  8 
#define VCONV_VCONV_SET_RGBLIMIT_RESERVED_BIT    0xFF
#define VCONV_VCONV_SET_RGBLIMIT_RESERVED_BITWIDTH 8
// Y2R_RGBMIN_LIMIT bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_RGBLIMIT_Y2R_RGBMIN_LIMIT_MASK 0xFF0000
#define VCONV_VCONV_SET_RGBLIMIT_Y2R_RGBMIN_LIMIT_SHIFT 16 
#define VCONV_VCONV_SET_RGBLIMIT_Y2R_RGBMIN_LIMIT_BIT 0xFF
#define VCONV_VCONV_SET_RGBLIMIT_Y2R_RGBMIN_LIMIT_BITWIDTH 8
// Reserved2 bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_RGBLIMIT_RESERVED2_MASK  0xFF000000
#define VCONV_VCONV_SET_RGBLIMIT_RESERVED2_SHIFT 24 
#define VCONV_VCONV_SET_RGBLIMIT_RESERVED2_BIT   0xFF
#define VCONV_VCONV_SET_RGBLIMIT_RESERVED2_BITWIDTH 8
// VCONV_SET_R2YMTX_OFFSET Register
#define VCONV_VCONV_SET_R2YMTX_OFFSET_OFS        0x00000080
// R2Y_YOFFSET bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_R2YMTX_OFFSET_R2Y_YOFFSET_MASK 0xFF
#define VCONV_VCONV_SET_R2YMTX_OFFSET_R2Y_YOFFSET_SHIFT 0 
#define VCONV_VCONV_SET_R2YMTX_OFFSET_R2Y_YOFFSET_BIT 0xFF
#define VCONV_VCONV_SET_R2YMTX_OFFSET_R2Y_YOFFSET_BITWIDTH 8
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_R2YMTX_OFFSET_RESERVED_MASK 0xFF00
#define VCONV_VCONV_SET_R2YMTX_OFFSET_RESERVED_SHIFT 8 
#define VCONV_VCONV_SET_R2YMTX_OFFSET_RESERVED_BIT 0xFF
#define VCONV_VCONV_SET_R2YMTX_OFFSET_RESERVED_BITWIDTH 8
// R2Y_COFFSET bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_R2YMTX_OFFSET_R2Y_COFFSET_MASK 0xFF0000
#define VCONV_VCONV_SET_R2YMTX_OFFSET_R2Y_COFFSET_SHIFT 16 
#define VCONV_VCONV_SET_R2YMTX_OFFSET_R2Y_COFFSET_BIT 0xFF
#define VCONV_VCONV_SET_R2YMTX_OFFSET_R2Y_COFFSET_BITWIDTH 8
// Reserved2 bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_R2YMTX_OFFSET_RESERVED2_MASK 0xFF000000
#define VCONV_VCONV_SET_R2YMTX_OFFSET_RESERVED2_SHIFT 24 
#define VCONV_VCONV_SET_R2YMTX_OFFSET_RESERVED2_BIT 0xFF
#define VCONV_VCONV_SET_R2YMTX_OFFSET_RESERVED2_BITWIDTH 8
// VCONV_SET_R2YMTX_COEF00 Register
#define VCONV_VCONV_SET_R2YMTX_COEF00_OFS        0x00000084
// R2Y_COEF00 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_R2YMTX_COEF00_R2Y_COEF00_MASK 0x3FF
#define VCONV_VCONV_SET_R2YMTX_COEF00_R2Y_COEF00_SHIFT 0 
#define VCONV_VCONV_SET_R2YMTX_COEF00_R2Y_COEF00_BIT 0x3FF
#define VCONV_VCONV_SET_R2YMTX_COEF00_R2Y_COEF00_BITWIDTH 10
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_R2YMTX_COEF00_RESERVED_MASK 0xFFFFFC00
#define VCONV_VCONV_SET_R2YMTX_COEF00_RESERVED_SHIFT 10 
#define VCONV_VCONV_SET_R2YMTX_COEF00_RESERVED_BIT 0x3FFFFF
#define VCONV_VCONV_SET_R2YMTX_COEF00_RESERVED_BITWIDTH 22
// VCONV_SET_R2YMTX_COEF01 Register
#define VCONV_VCONV_SET_R2YMTX_COEF01_OFS        0x00000088
// R2Y_COEF01 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_R2YMTX_COEF01_R2Y_COEF01_MASK 0x3FF
#define VCONV_VCONV_SET_R2YMTX_COEF01_R2Y_COEF01_SHIFT 0 
#define VCONV_VCONV_SET_R2YMTX_COEF01_R2Y_COEF01_BIT 0x3FF
#define VCONV_VCONV_SET_R2YMTX_COEF01_R2Y_COEF01_BITWIDTH 10
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_R2YMTX_COEF01_RESERVED_MASK 0xFFFFFC00
#define VCONV_VCONV_SET_R2YMTX_COEF01_RESERVED_SHIFT 10 
#define VCONV_VCONV_SET_R2YMTX_COEF01_RESERVED_BIT 0x3FFFFF
#define VCONV_VCONV_SET_R2YMTX_COEF01_RESERVED_BITWIDTH 22
// VCONV_SET_R2YMTX_COEF02 Register
#define VCONV_VCONV_SET_R2YMTX_COEF02_OFS        0x0000008C
// R2Y_COEF02 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_R2YMTX_COEF02_R2Y_COEF02_MASK 0x3FF
#define VCONV_VCONV_SET_R2YMTX_COEF02_R2Y_COEF02_SHIFT 0 
#define VCONV_VCONV_SET_R2YMTX_COEF02_R2Y_COEF02_BIT 0x3FF
#define VCONV_VCONV_SET_R2YMTX_COEF02_R2Y_COEF02_BITWIDTH 10
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_R2YMTX_COEF02_RESERVED_MASK 0xFFFFFC00
#define VCONV_VCONV_SET_R2YMTX_COEF02_RESERVED_SHIFT 10 
#define VCONV_VCONV_SET_R2YMTX_COEF02_RESERVED_BIT 0x3FFFFF
#define VCONV_VCONV_SET_R2YMTX_COEF02_RESERVED_BITWIDTH 22
// VCONV_SET_R2YMTX_COEF10 Register
#define VCONV_VCONV_SET_R2YMTX_COEF10_OFS        0x00000090
// R2Y_COEF10 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_R2YMTX_COEF10_R2Y_COEF10_MASK 0x3FF
#define VCONV_VCONV_SET_R2YMTX_COEF10_R2Y_COEF10_SHIFT 0 
#define VCONV_VCONV_SET_R2YMTX_COEF10_R2Y_COEF10_BIT 0x3FF
#define VCONV_VCONV_SET_R2YMTX_COEF10_R2Y_COEF10_BITWIDTH 10
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_R2YMTX_COEF10_RESERVED_MASK 0xFFFFFC00
#define VCONV_VCONV_SET_R2YMTX_COEF10_RESERVED_SHIFT 10 
#define VCONV_VCONV_SET_R2YMTX_COEF10_RESERVED_BIT 0x3FFFFF
#define VCONV_VCONV_SET_R2YMTX_COEF10_RESERVED_BITWIDTH 22
// VCONV_SET_R2YMTX_COEF11 Register
#define VCONV_VCONV_SET_R2YMTX_COEF11_OFS        0x00000094
// R2Y_COEF11 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_R2YMTX_COEF11_R2Y_COEF11_MASK 0x3FF
#define VCONV_VCONV_SET_R2YMTX_COEF11_R2Y_COEF11_SHIFT 0 
#define VCONV_VCONV_SET_R2YMTX_COEF11_R2Y_COEF11_BIT 0x3FF
#define VCONV_VCONV_SET_R2YMTX_COEF11_R2Y_COEF11_BITWIDTH 10
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_R2YMTX_COEF11_RESERVED_MASK 0xFFFFFC00
#define VCONV_VCONV_SET_R2YMTX_COEF11_RESERVED_SHIFT 10 
#define VCONV_VCONV_SET_R2YMTX_COEF11_RESERVED_BIT 0x3FFFFF
#define VCONV_VCONV_SET_R2YMTX_COEF11_RESERVED_BITWIDTH 22
// VCONV_SET_R2YMTX_COEF12 Register
#define VCONV_VCONV_SET_R2YMTX_COEF12_OFS        0x00000098
// R2Y_COEF12 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_R2YMTX_COEF12_R2Y_COEF12_MASK 0x3FF
#define VCONV_VCONV_SET_R2YMTX_COEF12_R2Y_COEF12_SHIFT 0 
#define VCONV_VCONV_SET_R2YMTX_COEF12_R2Y_COEF12_BIT 0x3FF
#define VCONV_VCONV_SET_R2YMTX_COEF12_R2Y_COEF12_BITWIDTH 10
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_R2YMTX_COEF12_RESERVED_MASK 0xFFFFFC00
#define VCONV_VCONV_SET_R2YMTX_COEF12_RESERVED_SHIFT 10 
#define VCONV_VCONV_SET_R2YMTX_COEF12_RESERVED_BIT 0x3FFFFF
#define VCONV_VCONV_SET_R2YMTX_COEF12_RESERVED_BITWIDTH 22
// VCONV_SET_R2YMTX_COEF20 Register
#define VCONV_VCONV_SET_R2YMTX_COEF20_OFS        0x0000009C
// R2Y_COEF20 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_R2YMTX_COEF20_R2Y_COEF20_MASK 0x3FF
#define VCONV_VCONV_SET_R2YMTX_COEF20_R2Y_COEF20_SHIFT 0 
#define VCONV_VCONV_SET_R2YMTX_COEF20_R2Y_COEF20_BIT 0x3FF
#define VCONV_VCONV_SET_R2YMTX_COEF20_R2Y_COEF20_BITWIDTH 10
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_R2YMTX_COEF20_RESERVED_MASK 0xFFFFFC00
#define VCONV_VCONV_SET_R2YMTX_COEF20_RESERVED_SHIFT 10 
#define VCONV_VCONV_SET_R2YMTX_COEF20_RESERVED_BIT 0x3FFFFF
#define VCONV_VCONV_SET_R2YMTX_COEF20_RESERVED_BITWIDTH 22
// VCONV_SET_R2YMTX_COEF21 Register
#define VCONV_VCONV_SET_R2YMTX_COEF21_OFS        0x000000A0
// R2Y_COEF21 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_R2YMTX_COEF21_R2Y_COEF21_MASK 0x3FF
#define VCONV_VCONV_SET_R2YMTX_COEF21_R2Y_COEF21_SHIFT 0 
#define VCONV_VCONV_SET_R2YMTX_COEF21_R2Y_COEF21_BIT 0x3FF
#define VCONV_VCONV_SET_R2YMTX_COEF21_R2Y_COEF21_BITWIDTH 10
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_R2YMTX_COEF21_RESERVED_MASK 0xFFFFFC00
#define VCONV_VCONV_SET_R2YMTX_COEF21_RESERVED_SHIFT 10 
#define VCONV_VCONV_SET_R2YMTX_COEF21_RESERVED_BIT 0x3FFFFF
#define VCONV_VCONV_SET_R2YMTX_COEF21_RESERVED_BITWIDTH 22
// VCONV_SET_R2YMTX_COEF22 Register
#define VCONV_VCONV_SET_R2YMTX_COEF22_OFS        0x000000A4
// R2Y_COEF22 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_R2YMTX_COEF22_R2Y_COEF22_MASK 0x3FF
#define VCONV_VCONV_SET_R2YMTX_COEF22_R2Y_COEF22_SHIFT 0 
#define VCONV_VCONV_SET_R2YMTX_COEF22_R2Y_COEF22_BIT 0x3FF
#define VCONV_VCONV_SET_R2YMTX_COEF22_R2Y_COEF22_BITWIDTH 10
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_R2YMTX_COEF22_RESERVED_MASK 0xFFFFFC00
#define VCONV_VCONV_SET_R2YMTX_COEF22_RESERVED_SHIFT 10 
#define VCONV_VCONV_SET_R2YMTX_COEF22_RESERVED_BIT 0x3FFFFF
#define VCONV_VCONV_SET_R2YMTX_COEF22_RESERVED_BITWIDTH 22
// VCONV_SET_YLIMIT Register
#define VCONV_VCONV_SET_YLIMIT_OFS               0x000000A8
// R2Y_YMAX_LIMIT bitfiled (RW) Reset=11111111
#define VCONV_VCONV_SET_YLIMIT_R2Y_YMAX_LIMIT_MASK 0xFF
#define VCONV_VCONV_SET_YLIMIT_R2Y_YMAX_LIMIT_SHIFT 0 
#define VCONV_VCONV_SET_YLIMIT_R2Y_YMAX_LIMIT_BIT 0xFF
#define VCONV_VCONV_SET_YLIMIT_R2Y_YMAX_LIMIT_BITWIDTH 8
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_YLIMIT_RESERVED_MASK     0xFF00
#define VCONV_VCONV_SET_YLIMIT_RESERVED_SHIFT    8 
#define VCONV_VCONV_SET_YLIMIT_RESERVED_BIT      0xFF
#define VCONV_VCONV_SET_YLIMIT_RESERVED_BITWIDTH 8
// R2Y_YMIN_LIMIT bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_YLIMIT_R2Y_YMIN_LIMIT_MASK 0xFF0000
#define VCONV_VCONV_SET_YLIMIT_R2Y_YMIN_LIMIT_SHIFT 16 
#define VCONV_VCONV_SET_YLIMIT_R2Y_YMIN_LIMIT_BIT 0xFF
#define VCONV_VCONV_SET_YLIMIT_R2Y_YMIN_LIMIT_BITWIDTH 8
// Reserved2 bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_YLIMIT_RESERVED2_MASK    0xFF000000
#define VCONV_VCONV_SET_YLIMIT_RESERVED2_SHIFT   24 
#define VCONV_VCONV_SET_YLIMIT_RESERVED2_BIT     0xFF
#define VCONV_VCONV_SET_YLIMIT_RESERVED2_BITWIDTH 8
// VCONV_SET_CLIMIT Register
#define VCONV_VCONV_SET_CLIMIT_OFS               0x000000AC
// R2Y_CMAX_LIMIT bitfiled (RW) Reset=11111111
#define VCONV_VCONV_SET_CLIMIT_R2Y_CMAX_LIMIT_MASK 0xFF
#define VCONV_VCONV_SET_CLIMIT_R2Y_CMAX_LIMIT_SHIFT 0 
#define VCONV_VCONV_SET_CLIMIT_R2Y_CMAX_LIMIT_BIT 0xFF
#define VCONV_VCONV_SET_CLIMIT_R2Y_CMAX_LIMIT_BITWIDTH 8
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_CLIMIT_RESERVED_MASK     0xFF00
#define VCONV_VCONV_SET_CLIMIT_RESERVED_SHIFT    8 
#define VCONV_VCONV_SET_CLIMIT_RESERVED_BIT      0xFF
#define VCONV_VCONV_SET_CLIMIT_RESERVED_BITWIDTH 8
// R2Y_CMIN_LIMIT bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_CLIMIT_R2Y_CMIN_LIMIT_MASK 0xFF0000
#define VCONV_VCONV_SET_CLIMIT_R2Y_CMIN_LIMIT_SHIFT 16 
#define VCONV_VCONV_SET_CLIMIT_R2Y_CMIN_LIMIT_BIT 0xFF
#define VCONV_VCONV_SET_CLIMIT_R2Y_CMIN_LIMIT_BITWIDTH 8
// Reserved2 bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_CLIMIT_RESERVED2_MASK    0xFF000000
#define VCONV_VCONV_SET_CLIMIT_RESERVED2_SHIFT   24 
#define VCONV_VCONV_SET_CLIMIT_RESERVED2_BIT     0xFF
#define VCONV_VCONV_SET_CLIMIT_RESERVED2_BITWIDTH 8
// VCONV_TRANS_IN_FORMAT Register
#define VCONV_VCONV_TRANS_IN_FORMAT_OFS          0x00000100
// IN_COLORFORMAT bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_IN_FORMAT_IN_COLORFORMAT_MASK 0x3
#define VCONV_VCONV_TRANS_IN_FORMAT_IN_COLORFORMAT_SHIFT 0 
#define VCONV_VCONV_TRANS_IN_FORMAT_IN_COLORFORMAT_BIT 0x3
#define VCONV_VCONV_TRANS_IN_FORMAT_IN_COLORFORMAT_BITWIDTH 2
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_IN_FORMAT_RESERVED_MASK 0xC
#define VCONV_VCONV_TRANS_IN_FORMAT_RESERVED_SHIFT 2 
#define VCONV_VCONV_TRANS_IN_FORMAT_RESERVED_BIT 0x3
#define VCONV_VCONV_TRANS_IN_FORMAT_RESERVED_BITWIDTH 2
// IN_PLANE bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_IN_FORMAT_IN_PLANE_MASK 0x30
#define VCONV_VCONV_TRANS_IN_FORMAT_IN_PLANE_SHIFT 4 
#define VCONV_VCONV_TRANS_IN_FORMAT_IN_PLANE_BIT 0x3
#define VCONV_VCONV_TRANS_IN_FORMAT_IN_PLANE_BITWIDTH 2
// Reserved2 bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_IN_FORMAT_RESERVED2_MASK 0xC0
#define VCONV_VCONV_TRANS_IN_FORMAT_RESERVED2_SHIFT 6 
#define VCONV_VCONV_TRANS_IN_FORMAT_RESERVED2_BIT 0x3
#define VCONV_VCONV_TRANS_IN_FORMAT_RESERVED2_BITWIDTH 2
// IN_SCAN bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_IN_FORMAT_IN_SCAN_MASK 0x100
#define VCONV_VCONV_TRANS_IN_FORMAT_IN_SCAN_SHIFT 8 
#define VCONV_VCONV_TRANS_IN_FORMAT_IN_SCAN_BIT  0x1
#define VCONV_VCONV_TRANS_IN_FORMAT_IN_SCAN_BITWIDTH 1
// Reserved3 bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_IN_FORMAT_RESERVED3_MASK 0xFE00
#define VCONV_VCONV_TRANS_IN_FORMAT_RESERVED3_SHIFT 9 
#define VCONV_VCONV_TRANS_IN_FORMAT_RESERVED3_BIT 0x7F
#define VCONV_VCONV_TRANS_IN_FORMAT_RESERVED3_BITWIDTH 7
// IN_FORMATID bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_IN_FORMAT_IN_FORMATID_MASK 0xFF0000
#define VCONV_VCONV_TRANS_IN_FORMAT_IN_FORMATID_SHIFT 16 
#define VCONV_VCONV_TRANS_IN_FORMAT_IN_FORMATID_BIT 0xFF
#define VCONV_VCONV_TRANS_IN_FORMAT_IN_FORMATID_BITWIDTH 8
// Reserved4 bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_IN_FORMAT_RESERVED4_MASK 0xFF000000
#define VCONV_VCONV_TRANS_IN_FORMAT_RESERVED4_SHIFT 24 
#define VCONV_VCONV_TRANS_IN_FORMAT_RESERVED4_BIT 0xFF
#define VCONV_VCONV_TRANS_IN_FORMAT_RESERVED4_BITWIDTH 8
// VCONV_TRANS_IN_HSIZE Register
#define VCONV_VCONV_TRANS_IN_HSIZE_OFS           0x00000104
// IN_HSIZE bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_IN_HSIZE_IN_HSIZE_MASK 0x7FF
#define VCONV_VCONV_TRANS_IN_HSIZE_IN_HSIZE_SHIFT 0 
#define VCONV_VCONV_TRANS_IN_HSIZE_IN_HSIZE_BIT  0x7FF
#define VCONV_VCONV_TRANS_IN_HSIZE_IN_HSIZE_BITWIDTH 11
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_IN_HSIZE_RESERVED_MASK 0xFFFFF800
#define VCONV_VCONV_TRANS_IN_HSIZE_RESERVED_SHIFT 11 
#define VCONV_VCONV_TRANS_IN_HSIZE_RESERVED_BIT  0x1FFFFF
#define VCONV_VCONV_TRANS_IN_HSIZE_RESERVED_BITWIDTH 21
// VCONV_TRANS_IN_VSIZE Register
#define VCONV_VCONV_TRANS_IN_VSIZE_OFS           0x00000108
// IN_VSIZE bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_IN_VSIZE_IN_VSIZE_MASK 0x7FF
#define VCONV_VCONV_TRANS_IN_VSIZE_IN_VSIZE_SHIFT 0 
#define VCONV_VCONV_TRANS_IN_VSIZE_IN_VSIZE_BIT  0x7FF
#define VCONV_VCONV_TRANS_IN_VSIZE_IN_VSIZE_BITWIDTH 11
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_IN_VSIZE_RESERVED_MASK 0xFFFFF800
#define VCONV_VCONV_TRANS_IN_VSIZE_RESERVED_SHIFT 11 
#define VCONV_VCONV_TRANS_IN_VSIZE_RESERVED_BIT  0x1FFFFF
#define VCONV_VCONV_TRANS_IN_VSIZE_RESERVED_BITWIDTH 21
// VCONV_TRANS_IN_BASEADDR_A Register
#define VCONV_VCONV_TRANS_IN_BASEADDR_A_OFS      0x00000110
// IN_BADDR_A bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_IN_BASEADDR_A_IN_BADDR_A_MASK 0xFFFFFFFF
#define VCONV_VCONV_TRANS_IN_BASEADDR_A_IN_BADDR_A_SHIFT 0 
#define VCONV_VCONV_TRANS_IN_BASEADDR_A_IN_BADDR_A_BIT 0xFFFFFFFF
#define VCONV_VCONV_TRANS_IN_BASEADDR_A_IN_BADDR_A_BITWIDTH 32
// VCONV_TRANS_IN_BASEADDR_B Register
#define VCONV_VCONV_TRANS_IN_BASEADDR_B_OFS      0x00000114
// IN_BADDR_B bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_IN_BASEADDR_B_IN_BADDR_B_MASK 0xFFFFFFFF
#define VCONV_VCONV_TRANS_IN_BASEADDR_B_IN_BADDR_B_SHIFT 0 
#define VCONV_VCONV_TRANS_IN_BASEADDR_B_IN_BADDR_B_BIT 0xFFFFFFFF
#define VCONV_VCONV_TRANS_IN_BASEADDR_B_IN_BADDR_B_BITWIDTH 32
// VCONV_TRANS_IN_BASEADDR_C Register
#define VCONV_VCONV_TRANS_IN_BASEADDR_C_OFS      0x00000118
// IN_BADDR_C bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_IN_BASEADDR_C_IN_BADDR_C_MASK 0xFFFFFFFF
#define VCONV_VCONV_TRANS_IN_BASEADDR_C_IN_BADDR_C_SHIFT 0 
#define VCONV_VCONV_TRANS_IN_BASEADDR_C_IN_BADDR_C_BIT 0xFFFFFFFF
#define VCONV_VCONV_TRANS_IN_BASEADDR_C_IN_BADDR_C_BITWIDTH 32
// VCONV_TRANS_IN_PITCH_A Register
#define VCONV_VCONV_TRANS_IN_PITCH_A_OFS         0x0000011C
// IN_PITCH_A bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_IN_PITCH_A_IN_PITCH_A_MASK 0x1FFF
#define VCONV_VCONV_TRANS_IN_PITCH_A_IN_PITCH_A_SHIFT 0 
#define VCONV_VCONV_TRANS_IN_PITCH_A_IN_PITCH_A_BIT 0x1FFF
#define VCONV_VCONV_TRANS_IN_PITCH_A_IN_PITCH_A_BITWIDTH 13
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_IN_PITCH_A_RESERVED_MASK 0xFFFFE000
#define VCONV_VCONV_TRANS_IN_PITCH_A_RESERVED_SHIFT 13 
#define VCONV_VCONV_TRANS_IN_PITCH_A_RESERVED_BIT 0x7FFFF
#define VCONV_VCONV_TRANS_IN_PITCH_A_RESERVED_BITWIDTH 19
// VCONV_TRANS_IN_PITCH_B Register
#define VCONV_VCONV_TRANS_IN_PITCH_B_OFS         0x00000120
// IN_PITCH_B bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_IN_PITCH_B_IN_PITCH_B_MASK 0x1FFF
#define VCONV_VCONV_TRANS_IN_PITCH_B_IN_PITCH_B_SHIFT 0 
#define VCONV_VCONV_TRANS_IN_PITCH_B_IN_PITCH_B_BIT 0x1FFF
#define VCONV_VCONV_TRANS_IN_PITCH_B_IN_PITCH_B_BITWIDTH 13
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_IN_PITCH_B_RESERVED_MASK 0xFFFFE000
#define VCONV_VCONV_TRANS_IN_PITCH_B_RESERVED_SHIFT 13 
#define VCONV_VCONV_TRANS_IN_PITCH_B_RESERVED_BIT 0x7FFFF
#define VCONV_VCONV_TRANS_IN_PITCH_B_RESERVED_BITWIDTH 19
// VCONV_TRANS_IN_PITCH_C Register
#define VCONV_VCONV_TRANS_IN_PITCH_C_OFS         0x00000124
// IN_PITCH_C bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_IN_PITCH_C_IN_PITCH_C_MASK 0x1FFF
#define VCONV_VCONV_TRANS_IN_PITCH_C_IN_PITCH_C_SHIFT 0 
#define VCONV_VCONV_TRANS_IN_PITCH_C_IN_PITCH_C_BIT 0x1FFF
#define VCONV_VCONV_TRANS_IN_PITCH_C_IN_PITCH_C_BITWIDTH 13
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_IN_PITCH_C_RESERVED_MASK 0xFFFFE000
#define VCONV_VCONV_TRANS_IN_PITCH_C_RESERVED_SHIFT 13 
#define VCONV_VCONV_TRANS_IN_PITCH_C_RESERVED_BIT 0x7FFFF
#define VCONV_VCONV_TRANS_IN_PITCH_C_RESERVED_BITWIDTH 19
// VCONV_TRANS_OUT_FORMAT Register
#define VCONV_VCONV_TRANS_OUT_FORMAT_OFS         0x00000140
// OUT_COLORFORMAT bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_OUT_FORMAT_OUT_COLORFORMAT_MASK 0x3
#define VCONV_VCONV_TRANS_OUT_FORMAT_OUT_COLORFORMAT_SHIFT 0 
#define VCONV_VCONV_TRANS_OUT_FORMAT_OUT_COLORFORMAT_BIT 0x3
#define VCONV_VCONV_TRANS_OUT_FORMAT_OUT_COLORFORMAT_BITWIDTH 2
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_OUT_FORMAT_RESERVED_MASK 0xC
#define VCONV_VCONV_TRANS_OUT_FORMAT_RESERVED_SHIFT 2 
#define VCONV_VCONV_TRANS_OUT_FORMAT_RESERVED_BIT 0x3
#define VCONV_VCONV_TRANS_OUT_FORMAT_RESERVED_BITWIDTH 2
// OUT_PLANE bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_OUT_FORMAT_OUT_PLANE_MASK 0x30
#define VCONV_VCONV_TRANS_OUT_FORMAT_OUT_PLANE_SHIFT 4 
#define VCONV_VCONV_TRANS_OUT_FORMAT_OUT_PLANE_BIT 0x3
#define VCONV_VCONV_TRANS_OUT_FORMAT_OUT_PLANE_BITWIDTH 2
// Reserved2 bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_OUT_FORMAT_RESERVED2_MASK 0xC0
#define VCONV_VCONV_TRANS_OUT_FORMAT_RESERVED2_SHIFT 6 
#define VCONV_VCONV_TRANS_OUT_FORMAT_RESERVED2_BIT 0x3
#define VCONV_VCONV_TRANS_OUT_FORMAT_RESERVED2_BITWIDTH 2
// OUT_SCAN bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_OUT_FORMAT_OUT_SCAN_MASK 0x100
#define VCONV_VCONV_TRANS_OUT_FORMAT_OUT_SCAN_SHIFT 8 
#define VCONV_VCONV_TRANS_OUT_FORMAT_OUT_SCAN_BIT 0x1
#define VCONV_VCONV_TRANS_OUT_FORMAT_OUT_SCAN_BITWIDTH 1
// Reserved3 bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_OUT_FORMAT_RESERVED3_MASK 0xFE00
#define VCONV_VCONV_TRANS_OUT_FORMAT_RESERVED3_SHIFT 9 
#define VCONV_VCONV_TRANS_OUT_FORMAT_RESERVED3_BIT 0x7F
#define VCONV_VCONV_TRANS_OUT_FORMAT_RESERVED3_BITWIDTH 7
// OUT_FORMATID bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_OUT_FORMAT_OUT_FORMATID_MASK 0xFF0000
#define VCONV_VCONV_TRANS_OUT_FORMAT_OUT_FORMATID_SHIFT 16 
#define VCONV_VCONV_TRANS_OUT_FORMAT_OUT_FORMATID_BIT 0xFF
#define VCONV_VCONV_TRANS_OUT_FORMAT_OUT_FORMATID_BITWIDTH 8
// Reserved4 bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_OUT_FORMAT_RESERVED4_MASK 0xFF000000
#define VCONV_VCONV_TRANS_OUT_FORMAT_RESERVED4_SHIFT 24 
#define VCONV_VCONV_TRANS_OUT_FORMAT_RESERVED4_BIT 0xFF
#define VCONV_VCONV_TRANS_OUT_FORMAT_RESERVED4_BITWIDTH 8
// VCONV_TRANS_OUT_HSIZE Register
#define VCONV_VCONV_TRANS_OUT_HSIZE_OFS          0x00000144
// OUT_HSIZE bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_OUT_HSIZE_OUT_HSIZE_MASK 0x7FF
#define VCONV_VCONV_TRANS_OUT_HSIZE_OUT_HSIZE_SHIFT 0 
#define VCONV_VCONV_TRANS_OUT_HSIZE_OUT_HSIZE_BIT 0x7FF
#define VCONV_VCONV_TRANS_OUT_HSIZE_OUT_HSIZE_BITWIDTH 11
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_OUT_HSIZE_RESERVED_MASK 0xFFFFF800
#define VCONV_VCONV_TRANS_OUT_HSIZE_RESERVED_SHIFT 11 
#define VCONV_VCONV_TRANS_OUT_HSIZE_RESERVED_BIT 0x1FFFFF
#define VCONV_VCONV_TRANS_OUT_HSIZE_RESERVED_BITWIDTH 21
// VCONV_TRANS_OUT_VSIZE Register
#define VCONV_VCONV_TRANS_OUT_VSIZE_OFS          0x00000148
// OUT_VSIZE bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_OUT_VSIZE_OUT_VSIZE_MASK 0x7FF
#define VCONV_VCONV_TRANS_OUT_VSIZE_OUT_VSIZE_SHIFT 0 
#define VCONV_VCONV_TRANS_OUT_VSIZE_OUT_VSIZE_BIT 0x7FF
#define VCONV_VCONV_TRANS_OUT_VSIZE_OUT_VSIZE_BITWIDTH 11
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_OUT_VSIZE_RESERVED_MASK 0xFFFFF800
#define VCONV_VCONV_TRANS_OUT_VSIZE_RESERVED_SHIFT 11 
#define VCONV_VCONV_TRANS_OUT_VSIZE_RESERVED_BIT 0x1FFFFF
#define VCONV_VCONV_TRANS_OUT_VSIZE_RESERVED_BITWIDTH 21
// VCONV_TRANS_OUT_BASEADDR_A Register
#define VCONV_VCONV_TRANS_OUT_BASEADDR_A_OFS     0x00000150
// OUT_BADDR_A bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_OUT_BASEADDR_A_OUT_BADDR_A_MASK 0xFFFFFFFF
#define VCONV_VCONV_TRANS_OUT_BASEADDR_A_OUT_BADDR_A_SHIFT 0 
#define VCONV_VCONV_TRANS_OUT_BASEADDR_A_OUT_BADDR_A_BIT 0xFFFFFFFF
#define VCONV_VCONV_TRANS_OUT_BASEADDR_A_OUT_BADDR_A_BITWIDTH 32
// VCONV_TRANS_OUT_BASEADDR_B Register
#define VCONV_VCONV_TRANS_OUT_BASEADDR_B_OFS     0x00000154
// OUT_BADDR_B bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_OUT_BASEADDR_B_OUT_BADDR_B_MASK 0xFFFFFFFF
#define VCONV_VCONV_TRANS_OUT_BASEADDR_B_OUT_BADDR_B_SHIFT 0 
#define VCONV_VCONV_TRANS_OUT_BASEADDR_B_OUT_BADDR_B_BIT 0xFFFFFFFF
#define VCONV_VCONV_TRANS_OUT_BASEADDR_B_OUT_BADDR_B_BITWIDTH 32
// VCONV_TRANS_OUT_BASEADDR_C Register
#define VCONV_VCONV_TRANS_OUT_BASEADDR_C_OFS     0x00000158
// OUT_BADDR_C bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_OUT_BASEADDR_C_OUT_BADDR_C_MASK 0xFFFFFFFF
#define VCONV_VCONV_TRANS_OUT_BASEADDR_C_OUT_BADDR_C_SHIFT 0 
#define VCONV_VCONV_TRANS_OUT_BASEADDR_C_OUT_BADDR_C_BIT 0xFFFFFFFF
#define VCONV_VCONV_TRANS_OUT_BASEADDR_C_OUT_BADDR_C_BITWIDTH 32
// VCONV_TRANS_OUT_PITCH_A Register
#define VCONV_VCONV_TRANS_OUT_PITCH_A_OFS        0x0000015C
// OUT_PITCH_A bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_OUT_PITCH_A_OUT_PITCH_A_MASK 0x1FFF
#define VCONV_VCONV_TRANS_OUT_PITCH_A_OUT_PITCH_A_SHIFT 0 
#define VCONV_VCONV_TRANS_OUT_PITCH_A_OUT_PITCH_A_BIT 0x1FFF
#define VCONV_VCONV_TRANS_OUT_PITCH_A_OUT_PITCH_A_BITWIDTH 13
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_OUT_PITCH_A_RESERVED_MASK 0xFFFFE000
#define VCONV_VCONV_TRANS_OUT_PITCH_A_RESERVED_SHIFT 13 
#define VCONV_VCONV_TRANS_OUT_PITCH_A_RESERVED_BIT 0x7FFFF
#define VCONV_VCONV_TRANS_OUT_PITCH_A_RESERVED_BITWIDTH 19
// VCONV_TRANS_OUT_PITCH_B Register
#define VCONV_VCONV_TRANS_OUT_PITCH_B_OFS        0x00000160
// OUT_PITCH_B bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_OUT_PITCH_B_OUT_PITCH_B_MASK 0x1FFF
#define VCONV_VCONV_TRANS_OUT_PITCH_B_OUT_PITCH_B_SHIFT 0 
#define VCONV_VCONV_TRANS_OUT_PITCH_B_OUT_PITCH_B_BIT 0x1FFF
#define VCONV_VCONV_TRANS_OUT_PITCH_B_OUT_PITCH_B_BITWIDTH 13
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_OUT_PITCH_B_RESERVED_MASK 0xFFFFE000
#define VCONV_VCONV_TRANS_OUT_PITCH_B_RESERVED_SHIFT 13 
#define VCONV_VCONV_TRANS_OUT_PITCH_B_RESERVED_BIT 0x7FFFF
#define VCONV_VCONV_TRANS_OUT_PITCH_B_RESERVED_BITWIDTH 19
// VCONV_TRANS_OUT_PITCH_C Register
#define VCONV_VCONV_TRANS_OUT_PITCH_C_OFS        0x00000164
// OUT_PITCH_C bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_OUT_PITCH_C_OUT_PITCH_C_MASK 0x1FFF
#define VCONV_VCONV_TRANS_OUT_PITCH_C_OUT_PITCH_C_SHIFT 0 
#define VCONV_VCONV_TRANS_OUT_PITCH_C_OUT_PITCH_C_BIT 0x1FFF
#define VCONV_VCONV_TRANS_OUT_PITCH_C_OUT_PITCH_C_BITWIDTH 13
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_OUT_PITCH_C_RESERVED_MASK 0xFFFFE000
#define VCONV_VCONV_TRANS_OUT_PITCH_C_RESERVED_SHIFT 13 
#define VCONV_VCONV_TRANS_OUT_PITCH_C_RESERVED_BIT 0x7FFFF
#define VCONV_VCONV_TRANS_OUT_PITCH_C_RESERVED_BITWIDTH 19
// VCONV_TRANS_OUT_HOFFSET Register
#define VCONV_VCONV_TRANS_OUT_HOFFSET_OFS        0x00000168
// OUT_HOFFSET bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_OUT_HOFFSET_OUT_HOFFSET_MASK 0x7FF
#define VCONV_VCONV_TRANS_OUT_HOFFSET_OUT_HOFFSET_SHIFT 0 
#define VCONV_VCONV_TRANS_OUT_HOFFSET_OUT_HOFFSET_BIT 0x7FF
#define VCONV_VCONV_TRANS_OUT_HOFFSET_OUT_HOFFSET_BITWIDTH 11
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_OUT_HOFFSET_RESERVED_MASK 0xFFFFF800
#define VCONV_VCONV_TRANS_OUT_HOFFSET_RESERVED_SHIFT 11 
#define VCONV_VCONV_TRANS_OUT_HOFFSET_RESERVED_BIT 0x1FFFFF
#define VCONV_VCONV_TRANS_OUT_HOFFSET_RESERVED_BITWIDTH 21
// VCONV_TRANS_OUT_VOFFSET Register
#define VCONV_VCONV_TRANS_OUT_VOFFSET_OFS        0x0000016C
// OUT_VOFFSET bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_OUT_VOFFSET_OUT_VOFFSET_MASK 0x7FF
#define VCONV_VCONV_TRANS_OUT_VOFFSET_OUT_VOFFSET_SHIFT 0 
#define VCONV_VCONV_TRANS_OUT_VOFFSET_OUT_VOFFSET_BIT 0x7FF
#define VCONV_VCONV_TRANS_OUT_VOFFSET_OUT_VOFFSET_BITWIDTH 11
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_OUT_VOFFSET_RESERVED_MASK 0xFFFFF800
#define VCONV_VCONV_TRANS_OUT_VOFFSET_RESERVED_SHIFT 11 
#define VCONV_VCONV_TRANS_OUT_VOFFSET_RESERVED_BIT 0x1FFFFF
#define VCONV_VCONV_TRANS_OUT_VOFFSET_RESERVED_BITWIDTH 21
// VCONV_TRANS_OUT_HSCALE Register
#define VCONV_VCONV_TRANS_OUT_HSCALE_OFS         0x00000170
// HSCALE_FRACTON bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_OUT_HSCALE_HSCALE_FRACTON_MASK 0xFFFF
#define VCONV_VCONV_TRANS_OUT_HSCALE_HSCALE_FRACTON_SHIFT 0 
#define VCONV_VCONV_TRANS_OUT_HSCALE_HSCALE_FRACTON_BIT 0xFFFF
#define VCONV_VCONV_TRANS_OUT_HSCALE_HSCALE_FRACTON_BITWIDTH 16
// HSCALE_INTEGER bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_OUT_HSCALE_HSCALE_INTEGER_MASK 0x70000
#define VCONV_VCONV_TRANS_OUT_HSCALE_HSCALE_INTEGER_SHIFT 16 
#define VCONV_VCONV_TRANS_OUT_HSCALE_HSCALE_INTEGER_BIT 0x7
#define VCONV_VCONV_TRANS_OUT_HSCALE_HSCALE_INTEGER_BITWIDTH 3
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_OUT_HSCALE_RESERVED_MASK 0xFFF80000
#define VCONV_VCONV_TRANS_OUT_HSCALE_RESERVED_SHIFT 19 
#define VCONV_VCONV_TRANS_OUT_HSCALE_RESERVED_BIT 0x1FFF
#define VCONV_VCONV_TRANS_OUT_HSCALE_RESERVED_BITWIDTH 13
// VCONV_TRANS_OUT_VSCALE Register
#define VCONV_VCONV_TRANS_OUT_VSCALE_OFS         0x00000174
// VSCALE_FRACTON bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_OUT_VSCALE_VSCALE_FRACTON_MASK 0xFFFF
#define VCONV_VCONV_TRANS_OUT_VSCALE_VSCALE_FRACTON_SHIFT 0 
#define VCONV_VCONV_TRANS_OUT_VSCALE_VSCALE_FRACTON_BIT 0xFFFF
#define VCONV_VCONV_TRANS_OUT_VSCALE_VSCALE_FRACTON_BITWIDTH 16
// VSCALE_INTEGER bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_OUT_VSCALE_VSCALE_INTEGER_MASK 0x70000
#define VCONV_VCONV_TRANS_OUT_VSCALE_VSCALE_INTEGER_SHIFT 16 
#define VCONV_VCONV_TRANS_OUT_VSCALE_VSCALE_INTEGER_BIT 0x7
#define VCONV_VCONV_TRANS_OUT_VSCALE_VSCALE_INTEGER_BITWIDTH 3
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_OUT_VSCALE_RESERVED_MASK 0xFFF80000
#define VCONV_VCONV_TRANS_OUT_VSCALE_RESERVED_SHIFT 19 
#define VCONV_VCONV_TRANS_OUT_VSCALE_RESERVED_BIT 0x1FFF
#define VCONV_VCONV_TRANS_OUT_VSCALE_RESERVED_BITWIDTH 13
// VCONV_TRANS_OUT_HDELTA Register
#define VCONV_VCONV_TRANS_OUT_HDELTA_OFS         0x00000178
// HDELTA bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_OUT_HDELTA_HDELTA_MASK 0x3FF
#define VCONV_VCONV_TRANS_OUT_HDELTA_HDELTA_SHIFT 0 
#define VCONV_VCONV_TRANS_OUT_HDELTA_HDELTA_BIT  0x3FF
#define VCONV_VCONV_TRANS_OUT_HDELTA_HDELTA_BITWIDTH 10
// reserved2 bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_OUT_HDELTA_RESERVED2_MASK 0x400
#define VCONV_VCONV_TRANS_OUT_HDELTA_RESERVED2_SHIFT 10 
#define VCONV_VCONV_TRANS_OUT_HDELTA_RESERVED2_BIT 0x1
#define VCONV_VCONV_TRANS_OUT_HDELTA_RESERVED2_BITWIDTH 1
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_OUT_HDELTA_RESERVED_MASK 0xFFFFF800
#define VCONV_VCONV_TRANS_OUT_HDELTA_RESERVED_SHIFT 11 
#define VCONV_VCONV_TRANS_OUT_HDELTA_RESERVED_BIT 0x1FFFFF
#define VCONV_VCONV_TRANS_OUT_HDELTA_RESERVED_BITWIDTH 21
// VCONV_TRANS_OUT_VDELTA Register
#define VCONV_VCONV_TRANS_OUT_VDELTA_OFS         0x0000017C
// VDELTA bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_OUT_VDELTA_VDELTA_MASK 0x3FF
#define VCONV_VCONV_TRANS_OUT_VDELTA_VDELTA_SHIFT 0 
#define VCONV_VCONV_TRANS_OUT_VDELTA_VDELTA_BIT  0x3FF
#define VCONV_VCONV_TRANS_OUT_VDELTA_VDELTA_BITWIDTH 10
// reserved2 bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_OUT_VDELTA_RESERVED2_MASK 0x400
#define VCONV_VCONV_TRANS_OUT_VDELTA_RESERVED2_SHIFT 10 
#define VCONV_VCONV_TRANS_OUT_VDELTA_RESERVED2_BIT 0x1
#define VCONV_VCONV_TRANS_OUT_VDELTA_RESERVED2_BITWIDTH 1
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_OUT_VDELTA_RESERVED_MASK 0xFFFFF800
#define VCONV_VCONV_TRANS_OUT_VDELTA_RESERVED_SHIFT 11 
#define VCONV_VCONV_TRANS_OUT_VDELTA_RESERVED_BIT 0x1FFFFF
#define VCONV_VCONV_TRANS_OUT_VDELTA_RESERVED_BITWIDTH 21
// VCONV_TRANS_FORCE_MODE Register
#define VCONV_VCONV_TRANS_FORCE_MODE_OFS         0x00000180
// FORCE_MODE bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_FORCE_MODE_FORCE_MODE_MASK 0x1
#define VCONV_VCONV_TRANS_FORCE_MODE_FORCE_MODE_SHIFT 0 
#define VCONV_VCONV_TRANS_FORCE_MODE_FORCE_MODE_BIT 0x1
#define VCONV_VCONV_TRANS_FORCE_MODE_FORCE_MODE_BITWIDTH 1
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_FORCE_MODE_RESERVED_MASK 0xFFFFFFFE
#define VCONV_VCONV_TRANS_FORCE_MODE_RESERVED_SHIFT 1 
#define VCONV_VCONV_TRANS_FORCE_MODE_RESERVED_BIT 0x7FFFFFFF
#define VCONV_VCONV_TRANS_FORCE_MODE_RESERVED_BITWIDTH 31
// VCONV_CH_FORCE_GY Register
#define VCONV_VCONV_CH_FORCE_GY_OFS              0x00000184
// FORCE_GY bitfiled (RO) Reset=0
#define VCONV_VCONV_CH_FORCE_GY_FORCE_GY_MASK    0xFF
#define VCONV_VCONV_CH_FORCE_GY_FORCE_GY_SHIFT   0 
#define VCONV_VCONV_CH_FORCE_GY_FORCE_GY_BIT     0xFF
#define VCONV_VCONV_CH_FORCE_GY_FORCE_GY_BITWIDTH 8
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_CH_FORCE_GY_RESERVED_MASK    0xFFFFFF00
#define VCONV_VCONV_CH_FORCE_GY_RESERVED_SHIFT   8 
#define VCONV_VCONV_CH_FORCE_GY_RESERVED_BIT     0xFFFFFF
#define VCONV_VCONV_CH_FORCE_GY_RESERVED_BITWIDTH 24
// VCONV_CH_FORCE_BCB Register
#define VCONV_VCONV_CH_FORCE_BCB_OFS             0x00000188
// FORCE_BCB bitfiled (RO) Reset=0
#define VCONV_VCONV_CH_FORCE_BCB_FORCE_BCB_MASK  0xFF
#define VCONV_VCONV_CH_FORCE_BCB_FORCE_BCB_SHIFT 0 
#define VCONV_VCONV_CH_FORCE_BCB_FORCE_BCB_BIT   0xFF
#define VCONV_VCONV_CH_FORCE_BCB_FORCE_BCB_BITWIDTH 8
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_CH_FORCE_BCB_RESERVED_MASK   0xFFFFFF00
#define VCONV_VCONV_CH_FORCE_BCB_RESERVED_SHIFT  8 
#define VCONV_VCONV_CH_FORCE_BCB_RESERVED_BIT    0xFFFFFF
#define VCONV_VCONV_CH_FORCE_BCB_RESERVED_BITWIDTH 24
// VCONV_CH_FORCE_R Register
#define VCONV_VCONV_CH_FORCE_R_OFS               0x0000018C
// FORCE_RCR bitfiled (RO) Reset=0
#define VCONV_VCONV_CH_FORCE_R_FORCE_RCR_MASK    0xFF
#define VCONV_VCONV_CH_FORCE_R_FORCE_RCR_SHIFT   0 
#define VCONV_VCONV_CH_FORCE_R_FORCE_RCR_BIT     0xFF
#define VCONV_VCONV_CH_FORCE_R_FORCE_RCR_BITWIDTH 8
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_CH_FORCE_R_RESERVED_MASK     0xFFFFFF00
#define VCONV_VCONV_CH_FORCE_R_RESERVED_SHIFT    8 
#define VCONV_VCONV_CH_FORCE_R_RESERVED_BIT      0xFFFFFF
#define VCONV_VCONV_CH_FORCE_R_RESERVED_BITWIDTH 24
// VCONV_CH_FORCE_A Register
#define VCONV_VCONV_CH_FORCE_A_OFS               0x00000190
// FORCE_ALPHA bitfiled (RO) Reset=0
#define VCONV_VCONV_CH_FORCE_A_FORCE_ALPHA_MASK  0xFF
#define VCONV_VCONV_CH_FORCE_A_FORCE_ALPHA_SHIFT 0 
#define VCONV_VCONV_CH_FORCE_A_FORCE_ALPHA_BIT   0xFF
#define VCONV_VCONV_CH_FORCE_A_FORCE_ALPHA_BITWIDTH 8
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_CH_FORCE_A_RESERVED_MASK     0xFFFFFF00
#define VCONV_VCONV_CH_FORCE_A_RESERVED_SHIFT    8 
#define VCONV_VCONV_CH_FORCE_A_RESERVED_BIT      0xFFFFFF
#define VCONV_VCONV_CH_FORCE_A_RESERVED_BITWIDTH 24
// VCONV_TRANS_CROP Register
#define VCONV_VCONV_TRANS_CROP_OFS               0x000001B0
// CROP_UPPER bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_CROP_CROP_UPPER_MASK   0xF
#define VCONV_VCONV_TRANS_CROP_CROP_UPPER_SHIFT  0 
#define VCONV_VCONV_TRANS_CROP_CROP_UPPER_BIT    0xF
#define VCONV_VCONV_TRANS_CROP_CROP_UPPER_BITWIDTH 4
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_CROP_RESERVED_MASK     0xF0
#define VCONV_VCONV_TRANS_CROP_RESERVED_SHIFT    4 
#define VCONV_VCONV_TRANS_CROP_RESERVED_BIT      0xF
#define VCONV_VCONV_TRANS_CROP_RESERVED_BITWIDTH 4
// CROP_LOWER bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_CROP_CROP_LOWER_MASK   0xF00
#define VCONV_VCONV_TRANS_CROP_CROP_LOWER_SHIFT  8 
#define VCONV_VCONV_TRANS_CROP_CROP_LOWER_BIT    0xF
#define VCONV_VCONV_TRANS_CROP_CROP_LOWER_BITWIDTH 4
// Reserved2 bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_CROP_RESERVED2_MASK    0xF000
#define VCONV_VCONV_TRANS_CROP_RESERVED2_SHIFT   12 
#define VCONV_VCONV_TRANS_CROP_RESERVED2_BIT     0xF
#define VCONV_VCONV_TRANS_CROP_RESERVED2_BITWIDTH 4
// CROP_LEFT bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_CROP_CROP_LEFT_MASK    0xF0000
#define VCONV_VCONV_TRANS_CROP_CROP_LEFT_SHIFT   16 
#define VCONV_VCONV_TRANS_CROP_CROP_LEFT_BIT     0xF
#define VCONV_VCONV_TRANS_CROP_CROP_LEFT_BITWIDTH 4
// Reserved3 bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_CROP_RESERVED3_MASK    0xF00000
#define VCONV_VCONV_TRANS_CROP_RESERVED3_SHIFT   20 
#define VCONV_VCONV_TRANS_CROP_RESERVED3_BIT     0xF
#define VCONV_VCONV_TRANS_CROP_RESERVED3_BITWIDTH 4
// CROP_RIGHT bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_CROP_CROP_RIGHT_MASK   0xF000000
#define VCONV_VCONV_TRANS_CROP_CROP_RIGHT_SHIFT  24 
#define VCONV_VCONV_TRANS_CROP_CROP_RIGHT_BIT    0xF
#define VCONV_VCONV_TRANS_CROP_CROP_RIGHT_BITWIDTH 4
// Reserved4 bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_CROP_RESERVED4_MASK    0xF0000000
#define VCONV_VCONV_TRANS_CROP_RESERVED4_SHIFT   28 
#define VCONV_VCONV_TRANS_CROP_RESERVED4_BIT     0xF
#define VCONV_VCONV_TRANS_CROP_RESERVED4_BITWIDTH 4
// VCONV_TRANS_STATUS Register
#define VCONV_VCONV_TRANS_STATUS_OFS             0x000001D0
// TRUNS_STATUS bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_STATUS_TRUNS_STATUS_MASK 0x1
#define VCONV_VCONV_TRANS_STATUS_TRUNS_STATUS_SHIFT 0 
#define VCONV_VCONV_TRANS_STATUS_TRUNS_STATUS_BIT 0x1
#define VCONV_VCONV_TRANS_STATUS_TRUNS_STATUS_BITWIDTH 1
// TRANS_CHANNEL bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_STATUS_TRANS_CHANNEL_MASK 0x2
#define VCONV_VCONV_TRANS_STATUS_TRANS_CHANNEL_SHIFT 1 
#define VCONV_VCONV_TRANS_STATUS_TRANS_CHANNEL_BIT 0x1
#define VCONV_VCONV_TRANS_STATUS_TRANS_CHANNEL_BITWIDTH 1
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_STATUS_RESERVED_MASK   0xFC
#define VCONV_VCONV_TRANS_STATUS_RESERVED_SHIFT  2 
#define VCONV_VCONV_TRANS_STATUS_RESERVED_BIT    0x3F
#define VCONV_VCONV_TRANS_STATUS_RESERVED_BITWIDTH 6
// MERGE_STATUS bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_STATUS_MERGE_STATUS_MASK 0x100
#define VCONV_VCONV_TRANS_STATUS_MERGE_STATUS_SHIFT 8 
#define VCONV_VCONV_TRANS_STATUS_MERGE_STATUS_BIT 0x1
#define VCONV_VCONV_TRANS_STATUS_MERGE_STATUS_BITWIDTH 1
// Reserved2 bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_STATUS_RESERVED2_MASK  0xFFFFFE00
#define VCONV_VCONV_TRANS_STATUS_RESERVED2_SHIFT 9 
#define VCONV_VCONV_TRANS_STATUS_RESERVED2_BIT   0x7FFFFF
#define VCONV_VCONV_TRANS_STATUS_RESERVED2_BITWIDTH 23
// VCONV_TRANS_LINE Register
#define VCONV_VCONV_TRANS_LINE_OFS               0x000001D4
// INPUT_LINE bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_LINE_INPUT_LINE_MASK   0x7FF
#define VCONV_VCONV_TRANS_LINE_INPUT_LINE_SHIFT  0 
#define VCONV_VCONV_TRANS_LINE_INPUT_LINE_BIT    0x7FF
#define VCONV_VCONV_TRANS_LINE_INPUT_LINE_BITWIDTH 11
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_LINE_RESERVED_MASK     0xF800
#define VCONV_VCONV_TRANS_LINE_RESERVED_SHIFT    11 
#define VCONV_VCONV_TRANS_LINE_RESERVED_BIT      0x1F
#define VCONV_VCONV_TRANS_LINE_RESERVED_BITWIDTH 5
// OUTPUT_LINE bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_LINE_OUTPUT_LINE_MASK  0x7FF0000
#define VCONV_VCONV_TRANS_LINE_OUTPUT_LINE_SHIFT 16 
#define VCONV_VCONV_TRANS_LINE_OUTPUT_LINE_BIT   0x7FF
#define VCONV_VCONV_TRANS_LINE_OUTPUT_LINE_BITWIDTH 11
// Reserved2 bitfiled (RO) Reset=0
#define VCONV_VCONV_TRANS_LINE_RESERVED2_MASK    0xF8000000
#define VCONV_VCONV_TRANS_LINE_RESERVED2_SHIFT   27 
#define VCONV_VCONV_TRANS_LINE_RESERVED2_BIT     0x1F
#define VCONV_VCONV_TRANS_LINE_RESERVED2_BITWIDTH 5
// VCONV_SET_IN_FORMAT0 Register
#define VCONV_VCONV_SET_IN_FORMAT0_OFS           0x00000200
// IN_COLORFORMAT0 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_IN_FORMAT0_IN_COLORFORMAT0_MASK 0x3
#define VCONV_VCONV_SET_IN_FORMAT0_IN_COLORFORMAT0_SHIFT 0 
#define VCONV_VCONV_SET_IN_FORMAT0_IN_COLORFORMAT0_BIT 0x3
#define VCONV_VCONV_SET_IN_FORMAT0_IN_COLORFORMAT0_BITWIDTH 2
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_IN_FORMAT0_RESERVED_MASK 0xC
#define VCONV_VCONV_SET_IN_FORMAT0_RESERVED_SHIFT 2 
#define VCONV_VCONV_SET_IN_FORMAT0_RESERVED_BIT  0x3
#define VCONV_VCONV_SET_IN_FORMAT0_RESERVED_BITWIDTH 2
// IN_PLANE0 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_IN_FORMAT0_IN_PLANE0_MASK 0x30
#define VCONV_VCONV_SET_IN_FORMAT0_IN_PLANE0_SHIFT 4 
#define VCONV_VCONV_SET_IN_FORMAT0_IN_PLANE0_BIT 0x3
#define VCONV_VCONV_SET_IN_FORMAT0_IN_PLANE0_BITWIDTH 2
// Reserved2 bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_IN_FORMAT0_RESERVED2_MASK 0xC0
#define VCONV_VCONV_SET_IN_FORMAT0_RESERVED2_SHIFT 6 
#define VCONV_VCONV_SET_IN_FORMAT0_RESERVED2_BIT 0x3
#define VCONV_VCONV_SET_IN_FORMAT0_RESERVED2_BITWIDTH 2
// IN_SCAN0 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_IN_FORMAT0_IN_SCAN0_MASK 0x100
#define VCONV_VCONV_SET_IN_FORMAT0_IN_SCAN0_SHIFT 8 
#define VCONV_VCONV_SET_IN_FORMAT0_IN_SCAN0_BIT  0x1
#define VCONV_VCONV_SET_IN_FORMAT0_IN_SCAN0_BITWIDTH 1
// Reserved3 bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_IN_FORMAT0_RESERVED3_MASK 0xFE00
#define VCONV_VCONV_SET_IN_FORMAT0_RESERVED3_SHIFT 9 
#define VCONV_VCONV_SET_IN_FORMAT0_RESERVED3_BIT 0x7F
#define VCONV_VCONV_SET_IN_FORMAT0_RESERVED3_BITWIDTH 7
// IN_FORMATID0 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_IN_FORMAT0_IN_FORMATID0_MASK 0xFF0000
#define VCONV_VCONV_SET_IN_FORMAT0_IN_FORMATID0_SHIFT 16 
#define VCONV_VCONV_SET_IN_FORMAT0_IN_FORMATID0_BIT 0xFF
#define VCONV_VCONV_SET_IN_FORMAT0_IN_FORMATID0_BITWIDTH 8
// Reserved4 bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_IN_FORMAT0_RESERVED4_MASK 0xFF000000
#define VCONV_VCONV_SET_IN_FORMAT0_RESERVED4_SHIFT 24 
#define VCONV_VCONV_SET_IN_FORMAT0_RESERVED4_BIT 0xFF
#define VCONV_VCONV_SET_IN_FORMAT0_RESERVED4_BITWIDTH 8
// VCONV_SET_IN_HSIZE0 Register
#define VCONV_VCONV_SET_IN_HSIZE0_OFS            0x00000204
// IN_HSIZE0 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_IN_HSIZE0_IN_HSIZE0_MASK 0x7FF
#define VCONV_VCONV_SET_IN_HSIZE0_IN_HSIZE0_SHIFT 0 
#define VCONV_VCONV_SET_IN_HSIZE0_IN_HSIZE0_BIT  0x7FF
#define VCONV_VCONV_SET_IN_HSIZE0_IN_HSIZE0_BITWIDTH 11
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_IN_HSIZE0_RESERVED_MASK  0xFFFFF800
#define VCONV_VCONV_SET_IN_HSIZE0_RESERVED_SHIFT 11 
#define VCONV_VCONV_SET_IN_HSIZE0_RESERVED_BIT   0x1FFFFF
#define VCONV_VCONV_SET_IN_HSIZE0_RESERVED_BITWIDTH 21
// VCONV_SET_IN_VSIZE0 Register
#define VCONV_VCONV_SET_IN_VSIZE0_OFS            0x00000208
// IN_VSIZE0 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_IN_VSIZE0_IN_VSIZE0_MASK 0x7FF
#define VCONV_VCONV_SET_IN_VSIZE0_IN_VSIZE0_SHIFT 0 
#define VCONV_VCONV_SET_IN_VSIZE0_IN_VSIZE0_BIT  0x7FF
#define VCONV_VCONV_SET_IN_VSIZE0_IN_VSIZE0_BITWIDTH 11
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_IN_VSIZE0_RESERVED_MASK  0xFFFFF800
#define VCONV_VCONV_SET_IN_VSIZE0_RESERVED_SHIFT 11 
#define VCONV_VCONV_SET_IN_VSIZE0_RESERVED_BIT   0x1FFFFF
#define VCONV_VCONV_SET_IN_VSIZE0_RESERVED_BITWIDTH 21
// VCONV_SET_IN_BASEADDR_A0 Register
#define VCONV_VCONV_SET_IN_BASEADDR_A0_OFS       0x00000210
// IN_BADDR_A0 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_IN_BASEADDR_A0_IN_BADDR_A0_MASK 0xFFFFFFFF
#define VCONV_VCONV_SET_IN_BASEADDR_A0_IN_BADDR_A0_SHIFT 0 
#define VCONV_VCONV_SET_IN_BASEADDR_A0_IN_BADDR_A0_BIT 0xFFFFFFFF
#define VCONV_VCONV_SET_IN_BASEADDR_A0_IN_BADDR_A0_BITWIDTH 32
// VCONV_SET_IN_BASEADDR_B0 Register
#define VCONV_VCONV_SET_IN_BASEADDR_B0_OFS       0x00000214
// IN_BADDR_B0 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_IN_BASEADDR_B0_IN_BADDR_B0_MASK 0xFFFFFFFF
#define VCONV_VCONV_SET_IN_BASEADDR_B0_IN_BADDR_B0_SHIFT 0 
#define VCONV_VCONV_SET_IN_BASEADDR_B0_IN_BADDR_B0_BIT 0xFFFFFFFF
#define VCONV_VCONV_SET_IN_BASEADDR_B0_IN_BADDR_B0_BITWIDTH 32
// VCONV_SET_IN_BASEADDR_C0 Register
#define VCONV_VCONV_SET_IN_BASEADDR_C0_OFS       0x00000218
// IN_BADDR_C0 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_IN_BASEADDR_C0_IN_BADDR_C0_MASK 0xFFFFFFFF
#define VCONV_VCONV_SET_IN_BASEADDR_C0_IN_BADDR_C0_SHIFT 0 
#define VCONV_VCONV_SET_IN_BASEADDR_C0_IN_BADDR_C0_BIT 0xFFFFFFFF
#define VCONV_VCONV_SET_IN_BASEADDR_C0_IN_BADDR_C0_BITWIDTH 32
// VCONV_SET_IN_PITCH_A0 Register
#define VCONV_VCONV_SET_IN_PITCH_A0_OFS          0x0000021C
// IN_PITCH_A0 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_IN_PITCH_A0_IN_PITCH_A0_MASK 0x1FFF
#define VCONV_VCONV_SET_IN_PITCH_A0_IN_PITCH_A0_SHIFT 0 
#define VCONV_VCONV_SET_IN_PITCH_A0_IN_PITCH_A0_BIT 0x1FFF
#define VCONV_VCONV_SET_IN_PITCH_A0_IN_PITCH_A0_BITWIDTH 13
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_IN_PITCH_A0_RESERVED_MASK 0xFFFFE000
#define VCONV_VCONV_SET_IN_PITCH_A0_RESERVED_SHIFT 13 
#define VCONV_VCONV_SET_IN_PITCH_A0_RESERVED_BIT 0x7FFFF
#define VCONV_VCONV_SET_IN_PITCH_A0_RESERVED_BITWIDTH 19
// VCONV_SET_IN_PITCH_B0 Register
#define VCONV_VCONV_SET_IN_PITCH_B0_OFS          0x00000220
// IN_PITCH_B0 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_IN_PITCH_B0_IN_PITCH_B0_MASK 0x1FFF
#define VCONV_VCONV_SET_IN_PITCH_B0_IN_PITCH_B0_SHIFT 0 
#define VCONV_VCONV_SET_IN_PITCH_B0_IN_PITCH_B0_BIT 0x1FFF
#define VCONV_VCONV_SET_IN_PITCH_B0_IN_PITCH_B0_BITWIDTH 13
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_IN_PITCH_B0_RESERVED_MASK 0xFFFFE000
#define VCONV_VCONV_SET_IN_PITCH_B0_RESERVED_SHIFT 13 
#define VCONV_VCONV_SET_IN_PITCH_B0_RESERVED_BIT 0x7FFFF
#define VCONV_VCONV_SET_IN_PITCH_B0_RESERVED_BITWIDTH 19
// VCONV_SET_IN_PITCH_C0 Register
#define VCONV_VCONV_SET_IN_PITCH_C0_OFS          0x00000224
// IN_PITCH_C0 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_IN_PITCH_C0_IN_PITCH_C0_MASK 0x1FFF
#define VCONV_VCONV_SET_IN_PITCH_C0_IN_PITCH_C0_SHIFT 0 
#define VCONV_VCONV_SET_IN_PITCH_C0_IN_PITCH_C0_BIT 0x1FFF
#define VCONV_VCONV_SET_IN_PITCH_C0_IN_PITCH_C0_BITWIDTH 13
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_IN_PITCH_C0_RESERVED_MASK 0xFFFFE000
#define VCONV_VCONV_SET_IN_PITCH_C0_RESERVED_SHIFT 13 
#define VCONV_VCONV_SET_IN_PITCH_C0_RESERVED_BIT 0x7FFFF
#define VCONV_VCONV_SET_IN_PITCH_C0_RESERVED_BITWIDTH 19
// VCONV_SET_OUT_FORMAT0 Register
#define VCONV_VCONV_SET_OUT_FORMAT0_OFS          0x00000240
// OUT_COLORFORMAT0 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_OUT_FORMAT0_OUT_COLORFORMAT0_MASK 0x3
#define VCONV_VCONV_SET_OUT_FORMAT0_OUT_COLORFORMAT0_SHIFT 0 
#define VCONV_VCONV_SET_OUT_FORMAT0_OUT_COLORFORMAT0_BIT 0x3
#define VCONV_VCONV_SET_OUT_FORMAT0_OUT_COLORFORMAT0_BITWIDTH 2
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_OUT_FORMAT0_RESERVED_MASK 0xC
#define VCONV_VCONV_SET_OUT_FORMAT0_RESERVED_SHIFT 2 
#define VCONV_VCONV_SET_OUT_FORMAT0_RESERVED_BIT 0x3
#define VCONV_VCONV_SET_OUT_FORMAT0_RESERVED_BITWIDTH 2
// OUT_PLANE0 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_OUT_FORMAT0_OUT_PLANE0_MASK 0x30
#define VCONV_VCONV_SET_OUT_FORMAT0_OUT_PLANE0_SHIFT 4 
#define VCONV_VCONV_SET_OUT_FORMAT0_OUT_PLANE0_BIT 0x3
#define VCONV_VCONV_SET_OUT_FORMAT0_OUT_PLANE0_BITWIDTH 2
// Reserved2 bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_OUT_FORMAT0_RESERVED2_MASK 0xC0
#define VCONV_VCONV_SET_OUT_FORMAT0_RESERVED2_SHIFT 6 
#define VCONV_VCONV_SET_OUT_FORMAT0_RESERVED2_BIT 0x3
#define VCONV_VCONV_SET_OUT_FORMAT0_RESERVED2_BITWIDTH 2
// OUT_SCAN0 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_OUT_FORMAT0_OUT_SCAN0_MASK 0x100
#define VCONV_VCONV_SET_OUT_FORMAT0_OUT_SCAN0_SHIFT 8 
#define VCONV_VCONV_SET_OUT_FORMAT0_OUT_SCAN0_BIT 0x1
#define VCONV_VCONV_SET_OUT_FORMAT0_OUT_SCAN0_BITWIDTH 1
// Reserved3 bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_OUT_FORMAT0_RESERVED3_MASK 0xFE00
#define VCONV_VCONV_SET_OUT_FORMAT0_RESERVED3_SHIFT 9 
#define VCONV_VCONV_SET_OUT_FORMAT0_RESERVED3_BIT 0x7F
#define VCONV_VCONV_SET_OUT_FORMAT0_RESERVED3_BITWIDTH 7
// OUT_FORMATID0 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_OUT_FORMAT0_OUT_FORMATID0_MASK 0xFF0000
#define VCONV_VCONV_SET_OUT_FORMAT0_OUT_FORMATID0_SHIFT 16 
#define VCONV_VCONV_SET_OUT_FORMAT0_OUT_FORMATID0_BIT 0xFF
#define VCONV_VCONV_SET_OUT_FORMAT0_OUT_FORMATID0_BITWIDTH 8
// Reserved4 bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_OUT_FORMAT0_RESERVED4_MASK 0xFF000000
#define VCONV_VCONV_SET_OUT_FORMAT0_RESERVED4_SHIFT 24 
#define VCONV_VCONV_SET_OUT_FORMAT0_RESERVED4_BIT 0xFF
#define VCONV_VCONV_SET_OUT_FORMAT0_RESERVED4_BITWIDTH 8
// VCONV_SET_OUT_HSIZE0 Register
#define VCONV_VCONV_SET_OUT_HSIZE0_OFS           0x00000244
// OUT_HSIZE0 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_OUT_HSIZE0_OUT_HSIZE0_MASK 0x7FF
#define VCONV_VCONV_SET_OUT_HSIZE0_OUT_HSIZE0_SHIFT 0 
#define VCONV_VCONV_SET_OUT_HSIZE0_OUT_HSIZE0_BIT 0x7FF
#define VCONV_VCONV_SET_OUT_HSIZE0_OUT_HSIZE0_BITWIDTH 11
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_OUT_HSIZE0_RESERVED_MASK 0xFFFFF800
#define VCONV_VCONV_SET_OUT_HSIZE0_RESERVED_SHIFT 11 
#define VCONV_VCONV_SET_OUT_HSIZE0_RESERVED_BIT  0x1FFFFF
#define VCONV_VCONV_SET_OUT_HSIZE0_RESERVED_BITWIDTH 21
// VCONV_SET_OUT_VSIZE0 Register
#define VCONV_VCONV_SET_OUT_VSIZE0_OFS           0x00000248
// OUT_VSIZE0 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_OUT_VSIZE0_OUT_VSIZE0_MASK 0x7FF
#define VCONV_VCONV_SET_OUT_VSIZE0_OUT_VSIZE0_SHIFT 0 
#define VCONV_VCONV_SET_OUT_VSIZE0_OUT_VSIZE0_BIT 0x7FF
#define VCONV_VCONV_SET_OUT_VSIZE0_OUT_VSIZE0_BITWIDTH 11
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_OUT_VSIZE0_RESERVED_MASK 0xFFFFF800
#define VCONV_VCONV_SET_OUT_VSIZE0_RESERVED_SHIFT 11 
#define VCONV_VCONV_SET_OUT_VSIZE0_RESERVED_BIT  0x1FFFFF
#define VCONV_VCONV_SET_OUT_VSIZE0_RESERVED_BITWIDTH 21
// VCONV_SET_OUT_BASEADDR_A0 Register
#define VCONV_VCONV_SET_OUT_BASEADDR_A0_OFS      0x00000250
// OUT_BADDR_A0 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_OUT_BASEADDR_A0_OUT_BADDR_A0_MASK 0xFFFFFFFF
#define VCONV_VCONV_SET_OUT_BASEADDR_A0_OUT_BADDR_A0_SHIFT 0 
#define VCONV_VCONV_SET_OUT_BASEADDR_A0_OUT_BADDR_A0_BIT 0xFFFFFFFF
#define VCONV_VCONV_SET_OUT_BASEADDR_A0_OUT_BADDR_A0_BITWIDTH 32
// VCONV_SET_OUT_BASEADDR_B0 Register
#define VCONV_VCONV_SET_OUT_BASEADDR_B0_OFS      0x00000254
// OUT_BADDR_B0 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_OUT_BASEADDR_B0_OUT_BADDR_B0_MASK 0xFFFFFFFF
#define VCONV_VCONV_SET_OUT_BASEADDR_B0_OUT_BADDR_B0_SHIFT 0 
#define VCONV_VCONV_SET_OUT_BASEADDR_B0_OUT_BADDR_B0_BIT 0xFFFFFFFF
#define VCONV_VCONV_SET_OUT_BASEADDR_B0_OUT_BADDR_B0_BITWIDTH 32
// VCONV_SET_OUT_BASEADDR_C0 Register
#define VCONV_VCONV_SET_OUT_BASEADDR_C0_OFS      0x00000258
// OUT_BADDR_C0 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_OUT_BASEADDR_C0_OUT_BADDR_C0_MASK 0xFFFFFFFF
#define VCONV_VCONV_SET_OUT_BASEADDR_C0_OUT_BADDR_C0_SHIFT 0 
#define VCONV_VCONV_SET_OUT_BASEADDR_C0_OUT_BADDR_C0_BIT 0xFFFFFFFF
#define VCONV_VCONV_SET_OUT_BASEADDR_C0_OUT_BADDR_C0_BITWIDTH 32
// VCONV_SET_OUT_PITCH_A0 Register
#define VCONV_VCONV_SET_OUT_PITCH_A0_OFS         0x0000025C
// OUT_PITCH_A0 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_OUT_PITCH_A0_OUT_PITCH_A0_MASK 0x1FFF
#define VCONV_VCONV_SET_OUT_PITCH_A0_OUT_PITCH_A0_SHIFT 0 
#define VCONV_VCONV_SET_OUT_PITCH_A0_OUT_PITCH_A0_BIT 0x1FFF
#define VCONV_VCONV_SET_OUT_PITCH_A0_OUT_PITCH_A0_BITWIDTH 13
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_OUT_PITCH_A0_RESERVED_MASK 0xFFFFE000
#define VCONV_VCONV_SET_OUT_PITCH_A0_RESERVED_SHIFT 13 
#define VCONV_VCONV_SET_OUT_PITCH_A0_RESERVED_BIT 0x7FFFF
#define VCONV_VCONV_SET_OUT_PITCH_A0_RESERVED_BITWIDTH 19
// VCONV_SET_OUT_PITCH_B0 Register
#define VCONV_VCONV_SET_OUT_PITCH_B0_OFS         0x00000260
// OUT_PITCH_B0 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_OUT_PITCH_B0_OUT_PITCH_B0_MASK 0x1FFF
#define VCONV_VCONV_SET_OUT_PITCH_B0_OUT_PITCH_B0_SHIFT 0 
#define VCONV_VCONV_SET_OUT_PITCH_B0_OUT_PITCH_B0_BIT 0x1FFF
#define VCONV_VCONV_SET_OUT_PITCH_B0_OUT_PITCH_B0_BITWIDTH 13
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_OUT_PITCH_B0_RESERVED_MASK 0xFFFFE000
#define VCONV_VCONV_SET_OUT_PITCH_B0_RESERVED_SHIFT 13 
#define VCONV_VCONV_SET_OUT_PITCH_B0_RESERVED_BIT 0x7FFFF
#define VCONV_VCONV_SET_OUT_PITCH_B0_RESERVED_BITWIDTH 19
// VCONV_SET_OUT_PITCH_C0 Register
#define VCONV_VCONV_SET_OUT_PITCH_C0_OFS         0x00000264
// OUT_PITCH_C0 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_OUT_PITCH_C0_OUT_PITCH_C0_MASK 0x1FFF
#define VCONV_VCONV_SET_OUT_PITCH_C0_OUT_PITCH_C0_SHIFT 0 
#define VCONV_VCONV_SET_OUT_PITCH_C0_OUT_PITCH_C0_BIT 0x1FFF
#define VCONV_VCONV_SET_OUT_PITCH_C0_OUT_PITCH_C0_BITWIDTH 13
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_OUT_PITCH_C0_RESERVED_MASK 0xFFFFE000
#define VCONV_VCONV_SET_OUT_PITCH_C0_RESERVED_SHIFT 13 
#define VCONV_VCONV_SET_OUT_PITCH_C0_RESERVED_BIT 0x7FFFF
#define VCONV_VCONV_SET_OUT_PITCH_C0_RESERVED_BITWIDTH 19
// VCONV_SET_OUT_HOFFSET0 Register
#define VCONV_VCONV_SET_OUT_HOFFSET0_OFS         0x00000268
// OUT_HOFFSET0 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_OUT_HOFFSET0_OUT_HOFFSET0_MASK 0x7FF
#define VCONV_VCONV_SET_OUT_HOFFSET0_OUT_HOFFSET0_SHIFT 0 
#define VCONV_VCONV_SET_OUT_HOFFSET0_OUT_HOFFSET0_BIT 0x7FF
#define VCONV_VCONV_SET_OUT_HOFFSET0_OUT_HOFFSET0_BITWIDTH 11
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_OUT_HOFFSET0_RESERVED_MASK 0xFFFFF800
#define VCONV_VCONV_SET_OUT_HOFFSET0_RESERVED_SHIFT 11 
#define VCONV_VCONV_SET_OUT_HOFFSET0_RESERVED_BIT 0x1FFFFF
#define VCONV_VCONV_SET_OUT_HOFFSET0_RESERVED_BITWIDTH 21
// VCONV_SET_OUT_VOFFSET0 Register
#define VCONV_VCONV_SET_OUT_VOFFSET0_OFS         0x0000026C
// OUT_VOFFSET0 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_OUT_VOFFSET0_OUT_VOFFSET0_MASK 0x7FF
#define VCONV_VCONV_SET_OUT_VOFFSET0_OUT_VOFFSET0_SHIFT 0 
#define VCONV_VCONV_SET_OUT_VOFFSET0_OUT_VOFFSET0_BIT 0x7FF
#define VCONV_VCONV_SET_OUT_VOFFSET0_OUT_VOFFSET0_BITWIDTH 11
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_OUT_VOFFSET0_RESERVED_MASK 0xFFFFF800
#define VCONV_VCONV_SET_OUT_VOFFSET0_RESERVED_SHIFT 11 
#define VCONV_VCONV_SET_OUT_VOFFSET0_RESERVED_BIT 0x1FFFFF
#define VCONV_VCONV_SET_OUT_VOFFSET0_RESERVED_BITWIDTH 21
// VCONV_SET_OUT_HSCALE0 Register
#define VCONV_VCONV_SET_OUT_HSCALE0_OFS          0x00000270
// HSCALE_FRACTON0 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_OUT_HSCALE0_HSCALE_FRACTON0_MASK 0xFFFF
#define VCONV_VCONV_SET_OUT_HSCALE0_HSCALE_FRACTON0_SHIFT 0 
#define VCONV_VCONV_SET_OUT_HSCALE0_HSCALE_FRACTON0_BIT 0xFFFF
#define VCONV_VCONV_SET_OUT_HSCALE0_HSCALE_FRACTON0_BITWIDTH 16
// HSCALE_INTEGER0 bitfiled (RW) Reset=1
#define VCONV_VCONV_SET_OUT_HSCALE0_HSCALE_INTEGER0_MASK 0x70000
#define VCONV_VCONV_SET_OUT_HSCALE0_HSCALE_INTEGER0_SHIFT 16 
#define VCONV_VCONV_SET_OUT_HSCALE0_HSCALE_INTEGER0_BIT 0x7
#define VCONV_VCONV_SET_OUT_HSCALE0_HSCALE_INTEGER0_BITWIDTH 3
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_OUT_HSCALE0_RESERVED_MASK 0xFFF80000
#define VCONV_VCONV_SET_OUT_HSCALE0_RESERVED_SHIFT 19 
#define VCONV_VCONV_SET_OUT_HSCALE0_RESERVED_BIT 0x1FFF
#define VCONV_VCONV_SET_OUT_HSCALE0_RESERVED_BITWIDTH 13
// VCONV_SET_OUT_VSCALE0 Register
#define VCONV_VCONV_SET_OUT_VSCALE0_OFS          0x00000274
// VSCALE_FRACTON0 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_OUT_VSCALE0_VSCALE_FRACTON0_MASK 0xFFFF
#define VCONV_VCONV_SET_OUT_VSCALE0_VSCALE_FRACTON0_SHIFT 0 
#define VCONV_VCONV_SET_OUT_VSCALE0_VSCALE_FRACTON0_BIT 0xFFFF
#define VCONV_VCONV_SET_OUT_VSCALE0_VSCALE_FRACTON0_BITWIDTH 16
// VSCALE_INTEGER0 bitfiled (RW) Reset=1
#define VCONV_VCONV_SET_OUT_VSCALE0_VSCALE_INTEGER0_MASK 0x70000
#define VCONV_VCONV_SET_OUT_VSCALE0_VSCALE_INTEGER0_SHIFT 16 
#define VCONV_VCONV_SET_OUT_VSCALE0_VSCALE_INTEGER0_BIT 0x7
#define VCONV_VCONV_SET_OUT_VSCALE0_VSCALE_INTEGER0_BITWIDTH 3
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_OUT_VSCALE0_RESERVED_MASK 0xFFF80000
#define VCONV_VCONV_SET_OUT_VSCALE0_RESERVED_SHIFT 19 
#define VCONV_VCONV_SET_OUT_VSCALE0_RESERVED_BIT 0x1FFF
#define VCONV_VCONV_SET_OUT_VSCALE0_RESERVED_BITWIDTH 13
// VCONV_SET_OUT_HDELTA0 Register
#define VCONV_VCONV_SET_OUT_HDELTA0_OFS          0x00000278
// HDELTA0 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_OUT_HDELTA0_HDELTA0_MASK 0x3FF
#define VCONV_VCONV_SET_OUT_HDELTA0_HDELTA0_SHIFT 0 
#define VCONV_VCONV_SET_OUT_HDELTA0_HDELTA0_BIT  0x3FF
#define VCONV_VCONV_SET_OUT_HDELTA0_HDELTA0_BITWIDTH 10
// reserved2 bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_OUT_HDELTA0_RESERVED2_MASK 0x400
#define VCONV_VCONV_SET_OUT_HDELTA0_RESERVED2_SHIFT 10 
#define VCONV_VCONV_SET_OUT_HDELTA0_RESERVED2_BIT 0x1
#define VCONV_VCONV_SET_OUT_HDELTA0_RESERVED2_BITWIDTH 1
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_OUT_HDELTA0_RESERVED_MASK 0xFFFFF800
#define VCONV_VCONV_SET_OUT_HDELTA0_RESERVED_SHIFT 11 
#define VCONV_VCONV_SET_OUT_HDELTA0_RESERVED_BIT 0x1FFFFF
#define VCONV_VCONV_SET_OUT_HDELTA0_RESERVED_BITWIDTH 21
// VCONV_SET_OUT_VDELTA0 Register
#define VCONV_VCONV_SET_OUT_VDELTA0_OFS          0x0000027C
// VDELTA0 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_OUT_VDELTA0_VDELTA0_MASK 0x3FF
#define VCONV_VCONV_SET_OUT_VDELTA0_VDELTA0_SHIFT 0 
#define VCONV_VCONV_SET_OUT_VDELTA0_VDELTA0_BIT  0x3FF
#define VCONV_VCONV_SET_OUT_VDELTA0_VDELTA0_BITWIDTH 10
// reserved2 bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_OUT_VDELTA0_RESERVED2_MASK 0x400
#define VCONV_VCONV_SET_OUT_VDELTA0_RESERVED2_SHIFT 10 
#define VCONV_VCONV_SET_OUT_VDELTA0_RESERVED2_BIT 0x1
#define VCONV_VCONV_SET_OUT_VDELTA0_RESERVED2_BITWIDTH 1
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_OUT_VDELTA0_RESERVED_MASK 0xFFFFF800
#define VCONV_VCONV_SET_OUT_VDELTA0_RESERVED_SHIFT 11 
#define VCONV_VCONV_SET_OUT_VDELTA0_RESERVED_BIT 0x1FFFFF
#define VCONV_VCONV_SET_OUT_VDELTA0_RESERVED_BITWIDTH 21
// VCONV_SET_FORCE_MODE0 Register
#define VCONV_VCONV_SET_FORCE_MODE0_OFS          0x00000280
// FORCE_MODE0 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_FORCE_MODE0_FORCE_MODE0_MASK 0x1
#define VCONV_VCONV_SET_FORCE_MODE0_FORCE_MODE0_SHIFT 0 
#define VCONV_VCONV_SET_FORCE_MODE0_FORCE_MODE0_BIT 0x1
#define VCONV_VCONV_SET_FORCE_MODE0_FORCE_MODE0_BITWIDTH 1
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_FORCE_MODE0_RESERVED_MASK 0xFFFFFFFE
#define VCONV_VCONV_SET_FORCE_MODE0_RESERVED_SHIFT 1 
#define VCONV_VCONV_SET_FORCE_MODE0_RESERVED_BIT 0x7FFFFFFF
#define VCONV_VCONV_SET_FORCE_MODE0_RESERVED_BITWIDTH 31
// VCONV_SET_FORCE_GY0 Register
#define VCONV_VCONV_SET_FORCE_GY0_OFS            0x00000284
// FORCE_GY0 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_FORCE_GY0_FORCE_GY0_MASK 0xFF
#define VCONV_VCONV_SET_FORCE_GY0_FORCE_GY0_SHIFT 0 
#define VCONV_VCONV_SET_FORCE_GY0_FORCE_GY0_BIT  0xFF
#define VCONV_VCONV_SET_FORCE_GY0_FORCE_GY0_BITWIDTH 8
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_FORCE_GY0_RESERVED_MASK  0xFFFFFF00
#define VCONV_VCONV_SET_FORCE_GY0_RESERVED_SHIFT 8 
#define VCONV_VCONV_SET_FORCE_GY0_RESERVED_BIT   0xFFFFFF
#define VCONV_VCONV_SET_FORCE_GY0_RESERVED_BITWIDTH 24
// VCONV_SET_FORCE_BCB0 Register
#define VCONV_VCONV_SET_FORCE_BCB0_OFS           0x00000288
// FORCE_BCB0 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_FORCE_BCB0_FORCE_BCB0_MASK 0xFF
#define VCONV_VCONV_SET_FORCE_BCB0_FORCE_BCB0_SHIFT 0 
#define VCONV_VCONV_SET_FORCE_BCB0_FORCE_BCB0_BIT 0xFF
#define VCONV_VCONV_SET_FORCE_BCB0_FORCE_BCB0_BITWIDTH 8
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_FORCE_BCB0_RESERVED_MASK 0xFFFFFF00
#define VCONV_VCONV_SET_FORCE_BCB0_RESERVED_SHIFT 8 
#define VCONV_VCONV_SET_FORCE_BCB0_RESERVED_BIT  0xFFFFFF
#define VCONV_VCONV_SET_FORCE_BCB0_RESERVED_BITWIDTH 24
// VCONV_SET_FORCE_RCR0 Register
#define VCONV_VCONV_SET_FORCE_RCR0_OFS           0x0000028C
// FORCE_RCR0 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_FORCE_RCR0_FORCE_RCR0_MASK 0xFF
#define VCONV_VCONV_SET_FORCE_RCR0_FORCE_RCR0_SHIFT 0 
#define VCONV_VCONV_SET_FORCE_RCR0_FORCE_RCR0_BIT 0xFF
#define VCONV_VCONV_SET_FORCE_RCR0_FORCE_RCR0_BITWIDTH 8
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_FORCE_RCR0_RESERVED_MASK 0xFFFFFF00
#define VCONV_VCONV_SET_FORCE_RCR0_RESERVED_SHIFT 8 
#define VCONV_VCONV_SET_FORCE_RCR0_RESERVED_BIT  0xFFFFFF
#define VCONV_VCONV_SET_FORCE_RCR0_RESERVED_BITWIDTH 24
// VCONV_SET_FORCE_A0 Register
#define VCONV_VCONV_SET_FORCE_A0_OFS             0x00000290
// FORCE_ALPHA0 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_FORCE_A0_FORCE_ALPHA0_MASK 0xFF
#define VCONV_VCONV_SET_FORCE_A0_FORCE_ALPHA0_SHIFT 0 
#define VCONV_VCONV_SET_FORCE_A0_FORCE_ALPHA0_BIT 0xFF
#define VCONV_VCONV_SET_FORCE_A0_FORCE_ALPHA0_BITWIDTH 8
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_FORCE_A0_RESERVED_MASK   0xFFFFFF00
#define VCONV_VCONV_SET_FORCE_A0_RESERVED_SHIFT  8 
#define VCONV_VCONV_SET_FORCE_A0_RESERVED_BIT    0xFFFFFF
#define VCONV_VCONV_SET_FORCE_A0_RESERVED_BITWIDTH 24
// VCONV_SET_CROP0 Register
#define VCONV_VCONV_SET_CROP0_OFS                0x000002B0
// CROP_UPPER0 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_CROP0_CROP_UPPER0_MASK   0xF
#define VCONV_VCONV_SET_CROP0_CROP_UPPER0_SHIFT  0 
#define VCONV_VCONV_SET_CROP0_CROP_UPPER0_BIT    0xF
#define VCONV_VCONV_SET_CROP0_CROP_UPPER0_BITWIDTH 4
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_CROP0_RESERVED_MASK      0xF0
#define VCONV_VCONV_SET_CROP0_RESERVED_SHIFT     4 
#define VCONV_VCONV_SET_CROP0_RESERVED_BIT       0xF
#define VCONV_VCONV_SET_CROP0_RESERVED_BITWIDTH  4
// CROP_LOWER0 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_CROP0_CROP_LOWER0_MASK   0xF00
#define VCONV_VCONV_SET_CROP0_CROP_LOWER0_SHIFT  8 
#define VCONV_VCONV_SET_CROP0_CROP_LOWER0_BIT    0xF
#define VCONV_VCONV_SET_CROP0_CROP_LOWER0_BITWIDTH 4
// Reserved2 bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_CROP0_RESERVED2_MASK     0xF000
#define VCONV_VCONV_SET_CROP0_RESERVED2_SHIFT    12 
#define VCONV_VCONV_SET_CROP0_RESERVED2_BIT      0xF
#define VCONV_VCONV_SET_CROP0_RESERVED2_BITWIDTH 4
// CROP_LEFT0 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_CROP0_CROP_LEFT0_MASK    0xF0000
#define VCONV_VCONV_SET_CROP0_CROP_LEFT0_SHIFT   16 
#define VCONV_VCONV_SET_CROP0_CROP_LEFT0_BIT     0xF
#define VCONV_VCONV_SET_CROP0_CROP_LEFT0_BITWIDTH 4
// Reserved3 bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_CROP0_RESERVED3_MASK     0xF00000
#define VCONV_VCONV_SET_CROP0_RESERVED3_SHIFT    20 
#define VCONV_VCONV_SET_CROP0_RESERVED3_BIT      0xF
#define VCONV_VCONV_SET_CROP0_RESERVED3_BITWIDTH 4
// CROP_RIGHT0 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_CROP0_CROP_RIGHT0_MASK   0xF000000
#define VCONV_VCONV_SET_CROP0_CROP_RIGHT0_SHIFT  24 
#define VCONV_VCONV_SET_CROP0_CROP_RIGHT0_BIT    0xF
#define VCONV_VCONV_SET_CROP0_CROP_RIGHT0_BITWIDTH 4
// Reserved4 bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_CROP0_RESERVED4_MASK     0xF0000000
#define VCONV_VCONV_SET_CROP0_RESERVED4_SHIFT    28 
#define VCONV_VCONV_SET_CROP0_RESERVED4_BIT      0xF
#define VCONV_VCONV_SET_CROP0_RESERVED4_BITWIDTH 4
// VCONV_SET_IN_FORMAT1 Register
#define VCONV_VCONV_SET_IN_FORMAT1_OFS           0x00000300
// IN_COLORFORMAT1 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_IN_FORMAT1_IN_COLORFORMAT1_MASK 0x3
#define VCONV_VCONV_SET_IN_FORMAT1_IN_COLORFORMAT1_SHIFT 0 
#define VCONV_VCONV_SET_IN_FORMAT1_IN_COLORFORMAT1_BIT 0x3
#define VCONV_VCONV_SET_IN_FORMAT1_IN_COLORFORMAT1_BITWIDTH 2
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_IN_FORMAT1_RESERVED_MASK 0xC
#define VCONV_VCONV_SET_IN_FORMAT1_RESERVED_SHIFT 2 
#define VCONV_VCONV_SET_IN_FORMAT1_RESERVED_BIT  0x3
#define VCONV_VCONV_SET_IN_FORMAT1_RESERVED_BITWIDTH 2
// IN_PLANE1 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_IN_FORMAT1_IN_PLANE1_MASK 0x30
#define VCONV_VCONV_SET_IN_FORMAT1_IN_PLANE1_SHIFT 4 
#define VCONV_VCONV_SET_IN_FORMAT1_IN_PLANE1_BIT 0x3
#define VCONV_VCONV_SET_IN_FORMAT1_IN_PLANE1_BITWIDTH 2
// Reserved2 bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_IN_FORMAT1_RESERVED2_MASK 0xC0
#define VCONV_VCONV_SET_IN_FORMAT1_RESERVED2_SHIFT 6 
#define VCONV_VCONV_SET_IN_FORMAT1_RESERVED2_BIT 0x3
#define VCONV_VCONV_SET_IN_FORMAT1_RESERVED2_BITWIDTH 2
// IN_SCAN1 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_IN_FORMAT1_IN_SCAN1_MASK 0x100
#define VCONV_VCONV_SET_IN_FORMAT1_IN_SCAN1_SHIFT 8 
#define VCONV_VCONV_SET_IN_FORMAT1_IN_SCAN1_BIT  0x1
#define VCONV_VCONV_SET_IN_FORMAT1_IN_SCAN1_BITWIDTH 1
// Reserved3 bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_IN_FORMAT1_RESERVED3_MASK 0xFE00
#define VCONV_VCONV_SET_IN_FORMAT1_RESERVED3_SHIFT 9 
#define VCONV_VCONV_SET_IN_FORMAT1_RESERVED3_BIT 0x7F
#define VCONV_VCONV_SET_IN_FORMAT1_RESERVED3_BITWIDTH 7
// IN_FORMATID1 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_IN_FORMAT1_IN_FORMATID1_MASK 0xFF0000
#define VCONV_VCONV_SET_IN_FORMAT1_IN_FORMATID1_SHIFT 16 
#define VCONV_VCONV_SET_IN_FORMAT1_IN_FORMATID1_BIT 0xFF
#define VCONV_VCONV_SET_IN_FORMAT1_IN_FORMATID1_BITWIDTH 8
// Reserved4 bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_IN_FORMAT1_RESERVED4_MASK 0xFF000000
#define VCONV_VCONV_SET_IN_FORMAT1_RESERVED4_SHIFT 24 
#define VCONV_VCONV_SET_IN_FORMAT1_RESERVED4_BIT 0xFF
#define VCONV_VCONV_SET_IN_FORMAT1_RESERVED4_BITWIDTH 8
// VCONV_SET_IN_HSIZE1 Register
#define VCONV_VCONV_SET_IN_HSIZE1_OFS            0x00000304
// IN_HSIZE1 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_IN_HSIZE1_IN_HSIZE1_MASK 0x7FF
#define VCONV_VCONV_SET_IN_HSIZE1_IN_HSIZE1_SHIFT 0 
#define VCONV_VCONV_SET_IN_HSIZE1_IN_HSIZE1_BIT  0x7FF
#define VCONV_VCONV_SET_IN_HSIZE1_IN_HSIZE1_BITWIDTH 11
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_IN_HSIZE1_RESERVED_MASK  0xFFFFF800
#define VCONV_VCONV_SET_IN_HSIZE1_RESERVED_SHIFT 11 
#define VCONV_VCONV_SET_IN_HSIZE1_RESERVED_BIT   0x1FFFFF
#define VCONV_VCONV_SET_IN_HSIZE1_RESERVED_BITWIDTH 21
// VCONV_SET_IN_VSIZE1 Register
#define VCONV_VCONV_SET_IN_VSIZE1_OFS            0x00000308
// IN_VSIZE1 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_IN_VSIZE1_IN_VSIZE1_MASK 0x7FF
#define VCONV_VCONV_SET_IN_VSIZE1_IN_VSIZE1_SHIFT 0 
#define VCONV_VCONV_SET_IN_VSIZE1_IN_VSIZE1_BIT  0x7FF
#define VCONV_VCONV_SET_IN_VSIZE1_IN_VSIZE1_BITWIDTH 11
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_IN_VSIZE1_RESERVED_MASK  0xFFFFF800
#define VCONV_VCONV_SET_IN_VSIZE1_RESERVED_SHIFT 11 
#define VCONV_VCONV_SET_IN_VSIZE1_RESERVED_BIT   0x1FFFFF
#define VCONV_VCONV_SET_IN_VSIZE1_RESERVED_BITWIDTH 21
// VCONV_SET_IN_BASEADDR_A1 Register
#define VCONV_VCONV_SET_IN_BASEADDR_A1_OFS       0x00000310
// IN_BADDR_A1 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_IN_BASEADDR_A1_IN_BADDR_A1_MASK 0xFFFFFFFF
#define VCONV_VCONV_SET_IN_BASEADDR_A1_IN_BADDR_A1_SHIFT 0 
#define VCONV_VCONV_SET_IN_BASEADDR_A1_IN_BADDR_A1_BIT 0xFFFFFFFF
#define VCONV_VCONV_SET_IN_BASEADDR_A1_IN_BADDR_A1_BITWIDTH 32
// VCONV_SET_IN_BASEADDR_B1 Register
#define VCONV_VCONV_SET_IN_BASEADDR_B1_OFS       0x00000314
// IN_BADDR_B1 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_IN_BASEADDR_B1_IN_BADDR_B1_MASK 0xFFFFFFFF
#define VCONV_VCONV_SET_IN_BASEADDR_B1_IN_BADDR_B1_SHIFT 0 
#define VCONV_VCONV_SET_IN_BASEADDR_B1_IN_BADDR_B1_BIT 0xFFFFFFFF
#define VCONV_VCONV_SET_IN_BASEADDR_B1_IN_BADDR_B1_BITWIDTH 32
// VCONV_SET_IN_BASEADDR_C1 Register
#define VCONV_VCONV_SET_IN_BASEADDR_C1_OFS       0x00000318
// IN_BADDR_C1 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_IN_BASEADDR_C1_IN_BADDR_C1_MASK 0xFFFFFFFF
#define VCONV_VCONV_SET_IN_BASEADDR_C1_IN_BADDR_C1_SHIFT 0 
#define VCONV_VCONV_SET_IN_BASEADDR_C1_IN_BADDR_C1_BIT 0xFFFFFFFF
#define VCONV_VCONV_SET_IN_BASEADDR_C1_IN_BADDR_C1_BITWIDTH 32
// VCONV_SET_IN_PITCH_A1 Register
#define VCONV_VCONV_SET_IN_PITCH_A1_OFS          0x0000031C
// IN_PITCH_A1 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_IN_PITCH_A1_IN_PITCH_A1_MASK 0x1FFF
#define VCONV_VCONV_SET_IN_PITCH_A1_IN_PITCH_A1_SHIFT 0 
#define VCONV_VCONV_SET_IN_PITCH_A1_IN_PITCH_A1_BIT 0x1FFF
#define VCONV_VCONV_SET_IN_PITCH_A1_IN_PITCH_A1_BITWIDTH 13
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_IN_PITCH_A1_RESERVED_MASK 0xFFFFE000
#define VCONV_VCONV_SET_IN_PITCH_A1_RESERVED_SHIFT 13 
#define VCONV_VCONV_SET_IN_PITCH_A1_RESERVED_BIT 0x7FFFF
#define VCONV_VCONV_SET_IN_PITCH_A1_RESERVED_BITWIDTH 19
// VCONV_SET_IN_PITCH_B1 Register
#define VCONV_VCONV_SET_IN_PITCH_B1_OFS          0x00000320
// IN_PITCH_B1 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_IN_PITCH_B1_IN_PITCH_B1_MASK 0x1FFF
#define VCONV_VCONV_SET_IN_PITCH_B1_IN_PITCH_B1_SHIFT 0 
#define VCONV_VCONV_SET_IN_PITCH_B1_IN_PITCH_B1_BIT 0x1FFF
#define VCONV_VCONV_SET_IN_PITCH_B1_IN_PITCH_B1_BITWIDTH 13
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_IN_PITCH_B1_RESERVED_MASK 0xFFFFE000
#define VCONV_VCONV_SET_IN_PITCH_B1_RESERVED_SHIFT 13 
#define VCONV_VCONV_SET_IN_PITCH_B1_RESERVED_BIT 0x7FFFF
#define VCONV_VCONV_SET_IN_PITCH_B1_RESERVED_BITWIDTH 19
// VCONV_SET_IN_PITCH_C1 Register
#define VCONV_VCONV_SET_IN_PITCH_C1_OFS          0x00000324
// IN_PITCH_C1 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_IN_PITCH_C1_IN_PITCH_C1_MASK 0x1FFF
#define VCONV_VCONV_SET_IN_PITCH_C1_IN_PITCH_C1_SHIFT 0 
#define VCONV_VCONV_SET_IN_PITCH_C1_IN_PITCH_C1_BIT 0x1FFF
#define VCONV_VCONV_SET_IN_PITCH_C1_IN_PITCH_C1_BITWIDTH 13
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_IN_PITCH_C1_RESERVED_MASK 0xFFFFE000
#define VCONV_VCONV_SET_IN_PITCH_C1_RESERVED_SHIFT 13 
#define VCONV_VCONV_SET_IN_PITCH_C1_RESERVED_BIT 0x7FFFF
#define VCONV_VCONV_SET_IN_PITCH_C1_RESERVED_BITWIDTH 19
// VCONV_SET_OUT_FORMAT1 Register
#define VCONV_VCONV_SET_OUT_FORMAT1_OFS          0x00000340
// OUT_COLORFORMAT1 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_OUT_FORMAT1_OUT_COLORFORMAT1_MASK 0x3
#define VCONV_VCONV_SET_OUT_FORMAT1_OUT_COLORFORMAT1_SHIFT 0 
#define VCONV_VCONV_SET_OUT_FORMAT1_OUT_COLORFORMAT1_BIT 0x3
#define VCONV_VCONV_SET_OUT_FORMAT1_OUT_COLORFORMAT1_BITWIDTH 2
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_OUT_FORMAT1_RESERVED_MASK 0xC
#define VCONV_VCONV_SET_OUT_FORMAT1_RESERVED_SHIFT 2 
#define VCONV_VCONV_SET_OUT_FORMAT1_RESERVED_BIT 0x3
#define VCONV_VCONV_SET_OUT_FORMAT1_RESERVED_BITWIDTH 2
// OUT_PLANE1 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_OUT_FORMAT1_OUT_PLANE1_MASK 0x30
#define VCONV_VCONV_SET_OUT_FORMAT1_OUT_PLANE1_SHIFT 4 
#define VCONV_VCONV_SET_OUT_FORMAT1_OUT_PLANE1_BIT 0x3
#define VCONV_VCONV_SET_OUT_FORMAT1_OUT_PLANE1_BITWIDTH 2
// Reserved2 bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_OUT_FORMAT1_RESERVED2_MASK 0xC0
#define VCONV_VCONV_SET_OUT_FORMAT1_RESERVED2_SHIFT 6 
#define VCONV_VCONV_SET_OUT_FORMAT1_RESERVED2_BIT 0x3
#define VCONV_VCONV_SET_OUT_FORMAT1_RESERVED2_BITWIDTH 2
// OUT_SCAN1 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_OUT_FORMAT1_OUT_SCAN1_MASK 0x100
#define VCONV_VCONV_SET_OUT_FORMAT1_OUT_SCAN1_SHIFT 8 
#define VCONV_VCONV_SET_OUT_FORMAT1_OUT_SCAN1_BIT 0x1
#define VCONV_VCONV_SET_OUT_FORMAT1_OUT_SCAN1_BITWIDTH 1
// Reserved3 bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_OUT_FORMAT1_RESERVED3_MASK 0xFE00
#define VCONV_VCONV_SET_OUT_FORMAT1_RESERVED3_SHIFT 9 
#define VCONV_VCONV_SET_OUT_FORMAT1_RESERVED3_BIT 0x7F
#define VCONV_VCONV_SET_OUT_FORMAT1_RESERVED3_BITWIDTH 7
// OUT_FORMATID1 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_OUT_FORMAT1_OUT_FORMATID1_MASK 0xFF0000
#define VCONV_VCONV_SET_OUT_FORMAT1_OUT_FORMATID1_SHIFT 16 
#define VCONV_VCONV_SET_OUT_FORMAT1_OUT_FORMATID1_BIT 0xFF
#define VCONV_VCONV_SET_OUT_FORMAT1_OUT_FORMATID1_BITWIDTH 8
// Reserved4 bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_OUT_FORMAT1_RESERVED4_MASK 0xFF000000
#define VCONV_VCONV_SET_OUT_FORMAT1_RESERVED4_SHIFT 24 
#define VCONV_VCONV_SET_OUT_FORMAT1_RESERVED4_BIT 0xFF
#define VCONV_VCONV_SET_OUT_FORMAT1_RESERVED4_BITWIDTH 8
// VCONV_SET_OUT_HSIZE1 Register
#define VCONV_VCONV_SET_OUT_HSIZE1_OFS           0x00000344
// OUT_HSIZE1 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_OUT_HSIZE1_OUT_HSIZE1_MASK 0x7FF
#define VCONV_VCONV_SET_OUT_HSIZE1_OUT_HSIZE1_SHIFT 0 
#define VCONV_VCONV_SET_OUT_HSIZE1_OUT_HSIZE1_BIT 0x7FF
#define VCONV_VCONV_SET_OUT_HSIZE1_OUT_HSIZE1_BITWIDTH 11
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_OUT_HSIZE1_RESERVED_MASK 0xFFFFF800
#define VCONV_VCONV_SET_OUT_HSIZE1_RESERVED_SHIFT 11 
#define VCONV_VCONV_SET_OUT_HSIZE1_RESERVED_BIT  0x1FFFFF
#define VCONV_VCONV_SET_OUT_HSIZE1_RESERVED_BITWIDTH 21
// VCONV_SET_OUT_VSIZE1 Register
#define VCONV_VCONV_SET_OUT_VSIZE1_OFS           0x00000348
// OUT_VSIZE1 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_OUT_VSIZE1_OUT_VSIZE1_MASK 0x7FF
#define VCONV_VCONV_SET_OUT_VSIZE1_OUT_VSIZE1_SHIFT 0 
#define VCONV_VCONV_SET_OUT_VSIZE1_OUT_VSIZE1_BIT 0x7FF
#define VCONV_VCONV_SET_OUT_VSIZE1_OUT_VSIZE1_BITWIDTH 11
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_OUT_VSIZE1_RESERVED_MASK 0xFFFFF800
#define VCONV_VCONV_SET_OUT_VSIZE1_RESERVED_SHIFT 11 
#define VCONV_VCONV_SET_OUT_VSIZE1_RESERVED_BIT  0x1FFFFF
#define VCONV_VCONV_SET_OUT_VSIZE1_RESERVED_BITWIDTH 21
// VCONV_SET_OUT_BASEADDR_A1 Register
#define VCONV_VCONV_SET_OUT_BASEADDR_A1_OFS      0x00000350
// OUT_BADDR_A1 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_OUT_BASEADDR_A1_OUT_BADDR_A1_MASK 0xFFFFFFFF
#define VCONV_VCONV_SET_OUT_BASEADDR_A1_OUT_BADDR_A1_SHIFT 0 
#define VCONV_VCONV_SET_OUT_BASEADDR_A1_OUT_BADDR_A1_BIT 0xFFFFFFFF
#define VCONV_VCONV_SET_OUT_BASEADDR_A1_OUT_BADDR_A1_BITWIDTH 32
// VCONV_SET_OUT_BASEADDR_B1 Register
#define VCONV_VCONV_SET_OUT_BASEADDR_B1_OFS      0x00000354
// OUT_BADDR_B1 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_OUT_BASEADDR_B1_OUT_BADDR_B1_MASK 0xFFFFFFFF
#define VCONV_VCONV_SET_OUT_BASEADDR_B1_OUT_BADDR_B1_SHIFT 0 
#define VCONV_VCONV_SET_OUT_BASEADDR_B1_OUT_BADDR_B1_BIT 0xFFFFFFFF
#define VCONV_VCONV_SET_OUT_BASEADDR_B1_OUT_BADDR_B1_BITWIDTH 32
// VCONV_SET_OUT_BASEADDR_C1 Register
#define VCONV_VCONV_SET_OUT_BASEADDR_C1_OFS      0x00000358
// OUT_BADDR_C1 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_OUT_BASEADDR_C1_OUT_BADDR_C1_MASK 0xFFFFFFFF
#define VCONV_VCONV_SET_OUT_BASEADDR_C1_OUT_BADDR_C1_SHIFT 0 
#define VCONV_VCONV_SET_OUT_BASEADDR_C1_OUT_BADDR_C1_BIT 0xFFFFFFFF
#define VCONV_VCONV_SET_OUT_BASEADDR_C1_OUT_BADDR_C1_BITWIDTH 32
// VCONV_SET_OUT_PITCH_A1 Register
#define VCONV_VCONV_SET_OUT_PITCH_A1_OFS         0x0000035C
// OUT_PITCH_A1 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_OUT_PITCH_A1_OUT_PITCH_A1_MASK 0x1FFF
#define VCONV_VCONV_SET_OUT_PITCH_A1_OUT_PITCH_A1_SHIFT 0 
#define VCONV_VCONV_SET_OUT_PITCH_A1_OUT_PITCH_A1_BIT 0x1FFF
#define VCONV_VCONV_SET_OUT_PITCH_A1_OUT_PITCH_A1_BITWIDTH 13
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_OUT_PITCH_A1_RESERVED_MASK 0xFFFFE000
#define VCONV_VCONV_SET_OUT_PITCH_A1_RESERVED_SHIFT 13 
#define VCONV_VCONV_SET_OUT_PITCH_A1_RESERVED_BIT 0x7FFFF
#define VCONV_VCONV_SET_OUT_PITCH_A1_RESERVED_BITWIDTH 19
// VCONV_SET_OUT_PITCH_B1 Register
#define VCONV_VCONV_SET_OUT_PITCH_B1_OFS         0x00000360
// OUT_PITCH_B1 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_OUT_PITCH_B1_OUT_PITCH_B1_MASK 0x1FFF
#define VCONV_VCONV_SET_OUT_PITCH_B1_OUT_PITCH_B1_SHIFT 0 
#define VCONV_VCONV_SET_OUT_PITCH_B1_OUT_PITCH_B1_BIT 0x1FFF
#define VCONV_VCONV_SET_OUT_PITCH_B1_OUT_PITCH_B1_BITWIDTH 13
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_OUT_PITCH_B1_RESERVED_MASK 0xFFFFE000
#define VCONV_VCONV_SET_OUT_PITCH_B1_RESERVED_SHIFT 13 
#define VCONV_VCONV_SET_OUT_PITCH_B1_RESERVED_BIT 0x7FFFF
#define VCONV_VCONV_SET_OUT_PITCH_B1_RESERVED_BITWIDTH 19
// VCONV_SET_OUT_PITCH_C1 Register
#define VCONV_VCONV_SET_OUT_PITCH_C1_OFS         0x00000364
// OUT_PITCH_C1 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_OUT_PITCH_C1_OUT_PITCH_C1_MASK 0x1FFF
#define VCONV_VCONV_SET_OUT_PITCH_C1_OUT_PITCH_C1_SHIFT 0 
#define VCONV_VCONV_SET_OUT_PITCH_C1_OUT_PITCH_C1_BIT 0x1FFF
#define VCONV_VCONV_SET_OUT_PITCH_C1_OUT_PITCH_C1_BITWIDTH 13
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_OUT_PITCH_C1_RESERVED_MASK 0xFFFFE000
#define VCONV_VCONV_SET_OUT_PITCH_C1_RESERVED_SHIFT 13 
#define VCONV_VCONV_SET_OUT_PITCH_C1_RESERVED_BIT 0x7FFFF
#define VCONV_VCONV_SET_OUT_PITCH_C1_RESERVED_BITWIDTH 19
// VCONV_SET_OUT_HOFFSET1 Register
#define VCONV_VCONV_SET_OUT_HOFFSET1_OFS         0x00000368
// OUT_HOFFSET1 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_OUT_HOFFSET1_OUT_HOFFSET1_MASK 0x7FF
#define VCONV_VCONV_SET_OUT_HOFFSET1_OUT_HOFFSET1_SHIFT 0 
#define VCONV_VCONV_SET_OUT_HOFFSET1_OUT_HOFFSET1_BIT 0x7FF
#define VCONV_VCONV_SET_OUT_HOFFSET1_OUT_HOFFSET1_BITWIDTH 11
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_OUT_HOFFSET1_RESERVED_MASK 0xFFFFF800
#define VCONV_VCONV_SET_OUT_HOFFSET1_RESERVED_SHIFT 11 
#define VCONV_VCONV_SET_OUT_HOFFSET1_RESERVED_BIT 0x1FFFFF
#define VCONV_VCONV_SET_OUT_HOFFSET1_RESERVED_BITWIDTH 21
// VCONV_SET_OUT_VOFFSET1 Register
#define VCONV_VCONV_SET_OUT_VOFFSET1_OFS         0x0000036C
// OUT_VOFFSET1 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_OUT_VOFFSET1_OUT_VOFFSET1_MASK 0x7FF
#define VCONV_VCONV_SET_OUT_VOFFSET1_OUT_VOFFSET1_SHIFT 0 
#define VCONV_VCONV_SET_OUT_VOFFSET1_OUT_VOFFSET1_BIT 0x7FF
#define VCONV_VCONV_SET_OUT_VOFFSET1_OUT_VOFFSET1_BITWIDTH 11
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_OUT_VOFFSET1_RESERVED_MASK 0xFFFFF800
#define VCONV_VCONV_SET_OUT_VOFFSET1_RESERVED_SHIFT 11 
#define VCONV_VCONV_SET_OUT_VOFFSET1_RESERVED_BIT 0x1FFFFF
#define VCONV_VCONV_SET_OUT_VOFFSET1_RESERVED_BITWIDTH 21
// VCONV_SET_OUT_HSCALE1 Register
#define VCONV_VCONV_SET_OUT_HSCALE1_OFS          0x00000370
// HSCALE_FRACTON1 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_OUT_HSCALE1_HSCALE_FRACTON1_MASK 0xFFFF
#define VCONV_VCONV_SET_OUT_HSCALE1_HSCALE_FRACTON1_SHIFT 0 
#define VCONV_VCONV_SET_OUT_HSCALE1_HSCALE_FRACTON1_BIT 0xFFFF
#define VCONV_VCONV_SET_OUT_HSCALE1_HSCALE_FRACTON1_BITWIDTH 16
// HSCALE_INTEGER1 bitfiled (RW) Reset=1
#define VCONV_VCONV_SET_OUT_HSCALE1_HSCALE_INTEGER1_MASK 0x70000
#define VCONV_VCONV_SET_OUT_HSCALE1_HSCALE_INTEGER1_SHIFT 16 
#define VCONV_VCONV_SET_OUT_HSCALE1_HSCALE_INTEGER1_BIT 0x7
#define VCONV_VCONV_SET_OUT_HSCALE1_HSCALE_INTEGER1_BITWIDTH 3
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_OUT_HSCALE1_RESERVED_MASK 0xFFF80000
#define VCONV_VCONV_SET_OUT_HSCALE1_RESERVED_SHIFT 19 
#define VCONV_VCONV_SET_OUT_HSCALE1_RESERVED_BIT 0x1FFF
#define VCONV_VCONV_SET_OUT_HSCALE1_RESERVED_BITWIDTH 13
// VCONV_SET_OUT_VSCALE1 Register
#define VCONV_VCONV_SET_OUT_VSCALE1_OFS          0x00000374
// VSCALE_FRACTON1 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_OUT_VSCALE1_VSCALE_FRACTON1_MASK 0xFFFF
#define VCONV_VCONV_SET_OUT_VSCALE1_VSCALE_FRACTON1_SHIFT 0 
#define VCONV_VCONV_SET_OUT_VSCALE1_VSCALE_FRACTON1_BIT 0xFFFF
#define VCONV_VCONV_SET_OUT_VSCALE1_VSCALE_FRACTON1_BITWIDTH 16
// VSCALE_INTEGER1 bitfiled (RW) Reset=1
#define VCONV_VCONV_SET_OUT_VSCALE1_VSCALE_INTEGER1_MASK 0x70000
#define VCONV_VCONV_SET_OUT_VSCALE1_VSCALE_INTEGER1_SHIFT 16 
#define VCONV_VCONV_SET_OUT_VSCALE1_VSCALE_INTEGER1_BIT 0x7
#define VCONV_VCONV_SET_OUT_VSCALE1_VSCALE_INTEGER1_BITWIDTH 3
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_OUT_VSCALE1_RESERVED_MASK 0xFFF80000
#define VCONV_VCONV_SET_OUT_VSCALE1_RESERVED_SHIFT 19 
#define VCONV_VCONV_SET_OUT_VSCALE1_RESERVED_BIT 0x1FFF
#define VCONV_VCONV_SET_OUT_VSCALE1_RESERVED_BITWIDTH 13
// VCONV_SET_OUT_HDELTA1 Register
#define VCONV_VCONV_SET_OUT_HDELTA1_OFS          0x00000378
// HDELTA1 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_OUT_HDELTA1_HDELTA1_MASK 0x3FF
#define VCONV_VCONV_SET_OUT_HDELTA1_HDELTA1_SHIFT 0 
#define VCONV_VCONV_SET_OUT_HDELTA1_HDELTA1_BIT  0x3FF
#define VCONV_VCONV_SET_OUT_HDELTA1_HDELTA1_BITWIDTH 10
// reserved2 bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_OUT_HDELTA1_RESERVED2_MASK 0x400
#define VCONV_VCONV_SET_OUT_HDELTA1_RESERVED2_SHIFT 10 
#define VCONV_VCONV_SET_OUT_HDELTA1_RESERVED2_BIT 0x1
#define VCONV_VCONV_SET_OUT_HDELTA1_RESERVED2_BITWIDTH 1
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_OUT_HDELTA1_RESERVED_MASK 0xFFFFF800
#define VCONV_VCONV_SET_OUT_HDELTA1_RESERVED_SHIFT 11 
#define VCONV_VCONV_SET_OUT_HDELTA1_RESERVED_BIT 0x1FFFFF
#define VCONV_VCONV_SET_OUT_HDELTA1_RESERVED_BITWIDTH 21
// VCONV_SET_OUT_VDELTA1 Register
#define VCONV_VCONV_SET_OUT_VDELTA1_OFS          0x0000037C
// VDELTA1 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_OUT_VDELTA1_VDELTA1_MASK 0x3FF
#define VCONV_VCONV_SET_OUT_VDELTA1_VDELTA1_SHIFT 0 
#define VCONV_VCONV_SET_OUT_VDELTA1_VDELTA1_BIT  0x3FF
#define VCONV_VCONV_SET_OUT_VDELTA1_VDELTA1_BITWIDTH 10
// reserved2 bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_OUT_VDELTA1_RESERVED2_MASK 0x400
#define VCONV_VCONV_SET_OUT_VDELTA1_RESERVED2_SHIFT 10 
#define VCONV_VCONV_SET_OUT_VDELTA1_RESERVED2_BIT 0x1
#define VCONV_VCONV_SET_OUT_VDELTA1_RESERVED2_BITWIDTH 1
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_OUT_VDELTA1_RESERVED_MASK 0xFFFFF800
#define VCONV_VCONV_SET_OUT_VDELTA1_RESERVED_SHIFT 11 
#define VCONV_VCONV_SET_OUT_VDELTA1_RESERVED_BIT 0x1FFFFF
#define VCONV_VCONV_SET_OUT_VDELTA1_RESERVED_BITWIDTH 21
// VCONV_SET_FORCE_MODE1 Register
#define VCONV_VCONV_SET_FORCE_MODE1_OFS          0x00000380
// FORCE_MODE1 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_FORCE_MODE1_FORCE_MODE1_MASK 0x1
#define VCONV_VCONV_SET_FORCE_MODE1_FORCE_MODE1_SHIFT 0 
#define VCONV_VCONV_SET_FORCE_MODE1_FORCE_MODE1_BIT 0x1
#define VCONV_VCONV_SET_FORCE_MODE1_FORCE_MODE1_BITWIDTH 1
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_FORCE_MODE1_RESERVED_MASK 0xFFFFFFFE
#define VCONV_VCONV_SET_FORCE_MODE1_RESERVED_SHIFT 1 
#define VCONV_VCONV_SET_FORCE_MODE1_RESERVED_BIT 0x7FFFFFFF
#define VCONV_VCONV_SET_FORCE_MODE1_RESERVED_BITWIDTH 31
// VCONV_SET_FORCE_GY1 Register
#define VCONV_VCONV_SET_FORCE_GY1_OFS            0x00000384
// FORCE_GY1 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_FORCE_GY1_FORCE_GY1_MASK 0xFF
#define VCONV_VCONV_SET_FORCE_GY1_FORCE_GY1_SHIFT 0 
#define VCONV_VCONV_SET_FORCE_GY1_FORCE_GY1_BIT  0xFF
#define VCONV_VCONV_SET_FORCE_GY1_FORCE_GY1_BITWIDTH 8
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_FORCE_GY1_RESERVED_MASK  0xFFFFFF00
#define VCONV_VCONV_SET_FORCE_GY1_RESERVED_SHIFT 8 
#define VCONV_VCONV_SET_FORCE_GY1_RESERVED_BIT   0xFFFFFF
#define VCONV_VCONV_SET_FORCE_GY1_RESERVED_BITWIDTH 24
// VCONV_SET_FORCE_BCB1 Register
#define VCONV_VCONV_SET_FORCE_BCB1_OFS           0x00000388
// FORCE_BCB1 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_FORCE_BCB1_FORCE_BCB1_MASK 0xFF
#define VCONV_VCONV_SET_FORCE_BCB1_FORCE_BCB1_SHIFT 0 
#define VCONV_VCONV_SET_FORCE_BCB1_FORCE_BCB1_BIT 0xFF
#define VCONV_VCONV_SET_FORCE_BCB1_FORCE_BCB1_BITWIDTH 8
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_FORCE_BCB1_RESERVED_MASK 0xFFFFFF00
#define VCONV_VCONV_SET_FORCE_BCB1_RESERVED_SHIFT 8 
#define VCONV_VCONV_SET_FORCE_BCB1_RESERVED_BIT  0xFFFFFF
#define VCONV_VCONV_SET_FORCE_BCB1_RESERVED_BITWIDTH 24
// VCONV_SET_FORCE_RCR1 Register
#define VCONV_VCONV_SET_FORCE_RCR1_OFS           0x0000038C
// FORCE_RCR1 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_FORCE_RCR1_FORCE_RCR1_MASK 0xFF
#define VCONV_VCONV_SET_FORCE_RCR1_FORCE_RCR1_SHIFT 0 
#define VCONV_VCONV_SET_FORCE_RCR1_FORCE_RCR1_BIT 0xFF
#define VCONV_VCONV_SET_FORCE_RCR1_FORCE_RCR1_BITWIDTH 8
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_FORCE_RCR1_RESERVED_MASK 0xFFFFFF00
#define VCONV_VCONV_SET_FORCE_RCR1_RESERVED_SHIFT 8 
#define VCONV_VCONV_SET_FORCE_RCR1_RESERVED_BIT  0xFFFFFF
#define VCONV_VCONV_SET_FORCE_RCR1_RESERVED_BITWIDTH 24
// VCONV_SET_FORCE_A1 Register
#define VCONV_VCONV_SET_FORCE_A1_OFS             0x00000390
// FORCE_ALPHA1 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_FORCE_A1_FORCE_ALPHA1_MASK 0xFF
#define VCONV_VCONV_SET_FORCE_A1_FORCE_ALPHA1_SHIFT 0 
#define VCONV_VCONV_SET_FORCE_A1_FORCE_ALPHA1_BIT 0xFF
#define VCONV_VCONV_SET_FORCE_A1_FORCE_ALPHA1_BITWIDTH 8
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_FORCE_A1_RESERVED_MASK   0xFFFFFF00
#define VCONV_VCONV_SET_FORCE_A1_RESERVED_SHIFT  8 
#define VCONV_VCONV_SET_FORCE_A1_RESERVED_BIT    0xFFFFFF
#define VCONV_VCONV_SET_FORCE_A1_RESERVED_BITWIDTH 24
// VCONV_SET_CROP1 Register
#define VCONV_VCONV_SET_CROP1_OFS                0x000003B0
// CROP_UPPER1 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_CROP1_CROP_UPPER1_MASK   0xF
#define VCONV_VCONV_SET_CROP1_CROP_UPPER1_SHIFT  0 
#define VCONV_VCONV_SET_CROP1_CROP_UPPER1_BIT    0xF
#define VCONV_VCONV_SET_CROP1_CROP_UPPER1_BITWIDTH 4
// Reserved bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_CROP1_RESERVED_MASK      0xF0
#define VCONV_VCONV_SET_CROP1_RESERVED_SHIFT     4 
#define VCONV_VCONV_SET_CROP1_RESERVED_BIT       0xF
#define VCONV_VCONV_SET_CROP1_RESERVED_BITWIDTH  4
// CROP_LOWER1 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_CROP1_CROP_LOWER1_MASK   0xF00
#define VCONV_VCONV_SET_CROP1_CROP_LOWER1_SHIFT  8 
#define VCONV_VCONV_SET_CROP1_CROP_LOWER1_BIT    0xF
#define VCONV_VCONV_SET_CROP1_CROP_LOWER1_BITWIDTH 4
// Reserved2 bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_CROP1_RESERVED2_MASK     0xF000
#define VCONV_VCONV_SET_CROP1_RESERVED2_SHIFT    12 
#define VCONV_VCONV_SET_CROP1_RESERVED2_BIT      0xF
#define VCONV_VCONV_SET_CROP1_RESERVED2_BITWIDTH 4
// CROP_LEFT1 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_CROP1_CROP_LEFT1_MASK    0xF0000
#define VCONV_VCONV_SET_CROP1_CROP_LEFT1_SHIFT   16 
#define VCONV_VCONV_SET_CROP1_CROP_LEFT1_BIT     0xF
#define VCONV_VCONV_SET_CROP1_CROP_LEFT1_BITWIDTH 4
// Reserved3 bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_CROP1_RESERVED3_MASK     0xF00000
#define VCONV_VCONV_SET_CROP1_RESERVED3_SHIFT    20 
#define VCONV_VCONV_SET_CROP1_RESERVED3_BIT      0xF
#define VCONV_VCONV_SET_CROP1_RESERVED3_BITWIDTH 4
// CROP_RIGHT1 bitfiled (RW) Reset=0
#define VCONV_VCONV_SET_CROP1_CROP_RIGHT1_MASK   0xF000000
#define VCONV_VCONV_SET_CROP1_CROP_RIGHT1_SHIFT  24 
#define VCONV_VCONV_SET_CROP1_CROP_RIGHT1_BIT    0xF
#define VCONV_VCONV_SET_CROP1_CROP_RIGHT1_BITWIDTH 4
// Reserved4 bitfiled (RO) Reset=0
#define VCONV_VCONV_SET_CROP1_RESERVED4_MASK     0xF0000000
#define VCONV_VCONV_SET_CROP1_RESERVED4_SHIFT    28 
#define VCONV_VCONV_SET_CROP1_RESERVED4_BIT      0xF
#define VCONV_VCONV_SET_CROP1_RESERVED4_BITWIDTH 4

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* _VCONV_REG_DEF_H */
