#
# linux/drivers/applite/veu
#

obj-${CONFIG_APPLITE_VEU} 		+= appliteveu.o

appliteveu-objs 	:= applite_veu_base.o \
			applite_veu_internal.o \
			applite_veu_procfs.o \
			applite_veu_dbg.o \
			applite_veu_ioctl.o \
			applite_veu_reset_power_seq.o \
			ve_access.o \
			ve_command.o \
			ve_response.o \
			ve_task.o \
			ve_api.o \
			ve_resources.o \
			ve_state.o \
			ve_trace.o
