#
# linux/drivers/staging/applite/syscon
#

obj-${CONFIG_APPLITE_SYSCON} 		+= syscon.o

syscon-objs 	:= applite_syscon_if.o applite_syscon_core.o applite_syscon_dbg.o applite_syscon_crypto.o applite_syscon_crypto_aes.o applite_syscon_crypto_sha.o applite_syscon_rng.o
